### PR TITLE
chunking + pureExternalModules is not working correctly

### PR DESCRIPTION
**Pull request by kellyselden**
An `import 'external';` is left behind under certain conditions when it shouldn't.

### CODE REVIEW

**Comment by lukastaegert** [comment]
Looks to me like this is not a bug.
1. As you are using `external` in `foo`, `pureExternalModules` does not apply as you actually need the import. `pureExternalModules` is only relevant if none of your code uses anything imported from an external library.
2. As `main` directly imports `foo`, this makes `external` a transitive dependency of `main`. What probably kicks in here is the transitive dependency pre-fetching logic which adds imports of transitive dependencies to chunks to put them into the import cache of the loader earlier to speed up loading the respective chunk. Maybe it might make sense to deactivate this feature for `experimentalPreserveModules`, though.

**Comment by lukastaegert** [comment]
> Maybe it might make sense to deactivate this feature for experimentalPreserveModules, though

Should we change the topic in this direction instead?

**Comment by jscinoz** [comment]
> Maybe it might make sense to deactivate this feature for experimentalPreserveModules, though

This would certainly be useful, as there are valid use cases for building things as in @kellyselden's test case; specifically when you wish to build a library consumable in either of the following forms, while still allowing proper tree shaking for downstream consumers:

```javascript
import { a, b, c } from "foo";

// Do things with a, b, c
```

```javascript
import a from "foo/a";

// Do things with a only
```

As things stand, building a module where the entry point is of the following form, without experimentalCodeSplitting will result in a single output file containing the content of "./a", "./b", "./c" which (unless I'm mistaken) would prevent proper tree shaking by downstream consumers if only one export is actually used.

```javascript
export { default as a } from "./a";
export { default as b } from "./b";
export { default as c } from "./c";
```

**Comment by lukastaegert** [comment]
If you bundle as ESM, tree-shaking individual exports will work equally well no matter if it is one or several files. Problems can occur when you export to CJS as here it is much more difficult for the downstream bundler to correctly remove unused exports due to the fact that everything is pinned to a common exports object.

The "feature" in question though is the fact that an "empty" `import "external"` is added to the bundled `main.js`. This should not interfere with tree-shaking at all as this just means that the file is loaded earlier and only its initialization code is included but none of its exports (unless they are required by the initialization code).

**Comment by shellscape** [comment]
@kellyselden you may have noticed from my other PR comments that I've been trying to touch base with the PR authors that have open PRs which have fallen by the wayside. We're sorry that's happened and we're trying to get more folks involved to avoid that in the future. Is this PR something that you feel is still a good addition?

I don't want to blow up the other open PRs you have there. Could you take a look at #2288, #2360, and #2373 as well when you have the opportunity?

**Comment by shellscape** [comment]
Closing for now as stale. @kellyselden if you'd like to reopen these please ping and it shall be done.

**Pull request closed without merging**
