### PR TITLE
[v3.0] Basic support for import assertions

### LINKED ISSUE #3799: Plan for import assertions and non-JS module types
### Feature Use Case

Importing JSON, CSS, and HTML according to upcoming JavaScript and HTML standards.

### Feature Proposal

Import assertions are a Stage 3 TC39 proposal to allow source code to assert that an import has a specific type (among other possible assertions): https://github.com/tc39/proposal-import-assertions

Assertions are being added to unblock the JSON, CSS, and HTML modules proposals which allow importing those file type as JavaScript modules.

This means that we'll be able to import JSON, CSS and HTML into JavaScript natively, and ideally in bundlers without any specific loaders (or perhaps a "web standard loader" that implements all web-native module types?):

```js
import styles from './styles.css' assert {type: 'css'};

// or

const styles = await import('./styles.css', {assert: {type: 'css'}});
```

I filed an [issue on Acorn for import assertion support](https://github.com/acornjs/acorn/issues/983).

The JSON and CSS proposals are furthest along, with implementations in Chromium behind flags.

- [Cascading Style Sheet Module Scripts Explainer](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md)
- [JSON Modules](https://github.com/tc39/proposal-json-modules)

### LINKED ISSUE #4530: `assert { type: 'json' }` results in "Error: Unexpected token"
### Rollup Version

2.75.6

### Operating System (or Browser)

macOS Monterey

### Node Version (if applicable)

16.15.1

### Link To Reproduction

https://rollupjs.org/repl/?version=2.75.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGRhdGElMjBmcm9tJTIwJTVDJTIydGVzdC1qc29uLWltcG9ydCUyRmRhdGEuanNvbiU1QyUyMiUyMGFzc2VydCUyMCU3QiUyMHR5cGUlM0ElMjAlNUMlMjJqc29uJTVDJTIyJTIwJTdEJTNCJTVDbiU1Q25jb25zb2xlLnRhYmxlKGRhdGEpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZGF0YS5qc29uJTIyJTJDJTIyY29kZSUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlMjAlMjAlNUMlMjJpZCU1QyUyMiUzQSUyMDElNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behaviour

When `index.js` includes `assert { type: 'json'}` on an import, and I run `yarn rollup index.js` it should not error.

This includes both non-npm module json files:
```
import data from "./data.json" assert { type: "json" };
```

And those in an npm module:
```
import data from "test-json-import/data.json" assert { type: "json" };
```

https://nodejs.org/docs/latest-v16.x/api/esm.html#json-modules

Also see this minimal reproduction repo: https://github.com/cmcculloh/rollup-import-json

### Actual Behaviour

Rollup errors on the `assert`

```
index.js → stdout...
[!] Error: Unexpected token
index.js (1:61)
1: import data from "./node_modules/test-json-import/data.json" assert { type: "json" };
```

image

### PR DESCRIPTION
**Pull request by lukastaegert**
BREAKING CHANGE: By default, this will add import assertions to all external `.json` file imports in the output.

This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
- resolves #4530
- resolves #3799

### Description
This PR adds basic support for import assertions to Rollup.
- In input files, arbitrary import assertions are allowed. However, there will be a non-blocking warning if the same module is imported with conflicting assertions.
- In ESM output by default for external modules, all assertions from the input are preserved. In case of conflicting assertions, the import assertions of the first import are used.
- While there is also a warning if there are conflicting import assertions for bundled modules, they do not have any effect on the generated output. They can however be inspected by plugins via `this.getModuleInfo`.
- Furthermore, there is a new `output.externalImportAssertions` option that allows to disabled assertions in the output.
- For plugins, assertions are now passed in as a parameter to `resolveId` and `resolveDynamicImport`. If plugins do not return a value for `assertions` in their `resolveId` hook, the assertions from the actual import are used, otherwise they can override assertions at this point. For symmetry with other module options, they can also be changed in the `load` and `transform` hooks. In `this.resolve`, you can now also pass assertions that will be forwarded to `resolveId`.

#### output.externalImportAssertions

Type: `boolean`<br> CLI: `--externalImportAssertions`/`--no-externalImportAssertions`<br> Default: `true`

Whether to add import assertions to external imports in the output if the output format is `es`. By default, assertions are taken from the input files, but plugins can add or remove assertions later. E.g. `import "foo" assert {type: "json"}` will cause the same import to appear in the output unless the option is set to `false`. Note that all imports of a module need to have consistent assertions, otherwise a warning is emitted.

#### `resolveId`

**Type:** `(source: string, importer: string | undefined, options: {isEntry: boolean, assertions: {[key: string]: string}, custom?: {[plugin: string]: any}}) => string | false | null | {id: string, external?: boolean | "relative" | "absolute", assertions?: {[key: string]: string} | null, meta?: {[plugin: string]: any} | null, moduleSideEffects?: boolean | "no-treeshake" | null, syntheticNamedExports?: boolean | string | null}`

…

`assertions` tells you which import assertions were present in the import. I.e. `import "foo" assert {type: "json"}` will pass along `assertions: {type: "json"}`.

…

If you return a value for `assertions` for an external module, this will determine how imports of this module will be rendered when generating `"es"` output. E.g. `{id: "foo", external: true, assertions: {type: "json"}}` will cause imports of this module appear as `import "foo" assert {type: "json"}`. If you do not pass a value, the value of the `assertions` input parameter will be used. Pass an empty object to remove any assertions. While `assertions` do not influence rendering for bundled modules, they still need to be consistent across all imports of a module, otherwise a warning is emitted. The `load` and `transform` hooks can override this.

#### `resolveDynamicImport`

**Type:** `(specifier: string | ESTree.Node, importer: string, {assertions: {[key: string]: string}}) => string | false | null | {id: string, external?: boolean | "relative" | "absolute", assertions?: {[key: string]: string} | null, meta?: {[plugin: string]: any} | null, moduleSideEffects?: boolean | "no-treeshake" | null, syntheticNamedExports?: boolean | string | null}`

…

`assertions` tells you which import assertions were present in the import. I.e. `import("foo", {assert: {type: "json"}})` will pass along `assertions: {type: "json"}`.

#### `load`

**Type:** `(id: string) => string | null | {code: string, map?: string | SourceMap, ast? : ESTree.Program, assertions?: {[key: string]: string} | null, meta?: {[plugin: string]: any} | null, moduleSideEffects?: boolean | "no-treeshake" | null, syntheticNamedExports?: boolean | string | null}`

…

`assertions` contain the import assertions that were used when this module was imported. At the moment, they do not influence rendering for bundled modules but rather serve documentation purposes. If `null` is returned or the flag is omitted, then `assertions` will be determined by the first `resolveId` hook that resolved this module, or the assertions present in the first import of this module. The `transform` hook can override this.

#### `shouldTransformCachedModule`

**Type:** `({id: string, code: string, ast: ESTree.Program, resolvedSources: {[source: string]: ResolvedId}, assertions: {[key: string]: string}, meta: {[plugin: string]: any}, moduleSideEffects: boolean | "no-treeshake", syntheticNamedExports: boolean | string}) => boolean`

#### `transform`

**Type:** `(code: string, id: string) => string | null | {code?: string, map?: string | SourceMap, ast? : ESTree.Program, assertions?: {[key: string]: string} | null, meta?: {[plugin: string]: any} | null, moduleSideEffects?: boolean | "no-treeshake" | null, syntheticNamedExports?: boolean | string | null}`

…

`assertions` contain the import assertions that were used when this module was imported. At the moment, they do not influence rendering for bundled modules but rather serve documentation purposes. If `null` is returned or the flag is omitted, then `assertions` will be determined by the `load` hook that loaded this module, the first `resolveId` hook that resolved this module, or the assertions present in the first import of this module.

#### `this.getModuleInfo`

**Type:** `(moduleId: string) => (ModuleInfo | null)`

Returns additional information about the module in question in the form

```ts
type ModuleInfo = {
  id: string; // the id of the module, for convenience
  code: string | null; // the source code of the module, `null` if external or not yet available
  ast: ESTree.Program; // the parsed abstract syntax tree if available
  hasDefaultExport: boolean | null; // is there a default export, `null` if external or not yet available
  isEntry: boolean; // is this a user- or plugin-defined entry point
  isExternal: boolean; // for external modules that are referenced but not included in the graph
  isIncluded: boolean | null; // is the module included after tree-shaking, `null` if external or not yet available
  importedIds: string[]; // the module ids statically imported by this module
  importedIdResolutions: ResolvedId[]; // how statically imported ids were resolved, for use with this.load
  importers: string[]; // the ids of all modules that statically import this module
  dynamicallyImportedIds: string[]; // the module ids imported by this module via dynamic import()
  dynamicallyImportedIdResolutions: ResolvedId[]; // how ids imported via dynamic import() were resolved
  dynamicImporters: string[]; // the ids of all modules that import this module via dynamic import()
  implicitlyLoadedAfterOneOf: string[]; // implicit relationships, declared via this.emitFile
  implicitlyLoadedBefore: string[]; // implicit relationships, declared via this.emitFile
  assertions: { [key: string]: string }; // import assertions for this module
  meta: { [plugin: string]: any }; // custom module meta-data
  moduleSideEffects: boolean | 'no-treeshake'; // are imports of this module included if nothing is imported from it
  syntheticNamedExports: boolean | string; // final value of synthetic named exports
};

type ResolvedId = {
  id: string; // the id of the imported module
  external: boolean | 'absolute'; // is this module external, "absolute" means it will not be rendered as relative in the module
  assertions: { [key: string]: string }; // import assertions for this import
  meta: { [plugin: string]: any }; // custom module meta-data when resolving the module
  moduleSideEffects: boolean | 'no-treeshake'; // are side effects of the module observed, is tree-shaking enabled
  syntheticNamedExports: boolean | string; // does the module allow importing non-existing named exports
};
```
#### `this.resolve`

**Type:** `(source: string, importer?: string, options?: {skipSelf?: boolean, isEntry?: boolean, assertions?: {[key: string]: string}, custom?: {[plugin: string]: any}}) => Promise<{id: string, external: boolean | "absolute", assertions: {[key: string]: string}, meta: {[plugin: string]: any} | null, moduleSideEffects: boolean | "no-treeshake", syntheticNamedExports: boolean | string>`

…

If you pass an object for `assertions`, it will simulate resolving an import with an assertion, e.g. `assertions: {type: "json"}` simulates resolving `import "foo" assert {type: "json"}`. This will be passed to any [`resolveId`](guide/en/#resolveid) hooks handling this call and may ultimately become part of the returned object.

#### `this.load`

**Type:** `({id: string, resolveDependencies?: boolean, assertions?: {[key: string]: string} | null, meta?: {[plugin: string]: any} | null, moduleSideEffects?: boolean | "no-treeshake" | null, syntheticNamedExports?: boolean | string | null}) => Promise<ModuleInfo>`

### CODE REVIEW

**Comment by justinfagnani** [comment]
@lukastaegert how does this work for inputs that have assertions when there is no special config?

Say:

```ts
import './foo.css' assert { type: 'css' };
```

That's preserved in the output, right?

**Comment by lukastaegert** [comment]
No it is not. Otherwise it would get really complicated. This solution just focuses on consistent output. And I am not aware that CSS is already standardized?

**Comment by justinfagnani** [comment]
Hmm... I think this is the biggest use case for import assertions right now. A library may publish code that uses assertions and non-JS module types and by default they should continue to work after bundling as they did before.

Yes, CSS modules are standardized (In the HTML spec [here](https://html.spec.whatwg.org/multipage/webappapis.html#css-module-script)) and shipping in Chrome and Edge since v93. Firefox and Webkit were involved in the development of import assertions as a result of working out CSS modules, and are both currently implementing the prerequisites for CSS modules (constructible stylesheets and adopedStyleSheets).

**Comment by lukastaegert** [comment]
> Yes, CSS modules are standardized (In the HTML spec [here](https://html.spec.whatwg.org/multipage/webappapis.html#css-module-script))

Fair enough, then we should also add them. Unfortunately I could not find an overview which assertions are supported where. Wasn't there also discussion about an `html` assertion?

**Comment by lukastaegert** [comment]
The problem with keeping assertions is right now that it would blow up the feature with lots of edge cases to be considered. Assertions need to be tracked, stored on external module instances, we need to handle inconsistent assertions. At the same time it can be useful to add assertions even where there were no assertions before. Primary use case would be required JSON that is turned into an import by the commonjs plugin. Though one could argue that that could be the responsibility of the commonjs plugin. The beauty of the current version is that it is easy to turn off.
Note that import assertions are not even a stage 4 feature at this point https://github.com/tc39/proposal-import-assertions

**Comment by thepassle** [comment]
This already looks really great. Thanks a lot for the time and effort you've put into this, and the quick response 🙂 However, as mentioned by Justin, my main usecase is this:

> @lukastaegert how does this work for inputs that have assertions when there is no special config?
> 
> Say:
> 
> ```ts
> import './foo.css' assert { type: 'css' };
> ```
> 
> That's preserved in the output, right?

In case it helps, let me clarify my usecase again: Currently, I can use css import assertions in my code and it will work in browsers that support them, or via something like es-module-shims which also supports them. However, when I try to bundle my app with Rollup, it'll fail on the import assertion. So the issue is that I have valid browser code, which my bundler crashes on.

Ideally what I'd like is for rollup to leave the following import intact:
**SOURCE CODE:**
```js
import './foo.css' assert { type: 'css' };
```

**OUTPUT CODE:**
```js
import './foo.css' assert { type: 'css' };
```

**Comment by lukastaegert** [comment]
> However, when I try to bundle my app with Rollup, it'll fail on the import assertion

This issue is already fixed by this PR.

I will see if we can change the default to keep assertions instead in the next days, but as I said, quite a bit of work.

**Comment by lukastaegert** [comment]
I completely reworked the feature now. See the updated PR description. Basically this will now only take assertions that are already present in the input and warn about conflicting assertions. Plugins can however easily add or remove assertions at many points. There is only a simple new option that allows you to turn off assertions altogether, but for fine-grained control you need the plugin interface.

Unless there are heavy concerns, I would plan to release this feature tomorrow together with Rollup 3.

**Comment by thepassle** [comment]
Judging from the updated description this indeed matches with how I'd expect this to work 🙂 Looking forward to trying this out. Thanks a lot for the discussion, and for the effort towards making this happen!

**Comment by justinfagnani** [comment]
Wow, this was quick work @lukastaegert! Agreed with @thepassle that this looks like what I need out of assertion support. This should allow for one build with no plugins for browsers with native CSS modules support and another build with a plugin to polyfill it, for instance. Thanks for adjusting the PR!!

**Comment by LarsDenBakker** [comment]
Thanks a lot for your efforts here @lukastaegert this really helps a lot to push standards-based development further!

**Comment by Ermelious** [comment]
Hi I'm trying to get "assert" or "with" to work, but after updating the rollup, it still doesn't resolve the issue. May I check how do I configure this so that eslint doesn't treats it as a syntax error?

**Pull request merged**
