### PR TITLE
Exported __esModule when bundling to CJS or UMD in named mode.

### PR DESCRIPTION
**Pull request by cameron-martin**
This is a follow-up PR for issue https://github.com/rollup/rollup/issues/650.

One thing that I'm not sure about is if I have broken sourcemaps. Since I have just added to the end of the output, the mapping should still be valid. But can somebody who is more knowledgeable confirm that I have not?

Also, should I add new test cases to explicitly test this behaviour?

EDIT: I see that [magic-string] takes care of keeping source maps correct.

[magic-string]: https://github.com/Rich-Harris/magic-string

### CODE REVIEW

**Comment by cameron-martin** [comment]
I noticed that babel [inserts this as the first thing in the file][babel], even before doing any requires. I assume this is to make circular dependencies work correctly.

In that case, this needs a minor rethink, potentially moving from [this][pr], to this:

```javascript

(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ?
	(Object.defineProperty(exports, "__esModule", { value: true }), factory(exports, require('external'))) :
	typeof define === 'function' && define.amd ? define(['exports', 'external'], factory) :
	(factory((global.myBundle = global.myBundle || {}),global.external));
}(this, function (exports,external) { 'use strict';

	class Foo extends external.Component {
		constructor () {
			super();
			this.isFoo = true;
		}
	}

	class Bar extends external.Component {
		constructor () {
			super();
			this.isBar = true;
		}
	}

	class Baz extends external.Component {
		constructor () {
			super();
			this.isBaz = true;
		}
	}

	const foo = new Foo();
	const bar = new Bar();
	const baz = new Baz();

	exports.foo = foo;
	exports.bar = bar;
	exports.baz = baz;

}));
```

[babel]: https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-0%2Cstage-2&code=import%20c%20from%20'foo'%3B%0A%0Aexport%20const%20a%20%3D%20'foo'%3B%0Aexport%20const%20b%20%3D%20'foo'%3B%0A%0Aexport%20default%20'foo'%3B
[pr]: https://github.com/cameron-martin/rollup/blob/a660b896dcbca62bbc0ee950aa4a9ebeef9460b9/test/form/dedupes-external-imports/_expected/umd.js

**Comment by guybedford** [comment]
Can we also add this in the AMD case? AMD also respects the __esModule flag in SystemJS, which would fix these builds in jspm too.

**Comment by joeldenning** [comment]
+1 for adding this to the AMD case.

**Comment by Rich-Harris** [comment]
Thanks all – have added support for AMD and the cyclical case with CJS. Had to do it in a separate branch, so there's a separate PR – #685

**Pull request merged**
