### PR TITLE
Wait for bundle input option

### PR DESCRIPTION
**Pull request by Heerschop**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

I'm not sure about the testing part, if it is not okay like this, than can you please give me some pointers.

### Description
Added the `--waitForBundleInput` option. The current version of rollup will generate the "Error: Could not resolve entry module" error when the input file or directory does not exists. With this pull request you can use the `--waitForBundleInput` option so rollup will wait for the input files to be created.

This will make the usage of rollup in conjunction with other tool easier. For example when you start `tsc --watch` and `rollup --watch` in parallel. The current version of rollup will generate an error, because the bundle input is not available yet. When using the new `--waitForBundleInput` option, rollup can just wait for the bundle input file to be available.

### Example using rollup when directory or file does not exist
``` bash
rollup --config --watch

rollup v2.10.2
bundles tmp/main.js → dist/bundle.js...
[!] Error: Could not resolve entry module (tmp/main.js).
Error: Could not resolve entry module (tmp/main.js).
    at error (./node_modules/rollup/dist/shared/rollup.js:161:30)
    at ModuleLoader.loadEntryModule (./node_modules/rollup/dist/shared/rollup.js:17547:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async getCombinedPromise (./node_modules/rollup/dist/shared/rollup.js:17438:13)
    at async ModuleLoader.awaitLoadModulesPromise (./node_modules/rollup/dist/shared/rollup.js:17443:9)
    at async ModuleLoader.addEntryModules (./node_modules/rollup/dist/shared/rollup.js:17339:33)
    at async Promise.all (index 0)
    at async Graph.parseModules (./node_modules/rollup/dist/shared/rollup.js:18548:63)
```

### Example using rollup with the new `--waitForBundleInput` option
``` bash
rollup --config --watch --waitForBundleInput

rollup v2.10.5
bundles tmp/main.js → dist/bundle.js...

[2020-05-21 12:02:40] waiting for bundle input tmp/main.js
created dist/bundle.js in 2.8s

[2020-05-21 12:03:08] waiting for changes...
```

### CODE REVIEW

**Comment by lukastaegert** [comment]
Thank you for your PR. I see how this is useful for your setup, however I am not sure if we want to make this a core feature. Reasons are mainly architecturally as I think this feature is only ever useful in watch-mode, but now adds quite a bit of additional churn to the already very crowded module loader. And there will be some maintenance cost in the future as well as this possibly makes some upcoming refactorings harder.

Why not make it a plugin, something like the following should solve your use case:

```js
function waitForInputPlugin() {
  return {
    name: 'wait-for-input',
    async buildStart(options) {
      const inputSpecifiers =
        typeof options.input === 'string'
          ? [options.input]
          : Array.isArray(options.input)
          ? options.input
          : Object.keys(input);

      let lastAwaitedSpecifier = null;
      checkSpecifiers: while (true) {
        for (const specifier of inputSpecifiers) {
          if (await this.resolve(specifier) === null) {
            if (lastAwaitedSpecifier !== specifier) {
              console.log(`Waiting for input "${specifier}"...`);
              lastAwaitedSpecifier = specifier;
            }
            await new Promise(resolve => setTimeout(resolve, 500));
            continue checkSpecifiers;
          }
        }
        break;
      }
    }
  };
}
```

It makes use of the fact that the builtin handler for `this.resolve` returns `null` for missing files. Then it prevents starting the build process by returning a promise in buildStart that only resolves once all inputs can be found.

**Comment by Heerschop** [comment]
Thank's for the feedback, the plugin approach  solve my issue very well. 

To make this easier to use by others, it might be an option to make this the default behavior when using watch-mode, in this way there will be way less churn. The change will mostly be limited to the `loadEntryModule` method in the `ModuleLoader.ts` file, it could look like this than:

``` typescript
let resolveIdResult: ResolveIdResult;
const unresolvedFiles = new Set<string>();

while (
  (resolveIdResult = await resolveId(
    unresolvedId,
    importer,
    this.preserveSymlinks,
    this.pluginDriver,
    null
  )) === undefined && this.graph.watcher !== null
) {
  if (!unresolvedFiles.has(unresolvedId)) {
    this.graph.watcher.emit('event', {
      code: 'INPUT_WAIT',
      input: unresolvedId
    });

    unresolvedFiles.add(unresolvedId);
  }

  await new Promise<void>(resolve => {
    setTimeout(resolve, 500);
  });
}
```
In this approach the availability of the `this.graph.watcher` field will determine when to wait or not.

I'm willing to change the pull request or create a new one, if you are interested, if not i'm happy also.

**Comment by lukastaegert** [comment]
I have thought about it a little and I am still somewhat hesitant about this. Nevertheless I see that ease of use is of course valuable. On the other hand, I do not feel good about this being the default behaviour for the pure JS API as well, there may be quite a few edge case scenarios that play into this.
One thing I could get behind, though, would be to make this a feature only for CLI. The CLI already has some special plugins it injects, e.g. for stdin pipe support here https://github.com/rollup/rollup/blob/462bff7b1a0c384ecc3e278b1ea877e637c70f41/cli/run/commandPlugins.ts#L10

Also it is a very well defined environment in that it always runs in Node and there are no downstream tools to consider.

The plugin could be injected somewhere here https://github.com/rollup/rollup/blob/462bff7b1a0c384ecc3e278b1ea877e637c70f41/cli/run/watch-cli.ts#L18

What do you think? With regard to testing, you could take inspiration from the tests here https://github.com/rollup/rollup/tree/master/test/cli/samples/watch

**Comment by Heerschop** [comment]
That sound like a solid solution. I tested it and it is working, in my test the plugin is loaded in the `watch-cli.ts` like this:
``` typescript
({ options: configs, warnings } = await loadAndParseConfigFile(configFile!, command));
reloadingConfig = false;

for(const config of configs){
  if (config.plugins) {
    config.plugins.push(waitForInputPlugin());
  }
}
```


I can update the pull request accordingly.

For my use case it would be practical to have the option to enable the plugin for build as well.
I tried something like this `rollup --config --plugin wait-for-input` but then it can not find and load the plugin. It has to be made available first some how, it think.

I can still add the plugin to the `rollup.config.js` as well. But then it will not overload the build-in one, nevertheless that they have the same name. This will result in loading the plugin two times when using the `--watch` option, or is it possible to use a plugin for a particular options only?

But maybe my use case is a bit too specialised.

**Comment by lukastaegert** [comment]
> For my use case it would be practical to have the option to enable the plugin for build as well

Then maybe we do it yet again slightly differently, add an option `--waitForBundleInput` but make it CLI only, like `--env` or `--plugin`. Then the plugin can be added together with all other plugins in `addCommandPluginsToInputOptions` in `commandPlugins.ts`, depending on this option.

**Comment by Heerschop** [comment]
That sounds good one small addition, shall we always load the plugin when in watch mode?

So the `--waitForBundleInput` option is not needed when using the `--watch` option. When doing it this way, there will be no way to disable the plugin when using the `--watch` option, this is not a problem is it?

**Comment by lukastaegert** [comment]
IMO if we add an option I would not set it automatically for the reason you mentioned, you cannot get rid of it. If there is a typo in the input name, it might be helpful for the build to fail even in watch-mode instead of "hanging". This will also make this very much a non-breaking change. One can still revisit making this a default for watch-mode with the next major.

**Comment by Heerschop** [comment]
I agree :-), i will update the pull request in the way you suggested.

**Comment by Heerschop** [comment]
I have updated the pull request as suggested. The test are probably not good enough but this is the best i can do.

**Comment by lukastaegert** [comment]
Looks good, I'll add some tests

**Comment by Heerschop** [comment]
No concerns at all thank you and it was nice working together.

**Pull request merged**
