### PR TITLE
[v3.0] New hashing algorithm that "fixes (nearly) everything"

### LINKED ISSUE #2839: Chunk hashes should be based on the output
### Expected Behavior / Situation

Adding a minification plugin (which will change a chunk's output contents) should also change the chunk's file hash.

### Actual Behavior / Situation

The chunk's hash is unchanged by minification plugins, which can result in lots of subtle bugs when deploying files to production.

For example, consider the following scenario:

- A user deploys a web app to production with buggy minification settings (e.g. property mangling that's inconsistent across chunks).
- The users discovers the mistake and redeploys, thinking they've fixed the problem.
- The bug will persist for any returning users since the chunk filenames won't have changed and the browser will load the old (cached) versions of those files.

### Modification Proposal

I see [hash determination was already discussed](https://github.com/rollup/rollup/issues/1995#issuecomment-367039123) when code splitting was added to rollup, but I think there are some problems with that logic -- specifically this part:

> Calculate a content hash for each chunk. This initial hash should only depend on the content of this chunk itself, not on its imports

If the imports are not included in the content hash calculation, then partial redeploys will break.

For example, consider a case where you have chunk `A` which depends on chunk `B`, which depends on chunk `C`. If the contents of `C` changes, **then the hashes of all three chunks needs to change**. The reason is because if the contents of `C` changes then it needs a new filename in order to cache-bust. But if `C` has a new filename then the contents of `B` must *also* change (e.g. the `import` path) in order to load the correct version of `C`. And if the contents of `B` change then it also needs a new filename, and so on and so forth all the way down to `A`.

As a result, I don't see any feasible way to correctly determine file hashes without considering the entire file, **including its imports and their file paths**.

My recommendation is Rollup should handle this itself after all plugins that can modify source code have run. If it processes all chunks in reverse [topologically](topological sort) sorted order, then it should be able to properly calculate the hashes of all chunks based on their full, final contents (including import statements).

The main problem/issue I see with this approach is how to handle circular dependencies. However, Rollup already warns on circular dependencies, so the simplest solution seems to be just continue to warn but add some additional text that explains that content hashes are non-deterministic in bundles with circular dependencies.

* * *

**Aside:** hopefully this issue won't be as tricky to solve in the future once all browsers support [import maps](https://github.com/WICG/import-maps), because once they do all file hashes can just be added to the import map declaration rather than having to appear in the file itself.

### LINKED ISSUE #3398: Parametrize output.banner/output.footer
### Feature Use Case
Prepend//append different content to different entry points.
At the moment e.g. the `banner` could be `string | (() => string | Promise<string>)`. In case of a function, it would be great to have some idea which entry point are we working with in order to resolve correct content and insert it to the code file.

This is obviously useful only when working with multiple entry points, i.e. `input` is of type `{ [entryName: string]: string }`

In my case, I'd use it for some of those standalone JSDoc such as `@module` which seem to disappear in the output generated from rollup.

### Feature Proposal
banner/footer function will have some more information in its parameters. 
It could be the value pair from `input` map.
It could be the placeholders' values used in `output.entryFileNames`
It could have more output chunk information ?
It could something else.

I'd go with the easiest choice, not sure which one it is.

### LINKED ISSUE #3415: JS hash fails to change when asset URL changes
- Rollup Version: 1.32.0
- Operating System (or Browser): OSX
- Node Version (if applicable): v12.16.1
- Link to reproduction: https://github.com/jakearchibald/rollup-hash-bug

In this demo, both `src1` and `src2` are built. The only difference between the two is the content of `some-asset.txt`.

### Expected Behavior

The hash of both the JS and asset is different between builds, since the JS imports the asset, the content of its file has changed.

### Actual Behavior

Only the hash of the txt file changes.

### LINKED ISSUE #3416: JS hash changes when src folder moved
- Rollup Version: 1.32.0
- Operating System (or Browser): OSX
- Node Version (if applicable): v12.16.1
- Link to reproduction: https://github.com/jakearchibald/rollup-hash-bug-2

### Expected Behavior

The two `src` folders have identical contents, their output filenames should not differ between builds.

### Actual Behavior

All three files change hash.

#2839 may be related.

### LINKED ISSUE #3519: Ability to collect chunk info before or during renderchunk
### Feature Use Case
I am writing a plugin that needs to do work in `renderChunk`, but in order to do this it has to know more about the rest of the chunk graph. For example for a given chunk's dynamic imports, it has to know their static imports. Right now I can access the dynamic imported filenames, but I have no way to acces the chunk info for this.

I tried a lot of different things, for example the `augmentChunkHash` hook gives some minimal chunk information, but it's not enough. 

I can use `generateBundle` as a general escape hatch, but the big downside here is that it runs after any chunk optimizations such as babel and terser.

### Feature Proposal

I don't know enough about the rollup internals, so I'm just throwing out some ideas from a plugin writer's perspective. Of course I'm happy to learn about methods available in the existing hooks I may have overlooked!

In order of preference:

- Add a `bundle` or `chunks` parameter to the `renderChunk` hook containing information about the other chunks. (probably with less info than in `generateBundle`)
- Add a hook that runs before `renderChunk` giving information about the chunking graph (again with less info) 
- Add a `this.getChunkInfo` method so that we can get the chunk based on the dynamic import id

### LINKED ISSUE #3697: Inconsistent (JS) Output Hashes with emitted CSS files
- Rollup Version: 2.23.0
- Operating System (or Browser): macOS
- Node Version (if applicable): 10.x - 14.6
- Link to reproduction: https://github.com/lukeed/bug-rollup-css-hashes

### Expected Behavior

The generated file hashes should be identical between builds since nothing is changing.

### Actual Behavior

Within ~10 builds of the same source files, there will be files that have different build hashes despite having identical output content – or in most cases, identical content _except_ for import statements to other files that also inexplicably change.

In the repro provided (please see readme), there are two files that will have different output hashes within a 10-build loop. They have a _maximum_ of 2 hash variations per file, which I find odd.

It seems to happen with a particular combination of shared dependency trees, dynamic imports, and CSS files (emitted as assets). I dumbed it down considerably, but it's by no means a farfetched application setup.

Thanks~!

### LINKED ISSUE #3790: A method of adding an import based on dependency graph
### Feature Use Case

Sapper has a CSS-handling plugin, which has recently been significantly cleaned up and is about ready to graduate into a separate Rollup plugin for wider community use:

https://github.com/sveltejs/sapper/blob/ead10eebb7416971a390a0190f1df7c1f3327791/src/core/create_compilers/RollupCompiler.ts#L156

It finds CSS that a dynamically imported chunk tree includes and then rewrites the dynamic imports with an extra bit of code. That code makes it so that in parallel to the original dynamic import we also write `link` tags pointing to the CSS.

So as not to duplicate code across chunks, this plugin emits a new `inject_styles` chunk. It then adds an import to that chunk where it's used. The problem here is that this `import` does not show up in the `chunk.imports` for the plugins that follow it.

### Feature Proposal

Things I've tried:
* I've tried doing `chunk.imports.push(newImport)` when adding the import in `generateBundle`. This does not persist for the next plugin
* I've tried rewriting the code in `transform`. This does not work because I don't have access to the dependency graph. When I call `this.getModuleInfo` it returns empty arrays for the `importedIds` and `dynamicallyImportedIds`
* I've tried rewriting the code in `renderChunk`. However, I don't know the file name to add. If I simply do `import __inject_styles from 'inject_styles.js'` then that doesn't get properly rewritten to include the hash in the filename.

It would be nice if at least one of these worked or there was another solution to this problem

### Related Requests

https://github.com/rollup/rollup/issues/3519

### LINKED ISSUE #4317: I need a longer hash with customizable length.
### Feature Use Case

The hash value of fixed 8-bit file content is too easy to conflict. I need a longer hash with customizable length. How should I set it

[hash:30]
[hash:6]

### Feature Proposal

[hash:30]
[hash:6]

### LINKED ISSUE #4426: How to keep [hash] unchanged when in different path
I found same source file will create different [hash] when in different file path. 

How to keep their hash unchanged even they are in different file path? Just according to their content, like [contenthash]

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [x] bugfix
- [x] feature
- [x] refactor
- [x] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [x] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

List any relevant issue numbers:
* Resolves #2839
* Resolves #3398
* Resolves #3415
* Resolves #3416
* Resolves #3519
* Resolves #3697
* Resolves #3790
* Resolves #4317
* Resolves #4426

### Description
This is the one feature I always wanted to have ready before releasing Rollup v3, which ultimately made me delay that release far too much.

#### The previous hashing algorithm

This is how the previous chunk hashing algorithm worked:
* render all modules except dynamic imports and import.meta chunk references
* based on this, calculate the content hash of all modules in a chunk
* extend those hashes by taking all known dependencies into account and everything dynamic that may be added in the chunk wrapper
* update the dynamic imports and import.meta chunk references
* render the chunk wrappers that include all static imports and exports
* run the result through the `renderChunk` plugin hook

This approach has several problems:
* any transformation in `renderChunk` is completely ignored.
* taking _every_ possible change in the chunk wrappers into account is a fragile business
* hashes are chronically unstable as they may take things into account that are actually not relevant for the result.

#### Possible solution: Sorted rendering

One way to solve this would be to first render all chunks that do not have any dependencies, then iteratively render all chunks that only have rendered chunks as dependencies until all chunks are rendered.
While this would work in some cases, this approach has several drawbacks:
* It does not support circular dependencies between chunks. This is a very important feature because in that context, a circular dependencies would also be two chunks that dynamically import each other. Moreover, Rollup heavily relies on this for dynamic imports by moving all dependencies that are shared between the importing chunk and the import target into the importing chunk, causing a static import of the importing chunk to appear in the imported chunk.
* It means we need to know all dependencies of a chunk before rendering the chunk even though the `renderChunk` hook might introduce additional dependencies.

#### Implemented solution: Hash placeholders

Therefore I decided upon a different solution that works like this:
* Assign a preliminary chunk name to each chunk. If there is no hash in the file name this will be the final file name, but if it would contain a hash it will instead contain a placeholder of equal length.
* Render all modules in the chunk. As we already have the preliminary file names, we can directly render all dynamic imports and import.meta chunk references.
* Render the chunk wrapper. We also use the preliminary file names for the chunk imports.
* Run the chunk through the `renderChunk` hook.
* Calculate the content-only hash of the chunk by replacing all placeholders in the chunk with a default placeholder and then generating a hash.
* Once this is done for all chunks, calculate the final hashes by searching which placeholders are contained in each chunk and updating the chunk hash, taking the content-only hashes of all transitive dependencies into account.
* Replace the placeholders with the final hashes. As we made sure the placeholders have the same length as the hashes, we do not need to update sourcemaps.

In order to avoid accidentally replacing non-placeholders, the placeholders make use of the fact that JavaScript supports unicode characters. I used four random characters from the reserved plane, currently `\uf7f9\ue4d3` for the start of the placeholder and `\ue3cc\uf1fe` for the end of the placeholder.

This approach also allows us, to give full access to the chunk graph in `renderChunk`, though the names are preliminary at this point. But as Rollup does not make assumptions about the output of `renderChunk`, you can freely inject chunk names in that hook now.

All in all, this changes the plugin hook graph in the following way:

```mermaid
flowchart TB
    classDef default fill:transparent, color:#000;
    classDef hook-parallel fill:#ffb3b3,stroke:#000;
    classDef hook-sequential fill:#ffd2b3,stroke:#000;
    classDef hook-first fill:#fff2b3,stroke:#000;
    classDef hook-sequential-sync fill:#ffd2b3,stroke:#f00;
    classDef hook-first-sync fill:#fff2b3,stroke:#f00;

    augmentchunkhash("augmentChunkHash"):::hook-sequential-sync
    click augmentchunkhash "/guide/en/#augmentchunkhash" _parent

	banner("banner"):::hook-sequential
	closebundle("closeBundle"):::hook-parallel
	footer("footer"):::hook-sequential
	generatebundle("generateBundle"):::hook-sequential
	intro("intro"):::hook-sequential
	outputoptions("outputOptions"):::hook-sequential-sync
	outro("outro"):::hook-sequential
	renderchunk("renderChunk"):::hook-sequential
	renderdynamicimport("renderDynamicImport"):::hook-first-sync
	rendererror("renderError"):::hook-parallel
	renderstart("renderStart"):::hook-parallel
	resolvefileurl("resolveFileUrl"):::hook-first-sync
	resolveimportmeta("resolveImportMeta"):::hook-first-sync
	writebundle("writeBundle"):::hook-parallel

	outputoptions
	--> renderstart
	--> |each chunk|beforerenderdynamicimport

	afteraddons
	--> |each chunk|renderchunk

	augmentchunkhash
	--> generatebundle
	--> writebundle
	.-> closebundle

	subgraph generateChunks [" "]
	    direction TB
	    beforerenderdynamicimport(( ))
        ---> beforeresolveimportmeta(( ))
        ----> beforereaddons(( ))
        --> banner & footer & intro & outro
        --> afteraddons(( ))
        .-> |next chunk|beforerenderdynamicimport

	    beforerenderdynamicimport
        --> |"each import()"|renderdynamicimport
        --> beforerenderdynamicimport

    	beforeresolveimportmeta
    	--> |each import.meta.*|beforeimportmeta(( ))
    	--> |import.meta.url|resolvefileurl
    	--> afterresolveimportmeta(( ))

	    beforeimportmeta
	    --> |other|resolveimportmeta
	    --> afterresolveimportmeta

	    afterresolveimportmeta
	    --> beforeresolveimportmeta
	end

	renderchunk
    --> augmentchunkhash
    .-> |next chunk|renderchunk

	style generateChunks stroke-width:0px;

	rendererror
	.-> closebundle

```

#### Chunk information available to hooks and options

Some hooks now receive additional information. To go into details, let's first define some types:

* A `PrerenderedChunk` contains very basic chunk information before any rendering takes place and before the chunk name has been generated. After this update, this reduced set of chunk information is only passed to the `entryFileNames`  and `chunkFileNames` options. Note that for obvious reasons, we no longer have the rendered module information available. Instead, this type now gets a list of included `moduleIds` so that one can at least know what is roughly contained in the chunk.
  ```ts
  interface PreRenderedChunk {
  	exports: string[];
  	facadeModuleId: string | null;
  	isDynamicEntry: boolean;
  	isEntry: boolean;
  	isImplicitEntry: boolean;
  	moduleIds: string[];
  	name: string;
  	type: 'chunk';
  }
  ```

* A `RenderedChunk` contains the full rendering information of the chunk. File names in imports and rendered modules will contain placeholders instead of file hashes, though. This information is available in the `renderChunk` hook, the `augmentChunkHash` hook, and in the `banner`/`footer`/`intro`/`outro` hooks and options.

  Also, the signature of `renderChunk` is extended to receive a fourth parameter `meta: { chunks: { [fileName: string]: RenderedChunk } }` that gives access to the entire chunk graph.

Note also that when adding or removing imports or exports in `renderChunk`, plugins should now take care to update the `RenderedChunk` object they receive to reflect the updated information. This will provide correct information to subsequent plugins and to the final bundle as Rollup will also replace hashes in `imports`, `importedBindings` and `dynamicImports` (besides `implicitlyLoadedBefore` and `fileName`).

  ```ts
  interface RenderedChunk {
  	dynamicImports: string[];
  	exports: string[];
  	facadeModuleId: string | null;
  	fileName: string;
  	implicitlyLoadedBefore: string[];
  	importedBindings: {
  		[imported: string]: string[];
  	};
  	imports: string[];
  	isDynamicEntry: boolean;
  	isEntry: boolean;
  	isImplicitEntry: boolean;
  	moduleIds: string[];
  	modules: {
  		[id: string]: RenderedModule;
  	};
  	name: string;
  	referencedFiles: string[];
  	type: 'chunk';
  }
  ```

#### Additional new features
* If `intro`, `outro`, `banner`, `footer` are functions, they are now called per chunk. While they do not get access to the rendered modules in the chunk, they get a list of all included module ids.
* Hash length can be changed in the file name pattern, e.g. `[name]-[hash:12].js` will create 12 character hashes

#### Breaking changes
* `entryFileNames` and `chunkFileNames` no longer get access to a `modules` object with the content of rendered modules. Instead, the get a list of included `moduleIds`.
* The order of plugin hooks has changed, compare the graph above with the graph at https://rollupjs.org/guide/en/#output-generation-hooks
* The 'fileName` and referenced `imports` in the `renderChunk` hook will get file names with placeholders instead of hashes. These file names can be safely used in the return value of the hook, though, as any hash placeholders will be replaced with the actual hashes in the end.

Also, some deprecated features have been removed, and the Node compatibility target has been raised, but I will create separate PRs for those to make them explicit.

### CODE REVIEW

**Comment by lukastaegert** [comment]
@yyx990803, @patak-dev, @antfu, @marvinhagemeister while it will take some time before I release this with Rollup 3 as I want to get some other PRs ready, this may be quite relevant for you, and supporting this will likely be a breaking change for you as well.
I will try to create a first pre-release version soon.

**Comment by patak-dev** [comment]
@lukastaegert this is huge! It will allow some heavy simplifications in Vite core, we may be able to remove most of our custom asset path handling in favor of a solution that plays well with other plugins in the rollup ecosystem.

It is also quite timely. We were about to release Vite v3, in around 10 days. But we may need to delay it as needed to already include the breaking to rollup v3. Thanks for the heads up, and a pre-release version will be quite helpful. Do you have some ETA in mind for releasing Rollup 3 stable? We could release Vite against a rollup v3 RC if necessary.

**Comment by marvinhagemeister** [comment]
This is awesome!! Thank you so much for tackling this problem 💯

**Comment by lukastaegert** [comment]
Thank you! @patak-dev Rollup 3 will definitely not be ready in 10 days, but a solid pre-release should be no problem. I hope we can pull off v3 in a month or two at most, I will try not to put too much else in it, but there are some other smaller breaking changes that have been held back for some time that I want to tackle.

**Comment by patak-dev** [comment]
Thanks for the info @lukastaegert, after some discussions with the team and ecosystem it, we are thinking of keeping our current plans and releasing Vite v3 using Rollup v2 in around ~10 days. Once Rollup v3 is stable, and plugins in the rollup ecosystem have been updated to support it, we can release Vite v4. So no rush from our side. Thanks again for all your work on improving rollup.

**Comment by frank-dspeed** [comment]
I see one edge case that needs extended info and testing when we use html as input it could get processed by parse5 and i am not sure if parse5 handels this correct parse5 gets used in many SSR stuff and other places its the defacto most often used HTMLParser at present in the NodeJS Ecosystem 

## Does Parse5 handle that correct?
the placeholders make use of the fact that JavaScript supports unicode characters. I used four random characters from the reserved plane, currently ```\uf7f9\ue4d3``` for the start of the placeholder and ```\ue3cc\uf1fe``` for the end of the placeholder.

**Comment by lukastaegert** [comment]
Currently, placeholders are only used inside JavaScript files while the asset handling logic has not changed. Therefore I do not see why you would use a placeholder in an HTML file, considering you would need to replace the placeholder yourself. That being said, if you would support us by testing this, it definitely does not hurt, maybe there will be a reason to extend the logic to asset files eventually.
In any case, you can use UTF-8 characters like emojis in HTML already, it would feel more like a bug of parse5 if it is not supported. There is a good reason I stayed away from characters with "meaning" like `\0`.

**Comment by frank-dspeed** [comment]
@lukastaegert your maybe correct but i only saw that rollup uses unicode chars an i remember that there are a lot of problems thats why i tought it would be clever to document that if it later becomes relevant i will also now work on a test inside parse5 with that chars and when it works it will not hurt and we are sure that there are no upcoming magic errors that we can not track.

**Comment by frank-dspeed** [comment]
also i guess we should add @jakearchibald here and invite him to test that as he is deep into hashing and has already tests for some cases i guess he creates the input for web.dev

**Comment by lukastaegert** [comment]
I already added comments to the issues he created over time 😜

**Comment by lukastaegert** [comment]
I know this probably needs much more testing and review, but I will merge it to the release branch early to create a "proper" pre-release tag and version for testing and do possible updates in separate PRs.

**Comment by lukastaegert** [comment]
I just released the first pre-release version `rollup@3.0.0-0` under the `beta` tag for you to try out. Maybe you can use it to already create test branch and see how it works for you. Feedback ab out the hashing should ideally go to this PR.

**Comment by develohpanda** [comment]
Thank you for this wonderful write up and the work that went into this PR! 🎉

> The order of plugin hooks has changed, compare the graph above with the graph at [rollupjs.org/guide/en/#output-generation-hooks](https://rollupjs.org/guide/en/#output-generation-hooks)

If anybody else was curious about the previous graph to compare against, now that this PR has been merged, I dug it out of Wayback Machine [here](https://web.archive.org/web/20220929174938/https://rollupjs.org/guide/en/#output-generation-hooks).

**Pull request merged**
