### PR TITLE
Implement try-statement-deoptimization for feature detection, tree-shake unused arguments

### LINKED ISSUE #1771: Unused constructor call is unsafely stripped out
Example [here](https://rollupjs.org/repl?version=0.52.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMGhhc0JhZFBvbHlmaWxsJTIwJTNEJTIwZmFsc2UlM0IlNUNudHJ5JTIwJTdCJTVDbiU1Q3R2YXIlMjBub25FeHRlbnNpYmxlT2JqZWN0JTIwJTNEJTIwT2JqZWN0LnByZXZlbnRFeHRlbnNpb25zKCU3QiU3RCklM0IlNUNuJTVDdG5ldyUyME1hcCglNUIlNUJub25FeHRlbnNpYmxlT2JqZWN0JTJDJTIwbnVsbCU1RCU1RCklM0IlNUNuJTVDdG5ldyUyMFNldCglNUJub25FeHRlbnNpYmxlT2JqZWN0JTVEKSUzQiU1Q24lN0QlMjBjYXRjaCUyMChlcnIpJTIwJTdCJTVDbiU1Q3RoYXNCYWRQb2x5ZmlsbCUyMCUzRCUyMHRydWUlM0IlNUNuJTdEJTVDbmNvbnNvbGUubG9nKGhhc0JhZFBvbHlmaWxsKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==):

```js
var hasBadPolyfill = false;
try {
	var nonExtensibleObject = Object.preventExtensions({});
	new Map([[nonExtensibleObject, null]]);
	new Set([nonExtensibleObject]);
} catch (err) {
	hasBadPolyfill = true;
}
console.log(hasBadPolyfill);
```

Result:

```js
'use strict';

var hasBadPolyfill = false;
try {
	var nonExtensibleObject = Object.preventExtensions({});
	
} catch (err) {
	hasBadPolyfill = true;
}
console.log(hasBadPolyfill);
```

However this breaks the feature detection we were trying to do.
(In our case, this led to a crash: https://github.com/facebook/react/pull/11745.)

### LINKED ISSUE #2273: Handling feature detections
Some ideas:

1. Deopt any literal value or return value interpretations when inside a `try {}` block, or even just deopt try blocks entirely.
2. On the "literal members" definitions, include a special property "featureDetection" whether that member might want to be feature detected. In those cases, we add unknown uncertainty to the feature detection patterns (`typeof X`, `Object.create === undefined`, etc)

### LINKED ISSUE #2540: "pureFunctions" are not actually pure, and are not safe to remove.
**tl;dr**: the vast majority of the language builtins listed in https://github.com/rollup/rollup/blob/master/src/ast/nodes/shared/pureFunctions.ts can throw exceptions, which makes them not "pure", and decidedly unsafe to remove.

Specifically, the es6-shim - something that is widely deployed on a not-insignificant percentage of the internet - has many things like [this line](https://github.com/paulmillr/es6-shim/blob/8583cbe2186ec12bfbf4218ccbce7fc73f96de87/es6-shim.js#L1622) that rely on a thrown exception, or lack thereof, to indicate if a builtin implementation is broken and needs replacement. We pre-build our shims at @airbnb with rollup, and this resulted in our website being broken for, in particular, IE 11 users - because rollup transpiled this:
```js
var objectKeysAcceptsPrimitives = !throwsError(function () { Object.keys('foo'); });
```
into this:
```js
var objectKeysAcceptsPrimitives = !throwsError(function () {  });
```

Anything that can possibly throw an exception under any circumstances (`Object.keys(null)`, for example) is not something that's necessarily safe to remove (depending on if the parameters are all inline literals that meet the appropriate criteria), and although I haven't exhaustively gone through the list of `pureFunctions`, at a glance, almost all of them have a path in the spec that can throw.

I've patched around this issue in v0.35.4 of es6-shim by adding `return` so that rollup is not fooled into thinking the statements are no-ops, but it'd be ideal to fix this in rollup itself - there may be other cases I've not yet discovered..

### LINKED ISSUE #2869: Tree-shaking drop useful code
Tree-shaking algorithm seems to be too aggressive; it drops some useful code breaking runtime feature detection. The dropped code is part of a module of core-js (v2.6.7) installed as dependencies of @babel/polyfill (v.7.4.4).

- Rollup Version: 1.12.3
- Operating System (or Browser): macOS Sierra 10.13.6
- Node Version: 8.11.1

### How Do We Reproduce?
Clone this repository https://github.com/straccia17/rollup-treeshake-bug, execute yarn, then yarn run build.

### Expected Behavior
Expected behavior is shown by dist/bundle-fixed.js files

### Actual Behavior
Actual behavior is shown by dist/bundle.js files

### Workaround
Set `treeshake: false` in rollup.config.js

### LINKED ISSUE #2891: Class expression with extends clause is removed
- Rollup Version: 1.13.1
- Operating System (or Browser):
- Node Version: 12.3.1

### How Do We Reproduce?

Consider the following exported function containing an anonymous class expression.

```js
export function isConstructor(fn) {
    if (fn === null)
        return false;
    try {
        void class extends fn { };
    } catch {
        return false;
    }
    return true;
}
```

In the bundled version, the class expression is dropped, causing the function to always branch out of the catch block.

```js
function isConstructor(fn) {
    if (fn === null)
        return false;
    try {
    } catch {
        return false;
    }
    return true;
}
```

The only way I found to fix the issue is turning off treeshaking completely, which is not desirable.

### Expected Behavior

```js
isConstructor(true);   // false
isConstructor(isNaN);  // false
isConstructor(String); // true
```

### Actual Behavior

```js
isConstructor(true);   // true
isConstructor(isNaN);  // true
isConstructor(String); // true
```

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
resolves #2891
resolves #2869
resolves #2540 
resolves #2273 
resolves #1771 

### Description
This PR adds a heuristic around try-catch blocks that allows for feature detection workflows, or workflows that depend on uncommonly thrown errors such as checking if `class test extends someVar {}` throws an error to see if `someVar` is a valid constructor.

I checked that with this modification, all feature detections of `core-js` should work as intended. Besides the try-catch deoptimization, this PR will also tree-shake unused function arguments.

#### Try-statement deoptimization
This PR adds a heuristic based on the idea that in order to detect an uncommonly thrown error, you will probably put it into the try-statement of a try-catch construct (alternatively promises would work as well but the heuristic will not cover those).

Therefore:
* Tree-shaking will be disabled inside try-statements, i.e. code directly nested inside a try-statement will be retained.
* If a variable is
  * called from inside try-statement
  * called directly, i.e. `myVar()` and not e.g. `(myVar || otherVar)()`.
  * can be uniquely resolved to a function declaration/expression (i.e. variable is never reassigned)
  
  then  tree-shaking will also be disabled in that function; however, other variables called from such a function will NOT be deoptimized to contain the infectious nature of this feature.
* If a parameter of a function is called inside a try-statement, this parameter is marked in a special way. In all places this function is called, the argument provided for this parameter will be treated the same way as if it was called from within the try-statement. This is to allow `core-js` style feature detection:
  ```js
  function fails(exec) {
    try {
      return !!exec();
    } catch (e) {
      return true;
    }
  }
  
  var MAX_UINT32 = 0xffffffff;
  var SUPPORTS_Y = !fails(function() {
  	RegExp(MAX_UINT32, 'y'); // this will now be retained by Rollup
  });
  ```

#### Unused argument tree-shaking
To use some of the logic built for this feature for other cool stuff, this PR will not also tree-shake unused arguments from function calls. To that end, each time the call target of a call can be uniquely resolved, unused arguments will be removed from the call. More precisely:
* A parameter that is either
  * not defined or
  * an identifier (i.e. the parameter is not a pattern or the paramter has a default value) and defined but not used by a function

  is "unused" unless `arguments` is accessed inside that function.
* Call arguments corresponding to "unused" parameters will be removed if
  * they have no side effects (e.g. they are not the result of a side-effect-ful function call)
  * there are no other arguments after that call that are included (to maintain the correspondence between arguments and parameters).
* Parameters themselves will *not* be removed even if they are unused to avoid difficult edge-cases when some logic relies on `functionName.length` to determine the number of parameters for e.g. currying.

This enables tree-shaking in scenarios such as

```js
// input
const options = {
  prefix: 'cool '
}

const useOptions = false;

function doIt(value, options) {
  if (useOptions) console.log(options.prefix + value);
  else console.log(value);
}

doIt('feature', options);

// result
function doIt(value, options) {
  console.log(value);
}

doIt('feature');
```

### CODE REVIEW

**Comment by lukastaegert** [comment]
At the moment it would not make a difference for dynamic imports. Except to make sure that dynamic imports inside try-blocks are always included if the try-block is included.

**Comment by ljharb** [comment]
It’d be great to test this on es5-shim, es6-shim, and all of airbnb-browser-shims, since that would catch the bug referenced in #2540.

**Comment by lukastaegert** [comment]
You can try it out by installing rollup via `npm install rollup/rollup#try-block-deoptimization`.

**Comment by lukastaegert** [comment]
at least es6-shim should be fine, `throwsError` is exactly something that should be caught by the heuristic.

**Comment by lukastaegert** [comment]
Any help here is welcome, a simple way to test it could be to write an entry point that contains the shim, e.g. `main.js`, and then run

```sh
npx rollup/rollup#try-block-deoptimization main.js --format esm > output.js
npx rollup/rollup#try-block-deoptimization main.js --format esm --no-treeshake > full-output.js
``` 

and diff the two files `output.js` and `full-output.js` with your favourite diffing tool to see if something vital is missing in `output.js`.

**Pull request merged**
