### PR TITLE
Make .intro, .outro, .banner, .footer to return promises

### PR DESCRIPTION
**Pull request by btd**
Implemented in a way discussed in https://github.com/rollup/rollup/pull/1177.
Currently all tests passed, without any modification. If code is ok, i will add tests for returning promises.

### CODE REVIEW

**Comment by btd** [comment]
@Rich-Harris I am sorry can this either be closed or reviewd or at least commented? Soon will be 1 year to this PR.

**Comment by lukastaegert** [comment]
Hi @btd,

sorry you have been left hanging for so long. I recently started working through older PRs and plan on taking a look at yours in the next days.

**Comment by adrianheine** [comment]
This PR has merge conflicts, though.

**Comment by btd** [comment]
@adrianheine i do not see any point in working on this PR if it will rest unmerged for another year.

**Pull request closed without merging**
