### PR TITLE
Stabilize watch tests

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
#4300

### Description
This attempts to follow ideas in https://github.com/rollup/rollup/pull/4300#issuecomment-1000907228 and others to stabilize the watch tests especially on MacOS.

### CODE REVIEW

**Comment by kzc** [comment]
The node12/macos race condition test failure in this PR "correctly rewrites change event during build delay" happens roughly 20% of the time on github CI.  Although not a proper fix, it might be helped by the timeout increase at the end of the patch https://github.com/rollup/rollup/pull/4300#issuecomment-1000907228.  I don't know why `await sander.copydir()` is insufficient.  The implementation of `sander.copydir` is quite interesting, and counter-intuitive for me at least.  I can only speculate that some of its file write actions are deferred and not accurately awaited.

**Comment by dnalborczyk** [comment]
> I don't know why `await sander.copydir()` is insufficient:
> ...
> The implementation of [`sander.copydir`](https://github.com/Rich-Harris/sander/blob/000590a0a4a954e0488c028fad4b7ca801023aee/src/extraMethods/copydir.js) is quite interesting, and counter-intuitive for me at least. I can only speculate that some of its file write actions are deferred and not accurately awaited.

might be time to replace `sander` with `fs-extra`. sander is unmaintained, last commit was 5+ years ago, 50k downloads/week. `fs-extra` is actively maintained, with 42 million downloads/week.

I'll have a look into a PR.

**Comment by kzc** [comment]
There are two predominant flaky tests on macos.

This particular watch test `test/cli/samples/watch/watch-config-early-update` fails on macos (usually macos/node12, but occasionally on macos/node16) around 20% of the time:

```
  1 failing

  1) rollup
       cli
         watch
           watch-config-early-update: immediately reloads the config file if a change happens while it is parsed:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'output1.js: const foo = 42;\n\nexport { foo };\n'
- 'output1.js: undefined'
               ^
      + expected - actual

      -output1.js: const foo = 42;
      -
      -export { foo };
      +output1.js: undefined
```

This is the other macos failure that occurs less than 10% of the time on macos/node12, which oddly is reported as 2 test failures by mocha when running `test/watch/index.js` "correctly rewrites change event during build delay":

```
  2 failing
npm ERR! code ELIFECYCLE

  1) rollup
npm ERR! errno 2
       rollup.watch
npm ERR! rollup@2.62.0 test:only: `mocha test/test.js`
         correctly rewrites change event during build delay:
npm ERR! Exit status 2
     Uncaught AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
npm ERR! 

npm ERR! Failed at the rollup@2.62.0 test:only script.
'update' !== null
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

      at Object.watchChange (test/watch/index.js:335:14)
      at PluginDriver.runHookSync (src/utils/PluginDriver.ts:357:30)
      at PluginDriver.hookSeqSync (src/utils/PluginDriver.ts:276:9)
      at WatchEmitter.handleChange (src/Graph.ts:82:23)
      at Timeout._onTimeout (src/watch/watch.ts:92:18)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) rollup
       rollup.watch
         correctly rewrites change event during build delay:
     Error: done() called multiple times in test <rollup rollup.watch correctly rewrites change event during build delay> of file /Users/runner/work/rollup/rollup/test/test.js; in addition, done() received error: AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'update'
- 'delete'
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

My initial suspicion that it was due to `await sander.copydir` doesn't appear to be the case: https://github.com/rollup/rollup/pull/4319#issuecomment-1001222943

**Comment by kzc** [comment]
For the second watch failure above, this hack appears to yield positive results on an overloaded macos box:

```patch
--- a/test/watch/index.js
+++ b/test/watch/index.js
@@ -309,29 +309,29 @@ describe('rollup.watch', () => {
        it('correctly rewrites change event during build delay', async () => {
                const WATCHED_ID = path.resolve('test/_tmp/input/watched');
                const MAIN_ID = path.resolve('test/_tmp/input/main.js');
                let lastEvent = null;
                await sander.copydir('test/watch/samples/watch-files').to('test/_tmp/input');
                await wait(100);
                watcher = rollup.watch({
                        input: 'test/_tmp/input/main.js',
                        output: {
                                file: 'test/_tmp/output/bundle.js',
                                format: 'cjs',
                                exports: 'auto'
                        },
                        watch: {
-                               buildDelay: 300,
+                               buildDelay: 600,
                                chokidar: {
                                        atomic: false
                                }
                        },
                        plugins: {
                                buildStart() {
                                        this.addWatchFile(WATCHED_ID);
                                },
                                watchChange(id, { event }) {
                                        if (id === WATCHED_ID) {
                                                assert.strictEqual(lastEvent, null);
                                                lastEvent = event;
                                        }
                                }
```

**Comment by lukastaegert** [comment]
I added the increased timeout. This is not fixed yet, but I will move it to master as it definitely appears to be an improvement.

**Pull request merged**
