### PR TITLE
chor: feature: bugfix: Add Typescript 4.5 nodenext node12 module resolution support

### PR DESCRIPTION
**Pull request by frank-dspeed**
Added Typescript 4.5+ Support for nodenext and node12 resolve it will not lookup typings

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

If we do not apply this changes users of Typescript 4.5 with moduleResolution nodenext and node12 will not be able to get typings

### CODE REVIEW

**Comment by lukastaegert** [comment]
Where is this documented in the TypeScript docs? I could not find it in the [TS 4.5 docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html). All I could find is this issue which is not resolved: microsoft/TypeScript#33079
Unless there is something I overlooked, I would wait for this feature to be released in a stable TypeScript version.

**Comment by frank-dspeed** [comment]
@lukastaegert it is inside the current 

Stable release | 4.5.4 / 13 December 2021

we did not documented that we assumed that people will understand it documentation is on the way but you can see that we do the changes all over https://github.com/microsoft/TypeScript/issues/46452#issuecomment-954879475

you can see it here it is in rxjs and many other popular repos also all plugins need that extra condition asap to be used with any project that uses moduleResolution nodenext or node12 from typescript ^4.5.0

https://github.com/rollup/plugins/pull/1114 i issued that as first step to look how it gets adopted but out of my view i can not maintain or use the plugins repo it is full of stuff that is not compatible with edge stuff so i would need to setup a legacy env to run the repo tooling for the plugins...

it would help if you could apply that operation on all repos or let me create a single update for all plugins so that they are compatible

**Comment by lukastaegert** [comment]
You should REALLY document such potentially breaking stuff up front, and inform people about in your release notes. I can merge it because it probably does not break stuff, but to me this looks like a process that should be improved.

**Review by lukastaegert — APPROVED** [review]

**Comment by frank-dspeed** [comment]
@lukastaegert sure everything can always get improved thanks.

**Comment by frank-dspeed** [comment]
@lukastaegert https://github.com/microsoft/TypeScript/issues/46454 the documentation will get updated so only the nightly users are at present facing this while all could use it because typescript had no ability to gate the feature at a diffrent place at present. 

so the problems will not happen again when typescript implemented experimental features.

**Pull request merged**
