### PR TITLE
[WIP] [BREAKING] add this.warn method to plugin contexts

### PR DESCRIPTION
**Pull request by Rich-Harris**
See #1140. This adds `this.warn` to plugin `transform` hooks. Usage:

```js
// simple case — a string
this.warn( 'a message' );

// equivalent to
this.warn({ message: 'a message' });

// custom code/other data
this.warn({
  code: 'MY_CUSTOM_CODE', // defaults to 'PLUGIN_WARNING'
  message: 'a message',
  foo: 'bar'
});

// include a character position that the warning pertains to. this
// will cause `pos`, `loc` and `frame` properties to be added
// to the warning object, as with internal `module.warn(...)`
this.warn( 'a message', 42 );
```

In addition to `code`, `pos`, `loc` and `frame` properties, a `plugin` property will be added which is the plugin's name.

TODO:

* [x] `this.error(...)` helper
* [x] Update `toString` method to include plugin name
* [x] Update CLI to print plugin name

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Technically a breaking change (it no longer manipulates error messages) so should be a 0.41 release, though unlikely to actually cause breakage in the wild.

**Comment by tivac** [comment]
@Rich-Harris do you have time to document this on the wiki? I'd love to add support but I haven't had a chance to fully grok this yet. Even some light docs would be really useful!

**Comment by Rich-Harris** [comment]
@tivac try this on for size https://github.com/rollup/rollup/wiki/Plugins#warnings-and-errors

**Comment by tivac** [comment]
Thanks!

**Pull request merged**
