### PR TITLE
feat(types): add generic type for plugin api

### PR DESCRIPTION
**Pull request by sxzz**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description

Add a generic type for Plugin.api

### CODE REVIEW

**Review by lukastaegert — APPROVED** [review]
Good idea!

**Comment by ArnaudBarre** [comment]
`vitejs/plugin-react` is overloading the type [like this](https://github.com/vitejs/vite-plugin-react/blob/3748fc7493cf0a07a2ae275fbd1ae035f01010cc/packages/plugin-react/src/index.ts#L82-L91):

```ts
declare module 'vite' {
  export interface Plugin {
    api?: {
      /**
       * Manipulate the Babel options of `@vitejs/plugin-react`
       */
      reactBabel?: ReactBabelHook
    }
  }
}
```

But this now fails with this generic types:
```
node_modules/vite/dist/node/index.d.ts:2856:11 - error TS2430: Interface 'import("/Users/arnaud/git/vite-plugin-react/packages/plugin-react/node_modules/vite/dist/node/index").Plugin<A>' incorrectly extends interface 'import("/Users/arnaud/git/vite-plugin-react/packages/plugin-react/node_modules/rollup/dist/rollup").Plugin<A>'.
  Types of property 'api' are incompatible.
    Type '{ reactBabel?: ReactBabelHook | undefined; } | undefined' is not assignable to type 'A | undefined'.
      Type '{ reactBabel?: ReactBabelHook | undefined; }' is not assignable to type 'A'.
        'A' could be instantiated with an arbitrary type which could be unrelated to '{ reactBabel?: ReactBabelHook | undefined; }'.

2856 interface Plugin<A = any> extends rollup.Plugin<A> {
```

I changed to try to directly overload the rollup types with:
```ts
declare module 'rollup' {
  export interface Plugin<A = any> {
    api?: {
      /**
       * Manipulate the Babel options of `@vitejs/plugin-react`
       */
      reactBabel?: ReactBabelHook
    }
  }
}
```

but I now get:
```
src/index.ts:84:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'api' must be of type 'A | undefined', but here has type '{ reactBabel?: ReactBabelHook | undefined; } | undefined'.
```

Does anyone knows how I can get the same behavior as before with this new type? Is there any expected way to type this?

**Comment by sxzz** [comment]
The react plugin itself should solve it. Please track issue https://github.com/vitejs/vite-plugin-react/issues/258

**Comment by ArnaudBarre** [comment]
Yeah but I don't know how to solve it

**Comment by adi-code** [comment]
@ArnaudBarre  What about using types like
```ts
interface ViteReactPlugin Api {
      /**
       * Manipulate the Babel options of `@vitejs/plugin-react`
       */
      reactBabel?: ReactBabelHook;
}

type ViteReactPlugin = Plugin<ViteReactPlugin>;
```
instead of `declare`?

**Pull request merged**
