### PR TITLE
Support native ESM configs in Node 13, support untranspiled configs

### LINKED ISSUE #2953: __dirname and import.meta in plugins
- Rollup Version: 1.15.6
- Operating System (or Browser): OSX
- Node Version: v12.4.0

### How Do We Reproduce?

In `/whatever/rollup.config.js`:

```js
import plugin from './lib/plugin.js';
```

In `/whatever/lib/plugin.js`:

```js
console.log(__dirname);
console.log(import.meta.url);
```

### Expected Behavior

Logs:

* `/whatever/lib`
* `file:///whatever/lib/plugin.js`

### Actual Behavior

Logs:

* `/whatever`
* `file:///whatever/rollup.config.js`

### LINKED ISSUE #3443: Cannot import pure ECMAScript modules in rollup.config.js
**package.json**:

<pre>
{
  "type": "module",
  "devDependencies": {
    "rollup": ">=2.0.6 <3",
    "rollup-plugin-thatworks": ">=1.0.3 <2"
  }
}
</pre>
**rollup.config.js**:
<pre>
import {shebang} from 'rollup-plugin-thatworks' // esm import
export default {input: 'rollup.config.js'}
</pre>
**Node.js**: v13.6.0

### Actual Behavior
<pre>
<strong>yarn && yarn rollup --config</strong>
yarn install v1.21.1                                                                                           
warning package.json: No license field                                                                         
warning No license field                                                                                       
[1/4] 🔍  Resolving packages...                                                                                
success Already up-to-date.                                                                                    
✨  Done in 0.18s.
yarn run v1.21.1
warning package.json: No license field                                                                         
$ /opt/foxyboy/sw/pri/code-samples/rollup2/node_modules/.bin/rollup --config                                   
loaded rollup.config.js with warnings                                                                          
(!) Unused external imports                                                                                    
shebang imported from external module 'rollup-plugin-thatworks' but never used                                 
[!] Error: Must use import to load ES Module: /opt/foxyboy/sw/pri/code-samples/rollup2/node_modules/rollup-plugin-thatworks/lib/thatworks.js                                                                                  
require() of ES modules is not supported.                                                                      
require() of /opt/foxyboy/sw/pri/code-samples/rollup2/node_modules/rollup-plugin-thatworks/lib/thatworks.js from /opt/foxyboy/sw/pri/code-samples/rollup2/rollup.config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.                                                                                                            
Instead rename thatworks.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /opt/foxyboy/sw/pri/code-samples/rollup2/node_modules/rollup-plugin-thatworks/package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1160:13)
    at Object.require.extensions.<computed> [as .js] (/opt/foxyboy/sw/pri/code-samples/rollup2/node_modules/rol
lup/dist/bin/rollup:1812:17)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/foxyboy/sw/pri/code-samples/rollup2/rollup.config.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.require.extensions.<computed> [as .js] (/opt/foxyboy/sw/pri/code-samples/rollup2/node_modules/rol
lup/dist/bin/rollup:1809:24)
    at Module.load (internal/modules/cjs/loader.js:993:32)
</pre>
### Expected Behavior
rollup 2.0.6 to be able to use import of ECMAScript modules in rollup.config.js per Node.js v12.0.0+

cause: rollup has an internal transpiler that converts import to require. Node.js ESM then fails

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description
resolves #3443 
resolves #2953 

This will add support for native ESM and untranspiled configs, which will solve two issues:
- If a config is in a `"type": "module"` folder, it could not import real ESM plugins in Node 13
- if a config imports a plugin from a nested folder, the `__dirname` and `import.meta.url` were wrong

Support will be based on file extension:
- If the extension is `.cjs`, the config will assumed to be CommonJS and will be required untranspiled
- If the extension is `.mjs` AND the Node version is at least 13, the config will be assumed to be native ESM and will be imported untranspiled
- Otherwise the old logic (transpiling to CJS) will be used

TODO:
- [x] Add helpful error messages for common issues that point users to using the correct extensions and file format
- [x] Automatically check for configs in the following order: `rollup.config.mjs`, `rollup.config.cjs`, `rollup.config.js`.

### CODE REVIEW

**Comment by brettz9** [comment]
With the latest Rollup release, despite this merge, with `/Users/brett/rollup-plugin-filesize/rollup.config.js`:

```js
import filesize from "./dist/index-esm.js";
```

...and `/Users/brett/rollup-plugin-filesize/dist/index-esm.js`:

```js
console.log(__dirname);
```

**Expected**

> /Users/brett/rollup-plugin-filesize/dist/

**Actual**

> /Users/brett/rollup-plugin-filesize/

**Comment by lukastaegert** [comment]
Please read the docs, you will only get an untranspiled config if you rename your config with an .mjs in Node 13 or .a cjs extension. Also I am not sure you can use `__dirname` in a native Node ES module. https://rollupjs.org/guide/en/#using-untranspiled-config-files

**Comment by brettz9** [comment]
Ah, my apologies, thank you!

**Comment by brettz9** [comment]
>... you will only get an untranspiled config if you rename your config with an .mjs in Node 13 or .a cjs extension

and from the docs:

> By default, Rollup will expect config files to be ES modules and bundle and transpile them and their relative imports to CommonJS before requiring them. 

But in my example, my relative imports are ESM, so shouldn't that work? (And I am on Node 10, FWIW.) I'm sorry to belabor this if I'm the one missing something, but I had taken a look at the docs, but was just unclear (and still am).

Re: `__dirname`, yes, you are right, it is not to be supported (per https://nodejs.org/dist/latest-v12.x/docs/api/esm.html#esm_no_require_exports_module_exports_filename_dirname ), but I get the same results with `import.meta.url`.

**Comment by lukastaegert** [comment]
>  and bundle and transpile them

This is what breaks `import.meta.url` and `__dirname`. Maybe this side-effect should be stated explicitly. A bundle of course has the `__dirname` of the bundled file. If you are stuck on Node 10, your only option for correct `__dirname` in relative imports is to switch to `.cjs`.

**Comment by brettz9** [comment]
I would understand the bundle having the `__dirname` or `import.meta.url` of the bundled file (being within `dist` where it is output). But these end up instead being the Rollup config file path--i.e., `/Users/brett/rollup-plugin-filesize/rollup.config.js` is what `import.meta.url` gives.

And even when testing on Node 12 with the `rollup.config.mjs` file, I am getting the same result--`import.meta.url` is showing the path of the `rollup.config.mjs` config file--not the path of the source file (nor of the destination file).

**Comment by brettz9** [comment]
I should mention that with `rollup.config.cjs` (and its change to point to the `dist` file, built with `@babel/plugin-syntax-import-meta`), things are working as expected, however.

**Comment by lukastaegert** [comment]
And mjs is only working natively in Node 13, as stated in the docs. Otherwise the config file is the bundled file, hence everything points there.

**Comment by brettz9** [comment]
Ah, ok, I see. Re: the config file itself being the bundled file, I see now how that can make sense.

Re: Node 13, my apologies, and thank you very much for your patience and help.

**Pull request merged**
