### PR TITLE
BREAKING: ensure import paths are case-sensitive

### PR DESCRIPTION
**Pull request by Rich-Harris**
Addresses #590. The suggestion there was that Rollup should warn if a module is imported twice with different casing, but to be honest I can't imagine a situation where you wouldn't want it to just fail altogether.

### CODE REVIEW

**Comment by guybedford** [comment]
One thing to think about is that Es modules as implemented in browsers will be case sensitive as far as I am aware. I believe importing the same module with different cases will execute twice in browsers.

So strictly, this is implementing nonstandard behavior even though it makes the most sense. Perhaps @domenic can weigh in here as well.

**Comment by domenic** [comment]
> I believe importing the same module with different cases will execute twice in browsers.

Not unless your web server serves the same body for `GET /foo.js` and `GET /FOO.js`. Behavior there generally varies across servers, but e.g. GitHub.com 404s.

If you want to emulate strict web servers here, using `fs.realPath` and making sure the imported case matches the real path might be the way to go.

**Comment by tomByrer** [comment]
Hmmm, I've heard of this mixed case problem [before](https://github.com/ractivejs/ractive/issues/527). ;)

**Comment by Rich-Harris** [comment]
Went ahead with the current implementation rather than `realpath` just because I expect that would cause some breaking behaviour with linked modules. Should be the same as regards case sensitivity. Can always revisit in future though. Thanks everyone

**Pull request merged**
