### PR TITLE
Add support for FreeBSD (x64 and arm64)

### LINKED ISSUE #5491: Support for FreeBSD
### Rollup Version

latest

### Operating System (or Browser)

FreeBSD

### Node Version (if applicable)

18

### Link To Reproduction

https://github.com/michal-stachura/free-bsd

### Expected Behaviour

Install dependencies corectly and run Nuxt3 project on FreeBSD

### Actual Behaviour

```
Your current platform "freebsd" and architecture "x64" combination is not yet supported by the native Rollup build. Please use the WASM build "@rollup/wasm-node" instead.

The following platform-architecture combinations are supported:
android-arm
android-arm64
darwin-arm64
darwin-x64
linux-arm
linux-arm (musl)
linux-arm64
linux-arm64 (musl)
linux-ppc64
linux-riscv64
linux-s390x
linux-x64
linux-x64 (musl)
win32-arm64
win32-ia32
win32-x64

If this is important to you, please consider supporting Rollup to make a native build for your platform and architecture available.
```

overriding "rollup" in package.json does not solve the problem.

```
"overrides": {
    "rollup": "npm:@rollup/wasm-node@latest"
  },
```

### PR DESCRIPTION
**Pull request by tagattie**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

- resolves #5491

### Description

This PR contains a set of changes necessary for building and publishing native binary for FreeBSD (x64 and arm64). Changes include:

- add `build-freebsd` job to GitHub Actions workflow
  - it is difficult to add a FreeBSD-related target to existing `build` job, so add a dedicated job
- add npm directories for freebsd-x64 and freebsd-arm64 along with changes to native.js and package.json
- make small changes for rust codes
  - freebsd-x64 requires local-dynamic-tls feature of mimalloc-rust crate

With those changes, `npm run test:only` finishes with the following output:

```
  5123 passing (2m)
  2 pending
  1 failing
  1) rollup
       cli
         watch
           watch-config-error: keeps watching the config file in case the config is changed to an invalid state:
     Error: Test aborted due to timeout.
      at /home/runner/work/rollup/rollup/test/cli/index.js:78:21
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

One failuer is apparently due to underlying chokidar module. [A similar change to chokidar](https://github.com/paulmillr/chokidar/pull/1375/files) solves the error and makes all tests pass.

I would much appreciate it if this PR is considered for inclusion for future releases.

### CODE REVIEW

**Review by lukastaegert — APPROVED** [review]
Looks good to me. I would merge this and create a patch release so you can check if the published version actually works as intended. And thanks so much for the work you put into this!

**Comment by lukastaegert** [comment]
I overlooked that the ARM build really is abysmally slow. Not sure I would want to keep it this way, for instance when publishing, everything is waiting for this one job for 15-20 minutes (still counting). Maybe it can be made faster by running on an actual ARM platform? But I did not look into details. After all, the x86 build is quite fast.

**Comment by lukastaegert** [comment]
But is it really necessary to use an arm64 platform to build for an arm64 platform? To my understanding, Rust is capable of cross-building to some degree?

**Comment by tagattie** [comment]
Yes, rust is indeed capable of cross-building for some target platforms. But FreeBSD arm64 platform is not (yet) supported as the target. An output from `rustup target list | grep freebsd` on FreeBSD x86-64 is as follows:

```
$ rustup target list | grep freebsd
i686-unknown-freebsd
x86_64-unknown-freebsd (installed)
```

So we need a native platform for building an artifact for FreeBSD arm64 at the moment...

**Comment by lukastaegert** [comment]
Ok, thanks for the info. So for the time being, maybe we stick with the current setup and see how annoying it is. And then let's hope that the Arm64 will really become available for Open Source eventually.

**Pull request merged**
