### PR TITLE
Use globals map for export name

### LINKED ISSUE #1746: globals/external not working as expected
In this repo: https://github.com/caub/Leaflet.Terminator/blob/npm/rollup.config.js

```js
  name: 'leaflet.terminator',
  external: ['leaflet'],
  globals: {
    'leaflet': 'L'
  },
```
output generated: (`format :'umd'`)
```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('leaflet')) :
	typeof define === 'function' && define.amd ? define(['leaflet'], factory) :
	(global.leaflet = global.leaflet || {}, global.leaflet.terminator = factory(global.L));
}(this, (function (L) { 'use strict';

L = L && L.hasOwnProperty('default') ? L['default'] : L;
// ........
```

I expect that `L` is used in the output, but `global.leaflet` is still there, so I made this hacky plugin, in the hope rollup has a better way

As you can see, only the UMD header has this issue

I've read the docs, and issues on external/globals, yet I can't figure this

rollup: "^0.51.7"

### PR DESCRIPTION
**Pull request by adrianheine**
Closes #1746. There should be a test for this.

### CODE REVIEW

**Comment by TrySound** [comment]
Tests?

**Comment by adrianheine** [comment]
Good point.

**Comment by adrianheine** [comment]
Current tests pass, I added a new one for this behavior and fixed another bug where IIFE would setup the wrong namespace.

**Comment by lukastaegert** [comment]
Hi @adrianheine,
looks really nice, thank you! I especially like that you extracted the common logic for both the iife and umd case. Just waiting a little if we can get some feedback from @caub who created the original issue.

**Comment by caub** [comment]
nice, I've [tested](https://github.com/caub/Leaflet.Terminator/blob/test/rollup.config.js) and both `name: 'L.terminator'` and `name: 'leaflet.terminator'` works

Thanks

**Comment by lukastaegert** [comment]
That was quick, thanks!

**Pull request merged**
