### PR TITLE
Allow to safely probe external namespaces

### LINKED ISSUE #3996: Invalid code when accessing `.default` on a namespace import from external dependency
- Rollup Version: 2.40.0
- Operating System (or Browser): not relevant
- Node Version (if applicable): not relevant
- Link to reproduction: [repl](https://rollupjs.org/repl/?version=2.41.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGRlcCUyMGZyb20lMjAlNUMlMjJkZXAlNUMlMjIlM0IlNUNuJTVDbmNvbnNvbGUubG9nKCU1QyUyMkhhcyUyMGRlZmF1bHQlM0YlNUMlMjIlMkMlMjAhIWRlcC5kZWZhdWx0KSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior

When getting `.default` from a namespace import, if the imported module doesn't have a default export it should return `undefined`.

The input code in the repl example should be left as-is:
```js
import * as dep from "dep";

console.log("Has default?", !!dep.default);
```

### Actual Behavior

It produces invalid code, generating a default import statement which throws at runtime if the dependency doesn't have a `default` export.

If the dependency is internal (bundled), Rollup warns but correctly generates `undefined` in the output code: [repl](https://rollupjs.org/repl/?version=2.41.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGRlcCUyMGZyb20lMjAlNUMlMjIuJTJGZGVwJTVDJTIyJTNCJTVDbiU1Q25jb25zb2xlLmxvZyglNUMlMjJIYXMlMjBkZWZhdWx0JTNGJTVDJTIyJTJDJTIwISFkZXAuZGVmYXVsdCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJkZXAuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjB4JTIwJTNEJTIwMiUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #3996

### Description
It is actually not safe to replace namespace imports with named imports in the case of external dependencies as the behaviour will be different if a named export does not exist: While for the namespace import, a property will just be `undefined`, the missing named import will throw at parse time.

This changes the behaviour to always keep external namespaces as objects and keep the property access. This allows to safely probe for the existence of named imports.

### CODE REVIEW

**Comment by stefcameron** [comment]
Hi @lukastaegert 👋 , this patch is causing problems for me. A third-party library that was once tree-shaken out of my production build is now suddenly not (was not in 2.41.3, is now in 2.41.4), and it's wrapped in this new chunk of code:

```javascript
var rtv = require('rtvjs');

function _interopNamespace(e) {
  if (e && e.__esModule) return e;
  var n = Object.create(null);
  if (e) {
    Object.keys(e).forEach(function (k) {
      if (k !== 'default') {
        var d = Object.getOwnPropertyDescriptor(e, k);
        Object.defineProperty(n, k, d.get ? d : {
          enumerable: true,
          get: function () {
            return e[k];
          }
        });
      }
    });
  }
  n['default'] = e;
  return Object.freeze(n);
}

var rtv__namespace = /*#__PURE__*/_interopNamespace(rtv);
```

I don't quite understand what's happening here. In my Rollup config, I'm making sure `rtvjs` is marked as having no side effects:

```javascript
    treeshake: {
      moduleSideEffects(id, external) {
        return !['rtvjs', 'hoist-non-react-statics'].includes(id);
      },
    },
```

`rtvjs` also includes the `sideEffects: false` flag in its [package.json](https://gitlab.com/stefcameron/rtvjs/-/blob/master/package.json#L11), though I think that's a Webpack-specific flag that Rollup ignores.

I'm also using the `@rollup/plugin-replace` plugin to define a `DEV: false` flag and all my calls into `rtvjs` are prefixed with `DEV && rtvjs...`

(FYI, I'm also the author of `rtvjs`, but this issue is not in that library per se. It's in a project that consumes that library.).

**Comment by stefcameron** [comment]
And yes, I'm doing `import * as rtv from 'rtvjs'` in my non-transpiled code. But as I mentioned, all references to properties/methods of `rtv` are prefixed with `DEV && rtv...`, so I expect those to be tree-shaken out when `DEV = false` during the Rollup build. I would also expect not to see `function _interopNamespace(e) { ... }` in the resulting bundle, either, since `var rtv__namespace = /*#__PURE__*/_interopNamespace(rtv);` shouldn't be in there, and so nothing would be calling `_interopNamespace()`.

But `rtvjs` provides an ESM build (in case it matters since #3996 seems related to CJS modules), which is referenced in the [package.json](https://gitlab.com/stefcameron/rtvjs/-/blob/master/package.json#L10) in the standard way with `module`. It just doesn't use default exports, so `import * as rtv from 'rtvjs'` should be an acceptable way to just import everything. I don't want to do individual imports of every last symbol in there and pollute my module's scope with those individual vars.

**Comment by lukastaegert** [comment]
Hi @stefcameron, still trying to understand how this comes to pass. So you are saying that in the production code, there should be no usages of rtv. But in that case, the namespace helper should not be included, for example (even without disabled moduleSideEffects) see http://rollupjs.org/repl/?version=2.41.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGZvbyUyMGZyb20lMjAnZm9vJyUzQiU1Q24lNUNuZnVuY3Rpb24lMjB1bnVzZWQoKSUyMCU3QiU1Q24lNUN0JTIwZm9vLmJhciUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==.

Are there any usages of the `rtv__namespace` variable in your generated code? You were saying that all usages are prefixed with a flag. Otherwise, a reproduction would be helpful for us to track what is going on.

**Comment by stefcameron** [comment]
@lukastaegert 
> Hi @stefcameron, still trying to understand how this comes to pass. So you are saying that in the production code, there should be no usages of rtv. But in that case, the namespace helper should not be included, for example (even without disabled moduleSideEffects) see http://rollupjs.org/repl/?version=2.41.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGZvbyUyMGZyb20lMjAnZm9vJyUzQiU1Q24lNUNuZnVuY3Rpb24lMjB1bnVzZWQoKSUyMCU3QiU1Q24lNUN0JTIwZm9vLmJhciUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==.
> 
> Are there any usages of the `rtv__namespace` variable in your generated code? You were saying that all usages are prefixed with a flag. Otherwise, a reproduction would be helpful for us to track what is going on.

Thank you for your time and for having a look, I really appreciate it!

So yes, there are usages in the code. For example:
```
const cssHexColorTs = [rtv__namespace.STRING, {
  exp: '^(#[0-9|a-f]{3}$|#[0-9|a-f]{6}$|transparent)',
  expFlags: 'i'
}];
```
where that used to be:
```
const cssHexColorTs = [rtv.STRING, {
  exp: '^(#[0-9|a-f]{3}$|#[0-9|a-f]{6}$|transparent)',
  expFlags: 'i'
}];
```

Now this code in is a module called `typesets.js`. The code in this module does not prefix all `rtvjs` references with `DEV &&`, however, symbols from that module are never referenced elsewhere outside of expressions prefixed with `DEV && rtvjs...`.

So this is a fuller (still contrived) scenario:

```javascript
//// typesets.js

import * as rtv from 'rtvjs';

export const cssHexColorTs = [
  rtv.STRING,
  { exp: '^(#[0-9|a-f]{3}$|#[0-9|a-f]{6}$|transparent)', expFlags: 'i' },
];

//// util.js

import * as rtv from 'rtvjs';

export const hexToRgb = function (color) {
  DEV && rtv.verify(color, cssHexColorTs);
  return color; // in reality, do the stuff to convert the color to 'rgb(...)'
};

//// index.js

import { hexToRgb } from './util';

console.log(hexToRgb('#00ff00')); // #00ff00
```

Before this change, typesets.js would not be included in the final bundle when DEV=false. Now it is.

Here's a repro for you to work with: https://github.com/stefcameron/rollup-2-41-4-bug-repro

**Comment by lukastaegert** [comment]
Thanks! Your repro helped me a lot to quickly spot what was missing. As we are now keeping external namespace accesses as property accesses, the logic to detect if accessing a property has a side-effect was kicking in, keeping the expressions in the code. However as namespace objects are not normal objects, it is not possible that a property of a namespace is a side-effectful getter. Fix at #4001.

**Comment by stefcameron** [comment]
> Thanks! Your repro helped me a lot to quickly spot what was missing. As we are now keeping external namespace accesses as property accesses, the logic to detect if accessing a property has a side-effect was kicking in, keeping the expressions in the code. However as namespace objects are not normal objects, it is not possible that a property of a namespace is a side-effectful getter. Fix at #4001.

My pleasure, glad I could help you, and the community! 🎉 Thank you for digging into it.

**Pull request merged**
