### PR TITLE
Fix for #149

### PR DESCRIPTION
**Pull request by lukeapage**
am looking for a fix, but might be some time, I'll keep this updated, let me know if you want to take over.

It seems that the parameter having the same name as the export is removing the rename in that scope.

### CODE REVIEW

**Comment by lukeapage** [comment]
some debugging info is on a `gh-149-debug` branch, I'm off for the day.
@Victorystick any pointers, or if you want to take over you're welcome. was going to next try and understand where scopes are created for function definitions and why the parameter is getting confused onto the global scope.

**Comment by lukeapage** [comment]
so...
this: https://github.com/rollup/rollup/blob/6e839f2d38b8b0e058d990c283849af7ae237e27/src/Statement.js#L401

looks wrong to me - the reason being that the newscopes names are being popped into a parent scope on leaving the node. so, my first change was to change this to...

```
					replacementStack.push( names );
					names = newNames;
```

next up.. this line: 
https://github.com/rollup/rollup/blob/6e839f2d38b8b0e058d990c283849af7ae237e27/src/Statement.js#L435
stops parameters from being renamed.. but if a parameter is shadowing a global that is being introduced (as in this test case) the parameter needs to be renamed..

I had to also remove the check on the next line because otherwise the function declaration wasn't getting changed as a result of the first thing.

I guess this code is here to stop the function name in a function expression not getting renamed as per the global scope.

Nextup, the crux of the problem. params are added to the block scope underneath them here: https://github.com/rollup/rollup/blob/6e839f2d38b8b0e058d990c283849af7ae237e27/src/Statement.js#L82

this means that it cannot rename parameters because the scope is the wrong one when walking the function declaration parameters.

I tried a fix to put the scope on the function declaration and add the params there e.g.

```
					case 'FunctionDeclaration':
						scope.addDeclaration( node, false, false );
					case 'FunctionExpression':
						newScope = new Scope({
							parent: scope,
							block: false,
							params: node.params
						});

						// named function expressions - the name is considered
						// part of the function's scope
						if ( node.type === 'FunctionExpression' && node.id ) {
							newScope.addDeclaration( node, false, false );
						}
						break;

					case 'BlockStatement':
						newScope = new Scope({
							parent: scope,
							block: true
						});
						break;
```

Now that, combined with the other 2 fixes, results in my test passing... however...

now `renamed-arguments` fails... it seems to be because the param and function name are the same, it thinks the function name has been re-declared and therefore doesn't need renaming.

I worked around that by making the function name rename happen before applying the scope as a special case..

any comments welcome, I now have 3 tests failing

**Comment by lukeapage** [comment]
am putting params back onto the body so that
```
function foo(foo) {
    var foo = foo;
}
```
works..

**Comment by lukeapage** [comment]
okay, fixed it, not the simplest thing to work out, let me know what you think.

**Comment by lukeapage** [comment]
@Rich-Harris I enhanced the test, do you want that? otherwise this can be closed

**Comment by Rich-Harris** [comment]
Updated the test, thanks

**Pull request closed without merging**
