### PR TITLE
Get rid of alternate screen and simplify screen clearing

### LINKED ISSUE #2252: using rollup --watch, I can't scroll up
Issue demonstrated here:

rollup

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no (unfortunately this is somewhat hard to test properly, suggestions welcome)

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:
Resolves #2252 

### Description
This will change Rollup to no longer use an alternate screen buffer which was causing issues as on most terminals, scrolling seems to be deactivated for alternate buffers. Also we go rid of the `ansi-escapes` dependency and some code could be simplified.

Would be nice if someone could check if this works as expected e.g. on Windows systems.

### CODE REVIEW

**Comment by timdavish** [comment]
Thanks for this! I was able to test real quick and it works great.

Unfortunately I can't help test on Windows but I'm using iTerm2/zsh.

**Comment by timdavish** [comment]
#2820 is possibly related as well

**Comment by lukastaegert** [comment]
I was thinking about #2820 but, without having tested it, the issue sounds somewhat different. We are still clearing the screen, albeit only the visible portion of it, so it might well be that the Sirv infos are still swallowed. However I also think this should be addressed on Svelte side, either by emitting the output in a Rollup hook or setting `clearScreen` to false.

**Comment by lukastaegert** [comment]
Ah what the hell, let's release it and see if anyone complains.

**Comment by atompkins** [comment]
Sorry for delay. if I have understood correctly new behaviour should still appear to clear the screen on build but allow scrolling back.
Screen is not clearing in integrated powershell terminal in vscode.
not a big deal for me, scrolling back is more important.

**Pull request merged**
