### PR TITLE
Improve type of RollupOutput.output

### PR DESCRIPTION
**Pull request by MattiasBuelens**
This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description

Now that Microsoft/TypeScript#24897 has [landed in TypeScript 3.2](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html), we can more precisely define the type of `RollupOutput.output` to assert that the first element will be an `OutputChunk`.

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
> Seems you broke the type check, though

Woops! 😅 

Right, so [`createOutput`](https://github.com/rollup/rollup/blob/38f3ca676ba67d740ef5cd2967f8412f80feeafe/src/rollup/index.ts#L354) builds the `output` array by mapping over the keys of `outputBundle` which is a `Record<string, OutputChunk | OutputAsset>`. The compiler doesn't know that `outputBundle` will have at least one property that is an `OutputChunk`, and it also doesn't know that the subsequent `sort()` will move any `OutputChunks` to the front of the array.

Should we just put in a type cast? Something like:
```typescript
Object.keys(outputBundle)
  .map(...)
  .sort(...) as [OutputChunk, ...(OutputChunk | OutputAsset)[]]
```

**Comment by lukastaegert** [comment]
Sounds good

**Comment by MattiasBuelens** [comment]
Very weird. Some unit tests are failing on [Node 6 according to CircleCI](https://circleci.com/gh/rollup/rollup/2532):
```
  2759 passing (34s)
  1 pending
  14 failing

  1) rollup
       function
         export-global: any global variables in scope can be re-exported:
     Error: Export 'Buffer' is not defined
      at error (src/utils/error.ts:7:11)
      at Module.error (src/Module.ts:558:3)
      at tryParse (src/Module.ts:127:5)
      at Module.setSource (src/Module.ts:235:29)
      at /home/circleci/project/src/Graph.ts:545:10

  2) rollup
       form
         system-uninitialized: supports uninitialized binding exports:
     Error: Export 'globalVar' is not defined
      at error (src/utils/error.ts:7:11)
      at Module.error (src/Module.ts:558:3)
      at tryParse (src/Module.ts:127:5)
      at Module.setSource (src/Module.ts:235:29)
      at /home/circleci/project/src/Graph.ts:545:10

  ...
```
But I only changed some types! 😭

**Comment by lukastaegert** [comment]
Sorry for the wait, finally managed to address those test issues. Basically, it was caused by version drift on Node 6 (which should no longer happen) and a breaking change in a patch version of acorn.

**Pull request merged**
