### PR TITLE
Move top-level await out of experimental

### PR DESCRIPTION
**Pull request by guybedford**
Now that TLA is Stage 3 and the Chrome implementation is currently in the process of being merged, it is coming around the time where the experimental flag is no longer necessary.

I would personally see no risk in landing this, but if there was a desire to be more conservative it could be worth waiting a couple of months for the Chrome implementation to at least land first too, although I'm not sure I see any benefit in waiting at this point either.

### CODE REVIEW

**Comment by lukastaegert** [comment]
To my knowledge, our implementation is rather non-spec-compliant, which is why I would avoid this unless we reimplement it.

**Comment by guybedford** [comment]
@lukastaegert are you referring to the timing issues we discussed before? Significant effort was actually put into the specification here to ensure there are no subtle timing issues with optimized output.

For the case of multiple async dependencies in the same chunk they will execute serially under the Rollup output instead of in parallel.

So if I had:

a.js
```javascript
console.log('sync part a');
await 0;
console.log('async part a');
```

b.js
```javascript
console.log('sync part b');
await 0;
console.log('async part b');
```

Then the expected output should be "sync part a", "sync part b", "async part a", "async part b", while under the Rollup output it would be "sync part a", "async part a", "sync part b", "async part b".

Fixing the above would be basically hoisting within a group of async siblings in a chunk the _sync statements up to the first await statement or expression_.

Personally I think we should wait on this advanced feature until we have module splitting optimizations in place, but if you would rather unblock unflagging on that then let's set up an issue for sure.

**Comment by shellscape** [comment]
@lukastaegert this would be a big win. can you please revisit the PR when you have the chance?

**Comment by lukastaegert** [comment]
Actually instead of renaming the flag (which happens in this PR) I would rather remove the flag altogether and make this “always on”. My concern is that the current execution order is sub-optimal because sibling dependencies are not executed in parallel, but this could be improved later via some code-splitting changes.

**Comment by lukastaegert** [comment]
By sub-optimal I mean non-spec compliant

**Comment by shellscape** [comment]
@lukastaegert OK, I'll tackle that change. Would this require a major version?

**Comment by lukastaegert** [comment]
No, it cannot break anything, there would just be no error when using TLA

**Pull request merged**
