### PR TITLE
Add isEntry flag to resolveId and this.resolve

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description
In the past, the way to detect if we are resolving an entry point in the `resolveId` hook was to check if the `importer` was `undefined`. However since we allowed to specify an `importer` in the `this.emitFile` hook, this check does not work in all cases any more.
This is problematic if you want to resolve entry points (and only those!) to proxies in a reliable manner.

This PR adds a new flag `isEntry` to the `resolveId` plugin hook to make this explicit. The same flag is also added to the `this.resolve` plugin context function. So resolving entries to plugins would now work like this:

```js
function onlyDefaultForEntriesPlugin() {
  return {
    name: 'only-default-for-entries',
    async resolveId(source, importer, options) {
      if (options.isEntry) {
        // options contains `custom` and `isEntry`, so we are forwarding both
        const resolution = await this.resolve(source, importer, { skipSelf: true, ...options });
        if (!resolution) return null;
        return `${resolution.id}?entry-proxy`;
      }
      return null;
    },
    load(id) {
      if (id.endsWith('?entry-proxy')) {
        const importee = id.slice(0, -'?entry-proxy'.length);
        return `export {default} from '${importee}';`;
      }
      return null;
    }
  };
}
```

In the `resolveId` hook, the value of `options.isEntry` is determined like this:
* If we are resolving an entry point or emitted chunk, it is `true`
* If we are resolving a (dynamic or static) import, it is `false`
* If we are resolving a call to `this.resolve` and `isEntry` is a boolean, this value is used, e.g. `this.resolve('foo', 'bar', {isEntry: true})`
* If we are resolving a call to `this.resolve` and `isEntry` is `undefined` (or we did not specify options at all), it is `true` if `importer` is `undefined`, otherwise it is `false`

The reason I need this is that I want to do exactly that in a forthcoming PR for the commonjs plugin (with the goal of handling circular dependencies correctly).

Once this is release, plugins should check if they need to forward this flag when they use `this.resolve`. It should be possible to implement support for this flag in a manner that is compatible with older Rollup versions (here you would just forward `undefined` which would trigger the fallback logic).

### CODE REVIEW

**Comment by lukastaegert** [comment]
@yyx990803 @patak-js tagging you as this is a (minor) extension to the plugin API that may or may not be relevant for you to implement. Please tell me if I should tag other people for such things in the future.

This flag will become relevant for the CommonJS plugin at some point (but there is a bigger one I am working on that will likely have more impact for you).

**Comment by guybedford** [comment]
LGTM. Just to clarify here, a dynamic import that becomes an emitted chunk would have `isEntry` set to true right?

**Comment by patak-js** [comment]
Thanks for the heads up @lukastaegert. It is relevant, as we need to implement it in the [plugin pipeline of Vite dev server](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugin.ts). 

LGTM. I started a branch in Vite to see what changes are needed on Vite side (see [commit](https://github.com/vitejs/vite/commit/f4e62f31514bb38b565a54e03d33b00d5867829f)). We would need to review later with proper test cases but this looks straightforward.

About other people that may be interested in these changes, @antfu from Vite's side and @marvinhagemeister, as they would need to do the same for WMR

A note about extending the plugin API, Vite added an `ssr` boolean flag to `resolveId`, `load`, and `transform`. See [docs](https://vitejs.dev/guide/ssr.html#ssr-specific-plugin-logic). This doesn't interfere in `resolveId` as it goes after the options param. But in `transform`, there isn't an options object. @lukastaegert if you think we may need to pass an `options` object to `transform` in the future, maybe we are still on time to change this SSR extension on our side (passing an empty `options` for the moment as the third param, or passing the `ssr` inside an options object). The SSR API is still marked as experimental, so I think these changes are possible. Current extended hook for reference:

```js
export function mySSRPlugin() {
  return {
    name: 'my-ssr',
    transform(code, id, ssr) {
      if (ssr) {
        // perform ssr-specific transform...
      }
    }
  }
}
```

**Comment by lukastaegert** [comment]
@guybedford the dynamic import would be resolved twice: Once for the import itself where `isEntry` is `false` and once when it is emitted where it is set to `true`. This works well for the entry proxy use case: You would not want to add a proxy for an internal dynamic import, but you might want to add a proxy if it becomes part of the public API. If you need special handling for dynamic imports, implement the `resolveDynamicImport` hook.

@patak-js I will need to think about this more, but one first thought is that a plain boolean parameter may not be forward looking. If you want to add more parameters in the future, you will be happy if you make it an object now. At this point, one could consider merging with Rollup‘a object if you do not add too much stuff that Rollup cannot use in the future :)

**Comment by lukastaegert** [comment]
@patak-js Expanding more on the idea of how to add a flag to Rollup's hooks that will not interfere with future extensions:
* An object is generally a better idea than primitive positional parameters. Besides the fact that it may or may not collide with future extensions of the `transform` and `load` apis in Rollup, it can prove problematic for future Vite extensions as well. So e.g. imagine you add a "legacy" mode. If you add another positional parameter, then plugins that just need that parameter but not the ssr parameter still needs to provide the ssr parameter to get the other one. Also it is very hard to deprecate positional parameters as we learned in Rollup.
* If we extend Rollup hooks, we try to go for option objects now, leaving the few positional parameters in place for legacy reasons.
* Rollup does not and will not validate option objects for unknown fields. This is because otherwise, we would make it harder to write plugins that work well across different Rollup versions.
* If you are afraid of potential future field name conflicts, you could consider namespacing vite parameters. These could be potential ways that I can guarantee will be future proof (and should not require you to clean up objects before passing them to Rollup):
  ```ts
  // Nested object
  interface Plugin {
    // ...
    resolveId?(
      source: string,
      importer: string | undefined,
      options: { custom?: CustomPluginOptions, vite?: {ssr: boolean} }
    ): Promise<ResolveIdResult> | ResolveIdResult
  }

  // Field prefixes
  interface Plugin {
    // ...
    resolveId?(
      source: string,
      importer: string | undefined,
      options: { custom?: CustomPluginOptions, viteSsr?: boolean }
    ): Promise<ResolveIdResult> | ResolveIdResult
    load?(
      this: PluginContext,
      id: string,
      options: {viteSsr?: boolean}
    ): Promise<LoadResult> | LoadResult
    transform?(
      this: TransformPluginContext,
      code: string,
      id: string,
      options: {viteSsr?: boolean}
    ): Promise<TransformResult> | TransformResult
  }
  ```

**Comment by patak-js** [comment]
Thanks for taking the time to share your experience here @lukastaegert, moving this discussion to https://github.com/vitejs/vite/discussions/5109 to avoid derailing this PR.

**Comment by marvinhagemeister** [comment]
@patak-js Thanks for tagging me!

Nothing more to add other than that this feature really helps us both vite and other bundlers 👍 So thanks @lukastaegert for adding it 🙌

**Pull request merged**
