### PR TITLE
feature: resolveId support dir by default

### PR DESCRIPTION
**Pull request by FoxDaxian**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

https://github.com/rollup/rollup/issues/4217

### Description

resolveId support dir by default

### CODE REVIEW

**Comment by lukastaegert** [comment]
Not sure how this relates to #4217. In any case, there is a reason we do not implement this in Rollup core. This behaviour is a Node.js idiosyncrasy that is not shared by other runtimes like browsers, Deno, or even Node itself when you are using ES modules. If you want this behaviour, you can use the node-resolve plugin, which will also make sure everything else works as well. See also https://rollupjs.org/guide/en/#why-isnt-node-resolve-a-built-in-feature

**Comment by FoxDaxian** [comment]
well, I has seen the reason just now, and make me thought the word: less is more. you are right~
btw, should rollup need support Integration some plugin as  node|browser|... preset env like webpack?

**Comment by lukastaegert** [comment]
Preset plugins is an idea that keeps coming up, but we did not work on this yet.

**Comment by FoxDaxian** [comment]
well. get it.
thanks~

**Pull request closed without merging**
