### PR TITLE
Apply prettier to codebase

### PR DESCRIPTION
**Pull request by guybedford**
I increased the line length to 120, as we currently use long lines in the codebase, but we could look at reducing this as well.

This will help to clean up the diffs for new PRs with the auto commit hook.

### CODE REVIEW

**Comment by asmockler** [comment]
@lukastaegert previously suggested we only run this on `*.ts` files – looks like there are some plain JS files peppered in there.

I think it is a good thing to run it wherever possible, though, esp. when it is in a big formatting PR like this; looks good to me 👍

**Comment by guybedford** [comment]
Sure, I've set the line length to 100 here.

I carefully applied prettier to test files that weren't expectations here, but yes we would need a better process for these going forward. I at least ran prettier on these to get close to a having the general code style enforced to set a common footing across the whole codebase.

Adding the tests to the commit hook and setting up the ignore file can be done with a further PR I think.

**Comment by lukastaegert** [comment]
👍

> Adding the tests to the commit hook and setting up the ignore file can be done with a further PR I think

Agreed. I take care that this is merged today.

**Comment by guybedford** [comment]
Thanks @lukastaegert, that was my expectation with this PR to not make merge difficulties. Merging into master sooner can be good to ensure there is less time for merge conflicts to arise when there are lots of PRs. Perhaps it would be worth discussing process a little bit here as well.

**Pull request merged**
