### PR TITLE
Improve test stability by getting independent of module id ordering in more places

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description
There were still some cases where module ids in tests were not properly ordered. This fixes this by using objects instead of arrays in some places, which also improves readability.

### CODE REVIEW

**Comment by dnalborczyk** [comment]
this might be another one: https://github.com/rollup/rollup/runs/5100138440?check_suite_focus=true if not yet fixed.

**Comment by dnalborczyk** [comment]
@lukastaegert are there (a lot?) of tests left needing to be fixed? anything I can help with?

**Comment by lukastaegert** [comment]
> this might be another on

These are the reason I did this 😉

> @lukastaegert are there (a lot?) of tests left needing to be fixed?

I hope not, but no way to be sure

**Comment by dnalborczyk** [comment]
> > this might be another on
> 
> These are the reason I did this 😉
> 
> > @lukastaegert are there (a lot?) of tests left needing to be fixed?
> 
> I hope not, but no way to be sure

ah, sweet!! 👍

**Pull request merged**
