### PR TITLE
feat: simplify `stack` info in cli error

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
related to #4687

### CODE REVIEW

**Comment by TrickyPi** [comment]
Weirdly, the `test/cli/samples/watch/bundle-error` test fail on some platforms.

**Comment by lukastaegert** [comment]
Yes, this is completely weird. It seems to be caused by your change, but I do not understand how. I also saw this problem locally for a moment, but then it worked again mysteriously.

**Comment by TrickyPi** [comment]
I found the `test/cli/samples/watch/bundle-error` test is similar to `test/cli/samples/watch/watch-config-initial-error`, the only difference is `test/cli/samples/watch/bundle-error` folder does not contain `main.js` file at first.

**Comment by lukastaegert** [comment]
Ok, here is what I found:
- abortOnStderr was triggered individually for each line in the output because `logging.ts` writes the error output in several chunks by calling the `stderr` function several times.
- because the error message was contained both in the first output line as well as the stack trace, this triggered rewriting the file twice.
- when the error message was removed from the stack trace, this obviously now only triggered writing the file once. Even though the test already had a 500ms wait between the message and writing the file, this apparently was not enough to pick up the changed file sometimes.
- when I changed the test to look for a text contained only in the stack trace, this fixed the test reliably. However, I would not want to make assertions on the stack trace content as functions are renamed from time to time.
- Instead, I changed `logging.ts` to write all lines together. This also fixes the test and is probably not a bad idea.

Unless you have anything else to add, I would merge this by tomorrow.

**Comment by TrickyPi** [comment]
Awesome

**Review by lukastaegert — APPROVED** [review]

**Pull request merged**
