### PR TITLE
Replace deprecated folder export with pattern export

### LINKED ISSUE #3890: Warning [DEP0148] DeprecationWarning
- Rollup Version: 2.34.0
- Operating System (or Browser): WIN10
- Node Version (if applicable): 15.2.1
- Link to reproduction (IMPORTANT, read below): https://gist.github.com/GrosSacASac/ec161cb36dea93a73f034783d860c9b5

### Expected Behavior

No Warning

### Actual Behavior

```
PS C:\XXXX\rollup-repro> node .\main.js
(node:2120) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./dist/" in the "exports" field module resolution of 
the package at C:\XXXX\rollup-repro\node_modules\rollup\package.json imported from C:\XXXX\rollup-repro\main.js.
Update this package.json to use a subpath pattern like "./dist/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #3890 

### Description
This follows official Node (14) guidance to prefer a pattern export over a folder export.

### CODE REVIEW

**Comment by Crenshinibon** [comment]
Hi. I just figured out, that this change broke the possibility to require "rollup/dist/loadConfigFile", that 'others' (in my case "cy-rollup") are using ... don't know if this warants an issue here or over there. But you can't even require loadConfigFile from the plain node repl ...

**Comment by guybedford** [comment]
@Crenshinibon if you use the explicit `.js` extension it should work correctly then.

**Comment by Crenshinibon** [comment]
Yes, probably. But I'm *only* using 'cy-rollup' which then requires 'loadConfigFile'.

Check out the docs regarding subpath patterns:
https://nodejs.org/api/packages.html#packages_subpath_patterns

I think you need to export: ".dist/\*": "./dist/\*.js"

Changing this locally brings everything back to normal for me.

**Comment by lukastaegert** [comment]
I guess I did not realize this would be a breaking change. I will revert this for now because as I see it, there is no way to allow requires both with and without extension to work with a pattern export.

**Pull request merged**
