### PR TITLE
Expose rendered module code to generateBundle hook

### PR DESCRIPTION
**Pull request by btd**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description

This fixes issues i created https://github.com/rollup/rollup/issues/3458. I would like to use this info for simple analysis and better code size estimations in visualizer plugin.

Let me know pls, if it could be done better.

### CODE REVIEW

**Review by lukastaegert — COMMENTED** [review]
Looks good, I think we can include this as it is, especially with the lazy evaluation. The only things missing to me are doc updates: `code` should be added both to `02-javascript-api.md` at line 58 and `05-plugin-development.md` at line 339.
Also I think returning `null` instead of `undefined` for the tree-shaken case might fit better with other APIs, but this is just my feeling.

**Comment by btd** [comment]
@lukastaegert thanks. I added docs and changed type to be string | null

**Review by lukastaegert — APPROVED** [review]
Looks great, thanks!

**Comment by btd** [comment]
Thank you

**Pull request merged**
