### PR TITLE
Prefer locally defined exports and reexports over external namespaces

### LINKED ISSUE #4049: [core] incorrect output of exporting of reference
- Rollup Version: 2.45.2
- Operating System (or Browser): macOS
- Node Version (if applicable): v14.16.0
- Link to reproduction (IMPORTANT, read below): [REPL](https://rollupjs.org/repl/?version=2.45.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJy4lMkZ0eXBlcyclNUNuZXhwb3J0JTIwKiUyMGZyb20lMjAnLiUyRnV0aWxzJyU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0eXBlcy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAqJTIwZnJvbSUyMCU1QyUyMnRzLWVzc2VudGlhbHMlNUMlMjIlM0IlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnV0aWxzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMG5vb3AlMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRnR5cGVzJTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGJhZE5vb3AlMjAlM0QlMjBub29wJTNCJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

### Expected Behavior

```js
import { noop } from 'ts-essentials'

export * from 'ts-essentials';
export const badNoop = noop;
```

### Actual Behavior

```js
export * from 'ts-essentials';
export { badNoop } from 'ts-essentials';
```

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #4049 

### Description
This resolves the scenario in #4049 where you have two competing namespace reexports in a file where the first one reexports the namespace of an external module. When looking for explicit reexports, the logic will first check all namespaces for exports that are not resolved via the external namespace until falling back to that one.

### CODE REVIEW

**Review by guybedford — APPROVED** [review]
This seems great. I wish we had had ambiguous errors for the namespace cases. I guess these could be refined over time possibly, but should likely be avoided anyway.

**Comment by lukastaegert** [comment]
I also refined how conflicts that we definitely know are handled. See in this example how `ns.foo` is replaced (correctly) with `undefined` and `ns` does not contain `foo`: https://rollupjs.org/repl/?pr=4064&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMG5zJTIwZnJvbSUyMCcuJTJGcmVleHBvcnQnJTNCJTVDbmNvbnNvbGUubG9nKG5zKSUzQiU1Q25jb25zb2xlLmxvZyhucy5mb28pJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIycmVleHBvcnQuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwKiUyMGZyb20lMjAnLiUyRmZpcnN0JyUzQiU1Q25leHBvcnQlMjAqJTIwZnJvbSUyMCcuJTJGc2Vjb25kJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmaXJzdC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGZvbyUyMCUzRCUyMDElM0IlNUNuZXhwb3J0JTIwY29uc3QlMjBiYXIlMjAlM0QlMjAxJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNlY29uZC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGZvbyUyMCUzRCUyMDIlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by lukastaegert** [comment]
As a consequence, using a non-namespace import will throw now (just as it would throw in a real engine): https://rollupjs.org/repl/?pr=4064&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmZvbyU3RCUyMGZyb20lMjAnLiUyRnJlZXhwb3J0JyUzQiU1Q25jb25zb2xlLmxvZyhmb28pJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnJlZXhwb3J0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJy4lMkZmaXJzdCclM0IlNUNuZXhwb3J0JTIwKiUyMGZyb20lMjAnLiUyRnNlY29uZCclM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZmlyc3QuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBmb28lMjAlM0QlMjAxJTNCJTVDbmV4cG9ydCUyMGNvbnN0JTIwYmFyJTIwJTNEJTIwMSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzZWNvbmQuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBmb28lMjAlM0QlMjAyJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=
(Note that you also get the conflicting namespace warning first, the REPL just does not display it, so that you can place the error in context)

**Comment by lukastaegert** [comment]
And last, I added a completely new warning when a named import cannot unambiguously be resolved via more than one external namespace: https://rollupjs.org/repl/?pr=4064&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmZvbyU3RCUyMGZyb20lMjAnLiUyRnJlZXhwb3J0JyUzQiU1Q25jb25zb2xlLmxvZyhmb28pJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnJlZXhwb3J0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJ2ZpcnN0JyUzQiU1Q25leHBvcnQlMjAqJTIwZnJvbSUyMCdzZWNvbmQnJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by guybedford** [comment]
Wow, that almost seems like parity and the warning is definitely very useful. Strictly speaking un-errored ambiguous properties are still on the namespace just as undefined values. I've posted a spec PR to explicitly define this in https://github.com/tc39/ecma262/pull/2401.

**Comment by guybedford** [comment]
> Strictly speaking un-errored ambiguous properties are still on the namespace just as undefined values. I've posted a spec PR to explicitly define this in tc39/ecma262#2401.

Turns out they aren't enumerable - should have checked the case more clearly here. So this PR does make RollupJS behaviour fully spec compatible down to the externalization ambiguity that we now have warnings for as well!

**Pull request merged**
