### PR TITLE
Tree shake parameter defaults

### LINKED ISSUE #4466: Dead-code elimination of unused default parameters
### Feature Use Case

I maintain [Libauth](https://github.com/bitauth/libauth/), a library that offers WebAssembly crypto implementations (`ripemd160`, `sha1`, `sha256`, `sha512`, and `secp256k1`). As a [pure ESM library](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), Libauth can asynchronously instantiate each WASM implementation internally, exporting simple interfaces that behave like collections of JS-only functions (with better performance). Many of Libauth's exported functions also use one of these built-in WASM instances as a default parameter. For example, `decodeBase58Address` has the definition:

```ts
export const decodeBase58Address = (
  address: string,
  sha256: { hash: (input: Uint8Array) => Uint8Array } = internalSha256
) => {
  // ...
};
```

Most applications can simply call `decodeBase58Address(address)` to automatically use the default, WASM-based `sha256` implementation (`internalSha256`).

However, applications that already have another `sha256` implementation can provide that implementation as the second parameter: `decodeBase58Address(address, mySha256Implementation)`. In this case, the default parameter (`internalSha256`) is dead code and should be possible to eliminate from the application's bundle, saving hundreds of KBs from those bundles.

### Feature Proposal

During dead-code elimination/tree shaking, default parameters that aren't used by the bundle can be removed.

For this simple example:

`module.js`:
```js
const internalAdd = (a, b) => (a === '0' ? b : a + b); // should not appear in bundle
export const addAndLog = (a, b, impl = internalAdd) => console.log(impl(a, b));
```

`app.js`:

```js
import { addAndLog } from './module.js';
const myAdd = (a, b) => a + b;
addAndLog(1, 2, myAdd); // => 3
```

The produced bundle should include only:
```js
const addAndLog = (a, b, impl) => console.log(impl(a, b));
const myAdd = (a, b) => a + b;
addAndLog(1, 2, myAdd); // => 3
```

A detailed example (testing with all known bundlers) is available at this repo: https://github.com/bitjson/shake-default-params

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
Resolves #4466

### Description

This allows tree-shaking for unnecessary default parameters in functions. This includes arrow functions but does not include nested defaults in destructuring patterns [REPL](https://rollupjs.org/repl/?pr=4498&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwKGElMjAlM0QlMjAncmVtb3ZlZCclMkMlMjAlN0IlMjBiJTIwJTNEJTIwJ3VudXNlZCUyMGJ1dCUyMGluY2x1ZGVkJyUyMCU3RCUyMCUzRCUyMCdyZW1vdmVkJyklMjAlM0QlM0UlNUNuJTIwJTIwY29uc29sZS5sb2coYSUyQ2IpJTNCJTVDbmZvbygnYSclMkMlMjAnYicpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

```js
// input
const foo = (a = 'removed', { b = 'unused but included' } = 'removed') =>
  console.log(a,b);
foo('a', 'b');

// output
const foo = (a, { b = 'unused but included' }) =>
  console.log(a,b);
foo('a', 'b');
```

While the feature may sound simple at first glance, it was actually quite complex. The main problem is that JavaScript does not make a difference between not passing a parameter to a function and passing the value `undefined`: In both cases, the default value will be used.

Therefore, there are quite some subtleties involved which in the end I resolved by extending the mechanism I created for omitting unneeded parameters. This mechanism was removing arguments from function calls if the corresponding parameter was unused. Now, it will also see if parameter defaults need to be included. Care was taken to ensure no side effects are omitted [REPL](https://rollupjs.org/repl/?pr=4498&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwKGElMjAlM0QlMjAncmVtb3ZlZCUyMGJlY2F1c2UlMjB1bnVzZWQnKSUyMCUzRCUzRSUyMGVmZmVjdCgpJTNCJTVDbmZvbygpJTNCJTVDbiU1Q25jb25zdCUyMGJhciUyMCUzRCUyMChhJTIwJTNEJTIwZWZmZWN0KCdpbmNsdWRlZCUyMGJlY2F1c2UlMjB0cmlnZ2VyZWQnKSklMjAlM0QlM0UlMjAlN0IlN0QlM0IlNUNuJTJGJTJGJTIwSXQlMjBkb2VzJTIwbm90JTIwbWFrZSUyMGElMjBkaWZmZXJlbmNlJTIwaWYlMjB5b3UlMjBwYXNzJTIwbm90aGluZyUyMG9yJTIwdW5kZWZpbmVkJTVDbmJhcih1bmRlZmluZWQpJTNCJTVDbiU1Q25jb25zdCUyMGJheiUyMCUzRCUyMChhJTIwJTNEJTIwZWZmZWN0KCdyZW1vdmVkJykpJTIwJTNEJTNFJTIwJTdCJTdEJTNCJTVDbmJheigndmFsdWUnKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

```js
// input
const foo = (a = 'removed because unused') => effect();
foo();

const bar = (a = effect('included because triggered')) => {};
// It does not make a difference if you pass nothing or undefined
bar(undefined);

const baz = (a = effect('removed')) => {};
baz('value');

// output
const foo = (a) => effect();
foo();

const bar = (a = effect('included because triggered')) => {};
// It does not make a difference if you pass nothing or undefined
bar();

const baz = (a) => {};
baz();
```

It is very important to track the instance where we "lose track" of how a function is used, e.g. because it is exported, passed to an unknown function etc. In those cases, all necessary defaults are included [REPL](https://rollupjs.org/repl/?pr=4498&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwZm9vJTIwJTNEJTIwKGElMjAlM0QlMjAnaW5jbHVkZWQnKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKGEpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

```js
// input
export const foo = (a = 'included') => console.log(a);

// output
const foo = (a = 'included') => console.log(a);

export { foo };
```

### CODE REVIEW

**Comment by lukastaegert** [comment]
This is ready for review now

**Comment by kingstone3** [comment]
function foo({
  o: { a = '/', b = '/' } = { a: '/', b: '/' },
}) {	 
	return () => {
		console.log(a)
	}
}

foo()

image

**Comment by kingstone3** [comment]
image

**Comment by bitjson** [comment]
For anyone else following – this seems to be the issue behind the revert: https://github.com/rollup/rollup/issues/4505

**Comment by lukastaegert** [comment]
There were actually two more issues. So far so I identified the causes but could not find time to fix stuff yet du to family things, so I reverted to get more time without people reporting the same issues again.

**Comment by lukastaegert** [comment]
There is a new attempt that does this more conservatively at #4510

**Comment by lukastaegert** [comment]
To everyone following this, I decided to roll back the feature for good as it turned out to be far too brittle with far too much overhead for my liking at the moment, see #4520

**Pull request merged**
