### PR TITLE
Empty chunk pruning

### LINKED ISSUE #2120: experimentalPreserveModules leaves in unused import statements
Here's a sample repo showing the problem. https://github.com/matthewp/rollup-bug

In short we have:

__main.js__

```js
import { a } from './one';

window.APP = { a };
```

__one.js__

```js
export { default as a } from './two';
export { default as b } from './three';
```

As you can see, the __three.js__ module is not used. This gets transformed into:

__main.js__

```js
import './one.js';
import a from './two.js';

window.APP = { a };
```

__one.js__

```js
import './two.js';
import './three.js';
```

As you can see, the __two.js__ module, which is used, gets promoted up to being an import for __main.js__. But __one.js__ still includes the import for __three.js__ even though it is not used in the application at all.

I understand that it might work this way because rollup cleans this up when it bundles. If you are using `experimentalPreserveModules`, however, you might be using something else for bundling (or perhaps not bundling at all), in which case it creates an unnecessary request for __three.js__.

### PR DESCRIPTION
**Pull request by guybedford**
This prunes dependencies on empty chunks.

Resolves #2120.

Note I suspect we're probably going to want to generalise this logic from empty chunks to `chunk.hasSideEffects()`, although this isn't a simple path, but perhaps this is a start towards such a thing.

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks for this! I added this test if you want to use it: https://github.com/stealjs/rollup/commit/83d3f841ba62965bd8f9051ddbe9e0cfe1f124f5

That test makes sure that the `imported` array is also pruned (not just the source). Just making sure, that is done here as well, right?

**Comment by guybedford** [comment]
@matthewp sure, I did see that and added your test case as `preserve-modules-empty`. Let me know if the output seems right.

**Comment by guybedford** [comment]
@lukastaegert I was looking at applying this to the EMPTY_BUNDLE warnings themselves, but am not getting `module.ast.included === false` for cases like -

https://rollupjs.org/repl?version=0.57.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGIlMjBmcm9tJTIwJy4lMkZiJyUzQiU1Q24lNUNudmFyJTIwdmFsJTIwJTNEJTIwYi5mb28oKSUzQiU1Q252YXIlMjB2YWwyJTIwJTNEJTIwYi5iYXIlM0IlNUNuJTVDbiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMGZvbyUyMCgpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjAxMCUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMHZhciUyMGJhciUyMCUzRCUyMDIwJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by guybedford** [comment]
Thanks @lukastaegert for the suggestion here - I've gone ahead and implemented that in the latest commit and it works well for the EMPTY_BUNDLE check now.

Note I need to implement hasEffects returning false on ImportDeclaration, not shouldBeIncluded, to get the logic here to work out.

**Comment by lukastaegert** [comment]
> Note I need to implement hasEffects returning false on ImportDeclaration, not shouldBeIncluded, to get the logic here to work out.

Ah yes, you are right. I thought they were somewhat equivalent but no, the relation is that `shouldBeIncluded` should always be true for nodes with side-effects but can also be true for side-effect-free nodes to have them included as well. It does not work the other way around so thanks for finding the right solution.

I like how this turns out and it really improves some core aspects of tree-shaking. Just two last things:
* When I "break" the hasEffects logic, the empty-chunks test does not turn red (which is why I thought my approach was working in the first place). This can be easily fixed by putting another dependency in front of `dep.js` that imports a specifier from `dep`, i.e. `import {treeshaken} from './dep.js'`
* For `experimentalPreserveModules`, it seems that empty modules are preserved (and you even added a test that proves that). I thought it was part of this feature to not output those as well any more (and as I understand, this also something that @kellyselden would be interested in). Do you think this would be possible as well?

**Comment by guybedford** [comment]
> When I "break" the hasEffects logic, the empty-chunks test does not turn red (which is why I thought my approach was working in the first place). This can be easily fixed by putting another dependency in front of dep.js that imports a specifier from dep, i.e. import {treeshaken} from './dep.js'

This might be that we still don't have treeshaking of unused imports due to the fact that we don't track import path usage at a chunking level.

Note that if you break the hasEffects logic in the latest comment, the EMPTY_BUNDLE test will fail though.

> For experimentalPreserveModules, it seems that empty modules are preserved (and you even added a test that proves that). I thought it was part of this feature to not output those as well any more (and as I understand, this also something that @kellyselden would be interested in). Do you think this would be possible as well?

Done :)

**Comment by lukastaegert** [comment]
Beautiful! I think this is how tree-shaking with preserved modules should work!

**Pull request merged**
