### PR TITLE
More watch test stabilization

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description
Most notably watch-config-early-update still fails sometimes.

### CODE REVIEW

**Comment by kzc** [comment]
On my Mac this is what I'm seeing with Node v16:

```patch
--- a/test/cli/samples/watch/watch-config-early-update/_config.js
+++ b/test/cli/samples/watch/watch-config-early-update/_config.js
@@ -5,6 +5,7 @@ const { atomicWriteFileSync } = require('../../../../utils');
 let configFile;
 
 module.exports = {
+  repeat: 10,
   description: 'immediately reloads the config file if a change happens while it is parsed',
   command: 'rollup -cw',
   before() {
@@ -24,7 +25,7 @@ module.exports = {
                 format: 'es'
               }
             }),
-          1000
+          114   // <------ 70% failure with 114ms. See chart below.
         );
       });
       `
```

| timeout | percent failure |
|:-------:|----------------:|
|   113   |             100 |
|   114   |              70 |
|   115   |              10 |
|   116   |               0 |

This ought to be enough to sway the race condition towards reliability on github CI:

```patch
--- a/test/cli/samples/watch/watch-config-early-update/_config.js
+++ b/test/cli/samples/watch/watch-config-early-update/_config.js
@@ -24,7 +24,7 @@ module.exports = {
                 format: 'es'
               }
             }),
-          1000
+          3000
         );
       });
       `
```

**Comment by kzc** [comment]
Isn't having a watcher of the config file followed by a timeout essentially a more elaborate version of the original test timeout race condition?

**Comment by lukastaegert** [comment]
It is, if it works, it is just much faster on a local machine while adapting to slow CI machines. The reason that a timeout is still necessary confuses me too, though. And maybe it is just stupid.

**Comment by lukastaegert** [comment]
Ok, went with the bigger timeout after all. Seems fairly stable for now.

**Comment by kzc** [comment]
I think the simple timeout increase is best.

The last few macOS releases reportedly have had markedly higher filesystem latency compared to the OS X releases several years ago.  Some users have also reported peculiar random pauses in filesystem use. This could explain why the macOS tests required longer timeouts.

Regarding the watch delays needed after a supposed synchronous file write, perhaps the reason is that the file on the filesystem needs to be properly flushed to the physical media.  This patch might aid that cause:

```patch
--- a/test/utils.js
+++ b/test/utils.js
@@ -16,6 +16,7 @@ exports.assertDirectoriesAreEqual = assertDirectoriesAreEqual;
 exports.assertFilesAreEqual = assertFilesAreEqual;
 exports.assertIncludes = assertIncludes;
 exports.atomicWriteFileSync = atomicWriteFileSync;
+exports.syncFile = syncFile;
 
 function normaliseError(error) {
        delete error.stack;
@@ -229,5 +230,13 @@ function assertIncludes(actual, expected) {
 function atomicWriteFileSync(filePath, contents) {
        const stagingPath = filePath + '_';
        fs.writeFileSync(stagingPath, contents);
+       syncFile(stagingPath);
        fs.renameSync(stagingPath, filePath);
+       syncFile(filePath);
+}
+
+function syncFile(filepath) {
+       let fd = fs.openSync(filepath, 'r+');
+       fs.fsyncSync(fd);
+       fs.closeSync(fd);
 }
```

**Pull request merged**
