### PR TITLE
docs(README): add `TypeScript` API section

### PR DESCRIPTION
**Pull request by alan-agius4**

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thanks @alan-agius4. I think maybe this would fit better in a section on https://github.com/rollup/rollupjs.org, rather than on the README directly (which is designed to be a quick overview of the project — using the API programmatically is an advanced topic by itself, with TypeScript doubly so). What do you reckon?

**Comment by alan-agius4** [comment]
I totally agree, though I don’t know where can I find the sourcecode of
that :)

**Comment by alan-agius4** [comment]
Ill try to do a PR there :)

**Comment by Rich-Harris** [comment]
cool! This is probably the right place for it — https://github.com/rollup/rollupjs.org/blob/master/guide/en/04-javascript-api.md

**Comment by alan-agius4** [comment]
PR done https://github.com/rollup/rollupjs.org/pull/108 :)

**Pull request closed without merging**
