### PR TITLE
fix(sourcemap): fall back to low-resolution line mapping

### LINKED ISSUE #3938: sourcemaps passed from non-js assets seem to be ignored
- Rollup Version: 2.38.0
- Operating System (or Browser): Windows 10 x64 (though irrelevant)
- Node Version (if applicable): 14.15.4 (though irrelevant)
- Link to reproduction (IMPORTANT, read below): https://repl.it/@CxRes/no-css-sourcemap

It seems that for a non-css source the sourcemap passed as return value of the transform plugin is ignored. We are observing this in [rollup-plugin-styles](https://github.com/Anidetrix/rollup-plugin-styles) where the generated css sourcemap that is passed is just ignored as can be seen in the reproduction. The relevant code lines are [linked here](https://github.com/Anidetrix/rollup-plugin-styles/blob/caff61f6aa32948571eb83a136ac13bd5637ca6e/src/index.ts#L118). Also, please refer to my discussion with the author @Anidetrix [here](https://github.com/Anidetrix/rollup-plugin-styles/issues/160#issuecomment-766811562). 

The author of this plugin @Anidetrix is forced to add the sourcemap directly to the css string bundled in the js output file as a string. But this puts sourcemaps in two places and is extremely ugly. Ideally all sources, js or not, should be in the same map file.

### Expected Behavior

The sourcemap for the CSS should be passed along the build pipeline and included in the generated sourcemap

### Actual Behavior

Missing css source in sourcemap.

PS: I have tried passing the code part only ie without the sourcemap added to the code, unlike what the plugin author does. It makes no difference!

### PR DESCRIPTION
**Pull request by aleclarson**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
- might fix #3938

### Description

Basically, segment tracing was failing when a high-resolution sourcemap (which is column sensitive) comes after a low-resolution sourcemap (whose segments only have line information). This led to the related source file being excluded from the collapsed sourcemap, which is bad.

I'm not sure if unit testing this change is necessary. I've tested it manually in my project, and it works great!

### CODE REVIEW

**Review by lukastaegert — COMMENTED** [review]
Thank you very much.

> I'm not sure if unit testing this change is necessary.

A test would really go a long way here, especially to document the case you are fixing. Currently I can only guess from your comments what the scenario is you are fixing, with a test we would actually know. This would also help if there are similar scenarios in the future.

**Comment by aleclarson** [comment]
Just added a similar fix to `getOriginalLocation` too.

I've no time to write tests for a fix that I know works, unfortunately. 
Hope you can merge this soon so I can stop using a fork :D

**Comment by lukastaegert** [comment]
> I've no time to write tests for a fix that I know works, unfortunately.

That is very unfortunate. You could tell us at least what plugins cause the issue so that someone else can add a test, or how these source maps are generated. That is, if you want to get rid of your fork.

**Comment by lukastaegert** [comment]
Now that I think I understand the issue I added some tests and changed the logic: Instead of adding a special case for mappings with a single mapping per line, the logic will now handle general cases of lower resolution sourcemaps by using the closest matching column if no exact match can be found, following the principle that an imprecise source map is still more helpful than none at all.
Please have another look if that still fixes your issue.

**Comment by aleclarson** [comment]
I believe your changes will work for me, thanks!

**Comment by TrySound** [comment]
@aleclarson Looks like you just made rollup sourcemaps twice bigger
https://unpkg.com/browse/rollup@2.69.0/dist/
https://unpkg.com/browse/rollup@2.69.1/dist/

**Comment by aleclarson** [comment]
@TrySound It was Lukas' commits, as evidenced by this fork that included eeca9a7f53f76eb4d4153ebb2beca4ef357ea4b6 but not those made by Lukas.

https://unpkg.com/browse/@aleclarson/rollup@2.62.1/dist/

**Comment by TrySound** [comment]
Ok, I'm just pointing fingers 😄

**Comment by lukastaegert** [comment]
Maybe they are also twice as good now?

**Comment by aleclarson** [comment]
> Maybe they are also twice as good now?

Probably 😄 

Vite doesn't publish sourcemaps to NPM anymore, perhaps Rollup should do the same?

The rationale is that people who need sourcemaps can clone the repository easily enough.

**Comment by lukastaegert** [comment]
We are only publishing the source map for the browser build, and the reason is that this allows people to use the REPL for debugging Rollup itself. This was done one request by the people from [replay](https://www.replay.io) who are using Rollup as some kind of example: https://app.replay.io/recording/rollupjs--fce3ed6c-091b-4c0d-95a5-33f35965986c?point=1622592768338673616292244694761494&time=1797&hasFrames=false

Nevertheless, this was already critizised by others and the plan is to move the browser build to a separate artifact with the next major version.

So the problem with the current sourcemaps is likely that generated most generated code fragments are now mapped to the closest source position in the same line instead of having no mappings. This will likely improve debugging in some cases, but otherwise just takes up a lot of space.

**Comment by lukastaegert** [comment]
Maybe we should go with Alec's solution after all, it will only blow up the source map if one plugin uses a low-resolution source map 😅

**Pull request merged**
