### PR TITLE
refactor: improve types

### PR DESCRIPTION
**Pull request by sxzz**
This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description

Enhance types of internal functions, stricter.

### CODE REVIEW

**Comment by sxzz** [comment]
@lukastaegert  A question: https://discord.com/channels/804011606160703521/997209205222158347/1029744026510954517

**Comment by lukastaegert** [comment]
No, this is by design. `rawOptions` are stuff users write in their config files, and we first need to figure out, if that is even valid. The alternative is just throwing unhelpful runtime errors.

**Comment by sxzz** [comment]
I see, but does it really help? I didn't change the runtime code actually, but removed type assertions `as`. It will `warnUnknownOptions` as like as before too.

**Comment by sxzz** [comment]
It will cause a pretty serious problem: when refactoring code, I can not find all the places that referenced types by TypeScript. #4668 is the example.

**Comment by sxzz** [comment]
Checking the configuration by TS type obviously doesn't work. A better way is to check it in normalize function. If the configuration is invalid, an exception needs to be thrown to avoid runtime errors.

We can see this here, `await rawPlugins.reduce(applyOptionHook(watchMode), Promise.resolve(rawInputOptions))` is `GenericConfigObject`, and it just passed to `normalizeInputOptions` with implicit converted to `InputOptions`. For example: if `onwarn` option is not a function, it will still apply this, and cause a runtime error.

https://github.com/rollup/rollup/blob/3cb7f1376f4bbd519d320491629111e1d26cfc80/src/rollup/rollup.ts#L128-L130

**Review by lukastaegert — APPROVED** [review]

**Pull request merged**
