### PR TITLE
Moved @types dependencies to devDependencied in package.json

### PR DESCRIPTION
**Pull request by AllNamesRTaken**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

Issue: https://github.com/rollup/rollup/issues/2580

### Description

- No new features
- No changed features
- No changed code
- Only package.json changed

### CODE REVIEW

**Comment by shellscape** [comment]
@AllNamesRTaken thanks for the PR. Unfortunately your PR doesn't contain any tests (though the box was checked) and there's not much of a description of _why_ this change was made, so reviewers cannot discern why it was created. It's a good habit to thoroughly explain the purpose of a PR before submitting it.

**Comment by AllNamesRTaken** [comment]
Thank you, I think I missunderstood it. My intention was that all tests are running as they should and my change did not change that. But there are ofc no tests to test this fix since it has nothing to do with the functionality of the package. Should I take some action?

**Comment by shellscape** [comment]
I unchecked the "tests included" checkbox. Thank you for clarifying.

**Comment by lukastaegert** [comment]
@AllNamesRTaken unfortunately you did not answer the other important question: Why? Do you have any issue with these types?

I am sorry but our exported types depend on the presence of these types on the users' system. More specifically, without these files our types will be broken for typescript users making this a breaking change indeed. We had long discussions about this. Bundling them the same way we do with our other dependencies is not an option as those bundled types would cause conflicts if a user depends on them as well. If you know a better solution, please come forward.

**Comment by AllNamesRTaken** [comment]
Thanks. Got it.
I saw your other comment and will work around it.
It might still be a healthy thing to fix I guess. :)

**Comment by lukastaegert** [comment]
I guess this can be closed for now?

**Comment by GrosSacASac** [comment]
As for why, this is causing installation issues when rollup is a dependency of a dev dependency. Current workaround is to use --ignore-scripts. I wil open a detailed issue when I have more time.

**Pull request closed without merging**
