### PR TITLE
Improve minChunkSize algorithm

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
- https://github.com/rollup/rollup/issues/4327#issuecomment-1323095433

### Description
This PR improves the minChunkSize algorithm in several ways:
- In a new first pass, the algorithm tries to merge small chunks with side effects with suitable chunks without side effects to increase size. A pure chunk is "suitable" for being merged if the entry points depending on that chunk are a sub set of the entry points of the chunk with side effects (that way, the side effect is not introduced to new entry points)
- In a second pass, small pure chunks are merged into other pure or non-pure chunks (following the above rule if the merge target has side effects)
- Chunks (small and large) are sorted by size first to increase the chance of small chunks finding merge partners vs larger chunks
- A merge will only be performed if it does not create a cyclic dependency

Even though we now have a step to merge chunks with side effects, it still requires a sufficient amount of pure chunks to be present, and there is no guarantee suitable merge partners are available. This PR also includes #4718 to allow to try out stuff.

It also contains some simple logging to get some numbers how many chunks were merged and which chunks were not merged.

@gajus would be nice if you could give this one a shot and report the results.

### CODE REVIEW

**Comment by lukastaegert** [comment]
@gajus please give this PR another shot and report the results.

**Comment by gajus** [comment]
> @gajus please give this PR another shot and report the results.

Is this the `3.6.0-1` release?

If yes, this logs at build time:

```
Created 439 chunks
----- pure  side effects
small 257   172
  big 0     10

Trying to find merge targets for 172 chunks smaller than 500 kB with side effects...
172 chunks smaller than 500 kB with side effects remaining.

Trying to find merge targets for 41 pure chunks smaller than 500 kB...
5 pure chunks smaller than 500 kB remaining.
```

and at runtime it breaks with

```
Uncaught TypeError: S is not a function
    at Ce (chunk-ErrorBoundary.26a1e903.js:79:5156)
    at chunk-usePersistedReferralIntent.252f193a.js:2:30771
Ce @ chunk-ErrorBoundary.26a1e903.js:79
(anonymous) @ chunk-usePersistedReferralIntent.252f193a.js:2
```

Removing `experimentalMinChunkSize` configuration makes the app work again.

**Comment by lukastaegert** [comment]
I see, I think I had some wrong assumptions here. I reworked the algorithm to explicitly avoid creating cycles within chunks, not module dependencies. Could you run it again with `rollup@3.6.1-0`?

**Comment by gajus** [comment]
> `3.6.1-0`?

haven't had a chance to debug yet, but it is a new error at the moment:

> Uncaught TypeError: Cannot read properties of undefined (reading 'exports')
>    at chunk-index.c5dffacd.js:11:83112

**Comment by gajus** [comment]
Build logs:

```
Created 461 chunks
----- pure  side effects
small 265   186
  big 0     10
Unoptimized chunks contain 0 cycles.

Trying to find merge targets for 186 chunks smaller than 500 kB with side effects...
186 chunks smaller than 500 kB with side effects remaining.
Generated chunks contain 179 cycles.

Trying to find merge targets for 7 pure chunks smaller than 500 kB...
1 pure chunks smaller than 500 kB remaining.
Generated chunks contain 200 cycles.
```

Runtime logs:

```
chunk-Stripes.eec2eb5e.js:1 Uncaught ReferenceError: Cannot access 'p' before initialization
    at chunk-Stripes.eec2eb5e.js:1:3546
```

Is there anything in terms of logs that you were seeking for?

**Comment by lukastaegert** [comment]
> Generated chunks contain 179 cycles.

Thanks, this answers my question. Need to think a little longer how to properly prevent the creation of cycles. But should be a solvable issue.

**Comment by lukastaegert** [comment]
Ok, I reworked the cycle prevention algorithm. Could you give `rollup@3.7.3-0` another go and report the console output and whether it now works?

**Comment by gajus** [comment]
👋 Let's see...

Console output:

```
Created 468 chunks
----- pure  side effects
small 269   189
  big 0     10
Unoptimized chunks contain 0 cycles.

Trying to find merge targets for 189 chunks smaller than 500 kB with side effects...
189 chunks smaller than 500 kB with side effects remaining.
Generated chunks contain 118 cycles.

Trying to find merge targets for 46 pure chunks smaller than 500 kB...
3 pure chunks smaller than 500 kB remaining.
Generated chunks contain 174 cycles.

202 chunks remaining.
```

Same error as earlier though:

```
chunk-index.module.ae520628.js:17 Uncaught TypeError: Cannot read properties of undefined (reading 'exports')
    at chunk-index.module.ae520628.js:17:14
```

**Comment by lukastaegert** [comment]
Ok, I managed to reproduce the issue locally and hopefully found a way to fix the issue for good. Apparently, I was not tracking transitive dependencies correctly. I hope performance of the current solution is still ok.
Please give `rollup@3.7.5-0` another go.

**Comment by gajus** [comment]
> Ok, I managed to reproduce the issue locally and hopefully found a way to fix the issue for good. Apparently, I was not tracking transitive dependencies correctly. I hope performance of the current solution is still ok. Please give `rollup@3.7.5-0` another go.

Unfortunately, same error. Happy to provide as much context as needed.

**Comment by lukastaegert** [comment]
So, no change in the number of cycles found?

**Comment by gajus** [comment]
```
✓ 8427 modules transformed.
Created 485 chunks
----- pure  side effects
small 277   198
  big 0     10
Unoptimized chunks contain 0 cycles.

Trying to find merge targets for 198 chunks smaller than 500 kB with side effects...
198 chunks smaller than 500 kB with side effects remaining.
Generated chunks contain 126 cycles.

Trying to find merge targets for 8 pure chunks smaller than 500 kB...
1 pure chunks smaller than 500 kB remaining.
Generated chunks contain 126 cycles.
```

**Comment by lukastaegert** [comment]
Usually I take pride in the great algorithms I devise but for this one, I do not know. In the end, I think it is premature optimization that has been breaking my neck. I now changed to a much simpler algorithm because I think all my ideas about caching transitive dependencies were misguided. Could you please try out `rollup@3.7.6-0` and also report what the logging says?

**Comment by gajus** [comment]
```
Created 536 chunks
----- pure  side effects
small 302   224
  big 0     10
Unoptimized chunks contain 0 cycles.

Trying to find merge targets for 224 chunks smaller than 500 kB with side effects...
224 chunks smaller than 500 kB with side effects remaining.
Generated chunks contain 0 cycles.

Trying to find merge targets for 10 pure chunks smaller than 500 kB...
2 pure chunks smaller than 500 kB remaining.
Generated chunks contain 0 cycles.

236 chunks remaining.
```

Sadly, same. If somehow helpful, I can link to the deployed instance of this code.

Here is the current error:

```
chunk-isValidEmail.422ea7aa.js:1 Uncaught ReferenceError: Cannot access 'p' before initialization
    at chunk-isValidEmail.422ea7aa.js:1:4221
(anonymous) @ chunk-isValidEmail.422ea7aa.js:1
chunk-index.fac8862b.js:118 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
62chunk-isValidEmail.422ea7aa.js:1 Uncaught ReferenceError: Cannot access 'p' before initialization
    at chunk-isValidEmail.422ea7aa.js:1:4221
```

What I do find slightly confusing about this is that `isValidEmail` does not even have dependencies. This is the source file:

```ts
/* eslint-disable unicorn/better-regex, no-useless-escape */
const EMAIL_REGEX =
  /^(([^<>()\[\]\/\\.,;:\s@"]+(\.[^<>()\[\]\/\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

export const isValidEmail = (email: string | null | undefined): boolean => {
  if (!email) return false;

  return EMAIL_REGEX.test(email);
};
```

And this is the chunk that is breaking:

```ts
import {a as f} from "./chunk-_commonjsHelpers.908afc9d.js";
import {j as r, a as i} from "./chunk-utils.afade0a9.js";
import {r as u, u as v} from "./entry-src/pages/stripe-3ds-return.page.client.af195d57.js";
import {s as p, a as x, b as g, B as w, q as m, l as E, c as L} from "./chunk-WorkAvailability.styles.2ac32e20.js";
var l = {
    exports: {}
};
(function(e) {
    function o(a) {
        if (a === void 0)
            throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
        return a
    }
    e.exports = o,
    e.exports.__esModule = !0,
    e.exports.default = e.exports
}
)(l);
const j = f(l.exports)
  , y = e=>r("svg", Object.assign({
    width: "1em",
    height: "1em",
    viewBox: "0 0 24 24",
    fill: "none",
    xmlns: "http://www.w3.org/2000/svg",
    focusable: "false",
    role: "img"
}, e, {
    children: [i("path", {
        d: "M13 1.5V3h6.94L9.47 13.47l1.06 1.06L21 4.06V11h1.5V1.5H13z",
        fill: "currentColor"
    }, void 0), i("path", {
        d: "M21 13h-1.5v3.95c0 .852 0 1.447-.038 1.91-.037.453-.107.714-.207.912a2.25 2.25 0 01-.983.983c-.198.1-.459.17-.913.207-.462.037-1.057.038-1.909.038h-8.4c-.852 0-1.447 0-1.91-.038-.453-.038-.714-.107-.911-.207a2.25 2.25 0 01-.984-.983c-.1-.198-.17-.459-.207-.913C3.001 18.397 3 17.802 3 16.95v-8.4c0-.852 0-1.447.038-1.91.037-.453.107-.714.207-.911a2.25 2.25 0 01.984-.984c.197-.1.458-.17.912-.207.462-.037 1.057-.038 1.909-.038H11V3H7.018c-.813 0-1.469 0-2 .043-.546.045-1.026.14-1.47.366a3.75 3.75 0 00-1.64 1.639c-.226.444-.32.924-.365 1.47-.043.531-.043 1.187-.043 2v8.464c0 .813 0 1.469.043 2 .045.546.14 1.026.366 1.47a3.75 3.75 0 001.639 1.64c.444.226.924.32 1.47.365.531.043 1.187.043 2 .043h8.464c.813 0 1.469 0 2-.043.546-.045 1.026-.14 1.47-.366a3.75 3.75 0 001.64-1.639c.226-.444.32-.924.365-1.47.043-.531.043-1.187.043-2V13z",
        fill: "currentColor"
    }, void 0)]
}), void 0)
  , C = e=>r("svg", Object.assign({
    width: "1em",
    height: "1em",
    viewBox: "0 0 24 24",
    fill: "none",
    xmlns: "http://www.w3.org/2000/svg",
    focusable: "false",
    role: "img"
}, e, {
    children: [r("g", Object.assign({
        clipPath: "url(#prefix__clip0_39_15279)",
        fill: "currentColor"
    }, {
        children: [i("path", {
            d: "M9.746 7.925l1 10-1.492.15-1-10 1.492-.15zM13.254 17.925l1-10 1.492.15-1 10-1.492-.15z"
        }, void 0), i("path", {
            fillRule: "evenodd",
            clipRule: "evenodd",
            d: "M11.42 0c-.535 0-.98 0-1.345.03-.38.03-.736.098-1.073.27A2.75 2.75 0 007.8 1.502c-.172.337-.24.693-.27 1.073-.011.131-.018.273-.022.425H1v1.5c.708 0 .904.008 1.05.05.365.107.661.374.806.725.058.141.086.335.16 1.04l1.44 13.677c.05.482.093.886.154 1.216.064.346.157.667.338.967.28.463.692.833 1.182 1.063.317.15.646.209.996.236.335.026.741.026 1.226.026h7.296c.485 0 .891 0 1.226-.026.35-.027.679-.086.996-.236.49-.23.901-.6 1.182-1.063.181-.3.274-.621.338-.967.061-.33.104-.734.154-1.216l1.44-13.677c.074-.705.102-.899.16-1.04a1.25 1.25 0 01.805-.725c.147-.042.343-.05 1.051-.05V3h-6.508a8.142 8.142 0 00-.022-.425c-.03-.38-.098-.736-.27-1.073A2.75 2.75 0 0015 .3c-.338-.172-.694-.24-1.074-.27C13.56 0 13.115 0 12.58 0h-1.16zm3.572 3a6.272 6.272 0 00-.017-.303c-.023-.287-.065-.424-.111-.514a1.25 1.25 0 00-.546-.547c-.091-.046-.228-.088-.515-.111-.296-.024-.68-.025-1.253-.025h-1.1c-.572 0-.957 0-1.252.025-.288.023-.425.065-.515.111a1.25 1.25 0 00-.547.547c-.046.09-.088.227-.111.514A6.24 6.24 0 009.008 3h5.984zM4.149 4.5h15.702a2.773 2.773 0 00-.094.205c-.151.368-.196.797-.254 1.35l-1.447 13.752c-.055.517-.092.863-.14 1.129-.048.256-.098.38-.147.462a1.25 1.25 0 01-.537.483c-.087.041-.215.077-.475.098-.27.02-.617.021-1.138.021H8.381c-.521 0-.869 0-1.138-.021-.26-.02-.387-.057-.475-.098a1.25 1.25 0 01-.537-.483c-.05-.083-.099-.206-.146-.462-.05-.266-.086-.612-.14-1.13L4.496 6.056c-.058-.554-.103-.983-.254-1.35A2.748 2.748 0 004.15 4.5z"
        }, void 0)]
    }), void 0), i("defs", {
        children: i("clipPath", Object.assign({
            id: "prefix__clip0_39_15279"
        }, {
            children: i("path", {
                fill: "#fff",
                d: "M0 0h24v24H0z"
            }, void 0)
        }), void 0)
    }, void 0)]
}), void 0)
  , A = (e,o,a)=>{
    const n = e.map(s=>window.matchMedia(s))
      , c = ()=>{
        const s = n.findIndex(t=>t.matches);
        return o[s] ?? a
    }
      , [d,h] = u.exports.useState(c);
    return v(()=>{
        const s = ()=>h(c);
        return n.forEach(t=>{
            typeof t.addEventListener == "function" ? t.addEventListener("change", s) : typeof t.addListener == "function" && t.addListener(s)
        }
        ),
        ()=>n.forEach(t=>{
            typeof t.removeEventListener == "function" ? t.removeEventListener("change", s) : typeof t.removeListener == "function" && t.removeListener(s)
        }
        )
    }
    ),
    d
}
  , I = p.div.withConfig({
    shouldForwardProp: x
})`
  ${g}
  ${w}
  ${m}
  ${E}
  ${L}
`
  , M = /^(([^<>()\[\]\/\\.,;:\s@"]+(\.[^<>()\[\]\/\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
  , O = e=>e ? M.test(e) : !1;
export {I as B, y as E, C as T, j as _, l as a, O as i, A as u};
```

Maybe this is expected, but sharing just in case.

I thought maybe `treeshake` configuration is messing with `experimentalMinChunkSize`, but removing it doesn't seem to change the behavior much:

```
Created 450 chunks
----- pure  side effects
small 186   253
  big 0     11
Unoptimized chunks contain 0 cycles.

Trying to find merge targets for 253 chunks smaller than 500 kB with side effects...
253 chunks smaller than 500 kB with side effects remaining.
Generated chunks contain 0 cycles.

Trying to find merge targets for 33 pure chunks smaller than 500 kB...
3 pure chunks smaller than 500 kB remaining.
Generated chunks contain 0 cycles.

267 chunks remaining.
```

Different error though:

```
chunk-ChevronDown.c735fda0.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'exports')
    at chunk-ChevronDown.c735fda0.js:1:172
    at chunk-ChevronDown.c735fda0.js:11:2682
```

**Comment by lukastaegert** [comment]
That is an intriguing error. Are you on the very latest version of the commonjs plugin?

**Comment by gajus** [comment]
Are you referring to `@rollup/plugin-commonjs`? I don't see this in our dependency tree at all.

**Comment by gajus** [comment]
I've added `@originjs/vite-plugin-commonjs`, removed `treeshake` and re-ran with `experimentalMinChunkSize`. It worked, I think? Adding `treeshake` breaks it, however. I am still debugging.

```
-rw-r--r--@   1 gajus  staff   1.0M Dec 20 12:29 chunk-styleOverrides.ad28bffe.js
-rw-r--r--@   1 gajus  staff   753K Dec 20 12:29 chunk-index.112ea425.js
-rw-r--r--@   1 gajus  staff   383K Dec 20 12:29 manifest.json
-rw-r--r--@   1 gajus  staff   380K Dec 20 12:29 chunk-mml-react.esm.f26c7395.js
-rw-r--r--@   1 gajus  staff   376K Dec 20 12:29 chunk-ErrorBoundary.73cc1762.js
-rw-r--r--@   1 gajus  staff   300K Dec 20 12:29 chunk-MainLayout.8c43d3c7.js
-rw-r--r--@   1 gajus  staff   277K Dec 20 12:29 chunk-index.c89c15bc.js
-rw-r--r--@   1 gajus  staff   265K Dec 20 12:29 chunk-Main.6203c3b2.js
-rw-r--r--@   1 gajus  staff   250K Dec 20 12:29 chunk-index.74f135ed.js
-rw-r--r--@   1 gajus  staff   246K Dec 20 12:29 chunk-ContraSlateEditorWrapper.4ad9587b.js
-rw-r--r--@   1 gajus  staff   239K Dec 20 12:29 entry-entry-client-routing.4de8d4d2.js
-rw-r--r--@   1 gajus  staff   236K Dec 20 12:29 chunk-ResourceDetails.af9c70fc.js
-rw-r--r--@   1 gajus  staff   200K Dec 20 12:29 entry-entry-server-routing.8cd41ac4.js
-rw-r--r--@   1 gajus  staff   169K Dec 20 12:29 chunk-ProfileLayout.51f8bbf5.js
-rw-r--r--@   1 gajus  staff   128K Dec 20 12:29 chunk-ContraPayments.6fa5dbeb.js
-rw-r--r--@   1 gajus  staff    93K Dec 20 12:29 chunk-ProjectProposalPageBackground.92728b13.js
...
-rw-r--r--@   1 gajus  staff    17K Dec 20 12:29 chunk-DiscoverTalentPageBackground.00afb016.js
-rw-r--r--@   1 gajus  staff    17K Dec 20 12:29 chunk-RolesList.63b14f2f.js
-rw-r--r--@   1 gajus  staff    16K Dec 20 12:29 chunk-AdminSignInUrl.94724207.js
-rw-r--r--@   1 gajus  staff    16K Dec 20 12:29 chunk-editIdProjectsClientPageQuery.graphql.2ec16293.js
-rw-r--r--@   1 gajus  staff    15K Dec 20 12:29 chunk-CardListItemAnimation.273022a3.js
-rw-r--r--@   1 gajus  staff    15K Dec 20 12:29 chunk-reducer.d13cb191.js
-rw-r--r--@   1 gajus  staff    15K Dec 20 12:29 chunk-ProfileOpportunities.c4c10af1.js
...
-rw-r--r--@   1 gajus  staff   570B Dec 20 12:29 chunk-OrSeparator.05e4c860.js
-rw-r--r--@   1 gajus  staff   553B Dec 20 12:29 chunk-BlankCardMessage.303f26d6.js
-rw-r--r--@   1 gajus  staff   496B Dec 20 12:29 chunk-DraftResourceTag.styles.a52f9630.js
-rw-r--r--@   1 gajus  staff   465B Dec 20 12:29 chunk-DraftResourceCallout.styles.45b50653.js
-rw-r--r--@   1 gajus  staff   401B Dec 20 12:29 chunk-Container.1dc36607.js
```

There are still many small chunks, but I believe this is because the custom `treeshake` configuration had to be disabled.

**Comment by gajus** [comment]
As a reminder, this is our `vite.config.ts` config:

```ts
import path from 'path';
import { viteCommonjs } from '@originjs/vite-plugin-commonjs';
import { default as react } from '@vitejs/plugin-react';
import { defineConfig, type BuildOptions } from 'vite';
import { default as viteCompression } from 'vite-plugin-compression';
import relay from 'vite-plugin-relay-lite';
import { default as ssr } from 'vite-plugin-ssr/plugin';
import { type UserConfig } from 'vitest/config';

const { VITEST, CWA_BASE_ASSETS_URL, CWA_BASE_SERVER_URL, GENERATE_SOURCEMAP } =
  process.env;

export default defineConfig(({ ssrBuild }) => {
  let build: BuildOptions | undefined;

  if (!ssrBuild) {
    build = {
      emptyOutDir: true,
      manifest: true,
      minify: true,
      modulePreload: {
        polyfill: true,
      },
      rollupOptions: {
        output: {
          chunkFileNames: 'chunk-[name].[hash].js',
          entryFileNames: 'entry-[name].[hash].js',
          experimentalMinChunkSize: 200_000,
          sourcemap: GENERATE_SOURCEMAP === 'true',
        },
        // treeshake: {
        //   manualPureFunctions: ['styled', 'css'],
        //   preset: 'recommended',
        // },
      },
      sourcemap: GENERATE_SOURCEMAP === 'true',
    };
  }

  const plugins = [
    viteCommonjs(),
    react(),
    relay({
      codegen: false,
    }),
  ];

  if (VITEST !== 'true') {
    plugins.push(
      viteCompression({
        // This is used mostly to speed up the integration tests.
        algorithm: 'brotliCompress',
      }),
      ssr({
        baseAssets: CWA_BASE_ASSETS_URL,
        baseServer: CWA_BASE_SERVER_URL,
      })
    );
  }

  const test: UserConfig['test'] = {
    clearMocks: true,
    coverage: {
      provider: 'istanbul',
      reporter: ['text-summary', 'lcov'],
    },
    environment: 'jsdom',
    include: [
      './src/**/__tests__/**/*.{js,jsx,ts,tsx}',
      './src/**/*.test.{js,jsx,ts,tsx}',
    ],
    setupFiles: './src/setupTests.ts',
  };

  return {
    build,
    plugins,
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src/'),
      },
    },
    test,
  };
});
```

**Comment by gajus** [comment]
I am a bit confused here. Reading Vite documentation, it does not seem like `@originjs/vite-plugin-commonjs` should be needed. Documentation implies that `@rollup/plugin-commonjs` is already used by Vite when building for production.

However, Vite does not have dependency on `@rollup/plugin-commonjs`.

**Comment by lukastaegert** [comment]
Interesting. Yes, I think Vite is using it by default, and the error reminded me of another issue for said plugin. I wonder if it is bundled. Otherwise, I wonder if explicitly installing the latest version of `@rollup/plugin-commonjs` has any effect. And then, I think with Vite 3 you can switch to using esbuild instead of the commonjs plugin for production bundling via some option, would be interesting to try that out as well.

**Comment by Dreamypops33** [comment]
Interesting

**Comment by fabiospampinato** [comment]
Random question: if I set the min chunk size to `Infinity`, is it equivalent to setting `manualChunks` to `{}`?

**Comment by lukastaegert** [comment]
No, this is not the same thing. `manualChunks` forces modules in the same chunk even if that changes produces side effects that should not happen and changes execution order. So for instance imagine

```js
// main.js
if (condition) {
  import('./other.js');
}

// other.js
console.log('other');
```

Using `manualChunks` will just put the two modules into the same chunk, which means the console.log will happen always and immediately and not after the dynamic import and only if the condition is met. This is why `manualChunks` should only ever be a last-resort option and really requires to have a manual look at the chunks you want to merge.

This feature, on the other hand, is based on side effect detection and will only merge very conservatively if it is absolutely sure side effects are not executed at the wrong time.

If you only have a single entry and all your modules except your entry module do not have side effects, then indeed it will merge everything into a single chunk.

**Comment by gajus** [comment]
@lukastaegert Could we update this branch/npm release with the latest changes?

**Comment by lukastaegert** [comment]
I sent you a message on Discord to discuss further options

**Comment by lukastaegert** [comment]
I removed the logging and will merge the changes from this branch into master and release them as I think they are still a net-improvement. But I guess we need to keep working on this feature.

**Comment by shirotech** [comment]
> Using `manualChunks` will just put the two modules into the same chunk

Can you use both `manualChunks` and `experimentalMinChunkSize` both will do it's own thing without one replacing the other?

**Comment by gajus** [comment]
@lukastaegert I've been heads down helping team to prepare for the upcoming launch, but now have a bit more time to debug this.

For what it is worth, I can see from debugging our build that the issue is caused by a circular reference.

I've removed all instances that were triggering `CYCLIC_CROSS_CHUNK_REEXPORT`. However, as soon as I re-add `minChunkSize`, it is starting to fail – seems like the dependencies that get bundled create a circular reference.

I am making further code changes on our end to reduce the risk of circular dependencies. Will follow up once I know more.

**Comment by gajus** [comment]
Removing all circular references from the codebase did not solve the issue.

**Comment by lukastaegert** [comment]
@shirotech

> Can you use both manualChunks and experimentalMinChunkSize both will do it's own thing without one replacing the other?

Exactly. It is possible that `experimentalMinChunkSize` merges additional chunks into a manual chunk.

@gajus 

Not sure if this is any option, but if you can grant me temporary access to your code (under an NDA of course), I could debug it from there, which would be much simpler. I sent you a Discord message regarding this.

**Comment by gajus** [comment]
> Not sure if this is any option, but if you can grant me temporary access to your code (under an NDA of course), I could debug it from there, which would be much simpler. I sent you a Discord message regarding this.

I saw your message (sorry again for poor communication), and I've asked to evaluate what would it take to share access. The problem is that app is part of a mono repo that includes a lot of sensitive information.

**Comment by gajus** [comment]
You know, I will just power through this and setup something. Might take a few days, but worth it. Will DM when ready.

**Comment by gajus** [comment]
Still trying to get an isolated app to work.

For what it is worth, the error that we are getting now is:

```
chunk-index.d8e05bc2.js:17 Uncaught TypeError: Cannot read properties of undefined (reading '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED')
    at chunk-index.d8e05bc2.js:17:228
    at chunk-index.d8e05bc2.js:147:612
```

Which is slightly different than what it was before.

It seems almost like there is a circular reference among react dependencies.

**Comment by gajus** [comment]
@lukastaegert So some good news and not so good news.

The not so good news is that I was not able to create an isolated example of what is breaking chunking.

The good news is that while trying to create an isolated project, I narrowed down the issue to just one dependency. So we just need to figure out what that (internal) dependency is doing that is breaking chunking.

**Comment by lukastaegert** [comment]
Great stuff! I will report back with my findings.

**Comment by gajus** [comment]
Heads up that this turned out to be mostly a false-positive finding. Sent an update through Discord.

**Comment by lukastaegert** [comment]
Hi. When I set `build.commonjsOptions.strictRequires: true` in your `vite.config.ts` it fixes the issue for me. Can you confirm this for your full build? That would confirm my belief that it has to do something with the commonjs plugin. In any case, setting this option to `true` is safe and even recommended. I currently ponder making this setting a default of the commonjs plugin.

As background, `build.commonjsOptions` directly configures `@rollup/plugin-commonjs`: https://github.com/rollup/plugins/tree/master/packages/commonjs#strictrequires

What puzzles me is how the chunking can trigger a bug here, so I will do some more digging. But maybe in the end, this can already be the solution. Otherwise, your reproduction is also a very good testing ground for build memory and performance improvements 😉

**Comment by gajus** [comment]
So, it is failing for a different reason now:

```
14chunk-useIsSmallScreen.4fff2a71.js:2048 Uncaught TypeError: Cannot set properties of undefined (setting 'Children')
    at chunk-useIsSmallScreen.4fff2a71.js:2048:26
    at chunk-useIsSmallScreen.4fff2a71.js:2086:9
    at requireReact_development (chunk-useIsSmallScreen.4fff2a71.js:2088:5)
    at chunk-useIsSmallScreen.4fff2a71.js:2098:24
    at requireReact (chunk-useIsSmallScreen.4fff2a71.js:2100:5)
    at chunk-index.e953bbca.js:21:20
```

which refers to:

```
        var Children = {
          map: mapChildren,
          forEach: forEachChildren,
          count: countChildren,
          toArray,
          only: onlyChild
        };
        exports.Children = Children;
        exports.Component = Component;
        exports.Fragment = REACT_FRAGMENT_TYPE;
```

This looks like a fragment of React library.

**Comment by lukastaegert** [comment]
Ah, that is very interesting. So it still seems to be related to some bug in the commonjs logic. If have some ideas for how I want to improve that plugin, I will try some things.

**Comment by gajus** [comment]
When doing `minChunkSize`, is there a way to tell not to merge specific chunks?

I just realized that it is merging page chunks, which is not desirable.

```
import "./me.page.client.a1bf777a.js";
import "../../chunk-useRoutes.ad41330f.js";
import "../../chunk-index.4988a863.js";
import "../../chunk-usePostHog.af72090a.js";
import "../../chunk-logger.40d3ad32.js";
import "./wallet.page.client.3636703f.js";
import "../../chunk-async-storage.39ded5be.js";
import "../../chunk-WindowDimensionsContext.e0712d35.js";
import "../../chunk-useUserTypeSelector.d0fa7beb.js";
import "../../chunk-index.ff67dbb0.js";
import "../../chunk-index.599a5f27.js";
import "./edit-profile.page.client.6afc5f59.js";
```

**Comment by lukastaegert** [comment]
Why is that not desireable? Is there a logic that relies on these chunks being present? Or is it causing issues in other places? We can certainly implement some option on top to preserve certain chunks, but the implementation depends on what issues the merge causes. But the more chunks are excluded, the harder it will be to meet any size constraints.

**Comment by lukastaegert** [comment]
Also, please give #4851 a spin!

**Comment by shirotech** [comment]
Hi @lukastaegert great work on the algorithm, just one thing I noticed when working with both `manualChunks` and `minChunkSize` together. Hoping to get some advice on that is it possible to override the behaviour of `minChunkSize` i.e. referring to the core function in `manualChunks`, and so it's more predictable.

For example I can see the main function is referred here: https://github.com/rollup/rollup/blob/a7b36ca8247c8e088f0782d64128ae6be1df24f5/src/utils/chunkAssignment.ts#L279

Would you be open to exporting all those functions in that file so that it is possible to make use of it within the `manualChunks` hook itself?

**Comment by lukastaegert** [comment]
Not sure. On the one hand this is still experimental and can and will change a couple more times during upcoming releases. But the main problem is that the algorithm heavily relies on analytics done in other parts of chunking algorithm, while `manualChunks` runs before other chunking to remove modules from the regular chunking algorithm. It very much depends on what you want to accomplish.

**Comment by lukastaegert** [comment]
> When doing minChunkSize, is there a way to tell not to merge specific chunks?

I just noticed that there are still scenarios where side effects are triggered earlier than they should, which may be the problem you are seeing. I have an idea how to fix this, will put this into #4851

**Comment by lukastaegert** [comment]
Ok, I reworked #4851, maybe that addresses the issues you saw with page chunks.

**Pull request merged**
