### PR TITLE
resolve implied /index.js

### PR DESCRIPTION
**Pull request by kellyselden**
This is normally accomplished via rollup-plugin-node-resolve, but since this doesn't involve searching node_modules, we should include this alongside the implied ".js" check we already do. This means we now search "file", "file.js", and "file/index.js".

### CODE REVIEW

**Comment by TrySound** [comment]
@kellyselden Does browser resolve `index.js` in the same way?

**Comment by guybedford** [comment]
I think it would be inconsistent to add parts of Node resolution without embracing others.

I'd rather see this handled through plugins or the underlying issue addressed by working on the usability problems to make Node preset workflows easier in Rollup.

**Comment by lukastaegert** [comment]
I totally agree with @guybedford here.

**Comment by kellyselden** [comment]
I disagree slightly. We are already assuming ".js" for people. Seems natural to complete the lookup by checking "/index.js" as well. That or move our ".js" assumption to node-resolve to be consistent.

**Comment by kellyselden** [comment]
It also seems a little counter intuitive. The idea that you only need rollup-plugin-node-resolve once your project starts using npm falls apart. Maybe I am missing something?

**Comment by lukastaegert** [comment]
As @Rich-Harris already stated at other times, the fact that you do not need a .js extension was quite probably a mistake that is now hard to put right. The JavaScript specs nowhere specify anything about extensions being unnecessary or index.js being loaded automatically when you import something. This is all part of the way node handles these things. So what assumptions should we be making about a user‘s system (all of which are wrong in a browser environment)? Also, it requires file system access to check these things anyway.

**Comment by shellscape** [comment]
@guybedford @lukastaegert given the consensus is that this would a negative change, should we decline this change and close the PR?

**Comment by guybedford** [comment]
I definitely think we still need to improve the "nodejs preset" use case, but we can track that separately.

**Pull request closed without merging**
