### PR TITLE
Add __esModule to namespaces

### LINKED ISSUE #3760: Output cjs chunk lost `__esModule ` for es module.
- Rollup Version: 2.26.5
- Operating System (or Browser): Mac
- Node Version (if applicable): 
- Link to reproduction (IMPORTANT, read below): https://github.com/tbgse/vite-ssr-example 

## Input
``` js
import {ssrRenderAttrs} from "@vue/server-renderer";
var script = {
  name: "PageB"
};
function ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<h1${ssrRenderAttrs(_attrs)}>I AM PAGE B</h1>`);
}
script.ssrRender = ssrRender;
export default script;
```
## Output
``` js
"use strict";
var renderer = require("@vue/server-renderer");
var script = {
  name: "PageB"
};
function ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<h1${renderer.ssrRenderAttrs(_attrs)}>I AM PAGE B</h1>`);
}
script.ssrRender = ssrRender;
exports.default = script;
```

Original issues: https://github.com/vitejs/vite/issues/764

The input is a chunk, not a entry.Maybe we should change this line to `(this.facadeModule !== null)`.I'm not sure for this, hope get some help,thanks.
https://github.com/rollup/rollup/blob/master/src/Chunk.ts#L714-L716

### Expected Behavior

Output cjs chunk should hsa `__esModule ` for es module. Has code `Object.defineProperty(exports, '__esModule', { value: true });`

### Actual Behavior

Output cjs chunk lost `__esModule ` for es module.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #3760 

### Description
Unless `output.esModule` is explicitly set to `false`, this will add the non-enumerable `__esModule` property to
1. external namespaces for non-ES formats unless `interop` is set to 'esModule'
2. chunks that are the target of a dynamic import where the namespace of the chunk correspond to the namespace of the original module for non-ES formats
3. reified namespace objects for ALL formats

Even though this property is not really standardized, this will solve some tricky interop issues when using CommonJS modules as well as allow to reliably detect if something is an ES namespace via `namespace.__esModule || namespace[Symbol.toStringTag] === 'Module'`.

As background, note that with the changes in `@rollup/plugin-commonjs@15`, CommonJS modules importing from an ES module will by default receive the namespace of the module. This would not work correctly if the CommonJS module is checking for the `__esModule` property to determine where to find the default export.

The three cases listed above are each solved slightly differently:
1. For external dependencies, direct references to the `__esModule` property of the import will be replaced with `true` [[REPL]](https://rollupjs.org/repl/?circleci=12868&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGZvbyUyMGZyb20lMjAnZXh0ZXJuYWwnJTNCJTVDbmNvbnNvbGUubG9nKGZvby5fX2VzTW9kdWxlKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE). If the namespace object is passed to a function or otherwise handled in a way so that the whole object is needed, the corresponding helper will add the new property [[REPL]](https://rollupjs.org/repl/?circleci=12868&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGZvbyUyMGZyb20lMjAnZXh0ZXJuYWwnJTNCJTVDbiU1Q25sb2dFc01vZHVsZShmb28pJTNCJTVDbiU1Q25mdW5jdGlvbiUyMGxvZ0VzTW9kdWxlKG5zKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZyhucy5fX2VzTW9kdWxlKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).
2. If the target of a dynamic import corresponds to a chunk, the `__esModule` property is added as with regular entry points [[REPL]](https://rollupjs.org/repl/?circleci=12868&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCgnLiUyRmZvbycpLnRoZW4obnMlMjAlM0QlM0UlMjBjb25zb2xlLmxvZyhucy5fX2VzTW9kdWxlKSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMDQyJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE). If the chunk uses default export mode, this is handled by the corresponding helper [[REPL]](https://rollupjs.org/repl/?circleci=12868&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCgnLiUyRmZvbycpLnRoZW4obnMlMjAlM0QlM0UlMjBjb25zb2xlLmxvZyhucy5fX2VzTW9kdWxlKSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMDQyJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).
3. If a namespace of a module is passed to a function, the property is added as well [[REPL]](https://rollupjs.org/repl/?circleci=12868&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGZvbyUyMGZyb20lMjAnLiUyRmZvby5qcyclM0IlNUNubG9nRXNNb2R1bGUoZm9vKSUzQiU1Q24lNUNuZnVuY3Rpb24lMjBsb2dFc01vZHVsZShucyklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2cobnMuX19lc01vZHVsZSklM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjA0MiUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

### CODE REVIEW

**Comment by lukastaegert** [comment]
I extended the description with some more examples to see how it works in the various situations.

**Review by guybedford — CHANGES_REQUESTED** [review]
I don't think we should enable this by default for the System and ES module formats.

That is allowing legacy interop concerns to then affect modern output which we may be stuck with in future.

If we need markers on namespaces for modern module formats, the marker should be the toStringTag marker as defined by the specification.

I was also under the impression that the `esModule` option only applied to non-es formats so I think we should retain that property.

**Comment by lukastaegert** [comment]
It did so far. However one important problem I am solving is this:
 Assume we have the following modules where main.js is CommonJS:

```js
// main.js
var _lib = _interopRequireDefault(require('./lib.js'));
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj };
}
console.log(_lib.default);

// lib.js
export default 42
```

If I bundle this via `@rollup/plugin-commonjs`, then it becomes something like

```js
var lib = 42;

var lib$1 = /*#__PURE__*/Object.freeze({
	__proto__: null,
	'default': lib
});

var main = createCommonjsModule(function (module) {
var _lib = _interopRequireDefault(lib$1);
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj };
}
console.log(_lib.default);
});
```

which will be broken for every output format because the generated namespace object does not contain the `__esModule` property.

Now this problem can also be solved within the CommonJS plugin, but the best solution I could come up with here is to add another non-trivial helper that takes the namespace object and basically creates a copy where the property is added, cf. rollup/plugins#552:

```js
function getAugmentedNamespace(n) {
	var a = Object.defineProperty({}, '__esModule', {value: true});
	Object.keys(n).forEach(function (k) {
		var d = Object.getOwnPropertyDescriptor(n, k);
		Object.defineProperty(a, k, d.get ? d : {
			enumerable: true,
			get: function () {
				return n[k];
			}
		});
	});
	return a;
}
```

Solving this in Rollup core is much more efficient and has the advantage that it also solves the problem presented in #3760. The alternative solution is having both the change to the commonjs plugin as outlined above + always activating the namespace toStringTag, which unfortunately is a breaking change as it requires the ES2015 baseline since it relies on `Symbol`.

And not only that, we need to expand the logic and add the tag to chunks that are imported dynamically as well as entry points. Thoughts?

**Comment by lukastaegert** [comment]
So to sum it up, just activating this for the non-ES formats will cause a disparity between CommonJS and non-CommonJS builds where the same logic that works in a CommonJS build breaks in an ES module build. I do not think this is desirable.

**Comment by guybedford** [comment]
I would actually argue that the non-functional RollupJS behaviour is correct in the example, because the representation of an ES module when required _should_ always be the full namespace. If the interop check really wanted to work against **real** ES modules it would have a string tag check for `[module Module]`. The point is the interop check simply doesn't work for real modules.

I understand following webpack compat is likely a good thing to do though, but just to let you know I see no issue with this case failing. Interop edge cases get so broken at some point it is better to just draw a line and define the simpler semantics (eg like we do in Node.js).

Perhaps another "marker" within the CommonJS plugin itself to indicate when something really is a CommonJS module. As a sort of reverse equivalent to __esModule SystemJS uses a __useDefault: true | __cjsModule marker similarly for these kinds of edge cases.

I'm not against a solution here, I'm just against a solution in core that brings legacy baggage to pure ES module workflows.

On a related note, we are discussing supporting the named exports for `__esModule` CommonJS modules within the modules meeting this week. The behaviour would be to extend named exports for these modules, but still have `default` be the original `module.exports` value, even if the default were also an export. I've managed to pattern match eg RollupJS and Babel output in https://github.com/guybedford/cjs-module-lexer#grammar, any feedback you have would be very welcome.

**Comment by lukastaegert** [comment]
I see. So to offer a solution here, I think I will indeed go for this approach
- I reactivate the PR I created for the commonjs plugin rollup/plugins#552. Even though this is less efficient, it is an opt-in solution and will very specifically fix this issue for CommonJS importers only.
- I create a PR to extend the `namespaceToStringTag` option to put the tag on ALL relevant namespaces, i.e. also on generated CommonJS output in cases where we would also add the `__esModule` marker. Then it is possible to have this as a standards compliant marker, even though it requires ES2015 compatible logic. My understanding, though, is that there is a polyfill to handle this by using special property names for Symbols as long as the polyfill is equally applied everywhere, will need to check.

**Comment by guybedford** [comment]
Firstly, to reiterate, I am a -0 for integrating this feature in the first place as I don't think this style of interop makes sense treating real modules like fake ones in interop and I would be very concerned if we were applying this pattern to any other case than commonjs imports.

It is important for things to break when they aren't supposed to work. Otherwise they break when switching between tools instead, driving lock in within the ecosystems and further sioling of the entire JS ecosystem into sub ecosystems.

That all said, the plugin PR approach sounds sensible to me. In addition I would have expected namespaceToStringTag to apply to all ES module namespaces already so that actually sounds like an incomplete feature / bug to me unless I'm misunderstanding.

**Comment by lukastaegert** [comment]
>  In addition I would have expected namespaceToStringTag to apply to all ES module namespaces already so that actually sounds like an incomplete feature / bug to me unless I'm misunderstanding

Yes, it was always just applied to reiified namespaces but not to real ones in non-ESM formats.

**Comment by guybedford** [comment]
Ah right, thanks I see what you're saying. Note that SystemJS automatically enables this so would just affect CommonJS and AMD output I believe.

**Comment by lukastaegert** [comment]
That's good because because I would not have known how to handle it for SystemJS 🙄

**Comment by guybedford** [comment]
@lukastaegert just to follow up here further - I know I've somewhat stated my opinion here but I also don't mean to impose it - I'm not opposed to this PR landing. My only direct opposition to this PR is it landing as a default. If you wanted to make this an option and enable it from the CommonJS plugin that might also be an approach?

**Comment by lukastaegert** [comment]
Hmmm, that would also be an option, somewhat undecided right now.

**Comment by lukastaegert** [comment]
The more I think about this, the more I tend to go for the solution in the commonjs plugin. Even though it is less efficient, there are two arguments in favour:
- It is very focused and only targets namespaces that are imported by CommonJS. There are no `__esModule` markers visible anywhere in the ESM code
- It solves another issue in that CommonJS importers tend to assume the export is a proper object with `Object` prototype. This is solved as well by the commonjs PR.

While the injected helper is slightly wordy, it is still deduplicated so it should not be so bad IMO.

**Pull request closed without merging**
