### PR TITLE
Make sure system exports are valid JavaScript

### PR DESCRIPTION
**Pull request by lukastaegert**
Also turn validate into a warning to be able to inspect generated output

This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description
As prompted by #3952, this wraps certain System export related expressions in parentheses to avoid invalid code. Also, this changes the `validate` option from throwing an error to emitting a warning to allow inspecting the generated output manually.

### CODE REVIEW

**Comment by kzc** [comment]
>  Also, this changes the validate option from throwing an error to emitting a warning to allow inspecting the generated output manually.

I was hoping the code frame showing the error would be enough, but I appreciate it may be convenient to inspect the invalid code after a `--validate` failure, but it would be better to error out in this situation given (1) it's an explicit opt-in and (2) it's a serious failure. I generally spawn rollup from a Makefile without a rollup config with a `--silent` flag, so a custom onWarn handler is awkward from the CLI. 

Is there a simple way to promote a warning to an error from the CLI while still retaining the output files? Perhaps this error could be deferred until after all the files have been emitted?

A good compromise would be to change the option to allow:

`--validate` to validate with warnings emitted and output files retained.
`--validate=error` to error out upon first validation failure.
`--validate=warning` which would be the same as `--validate`.

**Comment by kzc** [comment]
Is there an onWarn handler in test/chunking-form/index.js? It would be good if it also errored out if the `validate` of output chunks failed.

**Comment by kzc** [comment]
I see that `--silent` does not silence a `--validate` failure, which is good:
```
$ echo 'console.log(1 + 2)' | rollup --outro '/*' --silent --validate -o out.mjs && echo SUCCESS
(!) Chunk "out.mjs" is not valid JavaScript: Unterminated comment (3:0).
out.mjs (3:0)
1: console.log(1 + 2);
2: 
3: /*
   ^
SUCCESS
```
But the rollup process returning a zero error code upon `--validate` failure is not ideal for Makefiles and other similar build tools.

**Comment by lukastaegert** [comment]
You want `—failAfterWarnings`. The chunking form tests should also error for unexpected warnings, just like the form tests.

**Comment by lukastaegert** [comment]
https://rollupjs.org/guide/en/#--failafterwarnings

**Comment by kzc** [comment]
@lukastaegert Thanks for the quick reply. Unfortunately `--failAfterWarnings` is not working correctly:

```
$ rollup -v
rollup v2.39.0

$ node -v
v14.3.0
```
Without `-—failAfterWarnings` - zero exit code as expected:
```
$ echo 'console.log(1?2:3)' | rollup --silent --outro '/*' --validate && echo SUCCESS
(!) Chunk "-.js" is not valid JavaScript: Unterminated comment (3:0).
-.js (3:0)
1: console.log(2);
2: 
3: /*
   ^
console.log(2);

/*
SUCCESS
```

With `-—failAfterWarnings` - an unexpected error with a zero exit code indicating success:
```
$ echo 'console.log(1?2:3)' | rollup --silent --outro '/*' --validate -—failAfterWarnings && echo SUCCESS
(node:23952) UnhandledPromiseRejectionWarning: TypeError: input.indexOf is not a function
    at /opt/rollup/rollup/cli/run/index.ts:28:49
    at Array.some (<anonymous>)
...
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23952) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
SUCCESS
```

**Comment by kzc** [comment]
Wow... this is the weirdest thing. I had cut and pasted the option from https://github.com/rollup/rollup/pull/3960#issuecomment-778349411 and prepended the missing hyphen to get the error above.

But when I manually retyped it - and it's seemingly identical - it does work:

```
$ echo 'console.log(1?2:3)' | rollup --silent --outro '/*' --validate --failAfterWarnings && echo SUCCESS
(!) Chunk "-.js" is not valid JavaScript: Unterminated comment (3:0).
-.js (3:0)
1: console.log(2);
2: 
3: /*
   ^
console.log(2);

/*
[!] Warnings occurred and --failAfterWarnings flag present
```
There was a strange character in https://github.com/rollup/rollup/pull/3960#issuecomment-778349411 causing the problem:
```
$ echo '—failAfterWarnings' | od -c
0000000    —  **  **   f   a   i   l   A   f   t   e   r   W   a   r   n
0000020    i   n   g   s  \n                                            
0000025
```
That's nuts.

Luckily, this unknown invisible character is not present when copy/pasted from the official docs in https://rollupjs.org/guide/en/#--failafterwarnings.
```
$ echo '--failAfterWarnings' | od -c
0000000    -   -   f   a   i   l   A   f   t   e   r   W   a   r   n   i
0000020    n   g   s  \n                                                
```
No rollup bug.

**Comment by kzc** [comment]
Cursed unicode character ['EM DASH' (U+2014)](https://www.fileformat.info/info/unicode/char/2014/index.htm)!

```
$ echo '-—failAfterWarnings' | od -c -t x1
0000000    -   —  **  **   f   a   i   l   A   f   t   e   r   W   a   r
           2d  e2  80  94  66  61  69  6c  41  66  74  65  72  57  61  72
0000020    n   i   n   g   s  \n                                        
           6e  69  6e  67  73  0a                                        
0000026
```

I can't be the only one bit by this. `yargs-parser` ought to check for it.

**Comment by kzc** [comment]
Technically one could pathologically use EM DASH as a short flag like `-i`, so it's not technically a `yargs-parser` issue. 

In any case, this small patch could prevent such accidental CLI misuse of EM DASH and avoid hard to debug errors for others:

```patch
--- a/cli/run/index.ts
+++ b/cli/run/index.ts
@@ -11,2 +11,10 @@ import loadConfigFromCommand from './loadConfigFromCommand';
 export default async function runRollup(command: any) {
+       // error out on options with dash-like unicode characters EM DASH or TWO-EM DASH
+       if (("\u2014" in command) || ("\u2E3A" in command)) {
+               handleError({
+                       code: 'UNKNOWN_OPTION',
+                       message: 'EM-DASH-like character used instead of hyphen in a command line flag'
+               });
+       }
+
        let inputSource;
```

without patch:
```
$ echo 'console.log(1?2:3)' | rollup --silent --outro '/*' --validate -—failAfterWarnings && echo SUCCESS || echo FAIL
(node:23952) UnhandledPromiseRejectionWarning: TypeError: input.indexOf is not a function
    at /opt/rollup/rollup/cli/run/index.ts:28:49
    at Array.some (<anonymous>)
...
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23952) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
SUCCESS
```

with patch:
```
echo 'console.log(1?2:3)' | rollup --silent --outro '/*' --validate -—failAfterWarnings && echo SUCCESS || echo FAIL
[!] EM-DASH-like character used instead of hyphen in command arguments

FAIL
```

Note: EM-DASH characters can still be used as arguments to other CLI options with the patch:
```
$ echo 'console.log(1?2:3)' | rollup --silent --outro '/* EM—DASH used here */' | od -ct x1
0000000    c   o   n   s   o   l   e   .   l   o   g   (   2   )   ;  \n
           63  6f  6e  73  6f  6c  65  2e  6c  6f  67  28  32  29  3b  0a
0000020   \n   /   *       E   M   —  **  **   D   A   S   H       u   s
           0a  2f  2a  20  45  4d  e2  80  94  44  41  53  48  20  75  73
0000040    e   d       h   e   r   e       *   /  \n                    
           65  64  20  68  65  72  65  20  2a  2f  0a                    
0000053
```

**Pull request merged**
