### PR TITLE
Fix chunk graph update when merging chunks for minChunkSize

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no (The situation where the bug unfolds is quite complex to create as it only occurs in large code bases with many potential chunk merges. While I do have a reproduction, it currently has over 6000 files and is extremely hard to boil down due to very long iteration cycles. The fix, on the other hand, is quite straight-forward when you look at it).

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description
First, this will fix a bug when the chunk graph is updated after two chunks are merged due to the `experimentalMinChunkSize` option. Without this fix, internal references in the chunk graph are not updated correctly, which can have the effect that the cyclic dependency detection may fail to detect cycles, which in turn can lead the algorithm to produce cyclic dependencies between chunks that can result in broken output.

But secondly, I noticed that I had completely overlooked how transitive dependencies can introduce new side effects into unrelated chunks when chunks are merged. So I completely redesigned the algorithm in key places to hopefully now completely avoid side effects spilling over. I also added a longer plain text version of the algorithm as a code comment which I will repeat here if anyone is interested:

> We can only merge chunks safely if after the merge, loading any entry point in any allowed order will not trigger side effects that should not have been triggered. While side effects are usually things like global function calls, global variable mutations or potentially thrown errors, details do not matter here, and we just discern chunks without side effects (pure chunks) from other chunks.
>
> As a first step, we assign each pre-generated chunk with side effects a label. I.e. we have side effect "A" if the non-pure chunk "A" is loaded.
>
> Now to determine the side effects of loading a chunk, one also has to take the side effects of its dependencies into account. So if A depends on B (A -> B) and both have side effects, loading A triggers effects AB.
>
> Now from the previous step we know that each chunk is uniquely determine by the entry points that depend on it and cause it to load, which we will call its **dependent entry points**.
>
> E.g. if X -> A and Y -> A, then the dependent entry points of A are XY. Starting from that idea, we can determine a set of chunks—and thus a set of side effects—that must have been triggered if a certain chunk has been loaded. Basically, it is the intersection of all chunks loaded by the dependent entry points of a given chunk. We call the corresponding side effects the **correlated side effects** of that chunk.
>
> Example:
> X -> ABC, Y -> ADE, A-> F, B -> D
> Then taking dependencies into account, X -> ABCDF, Y -> ADEF The intersection is ADF. So we know that when A is loaded, D and F must also be in memory even though neither D nor A is a dependency of the other. If all have side effects, we call ADF the correlated side effects of A. The correlated side effects need to remain constant when merging chunks.
>
> In contrast, we have the **dependency side effects** of A, which represents the side effects we trigger if we directly load A. In this example, the dependency side effects are AF. For entry chunks, dependency and correlated side effects are the same.
>
> With these concepts, merging chunks is allowed if the correlated side effects of each entry do not change. Thus, we are allowed to merge two chunks if
> 1. the dependency side effects of each chunk are a subset of the correlated side effects of the other chunk, so no additional side effects are triggered for any entry, or
> 2. The signature of chunk A is a subset of the signature of chunk B while the dependency side effects of A are a subset of the correlated side effects of B. Because in that scenario, whenever A is loaded, B is loaded as well. But there are cases when B is loaded where A is not loaded. So if we merge the chunks, all dependency side effects of A will be added to the correlated side effects of B, and as the latter is not allowed to change, the former need to be a subset of the latter.
>
> Another consideration when merging small chunks into other chunks is to avoid that too much additional code is loaded. This is achieved when the dependent entries of the small chunk are a subset of the dependent entries of the other chunk. Because then when the small chunk is loaded, the other chunk was loaded/in memory anyway, so at most when the other chunk is loaded, the additional size of the small chunk is loaded unnecessarily.
>
> So the algorithm performs merges in two passes:
> 1. First we try to merge small chunks A only into other chunks B if the dependent entries of A are a subset of the dependent entries of B and the dependency side effects of A are a subset of the correlated side effects of B.
> 2. Only then for all remaining small chunks, we look for arbitrary merges following the above rules (1) and (2), starting with the smallest chunks to look for possible merge targets.

There is actually room for further improvement in this algorithm as for dynamic entries, we do not yet take into account if a side effect has already been triggered by the module doing the dynamic import. But I would want to postpone this improvement as I first want to rework that general algorithm to remedy its performance issues in some way.

### CODE REVIEW

**Comment by lukastaegert** [comment]
@gajus It turns out there was a simple bug hidden in Rollup. Thanks to your great reproduction, I was able to narrow it down. In the end, it was a two lines of code that were missing.
Can you please try this version against your full code base? This time I am quite confident it will work.

**Comment by gajus** [comment]
Cannot install these unversioned releases:

```
at 11:40:41 ❯ pnpm add -D rollup/rollup#fix-min-chunk-size
../../../../../Library/pnpm/store/v3/tmp/_tmp_9327_a081f99221b48086bd64f907614f0016 [rollup@3.15.0]: Running npm-install script, done in 31s
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
../..                                    |   +4   -1 +-
../../../../../Library/pnpm/store/v3/tmp/_tmp_9327_a081f99221b48086bd64f907614f0016 [rollup@3.15.0]: Running prepublishOnly script, failed in 50ms
...9327_a081f99221b48086bd64f907614f0016 prepublishOnly$ node scripts/check-release.js
└─ Failed in 51ms at /Users/gajus/Library/pnpm/store/v3/tmp/_tmp_9327_a081f99221b48086bd64f907614f0016
 ERR_PNPM_PREPARE_PACKAGE  Failed to prepare git-hosted package fetched from "https://codeload.github.com/rollup/rollup/tar.gz/b3866fb81e367d24d78e7aaa93ec0fa794d63fe2": rollup@3.15.0 prepublishOnly: `node scripts/check-release.js`
Exit status 1
../..                                    | Progress: resolved 1951, reused 1903, downloaded 0, added 0
```

**Comment by lukastaegert** [comment]
> However, cannot install unversioned release

Ah, my bad, here you go! ↑

**Comment by gajus** [comment]
Okay, so this seems like it made it _mostly_ work!

It works if I don't set any `manualPureFunctions` settings.

However, if I configure `manualPureFunctions`, e.g.

```
treeshake: {
  manualPureFunctions: ['styled', 'css'],
  preset: 'recommended',
},
```

It fails with a related error:

```
chunk-Container.1f69c504.js:40 Uncaught ReferenceError: Cannot access 'styled' before initialization
    at chunk-Container.1f69c504.js:40:25
```

Unfortunately, without this change we are still getting 100+ chunks that are 2< Kb.

**Comment by lukastaegert** [comment]
Ok, here is one thing you could do to help me. While I was rather sure that I had solved the circular dependency issues, maybe there is still something I overlooked. Can you figure out if there is a circular dependency between `chunk-Container.1f69c504.js` and the chunk from which `styled` is imported? I.e. does that chunk contain any import that may point back to `chunk-Container.1f69c504.js`?

**Comment by lukastaegert** [comment]
And also just to make sure: Am I correct to assume that the error does NOT happen if you set `treeshake` as described but
- put everything into a manual chunk, or
- do not use `experimentalMinChunkSize`?

**Comment by lukastaegert** [comment]
I also added some debug logging to this branch. It would be helpful if you could tell me what the logging says in the error case.

**Comment by gajus** [comment]
@lukastaegert Possible to release latest fix?

**Comment by lukastaegert** [comment]
Definitely, but from your comment 

> However, if I configure manualPureFunctions, It fails with a related error:

it seems to me like there is still a hidden bug I would like to understand. Which is why I released `rollup@3.15.1-1` with some additional debug logging that I would like to see for the error case.

**Comment by lukastaegert** [comment]
It would still be nice to get the additional log output from rollup@3.15.1-1 for one of the runs where you have variables being undefined. In any case, I will clean this up slightly now and put it into the next release.

**Comment by gajus** [comment]
> It would still be nice to get the additional log output from rollup@3.15.1-1 for one of the runs where you have variables being undefined. In any case, I will clean this up slightly now and put it into the next release.

We had to disable for now entirely `minChunkSize` just because it produced bundles that bundles VPS page files, and lots of dead code. Just loading all chunks at the moment https://contra.com/gajus

I will get a repro hopefully after our big launch next week

**Pull request merged**
