### PR TITLE
Use ES2015 features in generated code snippets

### LINKED ISSUE #2591: doesn't produce valid es3 javascript code
- Rollup Version: v0.66.4
- Operating System (or Browser): macOS
- Node Version: v11.3.0

### How Do We Reproduce?

Rollup doesn't quote keys in export objects and that is causing some reserved keywords (like "default") to be used as object keys. That is not compatible with es3 (ie6/ie7).

Proposed fix is:

```patch
diff --git a/src/ast/variables/NamespaceVariable.ts b/src/ast/variables/NamespaceVariable.ts
index f1221f5a..f8a0dbde 100644
--- a/src/ast/variables/NamespaceVariable.ts
+++ b/src/ast/variables/NamespaceVariable.ts
@@ -88,7 +88,8 @@ export default class NamespaceVariable extends Variable {
                                }${_}}`;
                        }
 
-                       return `${t}${name}: ${original.getName()}`;
+                       // quote name to escape JS reserved words, for example, "default" in es3
+                       return `${t}'${name}': ${original.getName()}`;
                });
 
                const name = this.getName();
```

I can submit PR and fix unit tests if you are ok with this solution.

Another solution is to create new rollup options where target js version is specified and according to es3/es5/es6 version we could escape only required parameters. Will need to steal some code from babel in that case and dev effort will be much higher.

### Expected Behavior

Ideally rollup bundle should be compatible with es3. It is minifier responsibility to remove extra quotation where it is needed.

### Actual Behavior

Produces objects like `{ default: ... }` in js source code and it is not parseable by IE7.

### PS

I know that IE6/7 are dead on desktop but these browsers are still used on mobile devices operating Windows CE 6/7 (a lot of zebra hand scanners, for example). It is nice that with modern build tools we could write once and transpile code to multiple platforms but, unfortunately, current rollup version has this small compatibility issue that could be easily fixed.

### LINKED ISSUE #3092: dynamic import doesn't capture outer context
- Rollup Version: v1.20.3
- Operating System (or Browser): macOS
- Node Version: v12.9.1

output.format: `cjs`

### How Do We Reproduce?

```js
class Foo {
  constructor() {
    this._filename = './some-path.js'
  }

  async bar() {
    await import(this._filename)
  }
}

new Foo().bar()
```
is transpiled to something like:
```js
class Foo {
  constructor() {
    this._filename = './some-path.js'
  }

  async bar() {
    await new Promise(function (resolve) { resolve(require(this._filename)) })
  }
}

new Foo().bar()
```
### Expected Behavior

it should potentially be transpiled to something like:
```js
// notice the arrow function
new Promise((resolve) => { resolve(require(this._filename)) })
```
to capture the outer context.

### Actual Behavior
throws exception when running bundled code:
`TypeError: Cannot read property '_filename' of undefined`

https://rollupjs.org/repl/?version=1.20.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMGNvbnN0cnVjdG9yKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwdGhpcy5fZmlsZW5hbWUlMjAlM0QlMjAnLiUyRmJhci5qcyclNUNuJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjBhc3luYyUyMGJhcigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGF3YWl0JTIwaW1wb3J0KHRoaXMuX2ZpbGVuYW1lKSU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiU1Q25uZXclMjBGb28oKS5iYXIoKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJhci5qcy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwJTdCJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

_edit: added repl, `cjs` note, some clarifications_

### LINKED ISSUE #3784: Rollup is injecting JS not supported by IE11 (is IE11 supported?)
- Rollup Version:  2.27.1 
- Operating System (or Browser):  IE11
- Node Version (if applicable):  NA
- Link to reproduction:  https://repl.it/@GordonSmith/QuaintPlumUtilities 

### Expected Behavior

RollupJS should not inject JS which is unsupported by IE11

### Actual Behavior

RollupJS is injecting `Object.assign` which is not supported in IE11

Generated code which includes Object.assign:
```
var _colorbrewer = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.assign(/*#__PURE__*/Object.create(null), colorbrewer$1, {
    'default': colorbrewer$1
}));
```

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [x] bugfix
- [x] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
Resolves #3784 
Resolves #3092 
Resolves #2591

### Description
This will finally support ES6 features like arrow functions in generated Rollup code. For now, this is completely opt-in, see below. Furthermore, this fixes some long-standing bugs and adds a new internal concepts of "code-snippets", small functions to generate parts of the code respecting the new options.

As it turns out, blindly switching to ES6 features is not always good idea, which is why most specifically, the `output.generatedCode.arrowFunctions` option will leave larger IIFE functions in place to avoid double parsing in Chrome (see the link in the documentation below for the reasoning). This is also linked to a hidden feature in this PR

#### Improved AMD and SystemJS wrapper performance
Following https://v8.dev/blog/preparser#pife, immediately (directly or indirectly) invoked functions in AMD and SystemJS wrappers now receive the same treatment as their counterparts in UMD wrappers in that they are wrapped in parentheses. They are also never written as arrow functions as I could confirm that the same optimization does not apply to those.

#### Improved ES3 compatibility
While ES3 compatibility is generally not a goal of Rollup, we were already spending quite a bit of effort in quoting reserved words that are used as properties. This PR aims to complete this effort by quoting them in many more (all?) places that are controlled by Rollup. Props quoting can now be turned off via the `output.generatedCode. reservedNamesAsProps` option.

For the next major version, I would consider defaulting this option to `true`.

#### Improved ES5 compatibility + live-bindings for merged namespaces
`Object.assign` is no longer used to merge namespaces. Instead, a custom helper function is injected, which not only improves compatibility but also retains live-bindings when internal and external or synthetic namespaces are reexported from the same file.

#### Preserve "this"-context for AMD/CommonJS dynamic imports
Previously, dynamic imports containing a "this" in their argument would [not preserve the context](https://rollupjs.org/repl/?version=2.56.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwaW1wb3J0V2l0aENvbnRleHQoKSUyMCU3QiU1Q24lNUN0aW1wb3J0KHRoaXMpLnRoZW4oY29uc29sZS5sb2cpJTNCJTVDbiU3RCU1Q24lNUNuaW1wb3J0V2l0aENvbnRleHQuY2FsbCgnZXh0ZXJuYWwnKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE). This is fixed now in two ways:
* If arrow functions are allowed, we use an arrow function in the corresponding place (this was one of the drivers to add arrow functions)
* Otherwise we [use an IIFE](https://rollupjs.org/repl/?pr=4215&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwaW1wb3J0V2l0aENvbnRleHQoKSUyMCU3QiU1Q24lNUN0aW1wb3J0KHRoaXMpLnRoZW4oY29uc29sZS5sb2cpJTNCJTVDbiU3RCU1Q24lNUNuaW1wb3J0V2l0aENvbnRleHQuY2FsbCgnZXh0ZXJuYWwnKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) to retain context for fully dynamic imports (no checking is done if a "this" is used, though):
  ```js
  (function (t) { return Promise.resolve().then(function () { return /*#__PURE__*/_interopNamespace(require(t)); }); })(this);
  ```

#### Fix shimMissingExports for internally used exports

As it turns out, shimMissingExports would fail to add the definition for the shim variable even though it is referenced for internally used imports.

#### New feature (copied from documentation): output.generatedCode
To get a feeling for what has changed, take a look at the expected test output here: https://github.com/rollup/rollup/tree/output-generated-code/test/form/samples/generated-code

Type: `"es5" | "es2015" | { arrowFunctions?: boolean, constBindings?: boolean, objectShorthand?: boolean, preset?: "es5" | "es2015", reservedNamesAsProps?: boolean }`<br> CLI: `--generatedCode <preset>`<br> Default: `"es5"`

Which language features Rollup can safely use in generated code. This will not transpile any user code but only change the code Rollup uses in wrappers and helpers. You may choose one of several presets:

- `"es5"`: Do not use ES2015+ features like arrow functions, but do not quote reserved names used as props.
- `"es2015"`: Use any JavaScript features up to ES2015.

**output.generatedCode.arrowFunctions**<br> Type: `boolean`<br> CLI: `--generatedCode.arrowFunctions`/`--no-generatedCode.arrowFunctions`<br> Default: `false`

Whether to use arrow functions for auto-generated code snippets. Note that in certain places like module wrappers, Rollup will keep using regular functions wrapped in parentheses as in some JavaScript engines, these will provide [noticeably better performance](https://v8.dev/blog/preparser#pife).

  **output.generatedCode.constBindings**<br> Type: `boolean`<br> CLI: `--generatedCode.constBindings`/`--no-generatedCode.constBindings`<br> Default: `false`

This will use `const` instead of `var` in certain places and helper functions. Depending on the engine, this can provide [marginally better performance](https://benediktmeurer.de/2017/06/29/javascript-optimization-patterns-part2) in optimized machine code. It will also allow Rollup to generate more efficient helpers due to block scoping.

```js
// input
export * from 'external';

// cjs output with constBindings: false
var external = require('external');

Object.keys(external).forEach(function (k) {
  if (k !== 'default' && !exports.hasOwnProperty(k))
    Object.defineProperty(exports, k, {
      enumerable: true,
      get: function () {
        return external[k];
      }
    });
});

// cjs output with constBindings: true
const external = require('external');

for (const k in external) {
  if (k !== 'default' && !exports.hasOwnProperty(k))
    Object.defineProperty(exports, k, {
      enumerable: true,
      get: function () {
        return external[k];
      }
    });
}
```

**output.generatedCode.objectShorthand**<br> Type: `boolean`<br> CLI: `--generatedCode.objectShorthand`/`--no-generatedCode.objectShorthand`<br> Default: `false`

Allows the use of shorthand notation in objects when the property name matches the value.

```javascript
// input
const foo = 1;
export { foo, foo as bar };

// system output with objectShorthand: false
System.register('bundle', [], function (exports) {
  'use strict';
  return {
    execute: function () {
      const foo = 1;
      exports({ foo: foo, bar: foo });
    }
  };
});

// system output with objectShorthand: true
System.register('bundle', [], function (exports) {
  'use strict';
  return {
    execute: function () {
      const foo = 1;
      exports({ foo, bar: foo });
    }
  };
});
```

**output.generatedCode.preset**<br> Type: `"es5" | "es2015"`<br> CLI: `--generatedCode <value>`

Allows choosing one of the presets listed above while overriding some options.

```js
export default {
  // ...
  output: {
    generatedCode: {
      preset: 'es2015',
      arrowFunctions: false
    }
    // ...
  }
};
```

**output.generatedCode.reservedNamesAsProps**<br> Type: `boolean`<br> CLI: `--generatedCode.reservedNamesAsProps`/`--no-generatedCode.reservedNamesAsProps`<br> Default: `false`

Determine whether reserved words like "default" can be used as prop names without using quotes.

```javascript
// input
const foo = null;
export { foo as void };

// cjs output with reservedNamesAsProps: false
Object.defineProperty(exports, '__esModule', { value: true });

const foo = null;

exports['void'] = foo;

// cjs output with reservedNamesAsProps: true
Object.defineProperty(exports, '__esModule', { value: true });

const foo = null;

exports.void = foo;
```

#### (Soft-) deprecation of preferConst
`output.generatedCode.constBIndings` should be used instead.

#### Use common helper for more invalid option errors
An effect of this is that all invalid option errors now contain a link to the corresponding documentation.

### CODE REVIEW

**Comment by guybedford** [comment]
For the SystemJS module format at least, it is recommended to retain a function declaration for the execute and declaration functions since SystemJS can control the `this` bindings (eg setting `this` to null for modules). While RollupJS handles some of those replacements it won't handle them for eg `eval` cases.

If there is a slowdown for some specific "large IIFE" cases, it could also be worth sticking to function declarations there.

I haven't been able to review all cases, as the diff is very hard to read on the web app, but also worth being very careful about `this` bindings in every function replacement scenario!

**Comment by lukastaegert** [comment]
> While RollupJS handles some of those replacements it won't handle them for eg eval cases.

But of course, eval is strongly discouraged to use in a bundling setup and we warn about it. Still, we could always use functions for `execute` (and I do not think we use `declaration`).

With regard to other function replacement scenario, e.g. in dynamic imports, here arrow functions actually fix long-standing bugs with regard to wrong `this` binding, notably #3092 .

However, this PR finally adds a clunky workaround for the function case as well.

**Comment by lukastaegert** [comment]
And sorry for the large diff, there was a lot of collateral damage as a result of unifying the rendering functions. The relevant tests to look at are those in `form/samples/generated-code` which show all changes for the various values of the flags.

**Comment by lukastaegert** [comment]
To get a feeling for what changed, take a look at the new test files here, this should be far better than browsing the diff: https://github.com/rollup/rollup/tree/output-generated-code/test/form/samples/generated-code

**Comment by shellscape** [comment]
Not stepping in to discourage or anything of the sort; I ran into this twitter thread by the Preact author the other day and thought it was good food for thought while pursuing this initiative - https://twitter.com/_developit/status/1437429523893600256

**Comment by lukastaegert** [comment]
I already reverted back to using ES5 syntax in the places where I am sure there would be a performance penalty. At this point, all remaining changes will provide either a small size reduction, or in the case of `const` instead of `var`, a theoretical small performance improvement though I cannot seem to find the article support this any more (the reasoning being that for `const`, the engine can drop some logic needed to handle reassignments, though the gain would be close to non-noticeable).

**Comment by lukastaegert** [comment]
However, there are mailing important refactorings and quite a few bug fixes that are also included here. Most importantly, I managed to get rid of quite a few places where Rollup was NOT generating strict ES5 output.

**Comment by lukastaegert** [comment]
This is finally ready for review! Have a look at the updated description, there are quite a few important fixes included as well.

**Review by guybedford — APPROVED** [review]
Excellent work, and glad to hear about the performance improvements.

I'd even consider making these features aggressive defaults - most users do want these features. Ideally a singular option for the target module format could apply across the board, for either enabling or disabling?

**Comment by lukastaegert** [comment]
Glad to hear you approve! I added the preset style to make this as easy as possible, i.e. `generatedCode: "es2015"` or `generatedCode: "es5"` would pull the switches for you.

> most users do want these features
I thought so originally, but there is still a large group of library bundlers who still think "es5" is what should go into node_modules. And many tools still assume that this is the case, forcing you to add exceptions to the config if you need anything in node_modules transpiled. But let's see what we make the default once Rollup 3 becomes more of a reality.

**Pull request merged**
