### PR TITLE
Format markdown with prettier and prepare SVG graphs for hooks

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description
This will replace markdownlint with prettier for formatting markdown files, which looks much better also with respect to code samples.

It also adds two [mermaid](https://mermaid-js.github.io) definition files that can be used to generate graphs for the build and output plugin hooks. Moreover, there is an HTML snippet to generate a legend for those files.
In the documentation itself, there are comments

```
<!-- html:hooks-legend.html -->
<!-- mermaid:build-hooks.mmd -->
```

That will be used by a forthcoming website update to actually replace them with the rendered graphs.

### CODE REVIEW

**Comment by lukastaegert** [comment]
Will merge this because I need the comments on master to fine-tune rollup/rollupjs.org#230

**Comment by shellscape** [comment]
FWIW the eslint+prettier config and setup in the plugins repo is very mature now. Might be worth a look.

**Comment by lukastaegert** [comment]
True, but I was under the impression that even with plugins, ESLint will only format code blocks inside markdown files while prettier also formats the surrounding content, which is something I liked very much. But as I did not check, this assumption might be wrong.

**Comment by shellscape** [comment]
The solution in plugins does both :)

**Comment by lukastaegert** [comment]
But it looks you are also using just bare prettier for markdown: https://github.com/rollup/plugins/blob/6463b9635e20b8425599f14005b9efdd8f94ecd6/package.json#L7

**Comment by shellscape** [comment]
It's a supplementary step. You don't have to take my word for it, but it runs like smooth butter over there. I've implemented the same setup for two companies now.

**Pull request merged**
