### PR TITLE
Prevent invalid keys from being passed in options.

### PR DESCRIPTION
**Pull request by eventualbuddha**
These are all the keys needed to make the test pass, but I may have missed something.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
@Rich-Harris ping.

**Comment by Victorystick** [comment]
@eventualbuddha Good idea. I see you're throwing an exception instead of returning a rejected Promise.

Since you're doing argument validation, throwing makes more sense to me. The reason I point this out is that the _two other argument validation_ conditions return a rejected Promise instead. I think those should probably throw as well.

**Comment by eventualbuddha** [comment]
@Victorystick ah, good point. Those should be consistent, I agree. It might make more sense for the function to always return a promise, though. That way callers simply need to have a `.catch(` call chained as the sole way to handle errors. Making `validateKeys` return a promise would be a little strange, though, so perhaps it's best to wrap it somehow in the call to `rollup`?

**Comment by Victorystick** [comment]
Isn't there a semantic difference between a rejected Promise and a thrown Error? I agree that it's better to have a single way to catch errors, but these are two completely different kinds of errors, no?

**Comment by eventualbuddha** [comment]
Imagine a caller of the `rollup` function wants to handle errors. With the
way it's done now there are two kinds of error: immediately thrown errors
and rejected-promise errors. That means you need something like this:

```js
try {
rollup(…)
.then(…)
.catch(/* rejected promise handler */);
} catch (err) {
/* immediately thrown handler */
}
```

Whereas if we always return a promise you can drop the surrounding
`try/catch`.

**Comment by TrySound** [comment]
@eventualbuddha If we use promises in rollup then we should always reject and error with it. As an alternative you can wrap all in Promise and throw and error there
```js
function rollup() {
  return Promise.resolve().then(function () {
    throw Error('Some error');
  });
}
```
This will be the same as returning Promise.reject();

**Comment by arv** [comment]
FWIW, this is the same motivation why ES'15 Promise functions do not throw but return rejected promises.

```js
Promise.all(42); // rejected Promise
```

(V8 gets this wrong [#4603](https://code.google.com/p/v8/issues/detail?id=4603))

**Comment by TrySound** [comment]
@arv Doesn't matter in this case

**Comment by eventualbuddha** [comment]
I'll redo it with the semantics discussed.

**Comment by eventualbuddha** [comment]
Done. Added a test for it as well.

**Comment by Rich-Harris** [comment]
I took the liberty of replacing the `for...of` loop with a `while` – with our current build setup, `for...of` isn't actually transpiled. We could add that setting to the `.babelrc`, but it [doesn't transpile well](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&playground=false&code=for%20(%20let%20key%20of%20actualKeys%20)%20%7B%0A%09%09if%20(%20allowedKeys.indexOf(%20key%20)%20%3C%200%20)%20%7B%0A%09%09%09return%20new%20Error(%0A%09%09%09%09%60Unexpected%20key%20'%24%7B%20key%20%7D'%20found%2C%20expected%20one%20of%3A%20%24%7B%20allowedKeys.join(%20'%2C%20'%20)%20%7D%60%0A%09%09%09)%3B%0A%09%09%7D%0A%09%7D), so I tend to include in the 'ES6 features to avoid' category.

**Pull request merged**
