### PR TITLE
docs: clarify rollup-plugin-node-resolve

### PR DESCRIPTION
**Pull request by xtuc**
Basically copied from https://github.com/rollup/rollup/issues/1555. I can make the same PR on your website.

### CODE REVIEW

**Comment by jbucaran** [comment]
Thanks @xtuc! Personally, I'd be happy with adding a FAQ section to the wiki with this, but what you guys think is best! 👋😄

**Comment by xtuc** [comment]
Yeah, just saw there is a FAQ section on the website, i'll make a PR later today.

**Comment by kzc** [comment]
The use of node "realpath" module resolution in Rollup brought to light by #1819 appears to be a counterexample of https://github.com/rollup/rollup/issues/1555#issuecomment-322862209.

**Comment by shellscape** [comment]
Closing given the PR's age, and in favor of https://github.com/rollup/rollupjs.org/pull/148 which stages changes to the site's FAQ as mentioned in this PR as the preferred vector for that information.

**Pull request closed without merging**
