### PR TITLE
fix circular member expression bug

### PR DESCRIPTION
**Pull request by kellyselden**
discovered from this source https://github.com/emberjs/data

### CODE REVIEW

**Comment by guybedford** [comment]
@kellyselden is this the full test?

**Comment by guybedford** [comment]
Ahh I see it is :)

**Comment by guybedford** [comment]
//cc @lukastaegert https://travis-ci.org/rollup/rollup/jobs/340331859#L1240

**Comment by lukastaegert** [comment]
Thanks! I'll have a look once my current PR is resolved.

**Comment by kellyselden** [comment]
I thought it would be difficult too. Pleasant surprise!

**Comment by lukastaegert** [comment]
I'm ok with the diff 😉

For those who do not know that: It is much easier to review a PR with white-space changes in Github if you ignore white-space by adding `?w=1` to the URL. Otherwise if you were using Webstorm, it's diffing tool is even better and able to ignore nearly all cases of added white-space and empty lines. But I see the cool kids are using VSCode these days...

**Pull request merged**
