### PR TITLE
Remove the need to provide an output name for IIFE bundles

### PR DESCRIPTION
**Pull request by bterrier**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
https://github.com/rollup/rollup-plugin-commonjs/issues/274

### Description
This remove the requirement to provide a name (`--name` or `--output.name`) when building an IIFE bundle.

The previous behavior was to force the user to provide a name and add `var name =` in front of the IIFE.

Practically it means that when running the bundle the last evaluated statement is the `var name =` assignation which "returns" `undefined`.

Now, when no name is provided, instead of failing, the bundle is generated without `var name =`. Which means that when running the bundle, the JS environment is not polluted by an extra variable and the last evaluated statement is the `return` from the bundle entry point, making it possible to retrieve this value.

### CODE REVIEW

**Comment by eight04** [comment]
AFAIK, @bterrier 's issue has nothing to do with commonjs (https://github.com/rollup/rollup-plugin-commonjs/issues/274#issuecomment-544485165). @bterrier 's goal is to generate an IIFE **with** a return value and **without** a variable declaration.

Though this use case is pretty rare and I'm not really sure whether it should be built into Rollup.

BTW, if @bterrier just want to generate a script that the last statement is the module exports, try adding a footer:
```js
{
  output: {
    footer: 'name;'
  }
}
```

**Comment by bterrier** [comment]
@eight04 The footer solution is not good. It creates a variable `name` outside of the IIFE scope.

To make it would I would need to define both a header and footer to wrap it in an extra IIFE so that it generates : 

```js
(function () {
    <bundle>
    return name;
}());
```

This adds noise to the rollup command (or config) and adds an extra useless function call in JS. 
 
I reckon that my use case may be pretty rare, but allowing IIFE exports without name is not a feature that has to be built into rollup. On the contrary, it is the forbidding of nameless IIFE that is a "feature" that was added to rollup. This is backed up by the fact that my commit is mostly removing code.

**Comment by lukastaegert** [comment]
But what do you need the return statement for? It does not have any effect.

**Comment by bterrier** [comment]
> But what do you need the return statement for? It does not have any effect.

Yes, it does. When you run JS code in a JS engine (from command line or from another language) you get the result of the last statement.

Having the `var name =` pollutes the scope and prevent getting back the return statement as `var name =` evals to `undefined`.

**Comment by lukastaegert** [comment]
I see. So how about keeping your changes and adding back the error in form of a warning instead?

**Comment by bterrier** [comment]
> I see. So how about keeping your changes and adding back the error in form of a warning instead?

Fine with me. Is there any specific text I should put in the warning?

**Comment by lukastaegert** [comment]
How about `If you do not supply "output.name", you may not be able to access the exports of an IIFE bundle.`

**Pull request merged**
