### PR TITLE
Add bundle write transform option

### PR DESCRIPTION
**Pull request by TrySound**
It's realy necessary thing. Use case is minifying.

### CODE REVIEW

**Comment by TrySound** [comment]
Also this tests fails on windows
```
form
  sourcemaps
    1) generates amd
    2) generates cjs
    3) generates es6
    4) generates iife
    5) generates umd
  sourcemaps-inline
    6) generates amd
    7) generates cjs
    8) generates es6
    9) generates iife
    10) generates umd
```

**Comment by Victorystick** [comment]
@TrySound Aah! That's probably related to #279! I couldn't reproduce it on Mac.

**Comment by TrySound** [comment]
@Victorystick Exactly. Okay, as windows user will try to fix that in free time.

**Comment by Victorystick** [comment]
I'd recommend using a tool like gulp or [`gobble`](https://github.com/gobblejs/gobble) if you're looking for a tool/build system to rollup and then minify code.

```js
var gobble = require( 'gobble' );

module.exports =
  gobble('src')
  .transform('rollup', {
    ...
  })
  .transform( 'uglifyjs' );
```

**Comment by TrySound** [comment]
@Victorystick I use gulp, but I don't want create wrapper until rollup has to much `sourceMap` options (rollup and plugins). And I don't want to create a plugin caz rollup use Promise API, which is also used by gulp. But I want to use rollup write method. Why too much duplicate code? Hook is a good stuff for postprocessing.

**Comment by TrySound** [comment]
@Rich-Harris https://github.com/rollup/rollup/issues/258#issuecomment-153210709
Not for plugins, but still hook :)

**Comment by TrySound** [comment]
@Rich-Harris Let's discuss. This is the only thing which don't let me use rollup.

**Comment by Victorystick** [comment]
@TrySound Why don't you just use [`gulp-rollup`](https://github.com/mcasimir/gulp-rollup)?

**Comment by TrySound** [comment]
@Victorystick Why use unnecessary plugin if we can use Rollup and Promises API? `bundle.write` is small build utility which should cover some features like post processing. Why you think it's bad? This case is the same as gulp-browserify. We don't need to use wrapper, but we need some stuff for it.

**Comment by Victorystick** [comment]
If what you want is to do in-memory minification, the why not use the in-memory, streaming gulp build system? We should keep Rollup's core focused. Why are you so determined to use `bundle.write`?

**Comment by TrySound** [comment]
@Victorystick I like promises more. I can just return promise in gulp task. It's really cool. But gulp-rollup is excess.

**Comment by TrySound** [comment]
If you want to have only process api, you should remove bundle.write method, else need to make to more friendly.

**Comment by TrySound** [comment]
I don't like gulp-rollup. I want to use this hook.

**Comment by TrySound** [comment]
Example
```js
rollup().then(function (bundle) {
  return bundle.write({
    dest: 'path.js',
    sourceMap: true,
    hook: function (result) {
      return uglify.minify(result.code, {
        fromString: true,
        inSourceMap: result.map
        outSourceMap: 'file.js.map'
      });
    }
  });
});
```

**Comment by Rich-Harris** [comment]
Thanks for the example @TrySound, I see what you're getting at now. Putting the hook here makes sense, since it means it's possible to generate a minified and non-minified version from the same `bundle` object without creating a bunch of unnecessary work for Rollup.

That said, it should be done in such a way that it could work as a plugin (e.g. if you didn't need to create a non-minified version, you could use a rollup-plugin-uglify or whatever). In that case the plugin would look something like

```js
export default myPlugin ( options = {} ) {
  return {
    hook ({ code, map }) {
      // some code happens
    }
};
```

`hook` is obviously too abstract in this context, and it'd be nice to use the same terminology everywhere. Maybe `transformBundle`?

**Comment by TrySound** [comment]
@Rich-Harris Maybe in bundle.write option it should have only `transform` option. But for plugins I'm not sure this feature is safe. There could be many unexpected behaviours.

**Comment by Rich-Harris** [comment]
I'm not sure why this would be any more prone to unexpected behaviour than any other hook. As long as the API is clear, then it's down to plugin authors to not write broken plugins, surely?

**Comment by TrySound** [comment]
@Rich-Harris Okay, but plugins bundle transformation is another pr I think

**Comment by TrySound** [comment]
@Rich-Harris Should I do something more for merge?

**Comment by TrySound** [comment]
@Rich-Harris Maybe we should let to return promise?

**Comment by TrySound** [comment]
@eventualbuddha Reproduced!

**Comment by TrySound** [comment]
I will add tests tomorrow. Maybe we can add uglifyjs [here](https://github.com/webpack/docs/wiki/comparison)?

**Comment by Rich-Harris** [comment]
:+1:, though I think this needs to be a plugin hook as well – that way it would also work with the CLI and with `bundle.generate` for no extra work, and it would make it possible to have a rollup-plugin-uglifyjs plugin. We can also do the delicate work of combining sourcemaps, if necessary, rather than making that the dev's responsibility. Hook would have to receive `dest`/`sourceMapFile` options at minimum, of course.

I'll open a separate issue for that.

**Comment by Victorystick** [comment]
How about renaming `hook` to `postprocess` or similar? It makes the intent clearer.

**Comment by Rich-Harris** [comment]
[At the moment](https://github.com/rollup/rollup/pull/282/files#diff-1d7a04be4b67a51bd7ca47ce6ccb680fR39) it's `transform` – do we prefer that or `postprocess`? `transform` is consistent with module transforms, though there is a difference insofar as module transforms happen *before* Rollup gets a look at them, whereas this happens afterwards. So I'm indifferent.

**Comment by Victorystick** [comment]
You suggested making it a plugin hook, so we've got to name it something other than `transform` since that's already used. That's why I suggested `postprocess`; an uglify plugin would just define a `postprocess` method. Unless you'd prefer `transformModule`/`transformBundle`?

**Comment by TrySound** [comment]
@Victorystick I more like `transformBundle`

**Comment by eventualbuddha** [comment]
:+1: `transformBundle`

**Comment by Rich-Harris** [comment]
Cool. `transformBundle` it is.

@TrySound as the resident Windows guy, any idea what's behind [this](https://ci.appveyor.com/project/Rich-Harris/rollup/build/435/job/3sxp1l7pygflik5v)?

screen shot 2015-12-29 at 1 34 41 pm

Have seen it before but can't imagine why it's happening...

**Comment by TrySound** [comment]
@Rich-Harris You mean this pr fail? It was fixed with my pluginutils pr. There was problem with path resolving in `rollup-plugin-babel`. Nothing was transpilled. Now everything should be okay.

**Comment by Rich-Harris** [comment]
Ah ok. I suspect we need to update rollup-plugin-babel to pick up the newer version of rollup-pluginutils in that case. Which means adopting Babel 6. Which I think means ditching `class` in favour of good old-fashioned prototypes, since using loose mode is a bit of a PITA in Babel 6, and non-loose classes are fat and slow. Will open a separate issue for that

**Comment by Rich-Harris** [comment]
@TrySound did you mean to close this?

**Comment by TrySound** [comment]
@Rich-Harris Will make new pr.

**Pull request closed without merging**
