### PR TITLE
refactor: use fs, fs-extra, remove sander

### PR DESCRIPTION
**Pull request by dnalborczyk**
This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor (tests)
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### CODE REVIEW

**Comment by kzc** [comment]
#4318 replaces `fs.writeFileSync` and `sander.writeFileSync` with [`atomicWriteSync`](https://github.com/rollup/rollup/pull/4318/files#diff-56d361e6893cf9d961de277f3986602b66ace5d977e446d4161c664a95a48f5bR226-R233) for reasons described in the link.

**Comment by kzc** [comment]
In an experiment, replacing `await sander.copydir()` with an equivalent `execSync` call copying the directory via shell commands did not improve the reliability of certain node12/macos watch tests.  Curiously, I haven't seen these watch test failures in node16/macos.  Not sure if this is due to node16 being a faster JIT VM, or whether a NodeJS bug on macos was fixed after node12, or if there is some other issue with the tests themselves, chokidar, or rollup.

**Comment by kzc** [comment]
> Curiously, I haven't seen these watch test failures in node16/macos.

I spoke too soon - here's a rare node16/macos failure in the commits of this PR:

https://github.com/rollup/rollup/runs/4634674788?check_suite_focus=true

**Comment by dnalborczyk** [comment]
> In an experiment, replacing `await sander.copydir()` with an equivalent `execSync` call copying the directory via shell commands did not improve the reliability of certain node12/macos watch tests. 

yeah, I didn't think the watch failures would go away with this. I agree with you that the timing and execution of the tests is likely at fault. I wanted to look after the last commits at the failures and/or wait for the other PR first.

I went a little further and made this PR also fully async.

**Comment by lukastaegert** [comment]
I like the idea of getting rid of sander, but maybe you are trying too much here by "fixing everything". Why not limit this one to replacing sander for now but keep especially the structure of the watch tests intact, and then improve them separately?

**Comment by dnalborczyk** [comment]
> I like the idea of getting rid of sander, but maybe you are trying too much here by "fixing everything". Why not limit this one to replacing sander for now but keep especially the structure of the watch tests intact, and then improve them separately?

good point. I haven't look at this PR for a while because of the mac os ci failures.
let me rebase and revert some stuff to make it stable.

**Comment by dnalborczyk** [comment]
@lukastaegert this should be good to go

**Review by lukastaegert — APPROVED** [review]
Great work 👍

**Pull request merged**
