### PR TITLE
follow symlinks

### PR DESCRIPTION
**Pull request by Rich-Harris**
PR for #447. Note that this only works for the default resolver – plugins would have to implement similar logic separately.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Seems sane :+1:

**Comment by Rich-Harris** [comment]
It fails on Windows, or at least the tests do. Presumably symlinks are handled different there? @TrySound any ideas on what we need to do to get this test to pass?

**Comment by eventualbuddha** [comment]
I can look into it if you give me Appveyor access for rollup.

**Comment by Rich-Harris** [comment]
@eventualbuddha can you send me the email address associated with your appveyor account? thanks

**Comment by leeyeh** [comment]
Any progress here?

**Comment by tivac** [comment]
I wonder if the windows builds are failing due to [git on windows not being able to create symlinks](https://github.com/git-for-windows/git/issues/117) on checkout?

[I ran into this recently :disappointed:](https://github.com/tivac/modular-css/pull/107)

**Comment by mmolhoek** [comment]
Any progress here? waiting for this one to be fixed, so [#447](https://github.com/rollup/rollup/issues/447) can be merged, so ionic 2 will handle linked node_modules correctly

**Comment by talltyler** [comment]
I personally feel like supporting non-windows environments is better than supporting nothing. 
It would be great to get this working.

**Comment by talltyler** [comment]
Is there a reason why non-windows support for this feature can't be merged?

**Comment by yaycmyk** [comment]
Wholeheartedly agree with @talltyler - would be awesome to get this in.

**Pull request merged**
