### PR TITLE
Add badge to display install size

### PR DESCRIPTION
**Pull request by styfle**
This adds a badge to the `README.md` that displays the npm install size

### CODE REVIEW

**Comment by styfle** [comment]
How can travis fail if I only changed the `README.md` file?

Anything I need to do here?

**Comment by lukastaegert** [comment]
No, this is an issue that happens at times. Not sure why, I hope we get to the bottom of this at some point, restarting CI solved the issue.

I like the idea but the link in the badge does not seem to load for me. Will try again tomorrow.

**Comment by lukastaegert** [comment]
Looks really nice, thanks a lot! Will add this to our readme, I guess Rollup's small install footprint is something we could definitely promote a little better 😜

**Comment by styfle** [comment]
Thanks! 🎉 

Rollup's small size is definitely a selling point when compared with [webpack](https://packagephobia.now.sh/result?p=webpack) or [browserify](https://packagephobia.now.sh/result?p=browserify).

**Comment by revelt** [comment]
To add a two-pence, rollup is a dev-dependency so sizes don't really matter because it does not end up bundled in the production code. But, as they say, the more badges the better! 👍

**Comment by vladshcherbin** [comment]
Really interesting, why this badge is even needed since it's a dev dependency.

**Comment by lukastaegert** [comment]
The badge has nothing to do with you creating small bundles or dependencies or whatever you create but this is about keeping your node_modules folder small and clean. There *are* people who care about this even if it is not you nor even a majority.

Just imagine you put this on a server or inside a docker container. Or for a more common situation in professional software development that I personally experienced, you have CI system that is not capable of caching your npm installs due to e.g. sandboxing. In this situation, it can be a noticeable improvement to your build pipeline time if you do not have to install 82MB of dev dependencies as you have to for e.g. parcel.

So please, yes, we know how npm install works, no reason to point out the obvious 🙄

**Comment by vladshcherbin** [comment]
@lukastaegert no pointing intended, just interested in use cases. Thanks for the explanation 😉

**Comment by styfle** [comment]
@lukastaegert Excellent points!

@revelt Thanks for the kind words!

The readme has a pretty thourugh description of why Package Phobia exists and how it’s different than other similar projects: https://github.com/styfle/packagephobia

**Pull request merged**
