### PR TITLE
Correctly associate pure annotations and remove invalid ones

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description
This PR will improve the handling of pure annotations in several respects:
* annotations in front of conditional, logical, binary or sequence expressions will be associated with the first element unless the expression is surrounded by parentheses [REPL](https://rollupjs.org/repl/?pr=4095&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolNDBfX1BVUkVfXyolMkZyZW1vdmUoKSUyMCUzRiUyMDElMjAlM0ElMjAyJTNCJTVDbiUyRiolNDBfX1BVUkVfXyolMkYoa2VlcCgpJTIwJTNGJTIwMSUyMCUzQSUyMDIpJTNCJTVDbiU1Q24lMkYqJTQwX19QVVJFX18qJTJGcmVtb3ZlKCklMjAlMjYlMjYlMjAxJTNCJTVDbiUyRiolNDBfX1BVUkVfXyolMkYoa2VlcCUyMCUyNiUyNiUyMDEpJTNCJTVDbiU1Q24lMkYqJTQwX19QVVJFX18qJTJGcmVtb3ZlKCklMkMlMjAxJTNCJTVDbiUyRiolNDBfX1BVUkVfXyolMkYoa2VlcCgpJTJDJTIwMSklM0IlNUNuJTVDbiU1Q24lMkYqJTQwX19QVVJFX18qJTJGcmVtb3ZlKCklMjAlMkIlMjAxJTNCJTVDbiUyRiolNDBfX1BVUkVfXyolMkYoa2VlcCgpJTIwJTJCJTIwMSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)
* annotations in front of call or new expressions will be associated with the expression even when there are parentheses
* annotations that cannot be associated with a call or new expression are always removed from the code [REPL](https://rollupjs.org/repl/?pr=4095&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmtlZXAoKSUyRiolNDBfX1BVUkVfXyolMkYlM0IlNUNua2VlcCgpJTNCJTJGKiU0MF9fUFVSRV9fKiUyRnJlbW92ZSgpJTIwJTNGJTIwMSUyMCUzQSUyMDIlM0IlNUNuJTJGKiU0MF9fUFVSRV9fKiUyRihrZWVwKCklMjAlM0YlMjAxJTIwJTNBJTIwMiklM0IlNUNuJTVDbiUyRiolNDBfX1BVUkVfXyolMkZyZW1vdmUoKSUyMCUyNiUyNiUyMDElM0IlNUNuJTJGKiU0MF9fUFVSRV9fKiUyRihrZWVwJTIwJTI2JTI2JTIwMSklM0IlNUNuJTVDbiUyRiolNDBfX1BVUkVfXyolMkZyZW1vdmUoKSUyQyUyMDElM0IlNUNuJTJGKiU0MF9fUFVSRV9fKiUyRihrZWVwKCklMkMlMjAxKSUzQiU1Q24lNUNuJTVDbiUyRiolNDBfX1BVUkVfXyolMkZyZW1vdmUoKSUyMCUyQiUyMDElM0IlNUNuJTJGKiU0MF9fUFVSRV9fKiUyRihrZWVwKCklMjAlMkIlMjAxKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

I verified that the implemented behaviour seems to be in line with how terser behaves. This would also resolve discussions from #4068

### CODE REVIEW

**Comment by lukastaegert** [comment]
cc @kzc

**Comment by kzc** [comment]
Good stuff. 

This is difficult to get right. I trust if the results were vetted with terser then it ought to be fine. Should there be pure annotation disagreements between minifiers, use the defacto behavior of `uglify-js` which happens to support ES2020+ these days.

With the recent PR on sequences it ought to be easy to support pure annotated calls with side effects in their parameters:

```
$ echo 'a(), /*@__PURE__*/ b(0, effect1(), /*@__PURE__*/ effect2(), 3);' | rollup --silent
a(), /*@__PURE__*/ b(0, effect1(), /*@__PURE__*/ effect2(), 3);

$ echo 'a(), /*@__PURE__*/ b(0, effect1(), /*@__PURE__*/ effect2(), 3);' | uglify-js -c
a(),effect1();
```

**Comment by kzc** [comment]
Good stuff. 

This is difficult to get right. I trust if the results were vetted with terser then it ought to be fine. Should there be pure annotation disagreements between minifiers, use the defacto behavior of `uglify-js` which happens to support ES2020+ these days.

With the recent PR on sequences it ought to be easy to support pure annotated calls with side effects in their parameters:

```
$ echo 'a(), /*@__PURE__*/ b(0, effect1(), /*@__PURE__*/ effect2(), 3);' | rollup --silent
a(), /*@__PURE__*/ b(0, effect1(), /*@__PURE__*/ effect2(), 3);

$ echo 'a(), /*@__PURE__*/ b(0, effect1(), /*@__PURE__*/ effect2(), 3);' | uglify-js -c
a(),effect1();
```

**Comment by kzc** [comment]
Side note... the surprising complexity of correctly associating comments with AST nodes is why I strongly discourage extending pure annotations to anything but calls and new expression. Anything can wrapped in pure IIFEs in the worst case anyway.

**Pull request merged**
