### PR TITLE
docs: cli help.md format and make tag display

### PR DESCRIPTION
**Pull request by cunzaizhuyi**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [X] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [X] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [X] no

List any relevant issue numbers:

### Description

docs: cli help.md format and make tag display

### CODE REVIEW

**Review by lukastaegert — COMMENTED** [review]
We can definitely talk about this change. What I do not like, though, is that now the explanations are no longer left-aligned, compare e.g. `--input` with `--sourcemap`.

Another point is that it violates the 80 character limit we had on this file, which also makes CI fail. The 80 character limit was to improve readability on smaller displays but I see with your change, this may no longer be necessary. But then, we should adapt the failing test and remove line-breaks e.g. from the `--config` option. Maybe we set the limit to 120 characters?
And last, this file should always be kept in sync with the corresponding section in the docs.

**Comment by cunzaizhuyi** [comment]
* what do you mean `improve readability on smaller displays`? maybe reading on mobile phones?
* `kept in sync with docs`, you mean we should also change the docs if we change this md ?
* how about change this into a table ?
At last, i change this md just because all options display in one line and the tags can't display.

**Comment by lukastaegert** [comment]
> what do you mean improve readability on smaller displays? maybe reading on mobile phones?

Well, this file is what is displayed when you run `rollup` in a terminal. I do not expect anyone to run Rollup in a terminal on a phone, but terminal windows can have any size and it should look readable if the window is smaller.

It is NOT intended to be read from within GitHub. For that reason, you can find the exact same list nicely formatted here https://rollupjs.org/command-line-interface/#command-line-flags

**Comment by cunzaizhuyi** [comment]
OK.I got it. maybe we shouldn't modify it.😃😃😃

**Pull request closed without merging**
