### PR TITLE
Document more ways to read package.json in ESM

### PR DESCRIPTION
**Pull request by berniegp**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description

What appears to me like the simplest options to read `package.json` from an ESM configuration file are not presented in the documentation. This PR adds them.

Special thanks to this SO answer: https://stackoverflow.com/a/66726426/1030527

### CODE REVIEW

**Comment by berniegp** [comment]
I'm debating which version for the 1st example works best for the docs:

```
    // rollup.config.mjs
    import { readFileSync } from 'fs';
    
    const packageJson = JSON.parse(readFileSync('./package.json'));

JSON.parse(readFileSync(new URL('../package.json', import.meta.url))).version;
```

or

```
    // rollup.config.mjs
    import { readFileSync } from 'fs';
    
    const packageJson = JSON.parse(readFileSync(new URL('./package.json', import.meta.url)));
```

The second option [uses this](https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_no_filename_or_dirname) and can prevent mistakes from users copy-pasting the code. It's also slightly more involved...

**Comment by lukastaegert** [comment]
Thanks a lot! I would be willing to merge this PR as it is for Rollup 2. However, incidentally I just reworked (rather: replaced) the entire section in another PR for Rollup 3: https://github.com/rollup/rollup/pull/4123/files#diff-3bcf69b015e1d47b66389aaafaf606be97b72f19240a58f5d87031b87ae2013cL269-R324

The reason is that I want "untranspiled files" to be the default anyway. They two ways I recommend there are import assertions for Node 18 or createRequire (and we will not support any Node version older than 14). It would be nice if you could have a look at that PR that I want to merge to the 3.0.0 release branch soon if you think we should improve the documentation there, and if you think it is worth adding the fs.readFile approach.

If you would add it, I would prefer the import.meta approach as it is independent of `process.cwd()`

**Review by lukastaegert — APPROVED** [review]

**Comment by berniegp** [comment]
Hi! Happy to have a look yes. It probably won't be until next weekend though.

Regarding the `import.meta.url` changes: did you do that yourself already? I see that this PR is already merged so I'm not sure.

**Comment by lukastaegert** [comment]
No, I did no do them.

**Comment by berniegp** [comment]
I can't access `lohfu:better-esm-config-file-support` to open a pull request. Is this a private repository?
Or would you rather I share my findings in the PR?

**Comment by lukastaegert** [comment]
It is already merged to the 3.0 release branch in the Rollup repo, either share your findings in the old PR or create a new PR against the release branch

**Pull request merged**
