### PR TITLE
Fix magic-string deprecations

### PR DESCRIPTION
**Pull request by Conduitry**
Prevent some warnings related to magic-string deprecations.

### CODE REVIEW

**Comment by kzc** [comment]
Just wondering if someone could explain what do the new `magic-string` `overwrite` options `storeName` and `contentOnly` do?
```js
code.overwrite( this.start, this.end, name, { storeName: true, contentOnly: false } );
```
I read the docs in the `magic-string` project but it's still not clear to me.

**Comment by Rich-Harris** [comment]
`storeName` means that the string being replaced should be considered a name that gets included in the sourcemap's `names` array — so if you have code like this...

```js
function foo () {
  throw new Error('oh no! something went wrong');
}
```

```js
code.overwrite(9, 12, 'bar', { storeName: true });
```

...then when you run the code, the sourcemapped stack trace will show that the error originated inside `foo`, not `bar`. [Demo](https://runkit.com/rich/593f4eb9d98c590011ff710d)

`contentOnly` means that the you're not replacing anything that was prepended or appended to the chunk. [Demo](https://runkit.com/rich/593f4fcf0f4e6200123c9d4a)

**Comment by Rich-Harris** [comment]
Thanks @Conduitry

**Comment by kzc** [comment]
@Rich-Harris Thanks for the great explanation!

**Pull request merged**
