### PR TITLE
safe hasOwnProperty call

### PR DESCRIPTION
**Pull request by LongTengDao**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description

There will be a bug when export names include `hasOwnProperty`.

I'm not sure how to add test for this case...

### CODE REVIEW

**Review by lukastaegert — COMMENTED** [review]
Looks reasonable, but it is not entirely clear to me what scenario we are guarding against. Most importantly, we would need a test (probably a `function` test that runs the generated code) that is broken without that change.
`exports` is an object provided by the runtime. Why wouldn't we want to use its `hasOwnProperty` method?

**Comment by LongTengDao** [comment]
@lukastaegert 

https://rollupjs.org/repl/?version=3.26.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwKiUyMGZyb20lMjAnZXh0ZXJuYWwnJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGhhc093blByb3BlcnR5JTIwJTNEJTIwKCklMjAlM0QlM0UlMjBmYWxzZSUzQiU1Q24lNUNuZXhwb3J0JTIwbGV0JTIweCUyMCUzRCUyMDElM0IlNUNuJTVDbnNldFRpbWVvdXQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIweCUyMCUzRCUyMDIlM0IlNUNuJTdEJTJDJTIwMCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIyZXh0ZXJuYWwlMjAoY2FzZSUzQSUyMG5vbi1nZXR0ZXIpJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGxldCUyMGhhc093blByb3BlcnR5JTIwJTNEJTIwZmFsc2UlM0IlNUNuJTVDbnNldFRpbWVvdXQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwaGFzT3duUHJvcGVydHklMjAlM0QlMjB0cnVlJTNCJTVDbiU3RCUyQyUyMDApJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmV4dGVybmFsJTIwKGNhc2UlM0ElMjB0aHJvdyklMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwZXh0ZXJuYWwlNUNuZXhwb3J0JTIwY29uc3QlMjBoYXNPd25Qcm9wZXJ0eSUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyRiolMjBkbyUyMHNvbWV0aGluZyUyMGhlcmUlMjAqJTJGJTVDbiU3RCUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJleHRlcm5hbCUyMChjYXNlJTNBJTIwc2lkZS1lZmZlY3RzKSUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlN0QlN0QlN0Q=

```js
// entry.js
export * from 'external';
```

You will got nothing dynamic re-export:

```js
// external (case: non-getter)
export const hasOwnProperty = () => false;
```

or got an error thrown:

```js
// external (case: throw)

export const hasOwnProperty = false;
```

even worse with side effects:

```js
// external (case: side-effects)
export const hasOwnProperty = () => {
  /* do something here */
};
```

see the generated code, and imagine what will happen in runtime:

```js
var external = require('external');

Object.keys(external).forEach(function (k) {
	if (k !== 'default' && !exports.hasOwnProperty(k)) Object.defineProperty(exports, k, {
		enumerable: true,
		get: function () { return external[k]; }
	});
});
```

**Comment by lukastaegert** [comment]
Thanks for clarifying. Then you should add this as a "function" test case, then we do not need to imagine.

**Comment by LongTengDao** [comment]
@lukastaegert here ready if I add the test right

**Review by lukastaegert — APPROVED** [review]
Looks perfect, thanks so much for following up on this!

**Pull request merged**
