### PR TITLE
Use mutable bindings for default exports

### LINKED ISSUE #2000: `export default x` live binding scenarios
Currently we output `export default x` when we have default exports instead of `export { x as default }`.

For example - https://rollupjs.org/repl?version=0.56.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMHglMjAlM0QlMjAxMCUzQiU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjB1cGRhdGUlMjAoKSUyMCU3QiU1Q24lNUN0eCUyMCUzRCUyMDExJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCJTIweCUyMGFzJTIwZGVmYXVsdCUyMCU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

The issue is that `export default x` is no longer a live binding, so it would actually be better to have `export { x as default }` to ensure the live binding!

This case came up considering live binding across chunking interfaces which all works out, except for default exports in this way.

Of course in scenarios where the default is a temporary variable created by Rollup, we know we can use `export default` as there is no live binding update in play.

For example with - https://rollupjs.org/repl?version=0.56.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMHglMjAlM0QlMjAxMCUzQiU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjB1cGRhdGUlMjAoKSUyMCU3QiU1Q24lNUN0eCUyMCUzRCUyMDExJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMHglM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

Perhaps we should work on distinguishing these cases and outputting appropriately.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
#4168 
resolves #2000

### Description
This aims to improve handling of default exports and solve many issues listed in #4168.

The most important change is that default exports are now always rendered as

```js
export {binding as default};
```

instead of

```js
export default binding;
```

This works much better with how we treat default exports internally (for the most part, not different from named exports) and will potentially allow consumers to avoid creating an additional binding.

Most importantly, this finally allows Rollup to create mutable default exports, something which was not possible before.

Secondly, this detects when we default export a binding in a position where the binding may be in a temporal dead zone and creates an additional variable in these cases so that the error is not swallowed.

Also, an inconsistency is fixed where `.default` was not written as a computed property.

What is **not solved** is the main issue listed in #4168 as detecting circular dependency situations is somewhat tricky.

Update: I decided not to add any special handling for using default export mode with a mutable default export yet as I could not decide how to approach this best.

### CODE REVIEW

**Comment by guybedford** [comment]
Nice to see. Note this fixes https://github.com/rollup/rollup/issues/2000.

**Comment by lukastaegert** [comment]
I decided not to add any special handling for using default export mode with a mutable default export yet as I could not decide how to approach this best.

**Comment by jirutka** [comment]
This change breaks [njs-typescript-starter](https://github.com/jirutka/njs-typescript-starter) ([#1](https://github.com/jirutka/njs-typescript-starter/issues/1)) because **njs** (NGINX JavaScript – an alternative JavaScript interpreter) doesn’t support named exports. It seems that this rollup feature is not configurable, so what am I supposed to do?

**Comment by lukastaegert** [comment]
I am sorry, but Rollup only promises to produce ECMA compatible code which it does. There is no spec that I am aware of where you only have some ES 2015 export features but not others,even though it might be breaking for your non-standard-compliant runtime.
If you rely on this, you can always rewrite anything in a renderChunk plugin hook.
If you think there is demand, you could also serve the community by publishing such a plugin.

**Comment by jirutka** [comment]
> There is no spec that I am aware of where you only have some ES 2015 export features but not others,even though it might be breaking for your non-standard-compliant runtime.

Yes, that’s true, njs is not fully ECMAScript compliant yet. But I really don’t understand why is Rollup replacing `export default { foo }` from the source with `export { foo as default }`, even when `output.exports` is explicitly set to `default`, not `named`. It’s already ES export, so why does Rollup transform it at all? Moreover, the documentation doesn’t mention this surprising behaviour at all.

> If you rely on this, you can always rewrite anything in a renderChunk plugin hook.

That’s what I’m trying to do now. However, I was hoping to find a more elegant way than replacing the rendered export using regex.

**Comment by dnalborczyk** [comment]
> It seems that this rollup feature is not configurable, so what am I supposed to do?

you can bug the `njs` maintainers to introduce proper `named exports`. the way it's currently implemented by `default exporting` an object is pretty weird.

meanwhile, you can `pin` down the rollup version to the version where the behavior was the same as what you expected.

> But I really don’t understand why is Rollup replacing export default { foo } from the source with export { foo as default },

the reason is to be ecma spec compliant. 

> even when output.exports is explicitly set to default, not named

it's still a default export. just a different syntax.

**Pull request merged**
