### PR TITLE
Force unix linebreaks

### PR DESCRIPTION
**Pull request by TrySound**
This rule do not let me lint on windows.

### CODE REVIEW

**Comment by TrySound** [comment]
Seems line one line in `test/cli/config-external/_expected.js` changed position.

**Comment by Rich-Harris** [comment]
Weirdly this branch works fine for me locally... any insight into why it's failing in both CI envs?

**Comment by Rich-Harris** [comment]
Never mind, not related to this PR (same thing happening while merging other PRs that were marked as passing) – looking into it

**Comment by Rich-Harris** [comment]
Bug was fixed in https://github.com/rollup/rollup/commit/884803d1f419259085c44bf733f7d93ba151ee1b

**Pull request merged**
