### PR TITLE
Include default exports used within the module but not by importers.

### PR DESCRIPTION
**Pull request by Permutatrix**
[They're currently omitted.](http://rollupjs.org/?shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBiJTIwJTdEJTIwZnJvbSUyMCcuJTJGbW9kdWxlLmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coYigpKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGEoKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZygneCcpJTNCJTVDbiUyMCUyMHJldHVybiUyMDUlM0IlNUNuJTdEJTVDbiU1Q25hKCklM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwYigpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMGEoKSUyMCUyQiUyMDEwJTNCJTVDbiU3RCU1Q24lMjIlN0QlNUQlN0Q=)

### CODE REVIEW

**Comment by Permutatrix** [comment]
With this change, Ractive.js will now build and pass tests again. That seems like a pretty cool milestone after the rewrite.

**Comment by mbostock** [comment]
I *think* this is functionally equivalent to my fix #972, and is slightly cleaner.

The only change I’d make is to remove the `&& !this.declaration.activated` check later in the function (on L79), since if you’re at that part of the code, `this.declaration.activated` is guaranteed to be false.

**Comment by mbostock** [comment]
I made a PR for your PR: Permutatrix/rollup#1.

**Comment by mbostock** [comment]
Using my tests from #972, I’ve confirmed this also fixes #970. And the tests here are equivalent so I’ve closed my PR.

**Comment by Permutatrix** [comment]
Alright, thanks, that's what I was about to check.

**Comment by mbostock** [comment]
I’ve discovered this bug is (perhaps not surprisingly) breaking D3 custom bundles, because D3 uses default exports in a number of places.  Here’s a greatly [reduced test case](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCZGVmYXVsdCUyMGFzJTIwc2VsZWN0aW9uJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZzZWxlY3Rpb24tc2VsZWN0aW9uJTVDJTIyJTNCJTVDbmltcG9ydCUyMCU1QyUyMi4lMkZ0cmFuc2l0aW9uLXNlbGVjdGlvbiU1QyUyMiUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzZWxlY3Rpb24tc2VsZWN0aW9uLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwU2VsZWN0aW9uKCklMjAlN0IlN0QlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwc2VsZWN0aW9uKCklMjAlN0IlMjByZXR1cm4lMjBuZXclMjBTZWxlY3Rpb24lM0IlMjAlN0QlNUNuU2VsZWN0aW9uLnByb3RvdHlwZSUyMCUzRCUyMHNlbGVjdGlvbi5wcm90b3R5cGUlMjAlM0QlMjAlN0IlN0QlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIydHJhbnNpdGlvbi1zZWxlY3Rpb24uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCZGVmYXVsdCUyMGFzJTIwc2VsZWN0aW9uJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZzZWxlY3Rpb24tc2VsZWN0aW9uJTVDJTIyJTNCJTVDbmltcG9ydCUyMCU3QlRyYW5zaXRpb24lN0QlMjBmcm9tJTIwJTVDJTIyLiUyRnRyYW5zaXRpb24tdHJhbnNpdGlvbiU1QyUyMiUzQiU1Q25zZWxlY3Rpb24ucHJvdG90eXBlLnRyYW5zaXRpb24lMjAlM0QlMjBmdW5jdGlvbigpJTIwJTdCJTIwcmV0dXJuJTIwbmV3JTIwVHJhbnNpdGlvbiUzQiUyMCU3RCUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0cmFuc2l0aW9uLXRyYW5zaXRpb24uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCZGVmYXVsdCUyMGFzJTIwc2VsZWN0aW9uJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZzZWxlY3Rpb24tc2VsZWN0aW9uJTVDJTIyJTNCJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwVHJhbnNpdGlvbigpJTIwJTdCJTdEJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMHRyYW5zaXRpb24oKSUyMCU3QiUyMHJldHVybiUyMHNlbGVjdGlvbigpLnRyYW5zaXRpb24oKSUzQiUyMCU3RCU1Q252YXIlMjBzZWxlY3Rpb25fcHJvdG90eXBlJTIwJTNEJTIwc2VsZWN0aW9uLnByb3RvdHlwZSUzQiU1Q25UcmFuc2l0aW9uLnByb3RvdHlwZSUyMCUzRCUyMHRyYW5zaXRpb24ucHJvdG90eXBlJTIwJTNEJTIwJTdCJTdEJTNCJTIyJTdEJTVEJTdE) that demonstrates the problem. When you import d3-transition, it uses a default export that is omitted from the output, so the resulting bundle crashes with the following error:

```
Transition.prototype = transition.prototype = {};
                       ^

ReferenceError: transition is not defined
```

**Comment by Rich-Harris** [comment]
Thanks so much and sorry for the delay merging this – released as 0.36.1

**Pull request merged**
