### PR TITLE
Perf boosting

### PR DESCRIPTION
**Pull request by TrySound**
Ref #723 #808

### CODE REVIEW

**Comment by TrySound** [comment]
Results before and after the last commit on very slow machine.
```
[15:01:46] Starting 'module:js'...
[15:01:56] Finished 'module:js' after 10 s
[15:01:56] Starting 'watch:js'...
[15:01:56] Finished 'watch:js' after 62 ms
[15:01:58] Starting 'module:js'...
[15:02:05] Finished 'module:js' after 6.47 s
[15:02:07] Starting 'module:js'...
[15:02:13] Finished 'module:js' after 6.53 s
```
```
[15:02:51] Starting 'module:js'...
[15:03:00] Finished 'module:js' after 8.84 s
[15:03:00] Starting 'watch:js'...
[15:03:00] Finished 'watch:js' after 47 ms
[15:03:03] Starting 'module:js'...
[15:03:08] Finished 'module:js' after 4.78 s
[15:03:10] Starting 'module:js'...
[15:03:15] Finished 'module:js' after 5.01 s
[15:03:17] Starting 'module:js'...
[15:03:22] Finished 'module:js' after 4.49 s
[15:10:36] Starting 'module:js'...
[15:10:41] Finished 'module:js' after 5.24 s
[15:10:42] Starting 'module:js'...
[15:10:47] Finished 'module:js' after 4.22 s
```

**Comment by Victorystick** [comment]
It'd be interesting to see the effects of each of these optimizations in isolation. How much faster is it with only the indentation adjustment?

**Comment by TrySound** [comment]
@Victorystick I already posted that in that issue.

**Comment by Victorystick** [comment]
I mean, it would be nice to contain the changes in two separate PRs; since they're caching and indentation are orthogonal features. They could be merged one at a time.

**Pull request closed without merging**
