### PR TITLE
Try to add a windows executor

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description
As Github actions tend to not run for PRs from forks, I am investigating here if we can use a Windows executor for CircleCI

### CODE REVIEW

**Comment by shellscape** [comment]
@lukastaegert we don't have any issues with Github actions running for forks in the plugins repo. Can you point me to a PR here that got messed up for a fork?

**Comment by lukastaegert** [comment]
Any PR from an account that does not itself have Github actions enabled. #3841 was the last one that had me scrambling to fix tests directly on master after merging the PR. As for an upcoming PR, you can see that #3883 does not have the Windows checks running either.

Unless Github changes their policy to also run Github actions for PRs from forks that do not have themselves Github actions enabled, I am seriously looking for alternatives here.

**Comment by shellscape** [comment]
Good lord, that's one hell of a bug in their system. I'm taking to Twitter to see if I can dig up anyone connected to that.

**Comment by lukastaegert** [comment]
Seems to work now with Github Actions, so I will close this PR. If we are happy, maybe at some point we can consider moving entirely to Github Actions on the other hand.

**Pull request closed without merging**
