### PR TITLE
[v2.0.0] Avoid empty imports from side-effect-free chunks

### LINKED ISSUE #3057: Removing empty imports of modules with moduleSideEffects: false
- Rollup Version: 1.19.4
- Operating System (or Browser): Linux, Mac
- Node Version: 10

### How Do We Reproduce?
I'm not sure if this is a bug or feature request. See the example [REPL](https://rollupjs.org/repl/?version=1.19.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBFWFRFUk5BTCUyMElNUE9SVFMlNUNuJTIwJTIwJTIwWW91JTIwY2FuJTIwaW1wb3J0JTIwZXh0ZXJuYWwlMjBtb2R1bGVzJTIwaW50byUyMHlvdXIlMjBidW5kbGUlMjAlRTIlODAlOTMlNUNuJTIwJTIwJTIwaXQlMjBkb2Vzbid0JTIwbWF0dGVyJTIwaWYlMjB0aGV5J3JlJTIwRVMyMDE1JTIwb3IlMjBsZWdhY3klMjAqJTJGJTVDbmltcG9ydCUyMCU3QkNvbXBvbmVudCU3RCUyMGZyb20lMjAnLiUyRmNvbXBvbmVudCclM0IlNUNuJTVDbmNvbnNvbGUubG9nKENvbXBvbmVudCklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYWluMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0JDb21wb25lbnQlN0QlMjBmcm9tJTIwJy4lMkZjb21wb25lbnQnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhDb21wb25lbnQpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY29tcG9uZW50LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QnRvb2wlN0QlMjBmcm9tJTIwJ3NvbWUtcHJpdmF0ZS1tb2R1bGUnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMENvbXBvbmVudCUyMCUzRCUyMCh4KSUyMCUzRCUzRSUyMHRvb2woeCklMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

There is an import of external module 
`import { tool } from 'some-private-module';` 
in  code (a shared chunk) shared across multiple entry points. 
Now the entry points contain
`import 'some-private-module';`

In our codebase, we created a rollup plugin with a `resolveId` hook which resolves our ` 'some-private-module'` as 
```
  {
      id: '...some id...',
      external: true,
      moduleSideEffects: false, // tried but didn't help
}
```
Correct me if I'm wrong, but I don't see a good reason why `import 'some-private-module';` exists in the entry points. 

### Expected Behavior
no `import 'some-private-module';` in entry points

### Actual Behavior
`import 'some-private-module';` in entry points exist

### LINKED ISSUE #3109: multiple inputs leading to full third party package imports
- Rollup Version: 1.20.2
- Operating System (or Browser): MacOS Mojave 10.14.6
- Node Version: 10.16.0

### How Do We Reproduce?

[Reproduction](https://rollupjs.org/repl/?version=1.21.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBNVUxUSVBMRSUyMEVOVFJZJTIwTU9EVUxFUyUyMColMkYlNUNuaW1wb3J0JTIwY3ViZSUyMGZyb20lMjAnLiUyRmN1YmUuanMnJTNCJTVDbmltcG9ydCUyMCU3QiUyMEtpbmQlMjAlN0QlMjBmcm9tJTIwJ2dyYXBocWwnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyglMjBjdWJlKCUyMDUlMjApJTIwKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm90aGVyRW50cnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwQWRkaXRpb25hbCUyMGVudHJ5JTIwbW9kdWxlcyUyMGNyZWF0ZSUyMG5ldyUyMGNodW5rcyU1Q25pbXBvcnQlMjBjdWJlJTIwZnJvbSUyMCcuJTJGY3ViZS5qcyclM0IlNUNuaW1wb3J0JTIwJTdCJTIwS2luZCUyMCU3RCUyMGZyb20lMjAnZ3JhcGhxbCclM0IlNUNuJTVDbmNvbnNvbGUubG9nKCUyMGN1YmUoJTIwNSUyMCklMjApJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY3ViZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBLaW5kJTIwJTdEJTIwZnJvbSUyMCdncmFwaHFsJyUzQiU1Q24lNUNuJTJGJTJGJTIwRXZlcnl0aGluZyUyMHVzZWQlMjBieSUyMGJvdGglMjBlbnRyeSUyMG1vZHVsZXMlMjB3aWxsJTIwYmVjb21lJTVDbiUyRiUyRiUyMGElMjBzZXBhcmF0ZSUyMGNodW5rJTIwdGhhdCUyMGlzJTIwaW1wb3J0ZWQlMjBieSUyMGJvdGglMjBlbnRyeSU1Q24lMkYlMkYlMjBjaHVua3MlMjB0byUyMGF2b2lkJTIwY29kZSUyMGR1cGxpY2F0aW9uJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGN1YmUlMjAoJTIweCUyMCklMjAlN0IlNUNuJTVDdHJldHVybiUyMHglMjAqJTIweCUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

Note how graphql goes from a tree-shakeable import to a "polyfill" one. The behavior in the actual repo is a bit more complicated since the import has to stay in the shared folder because it's used there. I can always supply more if needed, wanted to start out by having the most minimal reproduction.

I have linked the PR where the issue persists to this one, in that branch when you do:

`yarn && yarn build`

move to the `/dist/esm` folder and you'll see in `core.js` and `urql.js` that the full graphql and fast-json-stable-stringify are imported but only used in the shared index file.

Note that we are using

```
  treeshake: {
    moduleSideEffects: false,
    propertyReadSideEffects: false,
  }
```

And the graphql module itself has sideEffects: false

### Expected Behavior

I would expect the `graphql` import to be cut away in both entries and to only live in the shared if used there.

### Actual Behavior

The imports stay and are now a huge bundle bloat.

### LINKED ISSUE #3359: Inlining of deps from empty chunks with preserveModules doesn't check the moduleSideEffects flag
- Rollup Version: 1.29.1
- Operating System (or Browser): Windows 10
- Node Version: 10.18.0

Search terms:
treeshaking
moduleSideEffects
preserveModules
empty imports

Related:
#3057 
#3109 

### How Do We Reproduce?

Using the module layout here:
[REPL](https://rollupjs.org/repl/?version=1.29.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZpbmRleCclM0IlNUNuaW1wb3J0JTIwJTdCJTIwZCUyMCU3RCUyMGZyb20lMjAnLiUyRm9uZSclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGElMjAlMkIlMjBkKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmluZGV4LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZhJyUzQiU1Q25leHBvcnQlMjAlN0IlMjBiJTIwJTdEJTIwZnJvbSUyMCcuJTJGYiclM0IlNUNuZXhwb3J0JTIwJTdCJTIwYyUyMCU3RCUyMGZyb20lMjAnLiUyRmMnJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBhJTIwJTNEJTIwMSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwYiUyMCUzRCUyMDIlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGMlMjAlM0QlMjAzJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm9uZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBiJTIwJTdEJTIwZnJvbSUyMCcuJTJGaW5kZXgnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGQlMjAlM0QlMjBiJTIwJTJCJTIwNCUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
Specify `preserveModules: true` and `treeShaking.moduleSideEffects: false`

I understand the contract of the `moduleSideEffects` flag to mean, for a given module:
- `true`: All modules imported later than this module may have an implicit dependency on this module, and therefore this module must not be moved to be later in the load order (but may potentially be moved earlier)
- `false`: No modules have an implicit dependency on this module, and thus it may be safely moved later in the load order

### Expected Behavior
```js
// main.js
import { a } from '../a.js';
import { d } from '../other.js';

console.log(a + d);
```

### Actual Behavior
```js
// main.js
import { a } from '../a.js';
import '../b.js';
import { d } from '../other.js';

console.log(a + d);
```

Addressing this may be as simple as introducing a check in `inlineChunkDependencies`:
```diff
                if (!dep.isEmpty) {
+                   // In preserveModules mode, only inline the dep if it has side effects (being used elsewhere is not a side effect)
+                   if (!this.graph.preserveModules || !dep.facadeModule || dep.facadeModule.moduleSideEffects) {
                        this.dependencies.push(dep);
+                   }
                }
```

Edit: added info about `moduleSideEffects` expectations
Edit: added link to 3109

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [x] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:
Resolves #3359
Resolves #3109 
Resolves #3057 

### Description
Originally the goal with this PR was to just suppress empty imports from chunks if `moduleSideEffects` is `false`. However as it turned out, it was possible to extend this beyond the `moduleSideEffects` flag by using the existing tree-shaking mechanics to infer this flag for modules for which it was not explicitly set to `false`; moreover, Rollup will also generate fewer chunks in many situations.

To do this right, I implemented this on module level, not on chunk level. This means that after tree-shaking, each "empty" dependency (i.e. import where no bindings are actually imported) of a module is tested for side-effects and
- is removed if `moduleSideEffects` is `false` for this dependency
- is recursively replaced by its side-effectful dependencies if `moduleSideEffects` is `true` but no side-effects can be found inside the module
- is retained otherwise

This happens BEFORE chunks are generated, which means that after this PR, more efficient chunks will be generated! As an example, consider the following:

```js
// input
// main1.js
import dep from './dep.js';
dep();

// main2.js
import dep from './dep.js';
console.log('main2');

// dep.js
export default function onlyUsedByOne() {
	console.log('Hello');
}
```

If you run this in the REPL, you will get three chunks with an empty import from the `main2` chunk to the shared chunk–even though the shared chunk does not have side-effects: https://rollupjs.org/repl/?version=1.31.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGRlcCUyMGZyb20lMjAnLiUyRmRlcC5qcyclM0IlNUNuZGVwKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYWluMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBkZXAlMjBmcm9tJTIwJy4lMkZkZXAuanMnJTNCJTVDbmNvbnNvbGUubG9nKCdtYWluMicpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZGVwLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMG9ubHlVc2VkQnlPbmUoKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJ0hlbGxvJyklM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

With this PR, you will instead just get the following two chunks:

```js
// output
// main1.js
function onlyUsedByOne() {
	console.log('Hello');
}
onlyUsedByOne();

// main2.js
console.log('main2');
```

You can check this out here: https://rollupjs.org/repl/?circleci=9330&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGRlcCUyMGZyb20lMjAnLiUyRmRlcC5qcyclM0IlNUNuZGVwKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYWluMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBkZXAlMjBmcm9tJTIwJy4lMkZkZXAuanMnJTNCJTVDbmNvbnNvbGUubG9nKCdtYWluMicpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZGVwLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMG9ubHlVc2VkQnlPbmUoKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJ0hlbGxvJyklM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

This means you will not only get fewer chunks but the second chunk will also avoid loading quite a bit of maybe-not-dead-but-definitely-not-needed code.

Now assume that `dep.js` itself has a side-effectful dependency, for instance an external import:

```js
// input
// dep.js
import 'external-side-effect';
export default function onlyUsedByOne() {
	console.log('Hello');
}
```

Then you will STILL get two chunks, but the side-effect import will be hoisted to both chunks:

```js
// output
// main1.js
import 'external-side-effect';
function onlyUsedByOne() {
	console.log('Hello');
}
onlyUsedByOne();

// main2.js
import 'external-side-effect';
console.log('main2');
```

I think this is a great improvement for everyone and the first step to actually fixing many ordering issues we can currently have with code-splitting without creating endless amounts of chunks as side-effect-free modules can be moved around rather safely (not done in this PR yet, though).

I have marked this as "BREAKING" because with this change, side-effect-free modules will no longer appear as part of any chunk in the generated bundle object. Previously, they would always appear to be assigned to some chunk. I am not sure if there are tools that analyze tree-shaking quality that depend on all modules being mentioned in the output.

### CODE REVIEW

**Comment by lukastaegert** [comment]
<h3>This is a test</h3>
Demo: <strong><a href="https://rollupjs.org/repl/?circleci=https://circleci.com/gh/rollup/rollup/9302">Test in REPL</a></strong>

**Comment by lukastaegert** [comment]
Hello Test

**Comment by lukastaegert** [comment]
### Message from bot

You can try out this PR in the REPL here:
https://rollupjs.org/repl/?circleci=1234

**Comment by lukastaegert** [comment]
### Thank you for your contribution! ❤️

You can try out this pull request locally via

```
npm install gh-3359-chunk-module-side-effects
```

or load it into the REPL:
https://rollupjs.org/repl/?circleci=9314

**Comment by lukastaegert** [comment]
### Thank you for your contribution! ❤️

You can try out this pull request locally via

```
npm install test
```

or load it into the REPL:
https://rollupjs.org/repl/?circleci=1234d

**Comment by lukastaegert** [comment]
### Thank you for your contribution! ❤️

You can try out this pull request locally via

```
npm install rollup/rollup#gh-3359-chunk-module-side-effects
```

or load it into the REPL:
https://rollupjs.org/repl/?circleci=1234d

**Comment by lukastaegert** [comment]
### Thank you for your contribution! ❤️

You can try out this pull request locally via

```
npm install rollup/rollup#gh-3359-chunk-module-side-effects
```

or load it into the REPL:
https://rollupjs.org/repl/?circleci=1234d

**Comment by lukastaegert** [comment]
### Thank you for your contribution! ❤️

You can try out this pull request locally via

```
npm install rollup/rollup#gh-3359-chunk-module-side-effects
```

or load it into the REPL:
https://rollupjs.org/repl/?circleci=1234d

**Comment by lukastaegert** [comment]
### Thank you for your contribution! ❤️

You can try out this pull request locally via

```
npm install rollup/rollup#gh-3359-chunk-module-side-effects
```

or load it into the REPL:
https://rollupjs.org/repl/?circleci=1234d

**Comment by LarsDenBakker** [comment]
This is a huge deal for apps with a lot of dynamic imports. Would it be possible the provide this behind a flag in 1.x? Or is 2.x already close to shipping?

**Comment by tivac** [comment]
https://rollupjs.org/repl/?circleci=9330&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMG1haW4xLmpzJTVDbmltcG9ydCUyMGRlcCUyMGZyb20lMjAnLiUyRmRlcC5qcyclM0IlNUNuZGVwKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYWluMi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBtYWluMi5qcyU1Q25pbXBvcnQlMjBkZXAlMjBmcm9tJTIwJy4lMkZkZXAuanMnJTNCJTVDbmNvbnNvbGUubG9nKCdtYWluMicpJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmRlcC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBkZXAuanMlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwb25seVVzZWRCeU9uZSgpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZygnSGVsbG8nKSUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

Well *that's cool as hell*. 👍🏻👍🏻👍🏻

**Comment by lukastaegert** [comment]
@LarsDenBakker 
> Or is 2.x already close to shipping?

Actually really close https://github.com/rollup/rollup/projects/2, the only remaining thing would be aligning on and implementing #3370 . And possibly making a call on #3343: `experimentalOptimizeChunks` is buggy and makes refactoring and future innovations hard, I think I really want to get rid of it.

> Well that's cool as hell. 👍🏻👍🏻👍🏻
I spent some inspirational time today thinking that we finally should have a bot and be able to try out PRs in the REPL 😜

**Comment by tivac** [comment]
> I spent some inspirational time today thinking that we finally should have a bot and be able to try out PRs in the REPL 😜

Being able to easily try out big refactors by poking at them in the REPL or even installing them into existing projects is hugely helpful in terms of being able to provide real feedback. Thank you!

**Comment by lukeed** [comment]
Awesome work! 👏 It seems like this would also open up #2566 for a solution, right?

**Comment by lukastaegert** [comment]
There is not really a connection, but with this change, fixing #2566 would also benefit code-splitting.

**Pull request merged**
