### PR TITLE
Enable specifying implicit dependencies when emitting chunks

### LINKED ISSUE #3574: Allow specifying implicit dependencies when emitting chunks for better chunking
- Rollup Version: 2.10.5
- Operating System (or Browser): Chrome (the REPL runs in the browser?)
- Node Version (if applicable): NA
- Link to reproduction (IMPORTANT, read below): https://repl.it/repls/SpeedyEasyCoordinates

**Update**: As the discussion drifted towards a new feature, this text is no longer applicable, see the comments below.

### Expected Behavior
When manually emitting a chunk using `emitFile`, I would expect the emitted chunk to respect the `preserveEntrySignatures` option and reuse exports from the main entrypoint when they are available. 

### Actual Behavior
A new chunk is created and shared between the main entrypoint and the emitted chunk. 

When I trigger a chunk creation through a dynamic import, it does work correctly.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #3574 

### Description
This will enable chunk emitters to specify that an otherwise independent chunk will only be loaded if at least one of a list of modules has been loaded before, allowing Rollup to create fewer chunks. The logic will be the same as if the chunk was only reachable via dynamic import from any of the specified module ids. A good use-case could be when parsing an HTML file for scripts as entry points—subsequent scripts can rely on previous scripts having loaded and can import shared dependencies directly from the chunks of the previous scripts.

The API of `this.emitFile` will be extended to accept

```ts
interface EmittedChunk {
	fileName?: string;
	id: string;
	// This is the new property; if this is a non-empty array of module ids,
	// the new logic will kick in
	implicitlyLoadedAfterOneOf?: string[];
	importer?: string;
	name?: string;
	preserveSignature?: PreserveEntrySignaturesOption;
	type: 'chunk';
}
```

If there are one or more module ids in `implicitlyLoadedAfterOneOf`, then this chunk will assume that at least one of the chunks containing those modules is already in memory, basically exactly as if each of those modules contained a dynamic import of the newly emitted chunk.

This will be reflected in `this.getModuleInfo`

```ts
interface ModuleInfo {
	dynamicallyImportedIds: string[];
	dynamicImporters: string[];
	hasModuleSideEffects: boolean;
	id: string;
	// New properties to find implicit dependencies and dependants
	implicitlyLoadedAfterOneOf: string[];
	implicitlyLoadedBefore: string[];
	importedIds: string[];
	importers: string[];
	isEntry: boolean;
	isExternal: boolean;
}
```

as well as the bundle

```ts
interface PreRenderedChunk {
	code?: string;
	dynamicImports: string[];
	exports: string[];
	facadeModuleId: string | null;
	fileName?: string;
	// new property
	implicitlyLoadedBefore: string[];
	imports: string[];
	isDynamicEntry: boolean;
	isEntry: boolean;
	// new property
	isImplicitEntry: boolean;
	map?: SourceMap;
	modules: {
		[id: string]: RenderedModule;
	};
	name: string;
	type: 'chunk';
}
```

Things to do and clarify:
- [x] How do we handle the case where one of the `implicitlyLoadedAfterOneOf` modules is not part of the output graph, either because it is not found, it is empty, or it is only reachable via a tree-shaken dynamic import? Do we want to throw in all cases, or ignore those modules up to the point where our module is promoted to a regular entry point?
- [x] Chunks with `implicitlyLoadedAfterOneOf` should respect both the user-defined `preserveEntrySignatures` option as well as the `preserveSignature` emission option
- [x] Test: Emitted chunk is only loaded after an empty entry module
- [x] Test: Emitted chunk is only loaded after an empty non-entry module
- [x] Test: A chunk is emitted with several `implicitlyLoadedAfterOneOf` entries
- [x] Test: A chunk is emitted several times with different `implicitlyLoadedAfterOneOf` entries. In that case, we merge those entries. Could be combined with the previous test.
- [x] Test: A chunk is loaded after a dynamically imported module where the dynamic import is not included.
- [x] Test: A chunk is loaded after a module that is not part of the graph.
- [x] Test: A chunk is loaded after a module that is not found.
- [x] Test: A chunk is loaded after a module that is external.
- [x] Test: A chunk is loaded after a module in the same chunk.
- [x] Test: A chunk is emitted several times, once without implicit dependants
- [x] Test: An entry chunk is emitted with implicit dependants

### CODE REVIEW

**Comment by lukastaegert** [comment]
At the moment, the new property is `implicitDependants` and a chunk is an `implicitDependency` if it is only loaded AFTER the chunk it is a dependency of. This is taken from the terms used for dynamic imports but I find it very confusing the more I think about it.

Maybe when emitting, we call the property `implicitlyLoadedAfterOneOf` and the inverse property `implicitlyLoadedBefore`?

**Comment by lukastaegert** [comment]
Another point I keep stumbling about is how to handle implicit dependant modules that are not part of the graph. We already considered the case where the id does not exist, but another case is where the module is empty or otherwise has no relevant side-effects. In that case, it is not assigned to any chunk and it is unclear which chunk should be loaded before.

One way to handle this would be to throw an error here as well because by the implicit dependencies, there would be no way to reach that chunk.

Alternatively, we could ignore missing implicit dependant modules and if there are none in the end, we promote the chunk to a regular entry point? Any thoughts @LarsDenBakker?

Note that this should not be a problem if a chunks solely depends on entry modules because for those, a chunk is always created, but I need to check.

Another point that is still missing is that our chunks do not yet respect entry signatures.

**Comment by lukastaegert** [comment]
> How do we handle the case where one of the implicitlyLoadedAfterOneOf modules is not part of the output graph

After some configuration I think I want to throw errors for now. Replacing an error with a non-error logic can always be done in a non-breaking change, the alternative is more difficult.

**Comment by LarsDenBakker** [comment]
Thanks a lot for this! Sorry I haven't had any time to test this yet, will try it out soon.

**Comment by lukastaegert** [comment]
This is now fully working, all that is missing is some documentation

**Comment by LarsDenBakker** [comment]
Tried it out, it works exactly the way I was hoping for 👍

**Comment by lukastaegert** [comment]
Cool! I also added some documentation now, would be nice if someone could read it and see if it is sufficiently clear. Suggestions of course welcome!

**Pull request merged**
