### PR TITLE
Implement stdin input

### LINKED ISSUE #1440: Feature: accept stdin
This is useful for quick tests of for easy CLI piping:

```sh
 echo 'console.log("Hello!");' | rollup
🚨   You must specify an --input (-i) option
```

Browserify supports it:

```sh
echo 'console.log("Hello!");' | browserify - | babili | gzip-size
325 B
```

### LINKED ISSUE #3276: Input from string/input stream
### Feature Use Case
being forced to work with files is very limited and slow.  i could do much more with rollup if it was easier. '@rollup/plugin-virtual' is a complicated solution. 

### Feature Proposal
allow the input to be a string/input stream please.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Closes #1440
Closes #3276
Closes #3290 

### Description
This continues #3290 by @kzc. Unfortunately, the original repository was removed, which is why I moved it to the main Rollup repo.

Changes:
- It is only possible to use stdin when using the CLI. The CLI does it by injecting a plugin.
- When using no config file and providing no input, the CLI will take input form stdin in non-TTY situations (e.g. in a pipe)
- You can force reading the input from stdin in all environments or when using a config file by adding a new `--stdin` flag. This will replace all inputs in a config file.
- When using the CLI by default, using `-` as module name will read this module from stdin.
- You can prevent this and make `-` a regular module name by passing the `--no-stdin` CLI flag

Documentation is still missing, otherwise it should be fully functional.

### CODE REVIEW

**Comment by lukastaegert** [comment]
Also TODO: Fix tests on Windows.

**Comment by lukastaegert** [comment]
Ready to be merged now

**Comment by kzc** [comment]
LGTM. All my command line stdin scenarios continue to work.

Overriding all file inputs in the rollup config with `--stdin` is interesting. It could be useful for debugging a config. Glad to see that one can still mix stdin "-" inputs with regular named input filenames in a config if `--stdin` is not specified.

How might one enable stdin functionality from the API if they wanted to? Is the stdin plugin exported or accessible somehow?

Users will likely want to know how to process typescript or other input formats from stdin. Probably not possible unless one would have the ability to specify an implied stdin filename suffix somehow.

**Comment by lukastaegert** [comment]
> How might one enable stdin functionality from the API if they wanted to? Is the stdin plugin exported or accessible somehow?

I was wondering about this but I could not come up with a reasonable scenario where the API user should not rather collect and handle stdin themselves. stdin is a singleton and should IMO be the responsibility of the parent application and not the framework, which is why I moved it to the CLI part.

> Users will likely want to know how to process typescript or other input formats from stdin. Probably not possible unless one would have the ability to specify an implied stdin filename suffix somehow.

Interesting question. Maybe we should extend it to allow any suffix with '-'

**Comment by kzc** [comment]
> stdin is a singleton and should IMO be the responsibility of the parent application and not the framework, which is why I moved it to the CLI part.

I suspect that API users requiring stdin input would end up copying `cli/run/stdin.ts` into their projects if it's not exported. You might consider having API calls to get and override the default stdin plugin.

> Maybe we should extend it to allow any suffix with '-'

As long as the default CLI stdin user experience remains the same and assumes ECMAScript, sure. 

But neither of these issues is a showstopper and could be implemented in future PRs.

**Comment by lukastaegert** [comment]
> But neither of these issues is a showstopper and could be implemented in future PRs

Agreed, this could all be added in non-breaking PRs.

> Overriding all file inputs in the rollup config with --stdin is interesting

It is, but the longer I think about it, it also makes the `--stdin` flag much more confusing as it is a three-state flag now. It also makes it harder do document. I think I want to change that again so that it does not override stdin but just adds or removes the `stdin` plugin.

**Comment by kzc** [comment]
Good call. The `--stdin` file input override was indeed confusing.

**Comment by kzc** [comment]
Should you ever decide to expose the stdin plugin used in this PR, be aware that it has a data race if there are multiple callers of `readStdin()` separated by delays. They will not all be guaranteed to get the same input or error in some circumstances. It may be fine in the context of CLI only use. But in more generalized use it would benefit from the logic that guaranteed a single reader in PR #3290.

**Comment by kzc** [comment]
Upon further examination of the stdin plugin I now see that `function readStdin()` is not exported and will be called just a single time in `stdinPlugin().load()` which will return the same Promise instance each time. So it should be fine as long as all stdin reading code is using the same plugin.

**Pull request merged**
