### PR TITLE
[v4.0] Switch parser to SWC and introduce native/WASM code

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [x] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [x] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

List any relevant issue numbers:

### Description
This is a massive undertaking and there is still a lot to do. The goal is to switch the parser from `acorn` to `swc` while actually improving performance. Unfortunately, this does not mean using the [JavaScript bindings of swc](https://swc.rs/docs/usage/core). At least in my experience, the cost of serializing an deserializing the complex AST nearly eats up the performance benefits of switching the parser. Moreover, swc has a very different AST (and even if you use the ESTree compat module, it is still a Babel AST and not an ESTree AST). Also, and this is critical, it uses utf-8 file positions while Rollup relies on the standard JavaScript utf-16 positions.
Instead, the approach is to directly use the Rust bindings of swc and convert the AST to a binary format before passing it as an (Array)Buffer to JavaScript. While doing this, we account for the AST differences and correct the file positions. Passing an ArrayBuffer is basically a free operation, so we just need to teach the JavaScript side to work on the ArrayBuffer. Also, the buffer is only about a third the size of stringified JSON. And last, this will enable us to easily pass ASTs to different threads or rather, do the parsing in a WebWorker and pass the buffer to the main thread for free.
To interact with the Rust code, I use [napi-rs](https://napi.rs) in NodeJS and will probably use [wasm-pack](https://rustwasm.github.io/wasm-pack) for the browser build.
For now, the actual conversion is done. As a by-product of the process, the custom swc AST is converted to an ESTree-compliant AST, which has been verified by deep comparison with the acorn AST for all Rollup test cases.

The goal is to make this the core change in Rollup 4.

There is a lot that needs to be done, though, before this can even be tested.

#### Most critical changes to enable external testing
- [x] Add WASM browser build
- [x] Fix Node release process to allow the release of beta versions to enable others to test things

#### Critical for release
- [x] Publish `@rollup/browser` with included WASM file
- [x] Handle Syntax errors
- [x] Handle other errors that used to be handled by acorn, e.g. duplicate bindings
- [x] Handle PURE and other comments
- [x] Make CI tests work
- [x] Remove acorn options
- [x] Add a Node WASM release for StackBlitz and similar use cases
- [x] Make PRs available in REPL again (currently commented out on master)
- [x] Make build process work across environments. Add instructions at least for Mac and Windows somewhere in CONTRIBUTING.md how to set up Rust nightly.
- [x] Ensure `npm install github/branch` works again across environments. If necessary, add instructions how to install rustup nightly to PR comment. Remove browser build from `prepare` script to make this process faster.

#### Not critical but should be part of Rollup 4.0 to avoid a breaking change
- [x] Switch to final AST structure of import attributes

#### Nice to have but not critical
- [ ] Store binary buffers in Rollup cache instead of AST if available (this is not the case if a custom AST is returned by a plugin, in which case we probably stick with storing the AST itself).
- [x] @lukastaegert Make release comments work from CI in some way
- [ ] Enable aarch64-unknown-linux-musl target (currently commented out)
- [ ] See if using the browser readString version provides similar performance as using the Buffer method to simplify code
- [ ] Deduplicate strings in the binary AST
- [x] Use faster utf-8 to utf-16 conversion by querying positions only in ascending order and iterating code points lazily
- [x] Use one list of numeric ids for fixed strings
- [ ] Use one 32bit block for all booleans and fixed strings in any AST node to further reduce size
- [ ] Refine estimate for initial buffer size when converting the AST
- [x] Add an easy way to compare the AST against the acorn AST in tests
- [ ] Use WebWorkers for parsing
- [ ] JSX support that keeps JSX syntax but tracks usages and renamed variables
- [ ] JSX support that transpiles JSX
- [ ] TypeScript support that removes types
- [ ] TypeScript support that keeps types but performs tree-shaking and tracks renames (if possible)
- [ ] Improve `this.parse` API with an asynchronous alternative that does not create the actual AST and supports very fast tree-walking via special APIs.
- [ ] Do not create intermediate AST nodes but directly convert AST to Rollup nodes. This means we need a solution if a plugin DOES return an AST. Ideally, we also turn that into binary, and we need to handle unknown nodes.
- [ ] Add instructions for copying wasm files when using `@rollup/browser`.

### BREAKING CHANGES
- Acorn plugins are no longer supported, the `acornInjectPlugins` option has been removed
- The `acorn` option has been removed
- You can no longer pass additional options to `this.parse`
- Import assertions now use the [new import attribute AST structure](https://github.com/estree/estree/blob/master/experimental/import-attributes.md)
- The "with" syntax for import attributes is not yet supported, awaiting support in SWC
- "assertions" have been replaced with "attributes" in various places of the plugin interface
- `output.externalImportAssertions` has been deprecated in favor of `output.externalImportAttributes`
- The `INVALID_IMPORT_ASSERTION` error code has been replaced with `INVALID_IMPORT_ATTRIBUTE`

### CODE REVIEW

**Comment by TrickyPi** [comment]
This PR is so exciting! I want to be involved. Could I try to do "Add WASM browser build"?

**Comment by lukastaegert** [comment]
Yes, please, any support is welcome! To get you started, these are my thoughts about this so far:
- I think [wasm-pack](https://rustwasm.github.io/docs/wasm-pack/) is probably the best option to generate the Web Assembly. It is also what [swc itself uses](https://github.com/swc-project/swc/blob/main/package.json#L56).
- I split the Rust code into workspaces so that the actual parser is separate from the NApi bindings. My hope is that the Web Assembly entry can also be a separate workspace so that the NApi code is not accidentally compiled into the Web Assembly output and vice versa (I think it will actually not work if the entries are mixed up).
- I would only use wasm-pack to generate the wasm file but not to generate the JavaScript wrapper, unless this really provides some advantages. So far, I think that [`@rollup/plugin-wasm`](https://www.npmjs.com/package/@rollup/plugin-wasm) should be a better choice, it also mentions wasm-pack in its documentation. I.e. generate the WASM separately, import it in the browser build and the plugin will handle the rest. Just make sure it does not inline it as base64 but really outputs it as a separate file, there should be some options to control that. You will probably need to do something in the Rollup build to only import the wasm file in the browser build similar to how we replace some other modules already in the browser build.

In any case, the browser build is broken at the moment anyway, so feel free to mess with the build process :) In the end, the goal should be to fix both the browser build and the REPL in `npm run dev`. There is a [Vite plugin](https://www.npmjs.com/package/vite-plugin-wasm) to handle WASM that also mentions wasm-pack support.

**Comment by shellscape** [comment]
Have been using SWC through ts-node for some time now and very happy with it's performance. Generally in favor of the switch. We should think about an upgrade path for plugins using acorn internally (if there are still any)

**Comment by lukastaegert** [comment]
Annotation handling is now done. It turned out to be quite complicated because there is extensive logic to remove invalid annotations. To do that, we need to convert the boundaries of annotations to UTF-16, which is involved considering we have the restriction that we can only convert positions cheaply if we do so in ascending order.
The solution now only attaches annotations to the Node that actually relies on them, e.g. `CallExpression` for pure annotations. Then there is a new `removeAnnotation` function on all Nodes that delegates to child Nodes if needed when a Node is tree-shaken.

**Pull request merged**
