### PR TITLE
check that _interopDefault's input is a non-null object

### LINKED ISSUE #474: interopDefault fails if imported module is a non-object
If you have a situation like this...

```js
// node_modules/external-dependency/index.js
module.exports = 'a string';

// main.js
import x from 'external-dependency'
```

...the `interopDefault` function searches for `default` inside `'a string'` when the bundle runs. Need to check it's a non-null object.

### PR DESCRIPTION
**Pull request by borisirota**
fixes #474

### CODE REVIEW

**Comment by dariocravero** [comment]
It would be great to see this merged :)

**Comment by Rich-Harris** [comment]
Thanks @borisirota!

**Comment by dariocravero** [comment]
@Rich-Harris would you mind releasing that to npm? :) Thanks!

**Comment by Rich-Harris** [comment]
@dariocravero done!

**Pull request merged**
