### PR TITLE
remove, and warn about, unused imports from external modules

### LINKED ISSUE #595: Unused imports from external modules should be stripped from import statements in ES bundles
The following code...

``` js
// main.js
import { unused } from 'external';

function alsoUnused () {
  unused();
}
```

...could result in the following ES bundle (i.e. it imports the external module in case it has side-effects, but doesn't need `unused` specifically)...

``` js
import 'external';
```

...but instead we get this...

``` js
import { unused } from 'external';
```

...which causes [confusion](http://stackoverflow.com/questions/36417779/rollup-including-unneeded-dependancies-and-missing-a-function-in-output).

### PR DESCRIPTION
**Pull request by Rich-Harris**
fixes #595

### CODE REVIEW

**Comment by kzc** [comment]
Does this PR assume that unreferenced dropped imports do not have intentional side effects?

**Comment by Rich-Harris** [comment]
It'll still import the modules, it just skips the bindings, so this...

```js
import { unused } from 'external';

function alsoUnused () {
  unused();
}
```

...becomes this...

```js
import 'external';
```

...instead of this:

```js
import { unused } from 'external';
```

**Comment by kzc** [comment]
Ah okay. I misread the patch.

Perhaps Rollup could support an option to drop unreferenced imports like this:
```js
import { unreferenced } from 'external';
```
and keep imports like this:
```js
// Import an entire module for side effects only, without importing any bindings.

import "my-module";
```
as per https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/import

But then again, the warning might be enough to get the user to drop the import themself.

**Comment by Rich-Harris** [comment]
Not a bad idea. Will leave it in the nice-to-have pile for now until someone asks for it though, in the interests of getting through the backlog

**Comment by kzc** [comment]
Upon more thought, nothing in the ES2015 spec precludes `import { unreferenced } from 'external';` from having a side effect so it can't safely be dropped. So the idea wouldn't work.

**Pull request merged**
