### PR TITLE
Annotate frozen namespaces with #__PURE__ comment

### LINKED ISSUE #2042: Annotate frozen namespaces with #__PURE__
Would be super cool to have frozen namespaces annotated with `#__PURE__`. By adding #__PURE__ to the call to `Object.freeze()` it could get removed by UglifyJS when the namespace object is not used. I don't think there is any downside of adding those annotations.

This issue is also not about handling `#__PURE__` just like UglifyJS does - it's purely about adding this annotation to the generated code. 

I don't think rollup generates any extra runtime calls than this one, but if it does others could get considered for this too.

Reference [here](https://github.com/rollup/rollup/pull/2041#issuecomment-371906992)

cc @lukastaegert @kzc

### PR DESCRIPTION
**Pull request by Andarist**
fixes #2042

### CODE REVIEW

**Comment by kzc** [comment]
I'm trying to envision a real life use case. Will any of these tests produce a pure annotated `Object.freeze` call that will be dropped by uglify? Since all the references appear to be used, I suspect not.

**Comment by Andarist** [comment]
This particular annotation is targeting consumers' of splitted libraries.
```js
// library/index.js
import * as selectors from './chunk1.js'
console.log('selectors', selectors)
```

```js
// library/selectors.js
export { selectorA, selectorB }  from './chunk1.js'
```

```js
// library/chunk1.js
export const selectorA = () => {}
export const selectorB = () => {}

export const selectors = /*#__PURE__*/Object.freeze({
  selectorA,  
  selectorB,  
})
```

```js
// ./consumer.js
import { selectorA } from 'library/selectors'
selectorA()
```

**Comment by kzc** [comment]
I see the use case now - deep linked named imports from chunked libraries.

**Comment by guybedford** [comment]
@Andarist thanks for clarifying the use case.

It sounds like if we could get treeshaking to work for this use case - https://rollupjs.org/repl?version=0.56.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIweCUyMCUzRCUyME9iamVjdC5mcmVlemUoJTdCJTIwYXNkZiUzQSUyMCdhc2RmJyUyMCU3RCklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE then that would also solve the issue right?

//cc @lukastaegert any ideas?

**Comment by kzc** [comment]
> It sounds like if we could get treeshaking to work for this use case then that would also solve the issue right?

As long as side effects are taken into consideration in a freeze of an object literal, sure:
```js
const unused = Object.freeze({a: side_effect()});
```

**Comment by kzc** [comment]
Adding the pure annotation comment has one advantage - the rolled up chunked library will allow for webpack with scope hoisting to drop the unnecessary call. The ultimate consumer of the library may not be using Rollup.

**Comment by Andarist** [comment]
> the rolled up chunked library will allow for webpack with scope hoisting to drop the unnecessary call. The ultimate consumer of the library may not be using Rollup.

Exactly what I'm after with this PR :)

**Comment by lukastaegert** [comment]
@guybedford Yes, I already have plans how to get this to tree-shake, just didn't get to it yet. Doesn't make sense IMO doing this without refactoring all of the global handling to create a general solution for globals the only side-effect of which would be to modify (or call) one of their arguments. In this specific situation, the proper logic would include the statement if the argument is an included variable (or of course if the variable it is assigned to is used).

Otherwise, code-splitting is not even necessary for this to be useful. You could also export a namespace import from an external dependency as an object. All users of uglify would then benefit from this change.

**Comment by Andarist** [comment]
I've rebased my branch against latest master, this could be shipped with @guybedford's namespace improvements PR (if you decide it's ready)

**Pull request merged**
