### PR TITLE
Obscure bin require

### PR DESCRIPTION
**Pull request by guybedford**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description

This would allow jspm 2 support for installing Rollup, as it currently chokes on this require not resolving (since source-map-support is not a dependency).

Would be a great help for compatibility.

### CODE REVIEW

**Comment by guybedford** [comment]
(using `require && require` as this is not currently optimized by treeshaking)

**Comment by shellscape** [comment]
Looks good to me, but also looks like TypeScript isn't happy for some weird reason on Node 6

**Comment by guybedford** [comment]
That seems to be an unrelated CI failure, also in other recent PRs for some reason....

**Comment by lukastaegert** [comment]
Not sure I totally get it. Isn't it possible to write some kind of test? I believe for `function` tests, it is possible to override `require`.

**Comment by lukastaegert** [comment]
Otherwise we *will* break it when tree-shaking improves and not notice it.

**Comment by lukastaegert** [comment]
> That seems to be an unrelated CI failure, also in other recent PRs for some reason....

See #2488

**Comment by guybedford** [comment]
I've actually decided this is a common enough pattern that I will just pattern detect `try { require('x') } catch (e) {}` entirely. No need for this then.

**Pull request closed without merging**
