### PR TITLE
Make pretty-bytes a devDependency, update dependencies, fix linting of test config

### PR DESCRIPTION
**Pull request by lukastaegert**
pretty-bytes is bundled by rollup and should therefore be a devDependency so that users do not have this in their node_modules unnecessarily.

When also updating some other dependencies it turned out that our eslintignore file successfully prevented test configs from being linted so I fixed this as well and fixed the linting errors.

### CODE REVIEW

**Comment by Andarist** [comment]
What's the reasoning behind bundling this into the CLI bundle? Shouldnt this just be kept as dependency?

**Comment by lukastaegert** [comment]
Exactly. We do this for all dependencies. Thus they also get tree-shaken to what we actually need and we keep node_modules clean.

**Comment by Andarist** [comment]
Is "keeping node_modules clean" a real gain on its own? 🤔 Maybe I'm thinking too much from web/browsers perspective but in general I would say that trade-off of having dependencies deduplicated is over maybe slightly faster startup is better + security updates etc might get installed automatically for not bundled deps (but that's ofc a double edged sword as having it other way around might cause bug or accidential breaking change to get installed).

Just thinking out load, wanting to hear out ur point on view on this 😉

**Comment by lukastaegert** [comment]
It may be a valid point but I think it makes sense for rollup. Dependency deduplication may save you a few bytes on your hard drive—if the versions match well enough—but it will probably not bring any further advantages as it is unlikely that e.g. someone is bundling rollup together with some of its dependencies into a common bundle. Thus I would rather have the faster startup time and overall smaller size via scope-hoisting and tree-shaking.

Also this makes it easy to distribute it to the browser with minimal changes (though this is not as important for the CLI bundle of course).

And talking about automatic updates via version drift and security, I think Webpack can tell a story about this :)

**Comment by lukastaegert** [comment]
Expanding on this further, bundling our dependencies gives us full control over them so e.g. rollup@0.63.5 will be identical for everyone independent of e.g. the used package manager version.

**Comment by guybedford** [comment]
Put it this way - if every package on npm did what Rollup is doing, this would result in larger downloads, and slower execution due to large amounts of source being double-parsed (no shared dependencies).

So it's a do as we say not as we do sort of thing....

**Pull request merged**
