### PR TITLE
Cannot read property 'node' of undefined when declaration is SyntheticGlobalDeclaration

### PR DESCRIPTION
**Pull request by QiV**
Could not catch this in mocha tests. it seems like to crash only at compile time.

### CODE REVIEW

**Comment by TrySound** [comment]
@QiV Can you produce test case?

**Comment by TrySound** [comment]
Do you mean compile rollup itself? Or when rollup compile something?

**Comment by QiV** [comment]
Sorry for delay.
Rollup crashes when i try to compile my code, which exports global vars (window, document, location,  etc.)
I`ll try to produce this case at new repo a little bit later.

**Comment by QiV** [comment]
git clone git@github.com:QiV/test-rollup.git && npm i && npm test

**Comment by QiV** [comment]
Is it reproducable? Anything else I can do?

**Pull request closed without merging**
