### PR TITLE
chor(package.json): allow to import modules from dist without extension

### PR DESCRIPTION
**Pull request by frank-dspeed**
Allow to import modules without extension from dist see: https://github.com/rollup/rollup/pull/4436#issuecomment-1066403067

This should address your concerns in the comment and should fix your api problem.

when there are export or import issues with that patterns simply ping me i am really deep into all this resolve stuff. 

This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### CODE REVIEW

**Review by lukastaegert — CHANGES_REQUESTED** [review]
This unfortunately breaks imports WITH extensions, so this is not an option

**Comment by frank-dspeed** [comment]
@lukastaegert it does not tell me which extension do you want to enable!

**Comment by frank-dspeed** [comment]
for your info the most specific rule gets used like with css so i can add rules to cover that.

**Comment by frank-dspeed** [comment]
@lukastaegert list the extensions i looked into that and .d.ts is still useable as typescript resolves with its own algo and the package.json does also work i discovered no problems 

you should test it if you want i can add .json .d.ts but i see no reason to do so

**Review by frank-dspeed — COMMENTED** [review]
* maps expose nested subpaths as it is a string replacement syntax only.

All instances of * on the right hand side will then be replaced with this value, including if it contains any / separators.

so * acts as ** already

The property of exports being statically enumerable is maintained with exports patterns since the individual exports for a package can be determined by treating the right hand side target pattern as a ** glob against the list of files within the package. Because node_modules paths are forbidden in exports targets, this expansion is dependent on only the files of the package itself.

replace 
```
"./dist/**/*.js": "./dist/**/*.js", with "./dist/*.js": "./dist/*.js",
```
this is not a real glob pattern nodejs allows only one * per left or right hand side!


as you like docs: https://nodejs.org/api/packages.html#subpath-patterns

**Comment by frank-dspeed** [comment]
I need to say again so that some one who comes to this issue that the .d.ts export and the .json export should not be needed as we have only our linked types and the package.json it self will never be external imported via nodejs so it makes no sense to give it a nodejs loading rule

```
    "./dist/*": "./dist/*.js",
    "./dist/*.js": "./dist/*.js",
```
this are the only needed exports to cover all imports of all .js files with and without extension as they are string replacements with rules where the most specific gets used. so if some one writes something with .js at the end the secund gets used if he writes something without .js the first gets used.

typescript got own resolve algos that do not care for subpath patterns they are not even implemented but will get implemented and will workaround that!

but the extra .d.ts rules and .json rules are not conflicting or blocking anything so they are harmless but simply not needed.
they will simply never get triggered

**Comment by lukastaegert** [comment]
Did you actually try that out? Because the pattern `"./dist/*.js": "./dist/*.js"` does not work for me.

**Comment by guybedford** [comment]
@lukastaegert it's supported in Node.js 14+ only, I would only recommend shipping `*.js` patterns once 12 goes EOL at the end of April.

**Comment by frank-dspeed** [comment]
@lukastaegert i would vote for droping the exports fild until this can get merged as there are also cases with require without tests the most compatible way is to simply drop the subPath Patterns complet and go only with aliases import and require drop everything else this will be the most compatible way that allows at last extension less imports when require is used.

**Comment by guybedford** [comment]
@frank-dspeed it is just the pattern trailers that are not supported - `"./dist/*.js": "./dist/*.js"` Without the extension it is supported fine back to Node.js 12 - `"./dist/*": "./dist/*"`.

**Comment by lukastaegert** [comment]
Considering all options, I would prefer to leave the logic as it is for now.

**Pull request closed without merging**
