### PR TITLE
Module render performance tweak

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/rollup/rollup/issues/723

### CODE REVIEW

**Comment by ericf** [comment]
This was not safe, and started breaking my build.

Previously with `v0.34.3` my `format: 'es'` build worked correctly, then it started failing after this change. It was changing `React.createElement` to `React__default.createElement` but never defining `React__default`.

**Comment by TrySound** [comment]
@ericf Thank you for report. Will be fixed ASAP.

**Comment by TrySound** [comment]
@ericf Can you produce some minimal test case? Can't figure out how to build your repo on windows.

**Comment by ericf** [comment]
@TrySound I figured out the issue, and it makes sense why this change would cause it. I am calling `rollup()` once, but calling `bundle()` twice. I created this script before the targets feature was added: https://github.com/yahoo/react-intl/blob/master/scripts/build-lib.js#L31-L41

I will update my script to be more correct to fix this.

**Comment by yairEO** [comment]
@ericf - well? did the merge break your code or all is good?

**Comment by Rich-Harris** [comment]
@yairEO the change in this PR was undone in https://github.com/rollup/rollup/commit/1d7c853ce6fabec207401a53d8210ea25f08d72e

**Pull request merged**
