### PR TITLE
Throw warnings from plugins

### LINKED ISSUE #1501: Warnings can only be thrown from transform function of plugins
It would be usefull to be able to throw warnings from all functions of a plugin like it seem be the case with `this.warn` in the `transform` function

### PR DESCRIPTION
**Pull request by CodeTroopers**
Fix #1501 

Documentation must be updated with :
Plugin can throw warning with 
```
import { Warning } from 'rollup'

Warning.print({
     code: MY_PLUGIN_WARNING,
     message: 'This plugin throw a warning'
});
```

### CODE REVIEW

**Comment by lukastaegert** [comment]
Hi @CodeTroopers, thank you for your PR and sorry you had to wait so long 😕.
I really like the idea that all plugin functions should be able to throw warnings. However, I am not so happy about this solution (which I assume was also the reason why there was so little communication from others yet).
* This adds a new export to rollup that IMO is only interesting to plugins but not to general consumers of the Node API
* From the perspective of data flow, this forces plugins to directly depend on rollup. I really do  not like this at all as it breaks encapsulation and can make future refactoring and uses of rollup much more difficult. Also it is impossible to guarantee they are even importing the right version of rollup, e.g. they could be run from a fork under a different name.
* Also from this perspective, IMO Rollup should provide plugins with everything they need in the form of callbacks, not exports. I.e. I would prefer if we change each handler to grant access to `this.warn`. To avoid code duplication, this could be done internally by a function that creates a "plugin context" containing the `warn` handler and in the future possibly other handlers. If we do it this way, we might also in the future provide a way to deliberately suppress warnings from certain stages or plugins etc.

What to you think? Do any others have an opinion on this?

**Comment by CodeTroopers** [comment]
Yes, I entirely agree with you. Plugins didn't have a defined context (or I have not seen it) and I did not want to break all the mechanism of plugins. This PR covers just my need with a minimum of modifications but it's not the good solution. I let the experts of Rollup be in charge of the design of the API

**Comment by lukastaegert** [comment]
Still, I really value your effort here! The question is how we proceed with this PR. Another more internal issue I see is that you are modifying the `Warning` base class in https://github.com/CodeTroopers/rollup/blob/1ace61c10ec0595d1c4c329e41db920b473c03bd/src/rollup/index.js#L145 to change the `onwarn` handler which could cause strange interdependencies when multiple configurations with different `onwarn` handlers are used.

As I think this requires a markably different approach from this PR, I would suggest to close this PR for now to signify to others that the underlying issue still warrants a resolution. If you want to have another go under the constraints I outlined above, I would very much welcome this! (I.e. put the `warn` handler on the `this` context, keep it bundle specific internally)

**Comment by CodeTroopers** [comment]
@lukastaegert I close the PR but i have not enough time to work on a full solution

**Pull request closed without merging**
