### PR TITLE
Fix template string

### PR DESCRIPTION
**Pull request by styfle**
This PR contains:
- [x] bugfix

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)

Breaking Changes?
- [x] no

List any relevant issue numbers:

### Description

This error message should probably use a template string so that `pluginName` is not a literal but it's value is printed instead.

### CODE REVIEW

**Comment by styfle** [comment]
Should I add one more assert to check the error message string includes the plugin name? https://github.com/rollup/rollup/blob/138033ee89254f7d692c2aee809988107b46e564/test/hooks/index.js#L846

**Comment by shellscape** [comment]
@styfle nice catch! yes, please do add a test. definitely would not hurt.

**Comment by styfle** [comment]
@shellscape Done!

**Comment by shellscape** [comment]
thanks!

**Pull request merged**
