### PR TITLE
Fail on duplicating in export * from

### PR DESCRIPTION
**Pull request by TrySound**
Ref #722

### CODE REVIEW

**Comment by TrySound** [comment]
What's wrong with it?

**Comment by eventualbuddha** [comment]
Is this spec behavior? Last I knew this was allowed.

**Comment by TrySound** [comment]
Yeah, forgot to add it optionally. But is there a side effect to fail tests?

**Comment by Rich-Harris** [comment]
What if this was a warning instead? I can't imagine anyone is likely to set `failOnExportAllDup` just for the hell of it – if it caused a warning but didn't fail, then people would be more likely to find potential bugs without it causing the build to fail unnecessarily.

(test was failing because another one was out of date btw – have fixed)

**Comment by TrySound** [comment]
Yeah warning is good. But I'd like to have some linting effect to prevent merge or pull request with potential bug. Maybe we could collect all matches and throw them in the end? Also the name of option is not quite good, can you suggest something?

**Comment by TrySound** [comment]
Yeah, `onwarn` is good.

**Comment by TrySound** [comment]
Oh, heh :) Didn't realize we already have `onwarn` option ;)

**Comment by Rich-Harris** [comment]
👍  I changed the message to reflect the fact that conflicting namespaces are permitted, if discouraged (previously it said that modules *could not* export the same names, because we were treating it as an error)

**Comment by TrySound** [comment]
Okay. Thanks, Rich.

**Pull request merged**
