### PR TITLE
Port doc changes from #4572 and #4583 to 3.0

### PR DESCRIPTION
**Pull request by berniegp**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description

 - Ports doc changes from #4572 and #4583 to the 3.0 branch.
 - Shortened some code examples to focus on the relevant parts (hope that's ok)
 - The changes from #4584 have _not_ been ported. I expect they will get picked up in a merge with `master`.

### CODE REVIEW

**Comment by lukastaegert** [comment]
Could you lint your changes `npm run lint`?

**Comment by berniegp** [comment]
I rebased my branch on your latest v3.0 rebase.

I also ran `lint` and the only warning is on `cli/samples/symlinked-config/rollup.config.js`. I can push the fix, but it's not related to my changes. Let me know.

**Comment by lukastaegert** [comment]
No, it looks good now. Linting was broken for the previous build, `npm run lint` also runs prettier across your `.md` files and fixes them.

**Review by lukastaegert — APPROVED** [review]

**Comment by lukastaegert** [comment]
This PR has been released as part of rollup@3.0.0-3. Note that this is a pre-release, so to test it, you need to install Rollup via `npm install rollup@3.0.0-3` or `npm install rollup@beta`. It will likely become part of a regular release later.

**Comment by lukastaegert** [comment]
This PR has been released as part of rollup@3.0.0-3. Note that this is a pre-release, so to test it, you need to install Rollup via `npm install rollup@3.0.0-3` or `npm install rollup@beta`. It will likely become part of a regular release later.

**Comment by lukastaegert** [comment]
This PR has been released as part of rollup@3.0.0-4. Note that this is a pre-release, so to test it, you need to install Rollup via `npm install rollup@3.0.0-4` or `npm install rollup@beta`. It will likely become part of a regular release later.

**Pull request merged**
