### PR TITLE
Added Rollup logo in README.md

### PR DESCRIPTION
**Pull request by priyanshurav**
This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description
This PR adds the Rollup logo to README.md

### CODE REVIEW

**Review by lukastaegert — APPROVED** [review]
Looks good to me!

**Review by lukastaegert — CHANGES_REQUESTED** [review]
Except for the changes to the lockfile. While we will likely update to npm 7 soon, I would like you to revert the change for now.

**Comment by priyanshurav** [comment]
@lukastaegert I have now reverted the changes made to the lockfile.

**Comment by priyanshurav** [comment]
@lukastaegert I have now reverted the changes made to the lockfile.

**Review by lukastaegert — APPROVED** [review]

**Pull request merged**
