### PR TITLE
Per output plugins

### LINKED ISSUE #3098: Do not create conflicts between files emitted in `generateBundle` for different outputs
- Rollup Version: 1.20.3
- Operating System (or Browser): Any
- Node Version: 12

### How Do We Reproduce?

Taken from https://github.com/rollup/rollup/pull/2999#issuecomment-528589283:
Note that I did not verify this myself, but I do not want this to go unnoticed cc @wessberg

### Expected Behavior
When creating several outputs and emitting files in `generateBundle` using the `fileName` option, the files are unique to each output and there are not conflicts between outputs.

### Actual Behavior
Apparently, files in later outputs cannot be generated with the same name but will throw a name conflict error.

### LINKED ISSUE #3174: Concurrent generate calls share a mutable plugin driver
- Rollup Version: 1.25.0
- Operating System (or Browser): Any
- Node Version: 12.10

### How Do We Reproduce?

Create a plugin with a `generateBundle` hook that calls `this.emitFile({type: "asset", fileName: "myfile", source: "abc"})`.

Enable the plugin and run rollup on some code with multiple `output` targets. For example with this config file:

```javascript
export default {
  input: "./bar.js",
  output: [
    {
      file: "bar1.js",
      format: "cjs"
    },
    {
      file: "bar2.js",
      format: "esm"
    }
  ],
  plugins: [{
    generateBundle() {
      this.emitFile({type: "asset", fileName: "myfile", source: "abc"})
    }
  }]
}
```

Running rollup will produce this error:

```
[!] (plugin at position 1) Error: Could not emit file "myfile" as it conflicts with an already emitted file.
Error: Could not emit file "myfile" as it conflicts with an already emitted file.
    at error (/home/marijn/tmp/rollup-plugin-typescript2/node_modules/rollup/dist/rollup.js:10162:30)
    at reserveFileNameInBundle (/home/marijn/tmp/rollup-plugin-typescript2/node_modules/rollup/dist/rollup.js:16226:16)
    at FileEmitter.emitAsset (/home/marijn/tmp/rollup-plugin-typescript2/node_modules/rollup/dist/rollup.js:16350:17)
    at Object.FileEmitter.emitFile (/home/marijn/tmp/rollup-plugin-typescript2/node_modules/rollup/dist/rollup.js:16280:29)
    at Object.generateBundle (/home/marijn/tmp/rollup-plugin-typescript2/foo.js:21:12)
    at /home/marijn/tmp/rollup-plugin-typescript2/node_modules/rollup/dist/rollup.js:16635:25
```

Which, as per the discussion in #3150, is not the intended behavior in this case.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #3174 
Resolves #3098

### Description
This is the new big feature I have been working on. It will solve the issues of files emitted from different outputs overwriting each other by giving each output a separate FileEmitter, but more importantly, this will allow different outputs to have different plugins.

Example how this is useful:

```js
// rollup.config.js
import {terser} from 'rollup-plugin-terser';

export default {
  input: 'main.js',
  output: [
    {file: 'bundle.js', format: 'esm'},
    {file: 'bundle.min.js', format: 'iife', plugins: [terser()]},
  ]
};
```

The big advantage is that you can now generate a minified and a non-minified build together without needing to repeat the analysis step, which will be noticeably faster than run rollup twice.

Rules for output plugins:
- They can have the same hooks as regular plugins, BUT
- Hooks run during the build phase will NOT be repeated for them. Instead, a warning is given if a plugin has such hooks. This includes e.g. the `options` hook.
- To gain access to input and output options, the `renderStart` hook will now receive two arguments: `outputOptions` and `inputOptions`.

This is a draft PR as it still lacks any documentation. However, it should be fully useable and I invite everyone to test it via `npm i rollup/rollup#per-output-plugins`.

cc @marijnh

### CODE REVIEW

**Comment by marijnh** [comment]
> this will allow different outputs to have different plugins.

That's wonderful—I needed exactly that earlier today. Thanks for doing this work!

**Comment by Andarist** [comment]
From what I can see this can hook into rendering, but I'm not sure what rendering is - is tree-shaking process? from the prepared input graph to the output one? 

I'm wondering if this would allow me to in example build 2 bundles with process.env.NODE_ENV replaced to "production" and "development" in a single config.

**Comment by lukastaegert** [comment]
Output plugins act only after tree-shaking and chunking are done. Basically what you can do is transform the emitted chunks, add banners/footers etc.

Changing the tree-shaking between outputs would basically mean we need to repeat a lot between outputs and would mostly prevent the possible performance gains.

**Comment by calebeby** [comment]
Thanks Lukas this is an amazing feature :tada:

**Pull request merged**
