### PR TITLE
namespace imports are importing unused exports

### PR DESCRIPTION
**Pull request by kellyselden**
failing test:

```
  1) rollup
       chunking form
         namespace-imports-from-chunks-with-unused-exports
           generates es:

      AssertionError [ERR_ASSERTION]: Unexpected output for main2.js
      + expected - actual

      -import { p, q } from './main1.js';
      +import { p } from './main1.js';

       console.log( p );

      at fileNames.forEach.fileName (test\chunking-form\index.js:84:18)
      at Array.forEach (<anonymous>)
      at recurse (test\chunking-form\index.js:76:20)
      at bundle.write.then (test\chunking-form\index.js:90:11)
      at <anonymous>

  2) rollup
       chunking form
         namespace-imports-from-chunks-with-unused-exports
           generates system:

      AssertionError [ERR_ASSERTION]: Unexpected output for main2.js
      + expected - actual

       System.register(['./main1.js'], function (exports, module) {
        'use strict';
      - var p, q;
      + var p;
        return {
                setters: [function (module) {
                        p = module.p;
      -                 q = module.q;
                }],
                execute: function () {

                        console.log( p );

      at fileNames.forEach.fileName (test\chunking-form\index.js:84:18)
      at Array.forEach (<anonymous>)
      at recurse (test\chunking-form\index.js:76:20)
      at bundle.write.then (test\chunking-form\index.js:90:11)
      at <anonymous>
```

### CODE REVIEW

**Comment by kellyselden** [comment]
generates a file like:

```js
import { p, q } from './main1.js';

console.log( p );
```

**Comment by guybedford** [comment]
Thanks, yes this is a known issue with the code splitting.

**Comment by guybedford** [comment]
(Basically it requires per-module variable usage tracking, while our current tracking is over all modules)

**Comment by shellscape** [comment]
@kellyselden @guybedford @lukastaegert is this PR still valid? If so, what does it need to move forward?

**Pull request closed without merging**
