### PR TITLE
Failling test for #1104

### PR DESCRIPTION
**Pull request by btd**
@Rich-Harris i am really sorry for being that noisy.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Ah, of course, I hadn't considered that case. Is this something you're experiencing in the wild (as opposed to a theoretical issue – still needs fixing, but lower priority)?

**Comment by Rich-Harris** [comment]
Ignore that, just saw your comment on #1104 – it *is* happening in the wild

**Comment by Rich-Harris** [comment]
Added your fix back. Sorry for the confusion, I was careless and didn't read your patch properly. Much better than the crude regex approach

**Comment by btd** [comment]
@Rich-Harris Thank you. Yes i got this issue while working on postcss plugin. I have to write generated sourcemap for css to include it to bundle (css written as string literal).

**Pull request merged**
