### PR TITLE
remove acorn-bigint and acorn-dynamic-import devDenpendencies

### PR DESCRIPTION
**Pull request by LongTengDao**
This PR contains:
- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description

acorn built with bigint and dynamic import internal since 6.2.0 (while rollup depending on acorn ^6.2.1): https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md

(Note: don't update dependency acorn version to 7.0.0 for the moment, until most plugins compatible with that (at least waiting for acorn offcial stage3 plugins), and notice that `import()` has updated to `ImportExpression` in 7.0.0, which maybe need to update in rollup source.)

### CODE REVIEW

**Comment by LongTengDao** [comment]
@lukastaegert Could you figure out why the checks failed? If I missed something intricate, just treat this PR as an issue for refactor request.

**Comment by lukastaegert** [comment]
The PR changes how the acorn import is manifests in the ESM build. There is a special plugin that scans for how the import is written to rewrite it so that the ESM build can be reused properly by ESM aware bundlers. What needs to be done is basically to replace the generated default import (which comes from a poor CommonJS translation) with a namespace import. To that end, the two constants `expectedAcornImport` and `newAcornImport` need to be changed so that they line up with what can be found in the generated bundle.

**Comment by LongTengDao** [comment]
@lukastaegert Thanks for your explanation! I think I can't handle it. I will just leave this as an issue, waiting for someone else to do that.

**Comment by lukastaegert** [comment]
I fixed the import plugin but it appears dynamic imports are no longer recognized with these changes.

**Comment by lukastaegert** [comment]
Ok, seems they were lying about the minimum ECMA version, it needs to be 2020 (or 11) to work, not 10.

**Comment by LongTengDao** [comment]
Oh, 11 is right. I will recorrect the changelog and doc of acorn.

**Pull request merged**
