### PR TITLE
Add Logging API

### LINKED ISSUE #4981: RFC: Logging API
### Feature Use Case

Currently, the only way to log in a structured way from Rollup core is to (ab)use warnings. This turned out problematic for some recent features (especially `experimentalMinChunkSize`), where I wanted to log some status information for the user. The current "workaround" was to log to the console, but this is definitely not the desired goal:
- higher level tools like Vite should be able to filter logs or present them in a visually consistent way
- plugins should be able to add their own logs
- plugins should be able to access and filter logs

### Feature Proposal

I propose to add a new logging API to Rollup. My suggestion is to model it after `onwarn` but with additional plugin support. Similar to warnings, logs should be able to have custom properties that can be parsed by higher level tools to provide better handling, filtering and visual representation. It would have several parts:

### A user-facing `onLog` option

The user can supply an `onLog` function option with mostly the same signature and behavior as `onwarn`:

```ts
interface InputOptions {
	// ...
	onLog?: LogHandlerWithDefault;
}

interface NormalizedInputOptions {
	// ...
	onLog?: LogHandler;
}

type LogHandlerWithDefault = (
	log: GeneratedRollupLog,
	defaultHandler: LogHandler
) => void

type LogHandler = (log: GeneratedRollupLog) => void;

// In generated logs, at least the level is always present
interface GeneratedRollupLog extends RollupLog {
	level: LogLevel;
}

interface RollupLog {
	level?: LogLevel; // This is added for logs
	binding?: string;
	cause?: unknown;
	code?: string;
	exporter?: string;
	frame?: string;
	hook?: string;
	id?: string;
	ids?: string[];
	loc?: {
		column: number;
		file?: string;
		line: number;
	};
	message: string;
	names?: string[];
	plugin?: string;
	pluginCode?: string;
	pos?: number;
	reexporter?: string;
	url?: string;
}

type LogLevel = 'warning' | 'info' | 'debug';
```

Note that only the non-normalized `onLog` option receives the `default` handler. When used from the CLI, Rollup will pass in something that looks reasonable together with other output (and is passed to stderr) while the JavaScript API default handler will probably do a `console.info`, `console.warn` or `console.debug` depending on the log level.

Other high-level tools could similarly use the `options` hook to overwrite the `onLog` handler with their own implementation that passes in their own default handler to any user-provided function.

If an `onLog` function is supplied, it will "swallow" all logs unless they are passed on to the default handler.

All current warnings will also be passed to `onLog` with a level of `warning`, i.e. this can completely replace `onwarn`.

Note that this rich API will also allow logs to have a "position" in a module (as warnings currently have, at least some of them). This could be very useful for logs that are related to code positions.

The `code` property will allow certain types of logs to be identified to e.g. filter certain logs.

The fact that we have a fixed set of possible properties that always have a certain meaning should make it easy to provide a nice representation. I vaguely remember e.g. that there was some criticism that Vite would not always display code positions of warnings properly (but maybe this is fixed already?). In any case, here is how Rollup displays rich warnings (and also reduces the amount of similar warnings displayed): https://github.com/rollup/rollup/blob/master/cli/run/batchWarnings.ts

### Plugin logs

Similar to `this.warn`, there would be a `this.log` plugin context function:

```ts
interface PluginContext extends MinimalPluginContext {
	// ...
	log: (
		log: RollupLog | string,
		options?: {
			pos?: number | { column: number; line: number };
			dedupe?: true // idea to reduce noise?
		}
	) => void;
}
```

If a string is passed or otherwise no `level` is provided, the level would be `info`. Passing a `pos` would make Rollup add additional information to the log similar to `this.warn`, namely `id`, `column` and `line` (which are calculated from `pos` if that one is a number).

### Plugin hook

This would be a new addition.

```ts
FunctionPluginHooks {
	// ...
	onLog: (this: PluginContext, log: GeneratedRollupLog) => false | void;
}
```

The hook would be synchronous (as there could be many logs and sync is faster) and sequential. If a hook returns `false`, then the log is not passed to any further plugins but "swallowed" instead. To "replace" a log, a plugin could use `this.log` with the new log and return `false`. Otherwise, plugins can edit the properties of the log to add additional information and of course process the logs internally in some way.

### Open questions

- Should all logs have a `code`, either as a required property or Rollup adds a default `code` or are we happy with some logs not having a `code`?
- Currently, errors are also kind of logs but with the special effect that there can usually be only one error and that errors abort the build. Should errors also be passed to the logging API before aborting the build? I am currently leaning to "no" because plugins can easily access errors via the `buildEnd` and `renderError` hooks and there is no use to "filter" errors. Alternatively, do we want an "error" log level? Again, I am leaning towards "no" to have only one "kind of error".
- Should we return `false` to filter a log in the plugin hook, or should we instead return `true` or something else?

### RFC

I would be very interested to receive feedback on this one. I did not implement anything yet, but it should be fairly straightforward as it could reuse most of the warning API.

Would be nice if tools like Vite would add their own handling for this API if it is implemented.

cc e.g. @yyx990803 @antfu @patak-dev @marvinhagemeister @sapphi-red and anyone else interested.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
- resolves #4981

### Description
This implements a logging API as outlined in #4981. There are some differences from the outline that I want to highlight, though.

First, there is a new `onLog` input option, that receives three arguments: `level`, `log` and `defaultHandler`. The default handler is again called with two arguments `level` and `log`. If it is not called, the log is filtered, otherwise it is forwarded to `onwarn` if it is a warning and ultimately printed to the console. Here, level is either `warn`, `info` or `debug`. Errors are not passed through the Logging API, but logs can easily be turned into errors by calling the default handler with a level of `error`.

To filter logs by level, there is a new `logLevel` option that supports `warn`, `info, `debug` or `silent`.

Plugins can generate logs by calling either `this.warn`, `this.info`, or `this.debug`. Using separate functions per log level allows us to keep object identities between the generated logs and what is passed to `onLog` while also allowing us to efficiently replace those functions with noop handlers depending on the log level.

Plugins have an `onLog` hook that can easily filter logs by returning false, or emit new/additional logs like any other hook.

The console logs generated by `experimentalMinChunkSize` and `experimentalLogSideEffects` are turned into proper `info` logs with the codes `OPTIMIZE_CHUNK_STATUS` and `FIRST_SIDE_EFFECT`.

Please see the documentation changes for additional information, feedback welcome! cc @patak-dev @sapphi-red @marvinhagemeister @yyx990803 @antfu

#### logLevel

|          |                        |
| -------: | :--------------------- |
|    Type: | `LogLevel \| "silent"` |
|     CLI: | `--logLevel <level>`   |
| Default: | `"info"`               |

Determine which logs to process. See [`onLog`](#onlog) for the available log levels. The default `logLevel` of `"info"` means that info and warnings logs will be processed while debug logs will be swallowed, which means that they are neither passed to plugin [`onLog`](../plugin-development/index.md#onlog) hooks nor the `onLog` option or printed to the console.

When using the CLI, errors will still be printed to the console as they are not processed via the logging system. See the [`--silent`](../command-line-interface/index.md#silent) flag for how to suppress error logs.

#### onLog

|  |  |
| --: | :-- |
| Type: | `(level: LogLevel, log: RollupLog, defaultHandler: LogOrStringHandler) => void;` |

```typescript
type LogLevel = 'warn' | 'info' | 'debug';

type LogOrStringHandler = (
	level: LogLevel | 'error',
	log: string | RollupLog
) => void;

// All possible properties, actual properties depend on log
interface RollupLog {
	binding?: string;
	cause?: Error;
	code?: string;
	exporter?: string;
	frame?: string; // always printed by the CLI
	hook?: string;
	id?: string; // always printed by the CLI
	ids?: string[];
	loc?: {
		column: number;
		file?: string;
		line: number;
	}; // always printed by the CLI if id is present
	message: string; // the actual message, always printed by the CLI
	meta?: any; // add custom plugin properties to logs
	names?: string[];
	plugin?: string; // added by Rollup for plugin logs, only printed for warnings
	pluginCode?: string; // added by Rollup for plugin logs that contain a code
	pos?: number;
	reexporter?: string;
	stack?: string; // url for additional information, always printed by the CLI
	url?: string;
}
```

A function that intercepts log messages. If not supplied, logs are printed to the console, whereby Rollup CLI aggregates certain `"warn"` logs and prints consolidated warnings after the build to reduce noise. This handler is also triggered when using the [`--silent`](../command-line-interface/index.md#silent) CLI option.

The function receives three arguments: the log level, the log object and the default handler. Log objects have, at a minimum, a `code` and a `message` property, allowing you to control how different kinds of logs are handled. Other properties are added depending on the type of log. See [`utils/logs.ts`](https://github.com/rollup/rollup/blob/master/src/utils/logs.ts) for a complete list of built-in errors and logs together with their codes and properties.

If the default handler is not invoked, the log will not be printed to the console. Moreover, you can change the log level by invoking the default handler with a different level. Using the additional level `"error"` will turn the log into a thrown error that has all properties of the log attached.

```js
// rollup.config.js
export default {
	//...
	onLog(level, log, handler) {
		if (log.code === 'CIRCULAR_DEPENDENCY') {
			return; // Ignore circular dependency warnings
		}
		if (level === 'warn') {
			handler('error', log); // turn other warnings into errors
		} else {
			handler(level, info); // otherwise, just print the log
		}
	}
};
```

This handler will not be invoked if logs are filtered out by the [`logLevel`](#loglevel) option. I.e. by default, `"debug"` logs will be swallowed.

Some logs also have a `loc` property and a `frame` allowing you to locate the source of the log:

```js
// rollup.config.js
export default {
	//...
	onLog(level, { loc, frame, message }) {
		if (loc) {
			console.warn(`${loc.file} (${loc.line}:${loc.column}) ${message}`);
			if (frame) console.warn(frame);
		} else {
			console.warn(message);
		}
	}
};
```

#### onLog

|                |                                                        |
| -------------: | :----------------------------------------------------- |
|          Type: | `(level: LogLevel, log: RollupLog) => boolean \| null` |
|          Kind: | sync, sequential                                       |
| Previous/Next: | This hook can be triggered at any time.                |

See the [`onLog`](../configuration-options/index.md#onlog) option for the available `Loglevel` values and the `RollupLog` type.

A function that receives and filters logs and warnings generated by Rollup and plugins before they are passed to the [`onLog`](../configuration-options/index.md#onlog) option or printed to the console.

If `false` is returned from this hook, the log will be filtered. Otherwise, the log will be handed to the `onLog` hook of the next plugin, the `onLog` option, or printed to the console. Plugins can also change the log level of a log or turn a log into an error by passing the log to [`this.error`](#this-error), [`this.warn`](#this-warn), [`this.info`](#this-info) or [`this.debug`](#this-debug) and returning `false`. Note that unlike other plugin hooks that add e.g. the plugin name to the log, those functions will not add or change properties of the log. Additionally, logs generated by an `onLog` hook will not be passed back to the `onLog` hook of the same plugin. If another plugin generates a log in response to such a log in its own `onLog` hook, this log will not be passed to the original `onLog` hook, either.

```js
function plugin1() {
	return {
		name: 'plugin1',
		buildStart() {
			this.info({ message: 'Hey', pluginCode: 'SPECIAL_CODE' });
		},
		onLog(level, log) {
			if (log.plugin === 'plugin1' && log.pluginCode === 'SPECIAL_CODE') {
				// We turn logs into warnings based on their code. This warnings
				// will not be passed back to the same plugin to avoid an
				// infinite loop, but other plugins will still receive it.
				this.warn(log);
				return false;
			}
		}
	};
}

function plugin2() {
	return {
		name: 'plugin2',
		onLog(level, log) {
			if (log.plugin === 'plugin1' && log.pluginCode === 'SPECIAL_CODE') {
				// You can modify logs in this hooks as well
				log.meta = 'processed by plugin 2';
				// This turns the log back to "info". If this happens in
				// response to the first plugin, it will not be passed back to
				// either plugin to avoid an infinite loop. If both plugins are
				// active, the log will be an info log if the second plugin is
				// placed after the first one
				this.info(log);
				return false;
			}
		}
	};
}
```

Like the [`options`](#options) hook, this hook does not have access to most [plugin context](#plugin-context) utility functions as it may be run before Rollup is fully configured. The only supported properties are [`this.meta`](#this-meta) as well as [`this.error`](#this-error), [`this.warn`](#this-warn), [`this.info`](#this-info) and [`this.debug`](#this-debug) for logging and errors.

#### this.debug

|  |  |
| --: | :-- |
| Type: | `(log: string \| RollupLog \| (() => RollupLog \| string), position?: number \| { column: number; line: number }) => void` |

Generate a `"debug"` log. See [`this.warn`](#this-warn) for details. Debug logs always get `code: "PLUGIN_LOG"` added by Rollup. Make sure to add a distinctive `pluginCode` to those logs for easy filtering.

These logs are only processed if the [`logLevel`](../configuration-options/index.md#loglevel) option is explicitly set to `"debug"`, otherwise it does nothing. Therefore, it is encouraged to add helpful debug logs to plugins as that can help spot issues while they will be efficiently muted by default. If you need to do expensive computations to generate the log, make sure to use the function form so that these computations are only performed if the log is actually processed.

```js
function plugin() {
	return {
		name: 'test',
		transform(code, id) {
			this.debug(
				() =>
					`transforming ${id},\n` +
					`module contains, ${code.split('\n').length} lines`
			);
		}
	};
}
```

#### this.info

|  |  |
| --: | :-- |
| Type: | `(log: string \| RollupLog \| (() => RollupLog \| string), position?: number \| { column: number; line: number }) => void` |

Generate an `"info"` log. See [`this.warn`](#this-warn) for details. Info logs always get `code: "PLUGIN_LOG"` added by Rollup. As these logs are displayed by default, use them for information that is not a warning but makes sense to display to all users on every build.

If the [`logLevel`](../configuration-options/index.md#loglevel) option is set to `"warn"` or `"silent"`, this method will do nothing.

#### this.warn

|  |  |
| --: | :-- |
| Type: | `(log: string \| RollupLog \| (() => RollupLog \| string), position?: number \| { column: number; line: number }) => void` |

Using this method will generate warnings for a build, which are logs with log level `"warn"`. See the [`onLog`](../configuration-options/index.md#onlog) option for information about the `RollupLog` type. To generate other logs, see also [`this.info`](#this-info) and [`this.debug`](#this-debug). To generate errors, see [`this.error`](#this-error).

Just like internally generated warnings, these logs will be first passed to and filtered by plugin [`onLog`](#onlog) hooks before they are forwarded to custom [`onLog`](../configuration-options/index.md#onlog) or [`onwarn`](../configuration-options/index.md#onwarn) handlers or printed to the console.

The `warning` argument can be a `string` or an object with (at minimum) a `message` property:

```js
this.warn('hmm...');
// is equivalent to
this.warn({
	message: 'hmm...',
	pluginCode: 'CODE_TO_IDENTIFY_LOG',
	meta: 'Additional plugin specific information'
});
```

We encourage you to use objects with a `pluginCode` property as that will allow users to easily filter for those logs in an `onLog` handler. If you need to add additional information, you can use the `meta` property. If the log contains a `code` and does not yet have a `pluginCode` property, it will be renamed to `pluginCode` as plugin warnings always get a `code` of `PLUGIN_WARNING` added by Rollup. To prevent this behavior, plugins can instead use the normalized `onLog` option passed to the [`buildStart`](#buildstart) hook. Calling this option from a plugin will not change properties when passing the log to plugin `onLog` handlers and `onLog` or `onwarn` handlers.

If you need to do expensive computations to generate a log, you can also pass a function returning either a `string` or a `RollupLog` object. This function will only be called if the log is not filtered by the [`logLevel`](../configuration-options/index.md#loglevel) option.

```js
// This will only run if the logLevel is set to "debug"
this.debug(() => generateExpensiveDebugLog());
```

When used in the `transform` hook, the `id` of the current module will also be added and a `position` can be supplied. This is a character index or file location which will be used to augment the log with `pos`, `loc` (a standard `{ file, line, column }` object) and `frame` (a snippet of code showing the location).

If the [`logLevel`](../configuration-options/index.md#loglevel) option is set to `"silent"`, this method will do nothing.

### CODE REVIEW

**Comment by lukastaegert** [comment]
@dominikg Thanks for the feedback!

**once wrapper**

That is something we could add later, though I am still not convinced how necessary this feature is. It may be nice for debugging a plugin, but for logs that permanently stay in the plugin it should not be difficult to deduplicate within the plugin with a flag. On Rollup side, it would add some complexity that I would like to avoid.

And if we implement it with this chaining style, it would also create runtime overhead as the handler functions need to be recreated for some of the hooks for each invocation and plugin, which also means we need to always add the `once` handler. The effort might be lessened if I ever find the time to switch the context to a Proxy based approach, but I will not pursue this now.

**enabled flag**

I see the utility, but again runtime overhead is something I would like to reduce. I would have a different suggestion to address the same issue: Allow the log functions to receive a function creating the string/object instead of the log itself. Then your example would just become

```js
this.debug(() => expensiveCompute())
// or this.debug(expensiveCompute)
```

and this would just incur a minimal overhead when actually logging instead of needing to create those "enabled" properties every time a transform hook runs.

**debug scopes**

I am not sure I would want to reuse the `DEBUG` environment variable from the `debug` package, but in general, log properties would be the equivalent of scopes.

This is the one idea I really want to push, but maybe I should make this even clearer in the docs: Rollup logs are objects, and you should give logs a `code`, `pluginCode` or other properties to add meta information so that it is easy to identify types of logs.

While you cannot do it from the command line, at the moment you can easily use the `onLog` option to filter for exactly the logs you want to see:

```js
export default {
  //...
  onLog(level, log, handler) {
    if (log.plugin === 'node-resolve' && log.meta.scope === 'my-scope') {
      handler(level, log);
    }
  }
}
```

The `log.meta.scope` is just an example. In the TypeScript type of `RollupLog`, I added a `meta` attribute for adding custom information. The above would only display logs from `node-resolve` with this attribute.

Maybe I should add such an example to the docs.

One could consider turning this filtering into a CLI option, e.g. `--filterLogs "plugin:node-resolve,meta.scope:my-scope"`. Then this could filter for any kind of logs, not only plugin ones, based on their attributes, e.g. `--filterLogs code:MISSING_EXPORT,binding:foo`. What do you think?

**Comment by lukastaegert** [comment]
I have added the ability to use functions as logs and updated the documentation.

**Comment by lukastaegert** [comment]
From my side, everything is finalized now. If there are no further comments, I would like to release it tomorrow.

**Comment by dominikg** [comment]
I like the ability to do it with env vars as you can do that even if rollup is called in a way where you can't pass args to it or would have to edit a config file.

The more generic way to filter logs by prop is nice!

**Comment by lukastaegert** [comment]
> I like the ability to do it with env vars as you can do that even if rollup is called in a way where you can't pass args to it or would have to edit a config file.

Makes sense. I would add this as an additional improvement to not block the initial PR.

**Comment by lukastaegert** [comment]
@gajus This will make side effect logs filterable as they have a code of `FIRST_SIDE_EFFECT` and an `id` property corresponding to the current module.

**Comment by sapphi-red** [comment]
> ```js
> this.debug(() => expensiveCompute())
> ```

How about making `this.debug`/`this.info`/`this.warn` nullable?
Then, the caller can write `this.debug?.(heavycomputation())`.
`heavycomputation` won't be called; you can check it by:
```js
let f = undefined
f?.(console.log('foo'))
```
I don't know which is better in terms of overhead.

**Comment by lukastaegert** [comment]
Interesting idea. It means, however, that every single call needs the `?.` now. That would be a breaking change if we do it with `this.warn`.

**Comment by sapphi-red** [comment]
> That would be a breaking change if we do it with `this.warn`. Of course with the function approach, it is not that easy to polyfill `this.debug.enabled`, but you can still get the log level via the options in the `buildStart` hook.

Ah, that makes sense 👍

**Comment by lukastaegert** [comment]
@dominikg For filtering, see my proposal https://github.com/rollup/rollup/pull/5035

**Pull request merged**
