### PR TITLE
docs: update chat/support links

### PR DESCRIPTION
**Pull request by shellscape**
This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description

We've moved chat to Discord and are closing down the Gitter. This updates all of the links in this repo.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
What's the rationale for using a URL shortener? Seems like an unnecessary point of failure

**Comment by shellscape** [comment]
A friendlier presentation, ease of sharing from memory without looking it up. Discord currently lacks a friendly invite url.

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
Fair enough. Ideally it'd be https://rollupjs.org/chat, like we have with https://svelte.dev/chat, but that's tricky with a statically exported site (it'd work, sort of, because it just creates a page with `<script>location.href = 'blah'</script>` but that's not ideal). Maybe that'd make sense once we release SvelteKit and it's possible to make `/chat` a serverless function that redirects while everything else is static

**Comment by shellscape** [comment]
Could we just use a meta redirect?

**Comment by Rich-Harris** [comment]
Oh shit, I had no idea such a thing existed. Yeah, if we added a `/chat/index.html` file to https://github.com/rollup/rollupjs.org/tree/master/static containing

```html
<meta http-equiv="refresh" content="0;url=http://discord.com/whatever"
```

then it _should_ Just Work?

**Pull request merged**
