### PR TITLE
[WIP] chore(deps): switch to yargs-parser lib

### LINKED ISSUE #3376: [CLI]: Switch over to a less verbose argument parser library
### Expected Behavior / Situation
As of now the CLI depends on `minimist` for the purpose of argument parsing which isn't actively maintained anymore. Switching over to any of the better solutions, say `commander.js` would be a better idea.

### Actual Behavior / Situation
Consumes an `arg-parser library` which is no longer actively maintained.

### Modification Proposal
Switch over to a better argument parser library.

### PR DESCRIPTION
**Pull request by jamesgeorge007**
This PR contains:
- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description
Switch over to `yargs-parser` for the purpose of argument parsing. Closes #3376

### CODE REVIEW

**Comment by lukastaegert** [comment]
It seems Rollup CLI is very much broken with this update, see the test results. Can you try to fix this?

**Comment by jamesgeorge007** [comment]
```md

[!] ReferenceError: path is not defined
ReferenceError: path is not defined
    at external (/home/circleci/project/cli/run/loadConfigFile.ts:24:24)
    at configExternal.function.rest (/home/circleci/project/src/utils/mergeOptions.ts:81:5)
    at ModuleLoader.args [as isExternal] (/home/circleci/project/src/ModuleLoader.ts:52:52)
    at ModuleLoader.<anonymous> (/home/circleci/project/src/ModuleLoader.ts:202:9)
    at Generator.next (<anonymous>)
    at /home/circleci/project/node_modules/tslib/tslib.es6.js:73:71
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/circleci/project/node_modules/tslib/tslib.es6.js:69:12)
    at ModuleLoader.resolveId (/home/circleci/project/dist/rollup.js:12187:22)
    at ModuleLoader.<anonymous> (/home/circleci/project/src/ModuleLoader.ts:247:39)
```

This is what the CI complains about.

**Comment by lukastaegert** [comment]
Looks non-trivial. It seems like the presence of yargs-parser is messing up the path import. You can see this when you inspect dist/bin/rollup. Not sure how this is even possible, might be something messed up by the CommonJS plugin. This will require some digging.

**Comment by lukastaegert** [comment]
Seems like using named imports for 'path' fixes it. Now there is only one broken test that needs further inspection. Basically it seems that config files can no longer edit the command arguments.

**Comment by jamesgeorge007** [comment]
@lukastaegert thanks for the help :clap:

**Pull request merged**
