### PR TITLE
fix: Wrong namespace property definition

### LINKED ISSUE #5603: Wrong namespace property definition when namespaced `output.name` with first-level reserved key.
### Rollup Version

v4.20.0

### Operating System (or Browser)

macOS / Chrome

### Node Version (if applicable)

Does not apply

### Link To Reproduction

https://rollupjs.org/repl/?version=4.20.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q25pbXBvcnQlMjAlN0IlMjBqb2luJTIwJTdEJTIwZnJvbSUyMCdub2RlJTNBcGF0aCclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGN1YmUoNSkpJTNCJTIwJTJGJTJGJTIwMTI1JTVDbmpvaW4oJ2EnJTJDJTIwJ2InKSU1Q25leHBvcnQlMjBkZWZhdWx0JTIwam9pbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZXhwb3J0cyUyMiUzQSUyMm5hbWVkJTIyJTJDJTIyZXh0ZW5kJTIyJTNBZmFsc2UlMkMlMjJmb3JtYXQlMjIlM0ElMjJpaWZlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiUyMm5vZGUlM0FwYXRoJTIyJTNBJTIyMSUyMiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJ0b1N0cmluZy52YWx1ZU9mLmhlbGxvJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==

### Actual Behaviour

```js
this[undefined] = this[undefined] || {};
this[undefined].valueOf = this[undefined].valueOf || {};
this.toString.valueOf.hello = ...
```

### Expected Behaviour

```js
this.toString = this.toString || {};
this.toString.valueOf = this.toString.valueOf || {};
this.toString.valueOf.hello = ...
```

Or maybe throw an error 🤔 (?) It would be great to create a warning since it is an override to standard APIs, but it is not a illegal action.

These reserved keys include: `toString`, `valueOf`, etc.

### PR DESCRIPTION
**Pull request by thirumurugan-git**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

- resolves #5603

### CODE REVIEW

**Comment by thirumurugan-git** [comment]
@lukastaegert / @TrickyPi Could you review this pull request?

**Comment by TrickyPi** [comment]
Thanks for your contribution, It would be great if you can add specific tests for this fix!

**Comment by thirumurugan-git** [comment]
@TrickyPi / @lukastaegert I've added the test for the fix. Please review.

**Comment by lukastaegert** [comment]
Looks good to me, but you will need to run `npm run lint` once locally and commit the fixes 😉. Thanks for adding the tests!

**Review by lukastaegert — APPROVED** [review]

**Comment by thirumurugan-git** [comment]
@lukastaegert done! 😉

**Comment by thirumurugan-git** [comment]
@lukastaegert Can you approve the workflow?

**Review by lukastaegert — APPROVED** [review]

**Pull request merged**
