### PR TITLE
Tracks side effects of thenables

### LINKED ISSUE #4102: thenables in object literals erroneously dropped with accompanying async/await/Promise
- Rollup Version: rollup v2.50.3
- Operating System (or Browser): n/a
- Node Version (if applicable): v16.1.0

This is an obscure corner of the ECMAScript specification - thenables are similar to Promises:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve#resolving_thenables_and_throwing_errors

### Repro

[2.50.3 REPL](https://rollupjs.org/repl/?version=2.50.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZWZmZWN0cyUyMCUzRCUyMCU1QiU1RCUyQyUyMGVmZmVjdCUyMCUzRCUyMHglMjAlM0QlM0UlMjBlZmZlY3RzLnB1c2goeCklM0IlNUNuUHJvbWlzZS5yZXNvbHZlKCU3QiU1Q24lMjAlMjAlMjAlMjB0aGVuKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwZWZmZWN0KDEpJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lN0QpJTNCJTVDbihhc3luYyUyMGZ1bmN0aW9uKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHRoZW4oKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBlZmZlY3QoMiklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCU3RCUzQiU1Q24lN0QpKCklM0IlNUNuKGFzeW5jJTIwZnVuY3Rpb24oKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBhd2FpdCUyMCglN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdGhlbiUzQSUyMGZ1bmN0aW9uKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwZWZmZWN0KDMpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QpJTNCJTVDbiU3RCkoKSUzQiU1Q24oYXN5bmMlMjBmdW5jdGlvbigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGF3YWl0JTIwKCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBnZXQlMjB0aGVuKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwZWZmZWN0KDQpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCgpJTIwJTNEJTNFJTIwZWZmZWN0KDUpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QpJTNCJTVDbiU3RCkoKSUzQiU1Q24oYXN5bmMlMjBmdW5jdGlvbigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGF3YWl0JTIwKCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0aGVuKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwZWZmZWN0KDYpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QpJTNCJTVDbiU3RCkoKSUzQiU1Q24oYXN5bmMlMjBmdW5jdGlvbigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGF3YWl0JTIwYXdhaXQlMjAoJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHRoZW4ocmVzb2x2ZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmVzb2x2ZSglN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdGhlbigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGVmZmVjdCg3KSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTdEKSUzQiU1Q24lN0QpKCklM0IlNUNuYXN5bmMlMjBmdW5jdGlvbiUyMGFjdGlvbih4KSUyMCU3QiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjB4JTNCJTVDbiU3RCU1Q25hY3Rpb24oJTdCJTdEKSUzQiUyMCUyRiUyRiUyMG5vJTIwc2lkZSUyMGVmZmVjdHMlMjAtJTIwbWF5JTIwYmUlMjBkcm9wcGVkJTVDbnZhciUyMHByb21pc2UlMjAlM0QlMjBhY3Rpb24oOCklM0IlNUNuYWN0aW9uKCU3QiU1Q24lMjAlMjAlMjAlMjB0aGVuKHN1Y2Nlc3MlMkMlMjBmYWlsKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBzdWNjZXNzKGVmZmVjdCg5KSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU3RCklM0IlNUNucHJvbWlzZS50aGVuKHglMjAlM0QlM0UlMjBlZmZlY3QoeCkpJTNCJTVDbmFjdGlvbiglN0IlNUNuJTIwJTIwJTIwJTIwdGhlbihyZXNvbHZlKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXNvbHZlKCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0aGVuKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY29uc29sZS5sb2coZWZmZWN0cy5qb2luKCU1QyUyMiUyMCU1QyUyMikpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QpJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lN0QpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

```
$ cat then.js
const effects = [], effect = x => effects.push(x);
Promise.resolve({
    then() {
        effect(1);
    }
});
(async function() {
    return {
        then() {
            effect(2);
        }
    };
})();
(async function() {
    await ({
        then: function() {
            effect(3);
        }
    });
})();
(async function() {
    await ({
        get then() {
            effect(4);
            return () => effect(5);
        }
    });
})();
(async function() {
    await ({
        then() {
            effect(6);
        }
    });
})();
(async function() {
    await await ({
        then(resolve) {
            resolve({
                then() {
                    effect(7);
                }
            });
        }
    });
})();
async function action(x) {
    return x;
}
action({}); // no side effects - may be dropped
var promise = action(8);
action({
    then(success, fail) {
        success(effect(9));
    }
});
promise.then(x => effect(x));
action({
    then(resolve) {
        resolve({
            then() {
                console.log(effects.join(" "));
            }
        });
    }
});
```

### Expected Behavior

```
$ cat then.js | node
4 1 2 3 5 6 9 8 7
```

### Actual Behavior

```
$ cat then.js | rollup --silent | node
$ 
```
```
$ cat then.js | rollup --silent
const effects = [], effect = x => effects.push(x);
async function action(x) {
    return x;
}
var promise = action(8);
promise.then(x => effect(x));
```

**Edit 2:** test case was further refined.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #4102 

### Description
This handles side-effects that happen because async functions and Promise utility functions access the `then`  property of thenables. This happens by deoptimizing the global Promise helpers for now until we find a better solution. Async functions are also mostly deoptimized except if their return value has a side effect free `then` property, the same for awaited values.

While this may seem drastic, I would expect that most promise chains contain side effects anyway as they wrap some IO or other external process so not many people would notice this. It also fixes the last remaining issue we had with es6shim.

### CODE REVIEW

**Comment by kzc** [comment]
> This happens by deoptimizing the global Promise helpers for now until we find a better solution.

+1

Correctness is always the way to go.

**Comment by stefcameron** [comment]
@lukastaegert Hi, 👋 , unfortunately, this is again another patch that breaks our builds by introducing unnecessary code from what Rollup now thinks is a side effect.

**Comment by stefcameron** [comment]
> @lukastaegert Hi, 👋 , unfortunately, this is again another patch that breaks our builds by introducing unnecessary code from what Rollup now thinks is a side effect.

Sorry, spoke too soon. It's either #4111, #4112, or #4113 in the `2.50.4` patch that's causing an unintended inclusion of a library that does not have any side effects.

**Comment by stefcameron** [comment]
Based on the title, and some of our code, I'm going to guess it's #4113 so I will continue this over on #4113.

**Comment by shellscape** [comment]
@stefcameron hey hey, really appreciate the enthusiasm, but please use the Edit Reply capability rather than multiple replies in quick succession.

**Comment by stefcameron** [comment]
Sorry for the noise, just not fun having a build break as a result of a __patch__ update that suddenly treats existing code as having side effects when it doesn't, but I was able to figure out what the issue was. I'm still not sure if this is Rollup incorrectly identifying something as being side effectful, or if it's Rollup finding existing code may have side effects it didn't realize it may have had in past versions (since I understand that can be hard to determine), so I'm not sure how to repro.

**Comment by lukastaegert** [comment]
> Sorry for the noise, just not fun having a build break as a result of a patch update

In general I hope you will understand that we cannot make guarantees for the exact generated code even in patch releases. As we fix bugs, code may be rearranged or even some "wrong" code may be included.

For your particular issue, there was indeed still some room for improvement as the new deoptimization did  not respect `propertyReadSideEffects: false`. Maybe #4119 resolves your issue.

**Comment by stefcameron** [comment]
@lukastaegert Of course, I understand it's hard, there are no guarantees, and I appreciate your work nonetheless. I maintain a few OSS packages myself, albeit smaller ones than Rollup, and it's hard when you're serving "the world". Still, it's a patch, and in Semver, that does come with a level of hope of non-breakage, and I've had Rollup patches fail on me before due to bugs introduced.

This time, though, it's not so clear if it's a Rollup bug, or if it's a result of Rollup fixing a bug and now correctly identifying new code that may have side effects when it wasn't before. I've been able to work around (or with) the issue.

**Pull request merged**
