### PR TITLE
Update basic commands to show renamed options

### PR DESCRIPTION
**Pull request by sanbornhilland**
Using the old options shows a warning currently so it seems best to
update the docs to reflect the updated commands that won't
show a warning.

Renamed options are described here:
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32

This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### CODE REVIEW

**Comment by lukastaegert** [comment]
Hi @sanbornhilland, thanks for your contribution!

> Using the old options shows a warning currently

While this is true for options used in config files, this is not true for many options used on the command line such as `--format`. This is also how we communicate it on the website: https://rollupjs.org/guide/en#output-format-f-format

I believe we should change the gist, though, thanks for pointing this out!

Are there situations where you get a warning when using `--format` on the command line? Btw. note that `--name` and `--file` are technically output options as well.

**Comment by lukastaegert** [comment]
Could you give me the exact command that produced the warning?

**Comment by sanbornhilland** [comment]
Yeah for sure. I just copied the command for generating a `iife` and changed the input file. In my case:

`rollup src/index.js --format iife --name "myBundle" --file bundle.js`

And this gave me the following output: 

```
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
--format is now --output.format
```

But digging into it more it looks like I was accidentally using a global version of rollup that I had previously installed and that was on `0.52.1`. After using the `0.66.4` installed in the project the warning doesn't show up. So I guess I jumped the gun on this one.

**Comment by lukastaegert** [comment]
As the gist has been adjusted as well, I guess this can be closed. Feel free to reopen if you disagree.

**Pull request closed without merging**
