### PR TITLE
Remove one try-catch

### PR DESCRIPTION
**Pull request by KSXGitHub**
This PR contains:
- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description

I changed the code from this:

```typescript
function rollup(...): Promise<...> {
  try {
    ...
  } catch (err) {
    return Promise.reject(err);
  }
}
```

to this:

```typescript
async function rollup(...): Promise<...> {
  ...
}
```

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR :beer:

It's super important to explain the motivation for your change. Please add a description to the pull request to explain why you made the change, what benefits it will have moving forward, and why it's better than the code that previously existed.

**Comment by KSXGitHub** [comment]
@shellscape I don't quite understand your question. It's a simple refactoring, what's more do I have to explain?

**Comment by shellscape** [comment]
(I'm sure you know this, but for the sake of being verbose) Refactoring is typically for any number of reasons:

1. the code is inefficient
1. subjective preference of one code structure/paradigm over another or existing
1. preparation for larger/other changes to the codebase
1. elimination of unneeded code

When you present a refactor, you should always explain and justify why the refactor is necessary. That's helpful to maintainers that are evaluating your change, and any onlookers that may be tracking the project's progress. It's also generally considered good form to thoroughly explain a pull request, and why we have a pull request template that encourages people to do so.

**Comment by shellscape** [comment]
@lukastaegert for whatever reason, introducing this change is causing 4 of the tests to fail.

**Comment by lukastaegert** [comment]
I fear we have some blinking tests here, which is unrelated to this PR. I guess I have to look into this first before we merge any PRs. I think there is a race condition that can lead to undeterministic chunking in one test.

**Pull request merged**
