### PR TITLE
Refactor call handling

### LINKED ISSUE #1631: Rollup 0.49.3 regression bundling React
Working with React 15.6.1, I discovered a regression when bundling with Rollup 0.49.3 in the form of a `RangeError: Maximum call stack size exceeded` exception. This gist bundles without error with Rollup 0.49.2.

### Repro
[Gist reproduction](https://gist.github.com/shanewholloway/0300fe7a4f6ce1b200275b880f79a2d2#file-readme-md)

`git checkout https://gist.github.com/shanewholloway/0300fe7a4f6ce1b200275b880f79a2d2`

### Error text:

```node
Error during rollup build: RangeError: Maximum call stack size exceeded
    at Set.values (native)
    at Function.from (native)
    at Node.hasEffectsWhenMutated (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:6900:10)
    at Node.hasEffectsWhenMutated (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:7091:21)
    at declaration.declaration.included.declaration.isParam.declaration.isGlobal.declaration.isExternal.declaration.isNamespace.declaration.assignedExpressions.Array.from.some.node (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:6900:74)
    at Array.some (<anonymous>)
    at Node.hasEffectsWhenMutated (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:6900:55)
    at Node.hasEffectsWhenMutated (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:7091:21)
    at declaration.declaration.included.declaration.isParam.declaration.isGlobal.declaration.isExternal.declaration.isNamespace.declaration.assignedExpressions.Array.from.some.node (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:6900:74)
    at Array.some (<anonymous>)
```

### PR DESCRIPTION
**Pull request by lukastaegert**
So it here is, my second *huge* refactoring PR. This time, the focus is on refactoring the side-effect detection for calls and instantiations, something I had left out of the previous PR. Besides, quite a few issues will be fixed as well: #674, #677, #1187, #1235, #1289, #1391, #1615, #1622

# Improved results
This time the list of tests that have been added/changed and now produce different (and correct) results is REALLY long, so instead I will just list the highlights and you may check for yourself:
* Call expression handling now re-uses the same logic as the rest of rollup to determine if a function body has side-effects. An immediate result is that in `namespace-optimization-computed-string`, the several times re-exported but side-effect free function is now properly removed so the test needed to be adapted :)
* Class declarations and expressions are now properly removed unless there are computed keys in the body that cause side-effects or retrieving the super class has a side-effect
* Class instantiations are now removed if there is no constructor in the class or any super class or the relevant constructor has no side-effects
* Except for import and export declarations for which this remains to be done, all other kinds of declarations have been separated from their concept of a "variable", which is what is stored in the scope now
* This made it possible, that variable re-declarations with "var" or "function" are now recognized properly! See e.g. the test `redeclarations`
* Also, "this"-handling has been refactored. Now, "this" is actually a pseudo-variable on the scope. For now, it only assumes one of two pseudo-values, `UNKNOWN_LITERAL` and `UNKNOWN_ASSIGNMENT` but in the future we might start putting much more information here. The values of "this" are set during `.bind()` time.
* This also means that we can now properly remove nested mutations of "this" expressions if they do not have an effect!
* Generator functions without side-effects are removed as long as iteration has not started yet, see `side-effects-generators`
* New types of scopes like the `FunctionScope` have been added. Now functions actually create two new scopes: one for their parameters and one for their body. This resolves some elusive bugs.
* In the no-treeshake test, the namespace import is now properly replaced. This is handled by actually including ALL nodes when tree-shaking is off which should also resolve other problems related to tree-shaking being disabled.
* A crash with cyclic assignments has been resolved (also fixes #1631)
* Side-effects in default parameter values are now detected properly. Also, there have been many small fixes and improvements to the side-effect detection in pattern assignments and pattern defaults.
* Now if a for-in/of loop uses a global loop variable, this will be properly noted as an effect
* Tree-shaking inside LabeledStatements now works properly

# Other refactorings
* `Node` now has JSDoc comments describing the parameter types, return values and how and when to overwrite the individual methods. This should help others in determining what needs to be changed if they want to fix something via PR.
* hasEffects options have been refactored to be handled via a class that ensures immutability
* Node.hasEffectsWhenCalled is implemented
* VariableDeclarators no longer generate ProxyDeclarations for their children; instead, this has been moved to the individual Identifiers
* Variables on the scope are now usually declared by Identifiers and linked to Identifiers
* All kinds of variables are now derived from `Variable`; variables can be tested for certain effects
* callHasEffects and gatherPossibleValues could finally be removed
* All calls to a function are collected during bind time. For now, this is only used to detect "this" values. In the future, we might want to start collecting call parameters here to determine if a function does not have side-effects for specific parameters. E.g., if a Literal is passed as a parameter it is not a side-effect to mutate it.
* This time, there are many more small commits if anyone wants to follow the refactoring flow…
* And many more!

Have fun & I hope this works for everyone!

### CODE REVIEW

**Comment by lukastaegert** [comment]
For some reason when rebasing/merging, some commits were added twice so the list of commits might look a little bloated...

**Comment by TimvdLippe** [comment]
> Besides, quite a few issues will be fixed as well:

For GitHub to automatically close these issues, you need to explicitly add the keyword `Fixes` in the PR description for each issue number. E.g. Fixes #674, Fixes #677, etc...

**Comment by lukastaegert** [comment]
Actually, "resolve" and "close" also work quite well but I prefer to do it via the individual commits, that way the commit gets linked to the issue 😉

**Comment by lukastaegert** [comment]
But good point, added a comment for #1631.

**Comment by Rich-Harris** [comment]
🎉🎉🎉🎉🎉 

amazing work as ever, thank you!

**Pull request merged**
