### PR TITLE
[v2.0.0] Remove experimentalOptimizeChunks

### LINKED ISSUE #3340: Using `experimentalOptimizeChunks` with static and dynamic imports of the same file
- Rollup Version: 1.29.0
- Operating System (or Browser): Windows 10
- Node Version: 10.15.3

### How Do We Reproduce?

[Code REPL](https://rollupjs.org/repl/?version=1.29.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGNvbW1vbkVudHJ5JTIwZnJvbSUyMCcuJTJGY29tbW9uRW50cnknJTNCJTVDbiU1Q25jb25zb2xlLmxvZygnZW50cnkxJTIwY29tbW9uRW50cnknJTJDJTIwY29tbW9uRW50cnkpJTNCJTVDbiU1Q25pbXBvcnQoJy4lMkZhc3luY0VudHJ5JykudGhlbihhc3luY0VudHJ5JTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCdlbnRyeTElMjBhc3luY0VudHJ5JyUyQyUyMGFzeW5jRW50cnkpJTNCJTVDbiU3RCklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZW50cnkyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGNvbW1vbkVudHJ5JTIwZnJvbSUyMCcuJTJGY29tbW9uRW50cnknJTNCJTVDbmltcG9ydCUyMColMjBhcyUyMGFzeW5jRW50cnklMjBmcm9tJTIwJy4lMkZhc3luY0VudHJ5JyUzQiU1Q24lNUNuY29uc29sZS5sb2coJ2VudHJ5MiUyMGNvbW1vbkVudHJ5JyUyQyUyMGNvbW1vbkVudHJ5KSUzQiU1Q25jb25zb2xlLmxvZygnZW50cnkyJTIwYXN5bmNFbnRyeSclMkMlMjBhc3luY0VudHJ5KSUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhc3luYy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwJ2FzeW5jRW50cnlDb250ZW50JyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJub25FbnRyeUZpbGUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMCdub25FbnRyeUZpbGVDb250ZW50JyUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

Setting `experimentalOptimizeChunks` to true produces the following

### entry1.js
```js
'use strict';

var commonEntry = require('./asyncEntry-be86dbf9.js');

console.log('entry1 commonEntry', commonEntry.commonEntry);
new Promise(function (resolve) { resolve(require('./asyncEntry-3be3e543.js')); }).then(asyncEntry => {
  console.log('entry1 asyncEntry', asyncEntry);
});
```

### entry2.js
```js
'use strict';

var commonEntry = require('./asyncEntry-be86dbf9.js');

console.log('entry2 commonEntry', commonEntry.commonEntry);
console.log('entry2 asyncEntry', asyncEntry.asyncEntry$1);
```

### asyncEntry-3be3e543.js
```js
'use strict';

var asyncEntry = require('./asyncEntry-be86dbf9.js');



exports.default = asyncEntry.asyncEntry;
```

### asyncEntry-be86dbf9.js
```js
'use strict';

var commonEntry = 'commonEntryContent';

var asyncEntry = 'asyncEntryContent';

var asyncEntry$1 = /*#__PURE__*/Object.freeze({
	__proto__: null,
	'default': asyncEntry
});

exports.asyncEntry = asyncEntry;
exports.asyncEntry$1 = asyncEntry$1;
exports.commonEntry = commonEntry;
```

### Expected Behavior
The `entry1.js` file should async require `asyncEntry.js`, and `entry2.js` should statically require `asyncEntry.js`.

### Actual Behavior

In `entry2.js`, the static require statement for `asyncEntry.js` is completely missing. The identifier for `asyncEntry` is still used in the code but without the require statment it's resolving to a global that doesn't exist.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [x] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:
Closes #3340 

### Description
`experimentalOptimizeChunks` has for a long time been a badly tested, unmaintained huge chunk of code that added a lot of complexity. Now that actual issues started popping up for this feature, I would like to remove it for v2.0.0. If we want to reintroduce it later, I would write a completely new version based on moving the chunking to generateBundle first and not merging chunks after they have been created.

### CODE REVIEW

**Comment by frank-dspeed** [comment]
i am for letting it stay and do your reimplamentation in a extra branch while keeping the original implamentation some do relay on it.you can do a none experimentalOtimizeChunks

**Comment by lukastaegert** [comment]
I can let it stay, but really, we cannot give any support for this. `manualChunks` are a much better and well tested way of merging chunks that gives you full control. I recommend to rather switch to using manualChunks for fine-tuning.

**Comment by frank-dspeed** [comment]
@lukastaegert i totally agree with your idea of manual chunks that only should get better documented i am for a deprecation msg added to expermentalOptimized as also a link to a valid replacement example in the documentation using manualChunks

**Comment by LarsDenBakker** [comment]
Id say drop this, there is a lot of work being done to optimize chunking already.

**Comment by lukastaegert** [comment]
I will remove the feature from the 2.0.0 branch for the time being. Effectively what this feature does is creating small manual chunks for very small shared modules, albeit in a fashion that avoids too much unnecessary code being loaded. It can be replicated via manual chunks, albeit with a little work. Once 2.0.0 is settled and the necessary refactorings are done, we can look if we want to reintroduce something like this.

**Pull request merged**
