### PR TITLE
Expose full SHA256 hash in file name placeholders

### PR DESCRIPTION
**Pull request by mislav**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

### Description

Currently, `[hash]` is truncated to 8 characters, so add another placeholder `[fullhash]` to gain access to the untruncated value. The problem with truncated values is that the risk of collisions is larger.

Ideally, `[hash]` would be the full value itself and users could be given some other mechanism of truncating the value to a specific number of characters (e.g. `[hash:8]`), but changing that at this point would break backwards compatibility.

This is WIP and soliciting feedback! Open questions:
* Is `[fullhash]` an OK placeholder name?
* Where should I add tests for this? It's not clear to me where `[hash]` is tested in the first place; many different tests break if I purposely change `[hash]` behavior.

Thank you!

/cc @keithamus

### CODE REVIEW

**Comment by lukastaegert** [comment]
I still wonder how many billions of builds you deploy each day to get a reasonable risk of a hash collision. Previous hashing issues had nothing to do with this. `16^8 = 4.294.967.296`
But of course one can always talk about these things

**Comment by mislav** [comment]
@lukastaegert I agree that the risk of collision is relatively small; but I find it odd that the full checksum is not publicly accessible.

Alternatively, the full checksum could be available to a custom function if https://github.com/rollup/rollup/issues/2585 is implemented.

**Comment by lukastaegert** [comment]
> Alternatively, the full checksum could be available to a custom function if #2585 is implemented.

This would of course be the best solution but for the time being, providing `[fullhash]` as an additional option is ok with me. If you promise to actually use it!

**Comment by lukastaegert** [comment]
Also, it needs to be documented in the "big list of options" in the docs folder.

**Comment by sormy** [comment]
Probably `[hash:X]` could be a better option, where `X` is a number of characters in the hash

**Comment by shellscape** [comment]
@mislav Would you be up for adding the tests requested? It also looks like your fork could use a rebase and a few conflicts need to be addressed.

**Comment by mislav** [comment]
I haven't had time to rebase or to figure out where or how to add the new tests. Other people are welcome to use my branch as the starting point of implementing the same or similar feature. 🙇

**Pull request closed without merging**
