### PR TITLE
[v3.0] Improve interop defaults

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [x] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

List any relevant issue numbers:

### Description
This is a placeholder PR to allow for early discussions while I am working on this last change I want to prepare for Rollup 3. The goal is to improve the defaults of the swamp that is  "interop", i.e. how ESM input behaves when converted to and thrown into a CJS setting.

In Rollup, this is controlled by three options:
* `output.interop`: How to find the default import and handle namespace imports of external dependencies
* `output.exports`: What to do with default exports in your entry points
* `output.esModule`: Whether to add the "__esModule" special property as a hint when generating non-ESM output

The overall goal is to change the defaults so that Node’s interop behaviour is more or less the default behaviour. In Node
* The default export of a CommonJS module is `module.exports`
* Named exports are properties of `module.exports` (if Node detects them. But I think it should be fine if Rollup handles all named exports, otherwise we would need to replicate the exact detection algorithm of NodeJS, which I would want to avoid)
* `__esModule` is a regular export and not added by default
* You can check if a namespace import was from an ES module by checking `namespace[Symbol.toStringTag] === 'Module'`

This means I want to implement the following:

- [x] The new default value for `output.interop` is `"default"`
- [x] The `output.interop` values `true` and `false` are deprecated. However, I think the "duck-typing" interop of `true` is still very useful (i.e. for the default export, we check if there is a `default` property on `module.exports` first and return that, otherwise we return `module.exports`) because it works very well across tools with the only downside that it does not support "default" as a regular property on `module.exports`. Therefore, it will make a return with a new name, probably "compat".
- [x] `output.exports` will remain as it is and default to `"auto"`, which corresponds well to Node's interop where `module.exports` is the default import.
- [x] `output.esModule` will receive a new value "if-default-prop" which will become the new default and only add the flag if there is a default export and it is actually a property "default" on `module.exports`. This situation cannot be mapped to CommonJS in a way that would work with Node interop anyway and users already receive a warning. This should reduce the proliferation of `__esModule` properties in libraries.
- [x] When the default export is a property "default" on `module.exports`, we additionally set `module.exports[Symbol.toStringTag]` to `"Module"` to promote this interop mechanism (if Symbols are permitted)
- [x] For internal namespace object, we improve how checks for `Symbol.toStringTag` are handled so that they can be resolved statically
- [x] We ensure that `Symbol.toStringTag` is added/handled for external namespaces. Check what Node does for namespace imports from CJS

cc @guybedford who may have an opinion on this (and of course everyone else is invited to give feedback as well).

### CODE REVIEW

**Comment by guybedford** [comment]
Great to see this work, thanks for putting thought to these important defaults for Rollup module output to be as compatible as possible within the ecosystem.

> output.exports will remain as it is and default to "auto", which corresponds well to Node's interop where module.exports is the default import.

Excellent! Then we just need Babel to do this as well now! //cc @nicolo-ribaudo 

For `if-default-prop`, am I right in thinking this itself only ever applies to the interop auto mode? If so, perhaps we should validate this option to throw an error if the `output.interop` is not `auto`, to avoid weird compat cases?

Finally it's now worth also keeping an eye on compat with cjs-module-lexer at this point, to avoid possible named exports regressions against Node.js. A simple approach might be to include a test that runs cjs-module-lexer on Rollup output so that future changes don't break named exports detection by mistake.

**Comment by lukastaegert** [comment]
> For if-default-prop, am I right in thinking this itself only ever applies to the interop auto mode

No, it also applies to `named` export mode when there is a default export. Basically it covers exactly the case that cannot be mapped to NodeJS interop.

**Comment by lukastaegert** [comment]
> A simple approach might be to include a test that runs cjs-module-lexer on Rollup output so that future changes don't break named exports detection by mistake.

PR welcome! But I do not think it is critical as Rollup 3 and this PR do not change how exports themselves are written, it only changes import interop and the question whether to add the `__esModule` flag.

**Comment by lukastaegert** [comment]
This is now ready for merge. As one feature, accesses to `Symbol.toStringTag` on namespaces can now be resolved statically, avoiding the need for a dynamic namespace: https://rollupjs.org/repl/?pr=4611&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGZvbyUyMGZyb20lMjAnLiUyRmZvby5qcyclM0IlNUNuJTVDbmlmJTIwKGZvbyU1QlN5bWJvbC50b1N0cmluZ1RhZyU1RCklMjBjb25zb2xlLmxvZygnT0snKSUzQiU1Q25lbHNlJTIwY29uc29sZS5sb2coJ0ZBSUwnKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGZvbyUyMCUzRCUyMCdiYXInJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Pull request merged**
