### PR TITLE
Make it possible for plugin loaders to provide sourcemaps.

### PR DESCRIPTION
**Pull request by Permutatrix**
With this pull request, a loader can return either a `code` string or a `{ code, map }` object, just like a transformer.

The sourcemap can reference whatever sources it wants, or it can provide no sources, in which case it will be assumed to have one source which is the same as the module's ID.

One source can be referenced by multiple modules' sourcemaps; if no sourcemap provides the source content or if some sourcemaps provide source content while others don't, that will work, but an error will be thrown if multiple sourcemaps provide conflicting content for one source.

Sources, source roots, and module IDs are all assumed to function like normal paths. I'm not sure that's a good way to handle them, since a plugin could produce a sourcemap referencing a URI or maybe even some exotic thingamajig none of us have even heard of. [Mozilla's algorithm for finding sourcemap sources is a fair bit more sophisticated.](https://github.com/mozilla/source-map/blob/master/lib/util.js#L125)

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thanks for the PR @Permutatrix. Could you elaborate a bit on why you need this change? Just want to make sure this is a necessary addition before making the sourcemap code even more complicated :)

**Comment by Permutatrix** [comment]
@Rich-Harris People have been asking for [gulp-rollup v2](https://github.com/mcasimir/gulp-rollup/pull/16#issuecomment-156668598) for ages now, and I'm finally implementing it. This puts Rollup in the middle of the build process, so there's no telling what kinds of sources and transformations went into producing the input files. (There could be multiple Rollup steps for all we know. Probably not very useful, but interesting, and certainly impossible without this change if you want sourcemaps.)

**Comment by Rich-Harris** [comment]
You mean to say that Gulp expects each plugin to account for sourcemaps generated by prior transformations, rather than composing them itself? Well, I'm glad I don't use Gulp!

But since some unfortunate people *do* use Gulp, I guess this change makes sense – and is presumably a step towards https://github.com/rollup/rollup/issues/409

**Comment by Rich-Harris** [comment]
Released as 0.31.2. Thanks 👍

**Comment by Permutatrix** [comment]
@Rich-Harris gulp's "thing" is that it doesn't really do anything itself and lets plugins do all the work. It doesn't even know what a sourcemap _is_&mdash;preparing and outputting them is handled by a plugin. Goofballs like me are willing to pay these prices because it makes weird tasks just as easy as normal ones.

**Pull request merged**
