### PR TITLE
Reimplement variable deconflicting logic

### LINKED ISSUE #2680: Flattening imports MUST take care of javascript reserved words
- Rollup Version: v1.2.2
- Operating System (or Browser): Windows 10
- Node Version: 10.15.0

### How Do We Reproduce?
See https://github.com/matthiasg/rollup-reserved-word-issue/

Basically importing like this `import * as express from 'express'` and then using `express.static` does not work since the call is flattened to just `static` which is a reserved word.

### Expected Behavior
The resulting file should either leave the `module.static` call or rename `static` to a non-reserved word

### Actual Behavior
```
index.js → stdout...
[!] Error: The keyword 'static' is reserved
module.js (1:16)
1: export function static(text) {
                   ^
2:   console.log(text)
3: }
Error: The keyword 'static' is reserved
    at error (C:\Users\mgt57\AppData\Roaming\npm-cache\_npx\12096\node_modules\rollup\dist\rollup.js:3597:30)
    at Module.error (C:\Users\mgt57\AppData\Roaming\npm-cache\_npx\12096\node_modules\rollup\dist\rollup.js:14376:9)
    at tryParse (C:\Users\mgt57\AppData\Roaming\npm-cache\_npx\12096\node_modules\rollup\dist\rollup.js:14039:16)
    at Module.setSource (C:\Users\mgt57\AppData\Roaming\npm-cache\_npx\12096\node_modules\rollup\dist\rollup.js:14095:35)
    at C:\Users\mgt57\AppData\Roaming\npm-cache\_npx\12096\node_modules\rollup\dist\rollup.js:17409:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at findNodeScript.then.existing (C:\Users\mgt57\AppData\Roaming\npm\node_modules\npm\node_modules\libnpx\index.js:268:14)
```

index.js
```javascript
import * as module from './module'

module.static('test')
```

module.js
```javascript
export function static(text) {
  console.log(text)
}
```

### LINKED ISSUE #2683: Function parameters ending with ${int} in source aren't escaped, and shadow higher scoped generated variables
Context:
[BuckleScript](https://github.com/BuckleScript/bucklescript) generates variables like `name$1`.

- Rollup Version: v1.1.2
- Operating System (or Browser): All
- Node Version: v10.14.2

### Input

```js
// main.js
import {x} from "./maths.js";

console.log(x(value));
```

```js
// maths.js
var value = "1";

export function x(value$1) { return value$1 + value } 
```

### Expected Behavior

```js
var value$1 = "1";

function x(value$1$1) { return value$1$1 + value$1 }

console.log(x(value));
```

or

```js
var value$1 = "1";

function x(value_$_1) { return value_$_1 + value$1 }

console.log(x(value));
```

### Actual Behavior

```js
var value$1 = "1";

function x(value$1) { return value$1 + value$1 }

console.log(x(value));
```

https://rollupjs.org/repl?version=1.1.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QnglN0QlMjBmcm9tJTIwJTVDJTIyLiUyRm1hdGhzLmpzJTVDJTIyJTNCJTVDbiU1Q25jb25zb2xlLmxvZyh4KHZhbHVlKSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJ2YXIlMjB2YWx1ZSUyMCUzRCUyMCU1QyUyMjElNUMlMjIlM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIweCh2YWx1ZSUyNDEpJTIwJTdCJTIwcmV0dXJuJTIwdmFsdWUlMjQxJTIwJTJCJTIwdmFsdWUlMjAlN0QlMjAlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #2680 
Resolves #2683

### Description

I know my output is not as much as it used to be at the moment due to my family + day job taking its toll but this is what I have been working on the last weeks. This is basically a complete rework of the name deconflicting logic that lies at the core of scope-hoisting.

That old logic needed to make quite a few assumptions such as certain variable names not appearing (ever wondered why we had $1 and $$1 variables? This was really just a hack to heuristically avoid name clashes). #2683 is a nice example where this went wrong.

But no more!

The new logic already starts in the phase where internal variable objects are associated with variables defined in the code. During this stage, each scope now takes note which variables from outside are used by the code in this scope. To compensate for the additional logic, this noting is also used as caching i.e. when a variable is used more than once in a scope or sub-scope, only the first access will cause a full lookup while the remaining accesses get the cached result.

Now during the actual deconflicting phase, i.e. the phase where all variables receive their final render names, these results are used to deconflict all variables that would otherwise shadow actually used other variables—and only those! As a result, there will now be actually noticeably fewer renames!

Also, variables can now have two "render names": A "base" name and another name. If the base name is present, then this variable is actually rendered as an object member access, i.e. `baseName.variableName`. In such a situation, of course, only the base name needs to be considered in deconflicting.

Other improvements:
- Formats are taken into account, e.g. with the ESM target, `module` or `exports` will usually not be deconflicted automatically as they do not correspond to format specific globals
- Tree-shaking information is taken into account. Now, tree-shaken variables will no longer cause other variables to be renamed
- Reserved words are now taken into account, i.e. a variable will never be called `static` or `await`. My hope is that this will resolve #2680, @matthiasg @gund please tell me if this is not the case.
- Furthermore with the new logic, it was easy to switch some naming priorities. Now inside each chunk, local names take precedence over imported (e.g. external) names. For instance when importing `React.Component` and locally defining a `Component`, then the imported one will become a `Component$1` while the local one retains its name. My hope is that this change will make the code of libraries nicer overall but please give feedback if I overlooked something here.

This will also form a nice base for future improvements. For instance it would now be quite easy to minify all variable names using this logic. Of course this would probably not be very useful without minifying white-space as well. Another feature I hope to work on soon is merging block scopes into other scopes during rendering, getting rid of some unnecessary curly braces when tree-shaking.

### CODE REVIEW

**Comment by TrySound** [comment]
Awesome!

**Comment by thysultan** [comment]
>Also, variables can now have two "render names": A "base" name and another name. If the base name is present, then this variable is actually rendered as an object member access, i.e. `baseName.variableName`.

Wouldn't this have a runtime overhead when compared to the previous implementation, or am i reading this wrong?

**Comment by lukastaegert** [comment]
There should be no qualitative change to the runtime code. This is about cases where we already rewrote variables as object member accesses. The most common example is probably rewriting things like

```js
export let x = 1;
x = 2;
```

as

```js
exports.x = 1;
exports.x = 2;
```

to maintain the live binding. There are other examples which I must admit I forgot at the moment🙄 Not too common, though.

**Comment by lukastaegert** [comment]
Before, the variable would be treated as having the name `exports.x` which made deconflicting somewhat pointless.

**Comment by lukastaegert** [comment]
Ah of course, the more important case would be imports in formats other than ESM or SystemJS

**Comment by thysultan** [comment]
Just to be clear the following won't be affected? 

```js
// a.js
export x = 1

// b.js
export x = 2

// main.js
import * as A from a.js
import * as B from b.js

export default A.x + B.x
```

**Comment by TrySound** [comment]
@thysultan https://rollupjs.org/repl?version=1.2.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMEElMjBmcm9tJTIwJy4lMkZhLmpzJyUzQiU1Q25pbXBvcnQlMjAqJTIwYXMlMjBCJTIwZnJvbSUyMCcuJTJGYi5qcyclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBBLnglMjAlMkIlMjBCLnglMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIweCUyMCUzRCUyMDIlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHglMjAlM0QlMjAxJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Pull request merged**
