### PR TITLE
fix TypeError in arrow function without braces returning a function

### LINKED ISSUE #1032: TypeError: body is not iterable with function returning function
The issue is only raised for fat arrow functions without braces that returns a function

For instance, here the smallest code I could find to trigger that issue: 

``` js
const f = (a) => (b) => {}

function ff (a) { return f(a) }
```

While this version is processed properly: 

``` js
const f = (a) => { return (b) => {} }

function ff (a) { return f(a) }
```

It seems that it doesn't matter that the returned function is a fat arrow function with or without braces or a plain old `function () {}`.

Here's the stack trace when running rollup on such sample: 
<details>

```
TypeError: body[Symbol.iterator] is not a function
    at fnHasEffects (/<redacted>/rollup/src/ast/nodes/shared/callHasEffects.js:16:18)
    at callHasEffects (/<redacted>/rollup/src/ast/nodes/shared/callHasEffects.js:34:9)
    at CallExpression.hasEffects (/<redacted>/rollup/src/ast/nodes/CallExpression.js:29:10)
    at CallExpression.isUsedByBundle (/<redacted>/rollup/src/ast/nodes/CallExpression.js:38:15)
    at /<redacted>/rollup/src/Bundle.js:150:31
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

</details>

### PR DESCRIPTION
**Pull request by kzc**
Fixes #1032

### CODE REVIEW

**Comment by PaulBGD** [comment]
Would love to have this merged, currently just manually adding this in since we're still in development. `preact-render-to-string` is one module that causes this error.

**Comment by trbrc** [comment]
For what it's worth, there's a more minimal test case to [trigger the error](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJjb25zdCUyMGYlMjAlM0QlMjBhJTIwJTNEJTNFJTIwYiUyMCUzRCUzRSUyMG51bGwlM0IlNUNuJTJGJTJGJTIwVW5jb21tZW50JTIwdGhlJTIwbmV4dCUyMGxpbmUlMjB0byUyMHRyaWdnZXIlMjB0aGUlMjBlcnJvciU1Q24lMkYlMkYlMjBmKCklM0IlMjIlN0QlNUQlN0Q=):

```
const f = a => b => null;
f();
```

(I just ran in to this issue too and would love to see @kzc's fix merged.)

**Comment by kzc** [comment]
This is probably a more correct fix:
```patch
--- a/src/ast/nodes/shared/callHasEffects.js
+++ b/src/ast/nodes/shared/callHasEffects.js
@@ -11,7 +11,7 @@ function fnHasEffects ( fn ) {
 
        // handle body-less arrow functions
        const scope = fn.body.scope || fn.scope;
-       const body = Array.isArray(fn.body.body) && fn.body.body || [ fn.body ];
+       const body = fn.body.type === 'BlockStatement' ? fn.body.body : [ fn.body ];
 
        for ( const node of body ) {
                if ( node.hasEffects( scope ) ) {
```
It also passes the tests.

It's up to the maintainers.

**Comment by Rich-Harris** [comment]
Released 0.37 with the fix – thanks

**Pull request merged**
