### PR TITLE
chore: explicitly set rust toolchain channel

### PR DESCRIPTION
**Pull request by cijiugechu**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description

The purpose of this PR is to explicitly set Rust toolchain channel to ensure version consistency across all contributors.

### CODE REVIEW

**Review by lukastaegert — COMMENTED** [review]
I assume we also need to adapt the toolchain on CI? In this file, we manually set the toolchain to "nightly" https://github.com/rollup/rollup/blob/master/.github/workflows/build-and-tests.yml
How would this file need to be adapted?
Also have a look at the lint failures as that relates to `rustfmt` not being found

**Comment by cijiugechu** [comment]
> Thank you very much! I assume we also need to adapt the toolchain on CI? In this file, we manually set the toolchain to "nightly" https://github.com/rollup/rollup/blob/master/.github/workflows/build-and-tests.yml How would this file need to be adapted? Also have a look at the lint failures as that relates to `rustfmt` not being found

The corresponding adjustments for the CI environment have been made.

**Review by lukastaegert — APPROVED** [review]

**Comment by lukastaegert** [comment]
Any idea why it would fail for the two docker builds?

**Comment by cijiugechu** [comment]
> Any idea why it would fail for the two docker builds?

I guess it may be because this command is missing: `rustup default nightly-2023-10-05`

**Pull request merged**
