### PR TITLE
Only build latest node on windows

### PR DESCRIPTION
**Pull request by lukeapage**
and switch to node 4

### CODE REVIEW

**Comment by lukeapage** [comment]
hrmm.. fail!
it seems a consistent error - https://ci.appveyor.com/project/Rich-Harris/rollup/build/7#L33

am hoping https://github.com/gobblejs/gobble-cli/pull/17 will make it output something more useful ;)

**Comment by Rich-Harris** [comment]
:+1:

**Comment by lukeapage** [comment]
> it seems a consistent error -

I just got it on my computer so I think its a real issue, not a bad npm install or environment issue.

**Comment by Rich-Harris** [comment]
Can you post the text of the error? Some commits are building okay: https://ci.appveyor.com/project/Rich-Harris/rollup/build/14

**Comment by lukeapage** [comment]
yes its inconsistent...
Has happened here...
https://ci.appveyor.com/project/Rich-Harris/rollup/build/17/job/ewhiqemaxjy1g5w0#L30

so its an error object.. maybe need a stringify.

**Comment by Rich-Harris** [comment]
Man, I have no idea what's going on there. Maybe https://github.com/gobblejs/gobble-cli/commit/0baae94f5334d53bc99a3030bf3e3a6bf7ae48f1 will help...

**Comment by Rich-Harris** [comment]
Okay, so now we're getting somewhere:

screen shot 2015-09-30 at 4 35 34 pm

Looks like Gobble is aborting the build because the source files are changing somehow, which seems like the sort of thing that could happen non-deterministically but only on Windows...

**Comment by lukeapage** [comment]
total guess - something like last accessed being changed but it normally fires after finishing a file on a quick machine? 
if you want me to try anything, let me know

**Pull request merged**
