### PR TITLE
Implement stdin input with optional "-" as the file name.

### LINKED ISSUE #1440: Feature: accept stdin
This is useful for quick tests of for easy CLI piping:

```sh
 echo 'console.log("Hello!");' | rollup
🚨   You must specify an --input (-i) option
```

Browserify supports it:

```sh
echo 'console.log("Hello!");' | browserify - | babili | gzip-size
325 B
```

### LINKED ISSUE #3276: Input from string/input stream
### Feature Use Case
being forced to work with files is very limited and slow.  i could do much more with rollup if it was easier. '@rollup/plugin-virtual' is a complicated solution. 

### Feature Proposal
allow the input to be a string/input stream please.

### PR DESCRIPTION
**Pull request by kzc**
Set default output format to "es" to save CLI typing for the most common case.

Closes #1440
Closes #3276

This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

#1440 
#3276

### Description

Implement stdin input with optional "-" as the file name.

Set default output format to "es" to save CLI typing for the most common case.

### CODE REVIEW

**Comment by kzc** [comment]
@lukastaegert Everything passing except for code coverage. Please add additional tests if you like.

**Comment by lukastaegert** [comment]
Thanks a lot. Just a note, it will take a while until I can work fully through this.

**Comment by kzc** [comment]
Test coverage was improved, but was unable to get 100% patch coverage. For whatever reason I couldn't simulate a stdin read error on Node within CircleCI. The same test worked locally on all Node versions. That particular test was commented out in the PR. I don't plan to spend any more time on it.

**Comment by kzc** [comment]
Just so there's no confusion, this PR works fine. That simulated stdin read error test is just a nice to have. It's not clear to me whether Node actually generates stdin read errors in any circumstance.

**Comment by lukastaegert** [comment]
Moving this to a local branch as there are still some changes I want to add

**Pull request merged**
