### PR TITLE
getInteropBlock() to work with null prototype objects

### PR DESCRIPTION
**Pull request by jdalton**
…e objects

This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description

Currently, rollup attempts to detect how exports should be generated based on the exported values from the module entry.

1. If there is a [default export](https://rollupjs.org/repl/?version=1.32.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAnZGVmYXVsdC1leHBvcnQnJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyYW1kJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=), export the default property as-is.
2. If there is a [named export (`named`)](https://rollupjs.org/repl/?version=1.32.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwbmFtZWQlMjAlM0QlMjAnbmFtZWQtZXhwb3J0JyUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJhbWQlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==), rollup returns an object with the `named` property.
3. If there are both [a default export and a named export (`named`)](https://rollupjs.org/repl/?version=1.32.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwbmFtZWQlMjAlM0QlMjAnbmFtZWQtZXhwb3J0JyUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwJ2RlZmF1bHQtZXhwb3J0JyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmFtZCUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE), rollup returns an object with the `default` and the `named` property. It's important to note that if no `output.exports` property is set, rollup warns in this case.

On the other hand, when importing the default value from an external module, rollup injects [some interop](https://rollupjs.org/repl/?version=1.32.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAnbW9kdWxlJTJGZm9vJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmFtZCUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) code extract the code right default value. This interop checks the presence of the `default` property on the exported object using `module.hasOwnProperty('default')`.

I recently ran into a case where the interop code throws an error because `hasOwnProperty` is not defined on the external module. This happens because the module (`module/a`) has a single default export and the default export value has no prototype. In this case, if another module (`module/b`) imports the default export the interop code will throw because `hasOwnProperty` is not defined on the object.

```js
/* `module/a` original code */
export default { __proto__: null, name: 'a' };

/* `module/a` generated code */
define('module/a', function () { 'use strict';
  var main = { __proto__: null, name: 'a' };
  return main;
});
```

```js
/* `module/b` original code */
import a from 'module/a';
console.log(a.name);

/* `module/b` generated code */
define('module/b', ['module/a'], function (a) { 'use strict';
  a = a && a.hasOwnProperty('default') ? a['default'] : a;
  //              ^ throws here because a does inherit from object!
  console.log(a.name);
});
```

### CODE REVIEW

**Comment by jdalton** [comment]
I need to follow-up with a test specifically for the null prototype case. Current PR has just existing tests modified.

**Comment by jdalton** [comment]
**Update**: Added unit test to test this case specifically ✅

**Comment by lukastaegert** [comment]
> Update: Added unit test to test this case specifically ✅

Very welcome, and important to document why we do it this way, thanks a lot!

**Comment by jdalton** [comment]
Thank you @lukastaegert!

**Pull request merged**
