### PR TITLE
docs: add ROLLUP_WATCH envar to docs

### LINKED ISSUE #2711: ROLLUP_WATCH env variable is missing in the docs
Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

It's useful to know, when rollup is in `watch` mode, for example in plugins. There is `ROLLUP_WATCH` env variable, but it's not documented anywhere. Just saw it in readme of [rollup-plugin-run](https://github.com/rollup/rollup-plugin-run).

### Your Proposal for Changes

Document `ROLLUP_WATCH` env variable in the docs.

### PR DESCRIPTION
**Pull request by shellscape**
This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description

Small documentation update to include `ROLLUP_WATCH` envar.  fixes #2711.

### CODE REVIEW

**Comment by lukastaegert** [comment]
> Alternatively, the `ROLLUP_WATCH` environment variable may be set to `true` to enable watch mode

Looking at the code, this is not correct. Instead while in watch mode, Rollup CLI **adds** the new environment variable, which can be checked by plugins to exhibit different behaviour.

https://github.com/rollup/rollup/blob/6b2b65074f9f52ef8d179972672c4809da17a720/cli/run/index.ts#L86

It can be argued that this is a weird way of doing it and a property on `this.meta` of the plugin context would be a better place to make this information available but this is how it is implemented. How about

> While in watch mode, the `ROLLUP_WATCH` environment variable will be set to `"true"` by Rollup's command line interface and can be checked by plugins and other processes.

**Comment by shellscape** [comment]
@lukastaegert that suggestion is good by me. are you OK with me updating master directly with that change?

**Comment by lukastaegert** [comment]
Sure, please go ahead!

**Comment by shellscape** [comment]
Done!

**Pull request merged**
