### PR TITLE
build(ci): factor out test jobs into a unique job

### PR DESCRIPTION
**Pull request by jerome-benoit**
This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

### Description

Factor out tests jobs into a unique job to 
+ ensure their coverage across node version and OS is the same during the CI runs
+ reduce the code surface to maintain

Changes: 

+ Create a unique tests job using node version and os matrix
+ Conditionally execute some steps where relevant
+ Remove EOLed node 14 
+ Make the current node LTS version the reference version for coverage, extended tests, ...  

Node version 20 is not added to the tests, but it's pretty easy to add if needed. 
The coverage related steps can also probably be limited to the current repo. 

Changes are validated, expect the coverage part: https://github.com/jerome-benoit/rollup/pull/1/checks

### CODE REVIEW

**Review by lukastaegert — COMMENTED** [review]
Thank you, but it is nice to have a discussion first. The LTS changes will happen with Rollup 4, which is in preparation. As this file will be replaced with something very different at that point, I respectfully decline these changes at this point to avoid friction.

**Comment by lukastaegert** [comment]
Once #5073 is stable, we can see how we can incorporate some of your suggestions there.

**Comment by jerome-benoit** [comment]
> Thank you, but it is nice to have a discussion first. 

The discussion can happen on the PR, which makes it better since the concrete material is part of it, but you've closed it instead of flagging it as 'needs discussion' or similar. 

> The LTS changes will happen with Rollup 4, which is in preparation. As this file will be replaced with something very different at that point, I respectfully decline these changes at this point to avoid friction.

Just ask for the changes to be done also on top of a targeted branch ;-)
The project takes PR on top of existing branches different than master?

Furthermore, I do not see why the current stable version should not have a CI with a proper tests coverage: 
+ The conflicts with the quoted branch are easy to solve: the filename with the changes is renamed -> delete old, keep new
+ The current changes can be forward ported to the quoted branch quiet easily

**Comment by lukastaegert** [comment]
> The discussion can happen on the PR

Definitely, but
- I am really happy with how coverage works at the moment, as it only runs on the fastest runner and I do not see any value in comparing coverage across environments. But it looks like you actually did not change that, so I do not see the point.
- We still support Node 14 as anything else would be a breaking change, and that will come with Rollup 4 once the other branch is ready.
- I would prefer not to mess with CI now that it is working and since this change to me does not seem to improve anything in a substantial way, I would like to keep it for the time being and not waste time on something that is thrown away.

> The current changes can be forward ported to the quoted branch quite easily

As the files have literally nothing in common, I tend to disagree. Once Rollup 4 is out, feel free to suggest improvements to the pipeline there, at which point I will give it more though.

**Comment by jerome-benoit** [comment]
> > The discussion can happen on the PR
> 
> Definitely, but
> 
> * I am really happy with how coverage works at the moment, as it only runs on the fastest runner and I do not see any value in comparing coverage across environments. But it looks like you actually did not change that, so I do not see the point.

By coverage, you mean the one done by codecov? static code analysis is independent of the underlying environment (theoretically), no need to duplicate it. 
The goal is to run the tests on several environments to trap any misbehaviors related to it. On node.js projects I comaintain, it has allowed to deal with windows node.js instabilities on specific major version, package instabilities with specific node major version (latest is babel with node 20), tests flakiness on specific node/OS, etc. before releasing and having to deal with issues unrelated to the project code.   
=> more automated testing on env used by end users, less work in the end.

> * We still support Node 14 as anything else would be a breaking change, and that will come with Rollup 4 once the other branch is ready.

Re-adding node 14 is 2 min of work. Like adding node 20. 

> * I would prefer not to mess with CI now that it is working and since this change to me does not seem to improve anything in a substantial way, I would like to keep it for the time being and not waste time on something that is thrown away.

cf. below. Few time spent on a non critical code piece bringing more stability to a whole code base.  

> 
> > The current changes can be forward ported to the quoted branch quite easily
> 
> As the files have literally nothing in common, I tend to disagree. 

It's just factoring out code without changing anything to its behavior. Cut and paste with trivial if branching to avoid the code duplication that basically represents less than one hour work, including testing on repo fork. And as a side effect, make maintenance easier.  
And given the fact that the release to come now contains indirectly Rust code compiling to native OS/arch binaries, running tests on the more node/OS/arch combination possible is becoming a prerequisite to assess stability.  

> Once Rollup 4 is out, feel free to suggest improvements to the pipeline there, at which point I will give it more thought.

I'm not that attached to that trivial PR, but given the substantial arguments given, you should reconsider the priority: having a comprehensive automated testing on a large new code base is better to have during the work on it than after.

**Comment by lukastaegert** [comment]
Awesome, I am looking forward to you using this as a basis to suggest improvements for the new pipeline then once it is done.

**Pull request closed without merging**
