### PR TITLE
[v3.0] Use ASCII characters for hash placeholders

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description
This changes the hash placeholder pattern to `_!~{\d+}~` where `\d+` are some digits to identify the chunks. This should still be sufficiently random to reduce the risk of accidental matches (it is not valid JavaScript so it can only occur in strings and comments where at least it should do limited damage, and we only replace a pattern if the exact sequence of digits is matched).
This should prevent issues we had from using generic unicode characters that were escaped by some tooling and also make debugging nicer.

cc @patak-dev @antfu

### CODE REVIEW

**Comment by patak-dev** [comment]
Thanks for digging into this. I agree that this will help with debugging. About the bump to 9 chars, looks like that will uncover some bugs in Vite as we have some regex expecting 8 chars. This is wrong on Vite's side though, and we will fix it, but I wonder if the bump to 9 chars could cause issues with other tools. Maybe it is something that would be good in the long run as the ecosystem shouldn't hardcode the hash length, and Rollup 3 is a good opportunity to force these fixes. FWIW, I think that `!~{\d+}~` could be enough in case it is better to keep 8 chars.

**Comment by lukastaegert** [comment]
They should not hard-code the hash length anyway because it is now legitimate to write things like `[hash:14]` in your file name pattern for arbitrary hash length! But admittedly, we can also remove one character. I just want to have enough room in the default pattern for 1000 chunks so people will not reach the ceiling easily.

**Comment by patak-dev** [comment]
Did you consider using `[a-z0-9]` instead of `\d` for the chunk codes? That would bump the default pattern to 40k+ chunks using 8 chars for `!~{\d+}~`, and at least to me, I wouldn't mind chunks identified as `ag4`

**Comment by lukastaegert** [comment]
Just laziness but you are right, there is probably no reason not to. I changed the algorithm to re-use a base64 conversion function we are already using elsewhere so by default, we now support 260k chunks...

**Pull request merged**
