### PR TITLE
Add support for entryFileNames pattern used in combination with preserveModules option

### LINKED ISSUE #2847: output.entryFileNames is ignored with preserveModules: true
I want to write my source in TypeScript, and output `.mjs` ES modules for each TypeScript source file.

- Rollup Version: 1.11.3
- Operating System (or Browser): macOS
- Node Version: v11.8.0

### How Do We Reproduce?

```bash
mkdir -p rollup-ts-esm/src
cd rollup-ts-esm
npm init -y
npm i --save-dev 'rollup@1.11.3' 'rollup-plugin-typescript2@0.21.0' 'typescript@3.4.5'
>rollup.config.js <<EOJS
import typescript2 from 'rollup-plugin-typescript2'

export default {
  input: 'src/index.ts',
  output: {
    dir: 'dist',
    entryFileNames: '[name].mjs',
    format: 'esm',
  },
  preserveModules: true,
  plugins: [
    typescript2({ include: 'src/**' }),
  ],
}
EOJS
>src/index.ts <<EOTS
export * from './lol'
export * from './wut'
EOTS
>src/lol.ts <<EOTS
export class Lol<T> {
  greater<T>(t1: T, t2: T): T {
    return t1 > t2 ? t1 : t2;
  }
}
EOTS
>src/wut.ts <<<'export class Wut {}'
npx rollup -c
ls dist
```

### Expected Behavior

Dist should contain:

```
index.mjs
lol.mjs
wut.mjs
```

`.mjs` extension, ESM-compliant contents.

### Actual Behavior

Dist contains:

```
index.ts
lol.ts
wut.ts
```

_`.ts`_ extension, ESM-compliant contents.

### PR DESCRIPTION
**Pull request by Andarist**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes
- [ ] no

Breaking Changes?
- [ ] yes 
- [x] no

List any relevant issue numbers:
fixes #2847

### Description
The main use case for this is to support "renaming" of the TS files to JS while transpiling.

I've skipped support for:
- `[ext]`- let's wait to see if anybody really wants it before introducing this
- `[hash]` - didn't have personal interest in implementing it and it wasn't straightforward for me how to implement this quickly, because `computeContentHashWithDependencies` expects `addons` argument, those were not passed into `generateIdPreserveModules` and I have no idea (without digging into this further) what those are

### CODE REVIEW

**Comment by lukastaegert** [comment]
Thanks for the PR! Just to let you know, I am a little busy with work-related things this week so a review may take until Friday. Thanks for your patience!

**Comment by Andarist** [comment]
No worries

**Comment by Andarist** [comment]
q: how `sanitizedId` (based on first item in `this.orderedModules`) differs from `this.getChunkName()` (if not given it's based on last item in `this.orderedModules`)?

**Comment by lukastaegert** [comment]
The key difference is that when the `name` is not explicitly specified (e.g. in the `preserveModules` case, as opposed to the case where you use an input object), `this.getChunkName()` will only be based on the "basename" via `getAliasName`, i.e. the last path fragment, while the `sanitizedId` is usually an absolute path.

**Comment by lukastaegert** [comment]
With that in mind, one could argue that maybe people expect `[name]` to contain the path relative to the common base dir, but I think your interpretation is more useful.

**Pull request merged**
