### PR TITLE
Bugfix: avoid infinite recursion in Bundle.sort()

### PR DESCRIPTION
**Pull request by phter**

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Can you add a test case that would exhibit the infinite recursion you mention? We'd like to be able to verify that this fixes a real problem.

**Comment by phter** [comment]
I ran into this bug while working on a rather complex library, so no simple test case, sorry.
But please just look at the current code of findParent(), it seems simple enough:
The function never returns a value, yet it contains the line
`if ( findParent( dependency ) ) return;` 
And it never checks if a module has already been visited, which doesn't go well with cyclical structures.

**Comment by phter** [comment]
npm install
npm run build
--> Maximum call stack size exceeded at findParent ...
Do I get a t-shirt now?

[rollup-test.zip](https://github.com/rollup/rollup/files/389045/rollup-test.zip)

**Comment by TrySound** [comment]
@phter Nice. Can you add it in PR?

**Comment by phter** [comment]
@TrySound Like this?

**Comment by phter** [comment]
@TrySound Uh, I messed up the branches of my forked repo, now some bogus commits appear to be part of the PR. That's annoying. Does it matter, though?

**Comment by TrySound** [comment]
@phter Yep. Can you rebase and squash them (you don't need to create new PR for this)?

**Comment by phter** [comment]
@TrySound ok, my git skills are somewhat lacking... but it seems to have worked.

**Comment by TrySound** [comment]
Nice. Thanks. Will check it out soon.

**Comment by TrySound** [comment]
https://github.com/rollup/rollup/commit/6ee27c6a7dcf5619074bc9c686386d0e948aa0d1

**Pull request merged**
