### PR TITLE
Set null prototype on namespace objects.

### PR DESCRIPTION
**Pull request by rpamely**
This PR contains:
- [X] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [X] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [X] no

List any relevant issue numbers: #3096

### Description

Set null prototype on namespace objects by using \_\_proto__. Previously it was not set so used default `Object.prototype`. ECMAScript spec defines [ES module namespaces as exotic objects](https://tc39.es/ecma262/#sec-module-namespace-exotic-objects) and says that their [[Prototype]] should be null.

### CODE REVIEW

**Comment by lukastaegert** [comment]
Can you check the remaining test failures? It seems to be just four left

**Comment by lukastaegert** [comment]
Ah, now it is running :)

**Comment by lukastaegert** [comment]
And sorry, there are some conflicts with master now 🙄

**Comment by rpamely** [comment]
@lukastaegert Think it's good now, tests are passing!

**Pull request merged**
