### PR TITLE
warn.code for missing output.name of IIFE bundle that has export

### PR DESCRIPTION
**Pull request by rail44**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description

Hi, I'm using rollup with typescript.
In my project, there are some modules built as iife, because they must assign some object into `window` when loaded .
But it also has `export` since its member's type definition was used by other modules.
In this case, rollup will warn that bundle is missing output.name.

This is request to add warn.code, useful for suppress by `onwarn()` .

### CODE REVIEW

**Comment by rail44** [comment]
writing test

**Comment by rail44** [comment]
@lukastaegert 
Thank you for your suggestion!

Then, should IIFE bundles also publish error, instead of warning?
And, when this PR will include such changes, it will become breaking change for people already having `onwarn()` with `INVALID_OPTION` won't it?

**Comment by lukastaegert** [comment]
You are somewhat right about the breaking change. Maybe we should make a separate PR for changing the error code to the `release-2.0.0` branch. Then I would actually just merge this one as it is.  Note though that since it is an error, not a warning, it will not get passed to onwarn handlers. The only way to see the code for errors is to use the JavaScript API and catch the call to `bundle.generate`.

> Then, should IIFE bundles also publish error, instead of warning?

If it produces working code, no reason to make it an error IMO. It's always possible someone depends on this...

**Comment by rail44** [comment]
@lukastaegert 

Sorry for late reply.  I was under busy.
I also create #3393 for UMD bundle.

**Comment by lukastaegert** [comment]
Let's wait how the discussion in #3393 pans out before merging

**Pull request merged**
