### PR TITLE
WIP: preserve modules

### PR DESCRIPTION
**Pull request by kellyselden**
This still needs a lot of work, but I want to submit for feedback. I'm still working to submit chunks as small PRs, and cleanup and removed dead experiments. It is stable in my testing.

Motivation:
I would like to use rollup to tree-shake Ember.js apps. Ember.js has a module loader system that requires the files not be bundled into a single file.

### CODE REVIEW

**Comment by kellyselden** [comment]
@guybedford @lukastaegert Is there anything that can be done to alleviate the rebase of this once #1841 merges?

**Comment by guybedford** [comment]
@kellyselden I'd suggest starting to try rebase on top of that branch on Rollup when you can, and sorry for the clash here. If you have any questions about getting this to work on top of that work (there may be some questions with the finalizers stuff), just let me know.

**Comment by guybedford** [comment]
@kellyselden can this be closed now?

**Comment by kellyselden** [comment]
Yep, superseded be #1922

**Pull request closed without merging**
