### PR TITLE
fix: deoptimize right of for of stmt when assign in for of

### LINKED ISSUE #4901: tree shake doesn't respect for...of literal of array
### Rollup Version

2.69.0

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

_No response_

### Link To Reproduction

https://rollupjs.org/repl/?version=2.69.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjBmb28lMjAlM0QlMjAlNUIlN0IlMjB2YWx1ZSUzQSUyMDElMjAlN0QlNUQlNUNuJTVDbmZvciUyMChjb25zdCUyMGl0ZW0lMjBvZiUyMGZvbyklMjAlN0IlNUNuJTIwJTIwaXRlbS52YWx1ZSUyMCUzRCUyMDAlNUNuJTdEJTVDbiU1Q25pZiUyMChmb28lNUIwJTVELnZhbHVlJTIwJTNEJTNEJTNEJTIwMCklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJ0hlbGxvJyklNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE

### Expected Behaviour

```js
const foo = [{ value: 1 }];

for (const item of foo) {
  item.value = 0;
}

if (foo[0].value === 0) {
  console.log('Hello');
}
```

### Actual Behaviour

```js
const foo = [{ value: 1 }];

for (const item of foo) {
  item.value = 0;
}
```

### PR DESCRIPTION
**Pull request by Kingwl**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

Closes #4901

### CODE REVIEW

**Comment by Kingwl** [comment]
Not sure it's the correct fix. Seems a little weird about access (and type cast) parent node in child node.

**Comment by XiSenao** [comment]
If there are no side effects inside the for...of, we need to remove this piece of code.

``` javascript
const list = [ { value: 1 } ];

for (const item of list) {
    // item.value = 0;
}

if (list[0].value === 0) {
    console.log(42);
}
```

**Comment by lukastaegert** [comment]
for..of loops are never removed at the moment. The reason is that Rollup cannot reliably detect side effects in custom iterators. For that reason, we decided to always keep them until someone implements something better.

The solution you implemented here is not completely off, but it is not 100% straightforward. The `deoptimizePath` method is always called for the left side of for-of statements because different values are assigned to the variable, even if it is not a declaration.

So what you did is equivalent to always deoptmizing the left side of the statement. Which I think is fine! It is simple and fixes the bug for now. But then, it should (and can) be done directly in ForOfStatement. Just add `this.right.deoptimizePath(UNKNOWN_PATH)` to `applyDeoptimizations` in `ForOfStatement`. Would you be willing to apply these changes?

Also, as the test checks for a bug, you should not use a `form` test. It is easy to update the test in bulk and overlook if the test is correct or broken. Instead, convert it to a `function` test. Those tests have access to Node's `assert` as a global variable, so do something like this

```js
const list = [ { value: 1 } ];

 for (const item of list) {
     item.value = 0;
 }

assert.ok(list[0].value === 0 ? true : false);
```

This currently becomes

```
assert.ok(false);
```

without the fix.

**Comment by lukastaegert** [comment]
I created #4949 to implement this solution.

**Pull request closed without merging**
