### PR TITLE
Slightly simplify namespace interop helpers

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description
Just a small refactoring that I stumbled upon that will save some bytes by not doing an else-after-return ^^

### CODE REVIEW

**Review by guybedford — APPROVED** [review]
I understand this is a simplification and not a change, but now that I see these code paths this makes me think we should not have the `__esModule` if statement here and instead treat it the same as all other namespaces from an interop perspective. This would then as a side effect cause the `default` to match the entire module.exports object which still seems important for Node.js compatibility to me.

**Comment by lukastaegert** [comment]
True, but the point of `__esModule` is exactly that the default does NOT match the entire exports. If you want this, you can select either
- `output.interop: default`, which will do exactly that: Remove the if-condition and always apply the second branch, or
- `output.interop: defaultOnly`, which will give you better Node semantics and a smaller helper by not adding any named exports but just the default

I would prefer to keep the `__esModule` semantics here.

**Comment by guybedford** [comment]
Thanks for the info, I hope we can make ‘default’ the default to match
Node.js on this. Having differences between platforms and tools causes
friction.

We should know next week for final whether Nodejs will be ‘default’ or
‘defaultOnly’. There’s still a small chance this could go either way.

**Comment by lukastaegert** [comment]
Well, if we do that, then we will definitely break compatibility with Webpack. And we are in for a myriad of issues where people complain that in the CommonJS build, they have to access their default as `namespace.default.default` while in the ESM version it is `namespace.default`.

Effectively we are saying that `__esModule` needs to die, and then we could as well remove it from Rollup entirely and force people to switch to Webpack. This may sound harsh, but these are the effects I fear. If we have the `__esModule` interop, then it needs to be consistent.

**Comment by guybedford** [comment]
> Well, if we do that, then we will definitely break compatibility with Webpack. And we are in for a myriad of issues where people complain that in the CommonJS build, they have to access their default as namespace.default.default while in the ESM version it is namespace.default.

Yes, but Webpack has also expressed an interest in maintaining stricter semantics so I don't think copying Webpack because that's what Webpack does should be used as a persuasive argument.

`__esModule` for interop between synthetic modules makes complete sense. Using `__esModule` to affect the way that CommonJS modules are interpreted from real ES modules was never the intention when I created the implementation in Traceur for and proposal to Babel for it. I did suggest early on a `__esModule || m[toStringTag] === 'module'` sort of branding check to include in `__esModule` for this case, but we felt it was too early to add such things into the ecosystem on the offchance it would be useful one day.

Node.js is defining an interop between ES modules and CommonJS at this point. Rollup and Webpack can decide independently what they want to support, but the frictions felt in the ecosystem are happening now, what we double down on decides if they stick around or if we can remove them for good.

**Comment by lukastaegert** [comment]
Not to forget TypeScript and especially Babel that also follow this pattern. Personally, I would go where Babel is going.

**Comment by lukastaegert** [comment]
As a matter of fact, I took deep inspiration from Babel's logic when designing this helper, except for the caching they implement: https://babeljs.io/repl/#?browsers=defaults%0A&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgFAcgGYQgglAOhgCwKYB2cBAhiHgM5gkDGeABALwB89NEBFEANnptxADmxMpWp1MAEzxISAV24x06ANxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.10.4&externalPlugins=

**Comment by lukastaegert** [comment]
> Using __esModule to affect the way that CommonJS modules are interpreted from real ES modules was never the intention

Technically, we are NOT importing commonjs modules from ES modules here. This helper is ONLY added when the target is CommonJS or AMD. There are no such interop helpers when the target is SystemJS or ESM. And my understanding was that these helpers were created for EXACTLY this use case?

**Comment by guybedford** [comment]
Ah, I might have misunderstood where this helper is being applied. I just did a test recently with RollupJS doing `import * as m from 'cjs'` built into ESM as a single bundle and noticed that the namespace object returned contained `default` pointing to the default export instead of the CommonJS exports. I was under the impression this helper and `interop: default` were responsible for that.

**Comment by guybedford** [comment]
(to be clear with `cjs` as either an external or as an inlined CommonJS module in the target runtime)

**Comment by lukastaegert** [comment]
The logic for CommonJS bundling is and remains entirely within `@rollup/plugin-commonjs`. Indeed, this logic always respects the `__esModule` flag at the moment, so maybe we need another Node-compatibility option here as well, like `commonJsDefaultExport: "module.exports" | "module.exports.default" | "auto"` where "module.exports" would be the Node version and "auto" would be the current behaviour. Note however that having anything other than "auto" as the default here will cause the issue that if you bundle everything together, it will behave differently than if you bundle first to CommonJS so that the original CommonJS import is an external import and then bundle everything together in a second pass. Because in that case, the usual interop helpers from Rollup core will kick in.

I am not sure we should change defaults here. A better approach could be to add a preset-like option to the commonjs plugin like `strictNodeInterop` that will implicitly set all relevant options both in the plugin and rollup core to the correct values. This will be great when bundling for Node, but I think users bundling for the Web may have a different stance here at least until the most important players have moved to proper ESM builds.

**Comment by guybedford** [comment]
Having different interop semantics depending on whether you are bundling CommonJS for Node.js or for the web is a recipe for lots of bugs.

I feel very strongly that full alignment with Node.js on these interop edge cases, down to the rule that if it works in Node.js interop semantics it works in RollupJS semantics would be best for RollupJS users. We can certainly do additional magic to make more work that wouldn't otherwise, but explicitly diverging will only solidifiy these issues when we have the opportunity to make a clean consolidation now.

I will post a meta issue on this next week once we have made Node.js progress on interop. I hope we can implement sane defaults that make interop frictions a thing of the past and ideally get Webpack on board with that as well.

**Comment by lukastaegert** [comment]
Solving things for good is awesome, just keep in mind that the current approach for Node interop without `__esModule` makes it impossible to support the scenario where
* ES module A imports stuff from ES module B
* ES module B exports a default and some named exports
* we transform both modules individually from ESM to CommonJS in a way so that functionality does not change

The only solution is to forbid users to use default exports.

**Comment by guybedford** [comment]
The argument is that the act of transforming ES modules to CommonJS is a
lossy transformation. For the boundary to alter on this edge case between
the systems is thus preferable to having interop issues perpetuate between
the systems. It’s a choice between that and breaking with the Node.js
execution convention. I feel quite strongly the latter is a stronger
invariant to maintain and justifies breaking the former. Let’s certainly
discuss more though and work through the scenarios of this edge case
further in a dedicated issue.

**Comment by lukastaegert** [comment]
I am also saying this as a reminder that you should be aware of during the continuing discussions in the Node team you were mentioning. This will be an issue that every single tool will be facing that does these transformations:
- Babel
- TypeScript
- Webpack
- Rollup
- Parcel
- ...

I would very much recommend you also talk at least to members of the first three in this list, especially Babel, for their stance on this. Currently you are depicting a future where ideally, default exports should be banned entirely, because for each usage there will be a transpilation or bundling scenario that will fail. And if there is a default export together with named exports, there is nowhere to put it after transpilation.

Having these discussions solely in the Rollup repos is nice, but I feel it puts a large burden of deciding the future of the JavaScript ecosystem on my shoulders, which not only keeps me (and has basically kept me for months) from building cool new stuff for Rollup but also does not give these issues the visibility and participation they deserve.

**Comment by guybedford** [comment]
@lukastaegert in the absolute worst case, a user will import a module as:

```js
import cjs from 'cjs';
const fn = cjs.default;

fn();
```

This is really as bad as it gets. Default exports always remain reachable. It is in the other case of masking the default with __esModule that reachability becomes a problem. To explain again why Node.js couldn't do this it is because updates to module.exports or new additional names added to module.exports cannot be pushed into the ES module representation as the full list of export names needs to be known before execution. If we allowed the `default` to be overridden that would remove information and force us to put the actual module somewhere else. Node.js can't then tell users to actuall do `import { __secretActualCJSModule }` as you know becomes the issue in this interop.

The code above is ugly yes. But at least it gives us something that works between tools.

Point taken we should get wider agreement though and I will see if I can put together a better point of collaboration than a RollupJS issue. But you cannot simply turn away from this problem and expect things to work out. RollupJS has collective responsibility in continuing to introduce these pain points if it just wants to make things work to look good while continuing to push edge case complexity down the road. It is clear that this is a case where it cannot just be following the greedy path (algorithmically at least!).

**Pull request merged**
