### PR TITLE
Allow to pass "true" to InputOptions.cache

### PR DESCRIPTION
**Pull request by danielrentz**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description

Vite has changed the default of this option to "false" (https://github.com/vitejs/vite/pull/11454), therefore it is needed to be able to set it to "true" explicitly. This may be useful in other situations too, e.g. extending some defaults options object which contains this option set to "false".

### CODE REVIEW

**Review by lukastaegert — CHANGES_REQUESTED** [review]
Yes you are right, that change makes sense. Some additional points, though:
- Currently, TypeScript tests are failing and Rollup does not build
- The documentation should be adapted in `docs/configuration-options/index.md` to change the type for the `cache` option and note that `true` is the default.

**Comment by danielrentz** [comment]
@lukastaegert Are the TS tests failing due to my change, or in general? (I have created the PR with the Gitlab inline editor).

**Comment by lukastaegert** [comment]
> Are the TS tests failing due to my change, or in general? (I have created the PR with the Gitlab inline editor).

Definitely due to your changes. We do not merge PRs if those tests fail, and CI makes sure this is not overlooked. Actually, it was the Netlify deploy that already failed, but you can inspect the test results yourself.

For that reason, I cannot recommend to do any production code changes in the inline editor. If you do not want to download it locally, try StackBlitz https://pr.new/github.com/danielrentz/rollup/tree/patch-1

**Comment by danielrentz** [comment]
I see, thanks for explaining. Will take care.

**Comment by danielrentz** [comment]
I decided to leave "NormalizedInputOptions" as-is (type `false`, not `boolean`), and to replace option "true" with "undefined". This way, all the remaininig code using this option can remain untouched.

**Comment by lukastaegert** [comment]
Seems at this point only the markdown linter is complaining, but I can fix that for you.

**Review by lukastaegert — APPROVED** [review]

**Pull request merged**
