### PR TITLE
feat: Export defineConfig defines the auxiliary function of the configuration

### PR DESCRIPTION
**Pull request by rxliuli**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers: https://github.com/rollup/rollup/issues/4125

### CODE REVIEW

**Review by lukastaegert — CHANGES_REQUESTED** [review]
Hi, thanks for the PR, I think this would make a useful addition. Two points:
* Could you fork your PR from `master` instead of the `treeshake-presets` branch? That one is still incomplete and not ready for release, so this will block your PR.
* If we add this, we should also document it somewhere on the website (i.e. in the `docs` folder). Probably similar to what they have on the Vite site (except that we do not directly support TypeScript), somewhere in 01-command-line-reference

**Comment by rxliuli** [comment]
> Hi, thanks for the PR, I think this would make a useful addition. Two points:
> 
> * Could you fork your PR from  instead of the  branch? That one is still incomplete and not ready for release, so this will block your PR.`master``treeshake-presets`
> * If we add this, we should also document it somewhere on the website (i.e. in the  folder). Probably similar to what they have on the Vite site (except that we do not directly support TypeScript), somewhere in 01-command-line-reference`docs`

Wait a minute, let me revise it and raise a PR again

**Comment by lukastaegert** [comment]
You could also just have force-pushed to your branch :)

**Comment by rxliuli** [comment]
> You could also just have force-pushed to your branch :)

I created a new PR: https://github.com/rollup/rollup/pull/4127

**Pull request closed without merging**
