### PR TITLE
feat: add support for private class methods

### PR DESCRIPTION
**Pull request by dnalborczyk**
add support for private methods: https://github.com/tc39/proposal-private-methods

[REPL](https://rollupjs.org/repl/?version=2.44.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBEWU5BTUlDJTIwSU1QT1JUUyU1Q24lMjAlMjAlMjBSb2xsdXAlMjBzdXBwb3J0cyUyMGF1dG9tYXRpYyUyMGNodW5raW5nJTIwYW5kJTIwbGF6eS1sb2FkaW5nJTVDbiUyMCUyMCUyMHZpYSUyMGR5bmFtaWMlMjBpbXBvcnRzJTIwdXRpbGl6aW5nJTIwdGhlJTIwaW1wb3J0JTIwbWVjaGFuaXNtJTVDbiUyMCUyMCUyMG9mJTIwdGhlJTIwaG9zdCUyMHN5c3RlbS4lMjAqJTJGJTVDbmlmJTIwKGRpc3BsYXlNYXRoKSUyMCU3QiU1Q24lNUN0aW1wb3J0KCcuJTJGbWF0aHMuanMnKS50aGVuKGZ1bmN0aW9uJTIwKG1hdGhzKSUyMCU3QiU1Q24lNUN0JTVDdGNvbnNvbGUubG9nKG1hdGhzLnNxdWFyZSg1KSklM0IlNUNuJTVDdCU1Q3Rjb25zb2xlLmxvZyhtYXRocy5jdWJlKDUpKSUzQiU1Q24lNUN0JTdEKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBzcXVhcmUlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbiU1Q25leHBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjBzcXVhcmUlN0QlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbiU1Q25jbGFzcyUyMEElMjAlN0IlNUNuJTVDdCUyM3ByaXZhdGVNZXRob2QoKSUyMCU3QiU3RCU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3ViZSUyMCh4JTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwc3F1YXJlKHgpJTIwKiUyMHglM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNxdWFyZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBzcXVhcmUlMjAoJTIweCUyMCklMjAlN0IlNUNuJTVDdHJldHVybiUyMHglMjAqJTIweCUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### CODE REVIEW

**Comment by dnalborczyk** [comment]
`ci` on windows seems to have an issue:

```
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\bin\git.EXE ls-remote -h -t ssh://git@github.com/lukastaegert/is-reference.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

**Comment by lukastaegert** [comment]
I assume you are not using SSH to access Github? That could explain the test issues. Will see if we can change something on our side to improve here.

**Comment by dnalborczyk** [comment]
> I assume you are not using SSH to access Github? That could explain the test issues. Will see if we can change something on our side to improve here.

sorry, I was referring to the windows ci run: https://github.com/rollup/rollup/runs/2273299082 not any local runs (I'm using a mac).

my local git settings wouldn't have any effect on how the ci pulls the dependency repo? or would it?

**Comment by lukastaegert** [comment]
Probably not. Still I wonder why it could not fetch the dependency via SSH, my though is that it was using some settings from your fork, but then again, it is very weird. Others doing that did not have this issue. In any case, I fixed it by changing the dependency to force HTTPS instead of SSH, this should always work.

**Review by lukastaegert — APPROVED** [review]
Very nice, and glad you could finally remove the comments from the test cases!

**Comment by jef** [comment]
Did it have anything to do with the way npm 7 vs npm 6 worked in pulling the dependencies? I see the package-lock changed between the two as well.

**Comment by lukastaegert** [comment]
Possible. For now I did not dare updating the lock file. But more importantly, the original lock file contained an ssh references while the new one uses https for the is_references package.

**Comment by dnalborczyk** [comment]
> But more importantly, the original lock file contained an ssh references while the new one uses https for the is_references package.

ah, I see, that was the issue then! yeah, I was using node.js v15+ w/ npm 7+. forgot the fact that they updated the package-lock format (v2).

thank you for looking into this @jef !

**Pull request merged**
