### PR TITLE
Extend manualChunks API

### LINKED ISSUE #3520: Influence chunking
### Feature Use Case
I am migrating a large web application from webpack to rollup. In this application we use a translation system based on es modules. The application is built out of 100s of components, spread across many NPM packages. 

Each component fetches it's translations(texts, labels etc.) with a pattern like this:

```js
switch (document.documentElement.lang) {
  case 'en-GB': return import('./translations/en-GB.js');
  case 'nl-NL': return import('./translations/nl-NL.js');
  case 'nl-BE': return import('./translations/nl-BE');
  ...etc.
}
```

In terms of code maintenance this is great, each component fetches it's own translations based on the language of the user and we never load any unnecessary code. This does lead to a lot of parallel dynamic import requests at runtime, even after bundling.

In webpack I wrote a plugin which looks at the chunking graph, and then as components are bundled together in chunks it also groups together the translations of the same language to match the chunks of the components. The effect is that for a given chunk, only one extra chunk of translations is dynamically loaded.

I'm looking for a way to implement this in Rollup, but I've not been able to do this. The closest is to use manualChunks, but there I don't have any information about the chunking done by rollup. The best I can do there is group based on node_modules package.

### Feature Proposal

Add the ability for plugins to inspect the chunk graph and rearrange modules and chunks.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #3520

### Description
This will extend the `manualChunks` function so that it gets a second parameter of the form

```
{
  getModuleInfo: GetModuleInfo;
  getModuleIds: () => IterableIterator<string>;
}
```

where `getModuleInfo` is the same function as on the plugin context.
- [x] TODO: I will also soft-deprecate `this.moduleIds` on the plugin context in favour of an explicit `this.getModuleIds()`.

Additionally, the object returned by `getModuleInfo` is extended by `importers: string[]` and `dynamicImporters: string[]` which allow traversing the graph backwards in order to find out e.g. which entries import a module.

For instance consider a scenario where you have a set of components, each of which dynamically imports a set of translated strings, i.e.

```js
// Inside the "foo" component

function getTranslatedStrings(currentLanguage) {
  switch (currentLanguage) {
    case 'en': return import('./foo.strings.en.js');
    case 'de': return import('./foo.strings.de.js');
    // ...
  }
}
```

If many components are used together, this will result in a lot of dynamic imports of very small chunks even though it is known that all language files of the same language that are imported by the same chunk will always be used together.

The following code will merge all files of the same language that are only used by a single entry point, and put all files that are used by multiple entry points into "shared" chunks:

```js
manualChunks(id, { getModuleInfo }) {
  const match = /.*\.strings\.(\w+)\.js/.exec(id);
  if (match) {
    const language = match[1];
    const dependentEntryPoints = [];

    // we use a Set here so we handle each module at most once, which
    // prevents infinite loops in case of circular dependencies
    const idsToHandle = new Set(getModuleInfo(id).dynamicImporters);

    for (const moduleId of idsToHandle) {
      const { isEntry, isDynamicEntry, importers } = getModuleInfo(moduleId);
      if (isEntry || isDynamicEntry) dependentEntryPoints.push(moduleId);

      // The Set iterator is intelligent enough to iterate over elements that
      // are added during iteration
      for (const importerId of importers) idsToHandle.add(importerId);
    }

    // If there is a unique entry, we put into into a chunk based on the entry name
    if (dependentEntryPoints.length === 1) {
      return `${dependentEntryPoints[0].split('/').slice(-1)[0]}.strings.${language}`;
    }
    // For multiple entries, we put it into a "shared"  chunk
    if (dependentEntryPoints.length > 1) {
      return `shared.strings.${language}`;
    }
  }
}
```

### CODE REVIEW

**Comment by lukastaegert** [comment]
This PR is now fully documented and ready to be released

**Comment by LarsDenBakker** [comment]
@lukastaegert in the example code snippet you mention `isDynamicEntry`, but I don't see this reflected in `getModuleInfo` here: https://github.com/rollup/rollup/pull/3542/files#diff-7c1e6304262c178e7fe268b62060e26bR265

It comes up undefined for every module when I try it out.

**Comment by lukastaegert** [comment]
True, that is wrong. Instead you should check if there are `dynamicImporters`. Will try to update the docs by tomorrow, otherwise doc PR welcome!

**Comment by LarsDenBakker** [comment]
No problem, I'll check if I can make it work using `dynamicImporters` and update the docs.

**Pull request merged**
