### PR TITLE
Manual chunks function

### LINKED ISSUE #2336: Allow globs for manualChunks
Currently manualChunks requires you to explicitly name each module you want in a chunk.

For my case, I would find it much more useful to be able to specify globs, instead, so I could, for instance, use:
```
    manuaChunks: {
        vendor: ['node_modules/**/*.js']
    }
```
to place all 3rd party packages in a vendor chunk.

### LINKED ISSUE #2688: Allow more programmatic control over manual chunks
### Feature Use Case

*Note: I'm trying to do something with Rollup that I don't think is possible, so consider this a feature request. If it is possible, please let me know how it can be done.*

What I want to do is use Rollup to generate multiple output files (chunks) from a single input file. The reason I want to do this, is I want to deploy and version my application code separately from my third-party dependency code.

As an example, imagine my app has entry point `./main.mjs`, and this file loads other modules both local to my application as well as some in `node_modules`. Here's some super simplified code:

```js
import {vendor1} from 'npm-pkg-1';
import {vendor2a, vendor2b} from 'npm-pkg-2';

import {localA} from './localA.mjs';
import {localB} from './localB.mjs';

// ...
```

After running this through Rollup, I want my output files to look like this:

```
build/
  npm-pkg-1-XXXXXXXX.mjs
  npm-pkg-2-XXXXXXXX.mjs
  main-XXXXXXXX.mjs
```

And I want to load them using a single script tag like this:

```html
<script type="module" src="./main-XXXXXXXX.mjs"></script>
```

And inside `./main-XXXXXXXX.mjs` it would look like this:

```js
import { vendor1 } from './npm-pkg-1-XXXXXXXX.mjs';
import { vendor2a, vendor2b } from './npm-pkg-2-XXXXXXXX.mjs';

// The rest of the `main.mjs` bundle goes here...
```

The point here is that all modules from `npm-pkg-1` get collapsed into a single module (with a version string), and all modules from `npm-pkg-2` get collapsed into a different module (with its own version string as well).

Or, if you wanted, you should be able to configure rollup to collapse *all* third-party code into a single `vendor-XXXXXXXX.mjs` module.

Note, webpack already supports a feature similar to this using its [`optimization.splitChunks`](https://webpack.js.org/configuration/optimization#optimizationsplitchunks) and [`optimization.splitChunks.cacheGroups`](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroups) options. For example, on my blog I have the following config that allows me to independently version all my npm dependencies:

```js
splitChunks: {
  chunks: 'all',
  maxInitialRequests: Infinity,
  minSize: 0,
  cacheGroups: {
    npm: {
      test: /node_modules/,
      name: (mod) => {
        const pkgName = mod.context.match(/node_modules\/([^/]+)/)[1];
        return `npm-${pkgName}`;
      },
    },
  },
},
```

The only difference between what I'm suggesting here and what I can do with webpack, is with webpack I have to load the scripts individually in my HTML (and also include the webpack runtime):

```html
<script type="module" src="./runtime-XXXXXXXX.mjs"></script>
<script type="module" src="./npm-pkg-1-XXXXXXXX.mjs"></script>
<script type="module" src="./npm-pkg-2-XXXXXXXX.mjs"></script>
<script type="module" src="./main-XXXXXXXX.mjs"></script>
```

While listing all modules in the HTML isn't that much of a burden, my preference would be to just leverege the native module loader and not have to include the runtime.

Another side benefit of a feature like this, is you can dramatically reduce the number of total `import` statements your production code makes, which should help a lot with performance when using native modules in production.

Does something like this seem feasible?

### Feature Proposal

I expected the `manualChunks` option to work this this already, but it doesn't seem like it does. If that option could be extended (or a new option creating) to take a function that gets invoked with the module ID and returns a chunk name, that seems like the simplest API to me:

```js
manualChunks: (moduleID) => {
  if (moduleID.includes('node_modules')) {
    const packageName = moduleID.match(/node_modules\/([^/]+)/)[1];
    return packageName;
  } else {
    return 'main';
  }
},
```

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #2688, resolves #2336 

### Description
This will allow the `manualChunks` option to be a function. If that is the case, all module ids are passed to this function. If this function returns a string, the given module and all its dependencies are added to the manual chunk with the given name.

This makes it possible to e.g. create vendor chunks via

```javascript
manualChunks(id) {
  if (id.includes('node_modules')) {
    return 'vendor';
  }
}
```

All combinatorics should work, if they don't, please let me know. There also should not be any issues any more if some of the files are dependencies of other files.

### CODE REVIEW

**Comment by tivac** [comment]
@lukastaegert you're awesome, thanks so much for this!

**Comment by philipwalton** [comment]
@lukastaegert thanks so much for working on this!

One question, you said:

> If this function returns a string, the given module and all its dependencies are added to the manual chunk with the given name.

I'm assuming here that you mean all its dependencies **not already in their own chunks**, correct? E.g. I'm assuming it would be possible to put all npm dependencies into their own chunks, even if they have cross references to other npm dependencies, correct?

**Comment by lukastaegert** [comment]
Yes, you are correct. I was not sure how to express this well without going too much into technical details. The way this works is that each time you return a string, the string is assigned to the module as a label. Then in a later stage when the manual chunks are created, we start with each labelled module and then assign the same label to all its dependencies unless the dependency already has a label.
There are some edge cases with shared dependencies where it would be a matter of ordering if a non-labeled dependency ends up in one chunk or another but in general it should work quite well.

**Comment by clintwood** [comment]
@lukastaegert really appreciate this PR.

One question my `manualChunks` function returns 'vendor' yet I am getting an outputted chunk with a name `vendor-<hash>`.  I was expecting an unhashed manual chunk name - is this expected?

**Comment by lukastaegert** [comment]
Yes, the return value just replaces the `[name]` placeholder in your `output.chunkFileNames` property. If you do not want the hash, you have to change the pattern in `output.chunkFileNames` which contains the hash by default.

**Comment by clintwood** [comment]
Thanks - appreciate the quick response!

**Comment by philipwalton** [comment]
@lukastaegert thanks for the clarification. I'm trying it out now, and it works great!

**Comment by MichaelRando** [comment]
> Yes, the return value just replaces the `[name]` placeholder in your `output.chunkFileNames` property. If you do not want the hash, you have to change the pattern in `output.chunkFileNames` which contains the hash by default.

How does one apply the hash conditionally? I've wanted to separate the preload chunk from normal chunks and thought this function was my key; but I got number ordered chunk names when I tried it, which are less optimal cache-wise.

**Comment by lukastaegert** [comment]
Different naming patterns are not yet implemented but there is an issue around this that I hope we will be able to address at some point: #2793

**Pull request merged**
