### PR TITLE
Simple ast memoization for in-process builds

### PR DESCRIPTION
**Pull request by guybedford**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevent issue numbers: #2398

### Description

So with the caching work, we've effectively shifted the work of caching transforms to plugins themselves, with their own cache objects.

The goal with this is that we can then deprecate the existing approach which is that when the input source matches the previous input source, it uses the cached transform result and cached ast.

But in order to replace this we still need to handle the AST caching use case.

The insight here is that the value of caching the AST is only for in-memory builds. Serializing the AST to disk will not be a performance benefit over loading the source string directly (at least until we have binary AST formats). So we wouldn't even want to be writing the current module cache to disk with the ast serialization included.

Rather, we simply memoize the parsing step itself - where if the source hash matches a previous source hash, we can reuse the previous AST.

This then will handle the multiple inputs problem from #2398 as well allowing the AST to be shared between builds, even if they have completely different input options and transforms happening.

In theory there will be a minor performance regression here due to the work of hashing all output sources, but in testing of Rollup builds this was completely unnoticable.

### CODE REVIEW

**Comment by lukastaegert** [comment]
This looks quite simple but I see one major concern here: In watch mode, this will just fill up the memory with no way to free up memory again.

Here is one possible solution that comes to my mind:
We add a "marker" (e.g. a hash/random number) to each AST that is used in the current run. Then once all modules have been loaded, we delete all keys that are not used by the current run. This should nicely cover the watch mode case where only a single file or very few files change but all other files stay the same so we want to get rid of the AST for that single file.

This could also be extended to something more complex similar to the `cacheExpiry` option. It might even reuse this option for configuration so that there is a way to switch it off for very large builds that already scratch the memory ceiling.

The beauty of your memoization is that it will for the first time provide some speed-up for users returning an array from their config where there is an overlap between the individual builds.

Let me know your thoughts.

**Comment by guybedford** [comment]
@lukastaegert yes exactly the `cacheExpiry` approach would work here well for eviction.

**Comment by skeggse** [comment]
Can we offer any support on this initiative? The use-case described in #2398 is super valuable to us, and we'd like to move on from `multibuild` and `rollup-stream` as we suspect they may be causing substantial overhead.

**Comment by frank-dspeed** [comment]
@guybedford i think this is related  #2601

**Comment by shellscape** [comment]
Closing per offline request by @guybedford.

**Pull request closed without merging**
