### PR TITLE
Rollup v2.0.0

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [x] feature
- [x] refactor
- [ ] documentation
- [x] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [x] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:
See list of contained PRs at the bottom

## Description
This is the release branch for Rollup@2.
See https://github.com/rollup/rollup/projects/2 for the current state of the new release.

At the moment, the following changes are contained in this branch:

### Breaking Changes
* Rollup now requires at least Node 10 to run, or a sufficiently modern browser (#3346)
* The file structure of Rollup's ESM builds has changed:
  - The main ESM entry point is now at `rollup/dist/es/rollup.js` instead of `rollup/dist/rollup.es.js`
  - The ESM browser build is at `rollup/dist/es/rollup.browser.js` instead of `rollup/dist/rollup.browser.es.js`
  
  In general, the ESM builds now follow the same naming scheme as the CJS builds but are located in the `rollup/dist/es` subfolder instead of `rollup/dist` (#3391)
* The "watch.chokidar" option no longer accepts a `boolean` value but only an object of parameters that is passed to the bundled Chokidar instance. Chokidar installations by the user will be ignored in favour of the bundled instance (#3331)
* Modules that are completely tree-shaken will no longer be listed as part of any chunks in `generateBundle`
* The `experimentalOptimizeChunks` and `chunkGroupingSize` options have been removed
* [acorn](https://github.com/acornjs/acorn) plugins can only be used if they accept a passed-in acorn instance instead of importing it themselves. See https://github.com/acornjs/acorn/pull/870#issuecomment-527339830 for what needs to be done to make plugins compatible that do not support this yet (#3391)
* Emitted chunks now have the TypeScript type `UInt8Array` instead of `Buffer`. A `Buffer` can still be used, though (#3395)
* The TypeScript types no longer use ESTree types for AST nodes but a very generic type that does not contain information specific to certain node types (#3395)
* The signature of the `writeBundle` plugin hook has been changed to match `generateBundle`: The bundle object is now passed as second parameter instead of first and the first parameter is the output options (#3361)
* The following plugin hooks have been removed:
  - ongenerate: use `generateBundle` instead
  - onwrite: use `writeBundle` instead
  - transformBundle: use `renderChunk` instead
  - transformChunk: use `renderChunk` instead
* You can no longer access `this.watcher` on the plugin context.
* The `transform` hook can no longer return `dependencies`.
* The `treeshake.pureExternalModules` option will now show a deprecation warning when used: use `treeshake.moduleSideEffects: 'no-external'` instead
* Using `import.meta.ROLLUP_ASSET_URL_<..>` and `import.meta.ROLLUP_CHUNK_URL_<..>` in code will now show warnings: use `import.meta.ROLLUP_FILE_URL_<..>` instead
* The `resolveAssetUrl` hook will now show a deprecation warning when used: use `resolveFileUrl` instead
* The following plugin context functions will show warnings when used:
  - `this.emitAsset`: use `this.emitFile`
  - `this.emitChunk`: use `this.emitFile`
  - `this.getAssetFileName`: use `this.getFileName`
  - `this.getChunkFileName`: use `this.getFileName`
  - `this.isExternal`: use `this.resolve`
  - `this.resolveId`: use `this.resolve`
* Directly adding properties to the bundle object in the `generateBundle` is deprecated will show a warning (removing properties is allowed, though): Use `this.emitFile`
* Accessing `chunk.isAsset` on the bundle is deprecated: Use `chunk.type === 'asset'` instead
* The error code for a missing `name` property when targeting UMD has been changed to `MISSING_NAME_OPTION_FOR_IIFE_EXPORT` to emphasize this is needed for the IIFE part of UMD (#3393)

### Features
* Rollup now bundles [Chokidar](https://github.com/paulmillr/chokidar) for a better watch experience (#3331)
* Rollup now bundles [acorn](https://github.com/acornjs/acorn) again, removing its only external dependency (#3391)
* Do not consider empty imports from side-effect-free modules for chunking and hoist side-effect imports if necessary (#3369)
* Rollup can now be imported as an ES module in Node via `import {rollup} from 'rollup'`. Note that this relies on Node's experimental [conditional package exports](https://nodejs.org/dist/latest-v13.x/docs/api/esm.html#esm_conditional_exports) feature and is therefore itself experimental (#3391)
* `systemjs` can be used as format alias for `system` (#3381)

### Bug Fixes
* Unknown output options now trigger a warning when using the JavaScript API (#3352)
* Rollup will no longer introduce Node types into TypeScript projects that do not use them (#3395)
* Generate correct sourcemaps when tree-shaking occurs in a multi-file bundle (#3423)

### Pull Requests
* [#3331](https://github.com/rollup/rollup/pull/3331): Bundle Chokidar (@lukastaegert)
* [#3343](https://github.com/rollup/rollup/pull/3343): Remove experimentalOptimizeChunks (@lukastaegert)
* [#3346](https://github.com/rollup/rollup/pull/3346): Update minimum required Node version to 10 (@lukastaegert)
* [#3352](https://github.com/rollup/rollup/pull/3352): Remove active deprecations (@lukastaegert)
* [#3361](https://github.com/rollup/rollup/pull/3361): Change writeBundle signature to match generateBundle (@lukastaegert)
* [#3369](https://github.com/rollup/rollup/pull/3369): Avoid empty imports from side-effect-free chunks (@lukastaegert)
* [#3381](https://github.com/rollup/rollup/pull/3381): Rename esm to es everywhere, add systemjs alias (@lukastaegert)
* [#3391](https://github.com/rollup/rollup/pull/3391): Bundle acorn, allow importing Rollup as Node ES module, update dependencies (@lukastaegert)
* [#3393](https://github.com/rollup/rollup/pull/3393): Better error code for name-less umd bundle (@rail44)
* [#3395](https://github.com/rollup/rollup/pull/3395): Remove `@types` dependencies (@lukastaegert)
* [#3423](https://github.com/rollup/rollup/pull/3423): Update magic-string and fix sourcemaps (@lukastaegert)

### CODE REVIEW

**Comment by Andarist** [comment]
q: wasnt `"es"` format supposed to be renamed to `"esm"`? or you have decided not to proceed with this one?

**Comment by lukastaegert** [comment]
Yes it was. The problem is that this caused an inconsistency with plugins that still receive "es" as format specifier, which was confusing to say the least. Asking around for opinions, I agree with the following reasoning:

- CJS modules are called `cjs`
- AMD modules are called `amd`
- SystemJS modules are called `system`
- Why should ES modules be called `esm` and not `es`?

So it is much more consistent with the other format specifiers. Nevertheless this is not a breaking change: `esm` will continue to work as an alias and is not marked for deprecation, and `module` is supported as well.

**Comment by kzc** [comment]
I'm not convinced that bundling `acorn` and `magic-string` is a good idea. If there's a bug in one of those packages (as is currently the case with `magic-string`) there's no way for a user to supply an alternate package with a fix via `yarn` `resolutions` or other methods. The users would have to wait for the upstream package fix followed by a new `rollup` release.

**Comment by lukastaegert** [comment]
I see your point and we might revert this policy at some point. At the moment, bundling provides some slight size and parsing time advantages and allows for consistent behaviour between Node and browser builds.

I usually try to be quick on updating merged dependencies, so unless you want to use a Github build this should not be too big an issue. Let's see how this pans out.

**Comment by NotWoods** [comment]
Can you update `compilerOptions.target` in the tsconfig.json file to `"es2018"`? That'll tell Typescript to any syntax that can run in Node 10 and save us a few bytes.

**Comment by lukastaegert** [comment]
Thanks for checking, this has actually already been done in one of the PRs included here: https://github.com/rollup/rollup/blob/3f1052b1c967c4bd8cfc3f58c35ebe220cb48584/tsconfig.json#L12

**Comment by wessberg** [comment]
Hey Lukas. Great work, and congratulations on the v2 milestone :-)

Please let me know if you'd like me to create a new issue in relation to the following question. I'd like to understand if you have any plans for bringing back chunk grouping? For production applications built with Rollup with hundreds or thousands of chunks due to heavy use of code splitting, you might end up with many chunks weighing less than 1 kilobyte. My team is relying heavily on Rollup, but we're currently serving so many chunks to our users, most of which are less than or around 1kb in size, that it hurts performance. I've been following progress of the `experimentalChunkOptimization` flag with the hopes that it might help us due to the chunk grouping feature. However, I've also noticed that the feature didn't really work (hence the experimental nature of the feature), but I think it would be extremely valuable, at least to me and my team, but especially for those who rely on Rollup for building applications in a progressive and performance-sensitive way.

**Comment by lukastaegert** [comment]
So to give you some idea, these are the topics I want to work on next:
- Reduce the number of facade chunks. Facade chunks are reexport chunks that are generated whenever a chunk that contains an entry point would also contain additional exports. The plan is to add an option to configure Rollup more for web apps, which would get rid of facades for static entries. And later add an option to allow for "tainted" namespaces in dynamic imports, i.e. namespaces that contain additional exports. This would get rid of many facades for dynamic imports.
- Fix hashing by completely reworking how it is done.
- Refactor chunking so that it is no longer part of the "build" phase but moved to the "output generation" phase. This is a profound refactoring but would be a necessary step in order to implement a better "optimizeChunks". At that point, I would also consider adding a plugin API to allow plugins to directly control the chunking procedure. Depending how it is done, "optimizeChunks" could also become a plugin then.

However, it would take quite a bit of time to get there. For the time being, I would also have a look at manualChunks, which can basically be used to hand merge chunks. If all static entry points are always loaded together, one easy optimization could be to make all of them manual chunks. As a rule of thumb, an entry that is always loaded initially can always be made a manual chunk without risk. Manual chunks work like a flood fill paint, adding all statically imported modules to a chunk, unless they are already part of another manual chunk.

**Pull request merged**
