### PR TITLE
Adds type definitions for RollupWatcher events.

### PR DESCRIPTION
**Pull request by MicahZoltu**
This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

### Description

The type information is extracted from https://github.com/rollup/rollup/blob/master/src/watch/index.ts, someone should double check that I got it all right.  I'm new to rollup and have never actually used any of this stuff, but when I tried to I ran into the problem of there being no useful type information which caused me to have to read source code.  Rather than having everyone suffer like I did, I decided to create a PR to resolve the issue.

### CODE REVIEW

**Comment by lukastaegert** [comment]
Hi, thanks for the contribution! While these changes look sensible, they broke the TypeScript sanity test. Basically this does a TS compiler dry-run to check for type errors. Please run `npm run test:typescript` and see if you can fix the issues.

**Comment by MicahZoltu** [comment]
I took a very quick stab at fixing this, but unfortunately it caused a bunch of other typing problems to surface out of the woodwork.  I suspect fixing them wouldn't be particularly hard for someone familiar with the project, but I'm not in a position to go deep and resolve the cascading problems.

Note: After my fix commit, the problem is no longer with this PR but rather that the PR surfaced some type problems elsewhere in the project that were masked by the fact that this was basically unchecked code (`any`).

I'll leave the PR open in case someone wants to fix the rest of it, but if there are no takers then someone should close this PR as I won't likely be finishing it.

**Comment by shellscape** [comment]
@MicahZoltu let's leave this open. I think it's a valuable contribution and I'd like to see us clean up the rest of it so we can include it.

**Comment by shellscape** [comment]
@NotWoods is this something you might be interested in picking up? If not I think we'll close this as stale.

**Comment by NotWoods** [comment]
Yes, I can pick this up.

**Comment by NotWoods** [comment]
Superseded by #3302

**Pull request closed without merging**
