### PR TITLE
chmod a+x bin/rollup

### LINKED ISSUE #1209: generated bin/rollup not chmod +x
```
$ bin/rollup
bash: bin/rollup: Permission denied
```
```
$ node bin/rollup 

rollup version 0.39.2
=====================================

Usage: rollup [options] <entry file>
```

### PR DESCRIPTION
**Pull request by Rich-Harris**
fixes #1209

### CODE REVIEW

**Comment by kzc** [comment]
This works. Thanks.

**Comment by kzc** [comment]
Would `chmod a+x` work for Windows users?

I might have suggested the same patch but don't know the npm portable way to do this.

**Comment by Rich-Harris** [comment]
It passes CI so at the very least it doesn't break anything...

**Comment by tivac** [comment]
Something like [shelljs/shx](https://github.com/shelljs/shx) would presumably be a safer cross-platform way to do that. Dunno how you'd feel about that extra dependency though.

**Comment by Rich-Harris** [comment]
It only needs to run on the machine from which the package is being published though, no? As long as the file has the correct permissions when it's published, it'll have the correct permissions for everyone who installs the package regardless of OS?

**Comment by tivac** [comment]
npm takes care of setting the `.bin` dir entries to be `+x` already, I wouldn't expect many people to execute `node_modules/rollup/bin/rollup` directly.

The use-case I was thinking of was lost souls like myself that develop on windows 👻

**Comment by kzc** [comment]
There's always `fs.chmodSync(path, mode)`

https://nodejs.org/api/fs.html#fs_fs_chmodsync_path_mode

**Pull request merged**
