### PR TITLE
fix: use a new includedLabels in the body of the LabeledStatement

### LINKED ISSUE #5292: Treeshaking removes valid labels
### Rollup Version

v4.7.0

### Operating System (or Browser)

Linux and Browser

### Node Version (if applicable)

_No response_

### Link To Reproduction

https://rollupjs.org/repl/?version=4.7.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwcShnJTJDJTIwYiklMjAlN0IlNUNuJTIwJTIwdmFyJTIwYSUyMCUzRCUyMGIlNUIxJTVEJTNCJTVDbiUyMCUyMGIlM0ElMjBpZiUyMCh0eXBlb2YlMjBhJTIwISUzRCUzRCUyMCU1QyUyMm51bWJlciU1QyUyMiklNUNuJTIwJTIwJTIwJTIwc3dpdGNoJTIwKGElNUIwJTVEKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjYXNlJTIwNyUzQSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBxJTIwJTNEJTIwYSU1QjIlNUQlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwciUyMCUzRCUyMGElNUIxJTVEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHQlMjAlM0QlMjBiUyhyJTJDJTIwZnVuY3Rpb24lMjAoYSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwYyUyMCUzRCUyMGElNUIzJTVEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGQlMjAlM0QlMjBhJTVCMiU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBiJTIwJTNEJTIwYSU1QjElNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwYiUzQSUyMGlmJTIwKGMpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMGglMjAlM0QlMjBjJTVCMSU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBlJTIwJTNEJTIwaCU1QjElNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAodHlwZW9mJTIwZSUyMCElM0QlM0QlMjAlNUMlMjJudW1iZXIlNUMlMjIpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHN3aXRjaCUyMChlJTVCMCU1RCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDAlM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoaCU1QjQlNUQpJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKHRwKGIlNUIxJTVEJTJDJTIwJTVCMCUyQyUyMGUlNUIxJTVEJTVCMSU1RCU1RCkpJTIwcmV0dXJuJTIwJTVCMCUyQyUyMGIlMkMlMjBkJTJDJTIwMCU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBicmVhayUyMGIlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDExJTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKGQpJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMGklMjAlM0QlMjBjJTVCMSU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBrJTIwJTNEJTIwaSU1QjElNUQlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbCUyMCUzRCUyMGslNUIxJTVEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGYlMjAlM0QlMjBsJTVCMSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMCh0eXBlb2YlMjBmJTIwISUzRCUzRCUyMCU1QyUyMm51bWJlciU1QyUyMiUyMCUyNiUyNiUyMDAlMjAlM0QlM0QlM0QlMjBmJTVCMCU1RCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAobCU1QjQlNUQpJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKGklNUI0JTVEKSUyMGJyZWFrJTIwYiUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBtJTIwJTNEJTIwayU1QjIlNUQlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbiUyMCUzRCUyMGYlNUIxJTVEJTVCMSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChqJTIwJTI2JTI2JTIwdHAoYiU1QjElNUQlMkMlMjAlNUIwJTJDJTIwbiU1RCkpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU1QjAlMkMlMjBiJTJDJTIwJTVCMCUyQyUyMG0lNUQlMkMlMjAwJTVEJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGJyZWFrJTIwYiUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTVCMCUyQyUyMGIlMkMlMjBkJTJDJTIwbyhlUiUyQyUyMGMlMkMlMjBwKGclNUIzMyU1RCUyQyUyMGcpKSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU1QjAlMkMlMjAlNUI3JTJDJTIwdCUyQyUyMHElNUQlMkMlMjBiJTVCMiU1RCUyQyUyMGIlNUIzJTVEJTJDJTIwYiU1QjQlNUQlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY2FzZSUyMDExJTNBJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMGglMjAlM0QlMjBhJTVCMSU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjJTIwJTNEJTIwaCU1QjElNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAodHlwZW9mJTIwYyUyMCElM0QlM0QlMjAlNUMlMjJudW1iZXIlNUMlMjIlMjAlMjYlMjYlMjAxNCUyMCUzRCUzRCUzRCUyMGMlNUIwJTVEKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChjJTVCMiU1RCklMjBicmVhayUyMGIlM0IlMjAlMkYqJTIwJTNDLS0tJTIwZXJyb3IlMjB0cmlnZ2VyZWQlMjBoZXJlJTIwKiUyRiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChoJTVCNCU1RCklMjBicmVhayUyMGIlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwaSUyMCUzRCUyMGElNUIyJTVEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGYlMjAlM0QlMjBpJTVCMSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMCh0eXBlb2YlMjBmJTIwISUzRCUzRCUyMCU1QyUyMm51bWJlciU1QyUyMiUyMCUyNiUyNiUyMDklMjAlM0QlM0QlM0QlMjBmJTVCMCU1RCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoaSU1QjQlNUQpJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU1QjAlMkMlMjAlNUIxNCUyQyUyMGMlNUIxJTVEJTJDJTIwJTVCMCUyQyUyMGYlNUIxJTVEJTVEJTVEJTJDJTIwYiU1QjIlNUQlMkMlMjBiJTVCMyU1RCUyQyUyMGIlNUI0JTVEJTVEJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBicmVhayUyMGIlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGJyZWFrJTIwYiUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjYXNlJTIwMTglM0ElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwZCUyMCUzRCUyMGElNUIxJTVEJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKCFkKSUyMGJyZWFrJTIwYiUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBrJTIwJTNEJTIwZCU1QjIlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoIWspJTIwYnJlYWslMjBiJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKCFrJTVCMiU1RCklMjBicmVhayUyMGIlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwbCUyMCUzRCUyMGRtKGQpJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGUlMjAlM0QlMjBsJTVCMSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBkJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGUlM0ElMjBpZiUyMCh0eXBlb2YlMjBlJTIwISUzRCUzRCUyMCU1QyUyMm51bWJlciU1QyUyMiUyMCUyNiUyNiUyMDUlMjAlM0QlM0QlM0QlMjBlJTVCMCU1RCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwbiUyMCUzRCUyMGUlNUIxJTVEJTVCMSU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMCgwJTIwISUzRCUzRCUyMG4lNUIwJTVEKSUyMGJyZWFrJTIwZSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChzKG4lNUIxJTVEJTJDJTIwZDEpKSUyMGJyZWFrJTIwZSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChlJTVCMiU1RCklMjBicmVhayUyMGUlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAobCU1QjQlNUQpJTIwYnJlYWslMjBlJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMG0lMjAlM0QlMjAxJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGJyZWFrJTIwZCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwbSUyMCUzRCUyMDAlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKCFtKSUyMGJyZWFrJTIwYiUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjB1JTIwJTNEJTIwYjYobzgoYjYoZCkpKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZXR1cm4lMjAlNUIwJTJDJTIwJTVCOSUyQyUyMHUlNUQlMkMlMjBiJTVCMiU1RCUyQyUyMGIlNUIzJTVEJTJDJTIwYiU1QjQlNUQlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMHJldHVybiUyMENzKGclMkMlMjBiKSUzQiU1Q24lN0QlNUNucSgxJTJDJTIwMiklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE

### Expected Behaviour

Treeshaking should not remove well-defined labels that are used by some code.

### Actual Behaviour

In the REPL example, when selecting treeshaking `true`, the label `b` in line 5 disappears:

```js
function q(g, b) {
  var a = b[1];
  if (typeof a !== "number")
```

Disabling treeshaking leaves the label in place:

```js
function q(g, b) {
  var a = b[1];
  b: if (typeof a !== "number")
```

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

resolves #5292

### CODE REVIEW

**Review by lukastaegert — COMMENTED** [review]
I think the solution makes sense. There is one thing that worries me, though, but I could not produce an error from this: Usually, the label logic should be symmetric between `hasEffect` and `include`, which is no longer the case here.
The other thing is that I do not understand why I need a switch statement to create the error and cannot just create it with nested block scopes and functions.

**Comment by TrickyPi** [comment]
> The other thing is that I do not understand why I need a switch statement to create the error and cannot just create it with nested block scopes and functions.

I was curious about it before debugging. After debugging, I think the reason is the order of `BreakStatement` and `LabeledStatement`. If the `BreakStatement` comes before `LabeledStatement`, it will cause this problem. Otherwise, it works. see https://rollupjs.org/repl/?version=4.9.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiU1Q25vdXRlciUzQSUyMCU3QiU1Q24lNUN0c3dpdGNoJTIwKGdsb2JhbFRoaXMudW5rbm93biklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY2FzZSUyMDIlM0ElNUNuJTVDdCU1Q3QlNUN0YnJlYWslMjBvdXRlciUzQiU1Q24lNUN0JTVDdGNhc2UlMjAxJTNBJTVDbiU1Q3QlNUN0JTVDdCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUN0JTVDdCU1Q3QlNUN0b3V0ZXIlM0ElMjBjb25zb2xlLmxvZygncmV0YWluZWQnKSUzQiU1Q24lNUN0JTVDdCU1Q3QlN0QpKCklM0IlNUNuJTVDdCU3RCU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==
Notice: the last `SwitchCase` is first executed in the include logic.

So why we cannot just create it with nested block scopes and functions? becuase we have no way to place the `BreakStatement` before the `LabeledStatement` in that case.

BTW, the `If` conditional can also produce this error, see https://rollupjs.org/repl/?version=4.9.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMm91dGVyJTNBJTIwJTdCJTVDbiU1Q3RpZiUyMChnbG9iYWxUaGlzLnVua25vd24pJTIwJTdCJTVDbiU1Q3QlNUN0YnJlYWslMjBvdXRlciUzQiU1Q24lNUN0JTdEJTIwZWxzZSUyMCU3QiU1Q24lNUN0JTVDdCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUN0JTVDdCU1Q3RvdXRlciUzQSUyMGNvbnNvbGUubG9nKCdyZXRhaW5lZCcpJTNCJTVDbiU1Q3QlNUN0JTdEKSgpJTNCJTVDbiU1Q3QlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQXRydWUlN0QlN0Q=

**Comment by TrickyPi** [comment]
> There is one thing that worries me, though, but I could not produce an error from this: 

Yeah, I also feel a bit worried about this.

**Comment by lukastaegert** [comment]
Here is a situation where the asymmetry between `hasEffects` and `include` retains code that has no side effects: https://rollup-4yijtklk8-rollup-js.vercel.app/repl/?pr=5297&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMm91dGVyJTNBJTIwJTdCJTVDbiU1Q3RpZiUyMChnbG9iYWxUaGlzLnVua25vd24pJTIwJTdCJTVDbiU1Q3QlNUN0YnJlYWslMjBvdXRlciUzQiU1Q24lNUN0JTdEJTIwZWxzZSUyMCU3QiU1Q24lNUN0JTVDdCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUN0JTVDdCU1Q3Rpbm5lciUzQSUyMCU3QiU1Q24lNUN0JTVDdCU1Q3QlNUN0b3V0ZXIlM0ElMjAlN0IlNUNuJTVDdCU1Q3QlNUN0JTVDdCU1Q3RicmVhayUyMGlubmVyJTNCJTVDbiU1Q3QlNUN0JTVDdCU1Q3QlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwUmVtb3ZlJTIwdGhpcyUyMGxpbmUlMjBhbmQlMjBldmVyeXRoaW5nJTIwaXMlMjByZW1vdmVkJTVDbiU1Q3QlNUN0JTVDdCU1Q3Rsb2coJ2VmZmVjdCcpJTNCJTVDbiU1Q3QlNUN0JTVDdCU3RCU1Q24lNUN0JTVDdCU3RCkoKSUzQiU1Q24lNUN0JTdEJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE

This is easily fixed by adding the same logic to `hasEffects` that uses a fresh Set of included labels when checking effects of children.

If you add this test and fix, I will merge this because essentially, your solution IS the right one.

**Review by lukastaegert — APPROVED** [review]

**Pull request merged**
