### PR TITLE
0.15.0

### PR DESCRIPTION
**Pull request by Rich-Harris**
This incorporates PR #102

### CODE REVIEW

**Comment by Victorystick** [comment]
LGTM. :tada:

**Comment by Rich-Harris** [comment]
cool, have released to npm. Btw @Victorystick I just added you as an owner to the npm package so that you're able to publish releases as well – @eventualbuddha you too!

**Comment by Victorystick** [comment]
Sweet. Not that used to releasing, but I guess this'd be `npm release patch`, right?

**Comment by Rich-Harris** [comment]
Actually I've never used `npm release`. I typically update the package.json and CHANGELOG, commit those changes as `-> [version]`, tag the commit (`git tag -a v[version] -m 'version [version]'`) then `npm publish`. There are probably smarter ways :)

**Pull request merged**
