### PR TITLE
support loading ESM plugins from the CLI via `--plugin`

### PR DESCRIPTION
**Pull request by kzc**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

n/a

### Description

Rollup presently only supports CJS plugins from the CLI via `--plugin`. This PR adds seamless ESM plugin support to the CLI. To maintain backwards compatibility rollup will still attempt to resolve the plugin via `require` first, and only upon error will it attempt to load the plugin via a dynamic `import()`. This is due to the different module resolution semantics of CJS and ESM modules in NodeJS.

The use of dynamic import to load ESM plugins works with Node v12+.  No rollup CLI functionality is lost on NodeJS versions that do not support loading ESM via dynamic `import`.

### CODE REVIEW

**Comment by kzc** [comment]
Interesting... the new ESM CLI plugin tests succeed on Node v12 here, but not on my local machine. The Node v12 version used by github CI must be more recent than my local version. 

The Node v10 failures for the new ESM CLI plugin tests were expected - both here and on my local machine. I will add a condition to skip the ESM CLI plugin tests on Node v10, as no old functionality is lost on that Node version.

**Review by lukastaegert — APPROVED** [review]
Looks good to me, thanks a lot!

**Comment by dnalborczyk** [comment]
> Interesting... the new ESM CLI plugin tests succeed on Node v12 here, but not on my local machine. The Node v12 version used by github CI must be more recent than my local version.
> 
> The Node v10 failures for the new ESM CLI plugin tests were expected - both here and on my local machine. I will add a condition to skip the ESM CLI plugin tests on Node v10, as no old functionality is lost on that Node version.

the `experimental-modules` flag was removed in `v12.17`, and esm was considered stable in `v12.22`.

**Comment by dnalborczyk** [comment]
I think `rollup` should probably make the move to full `esm` for `v3` as well and move the ecosystem forward! it should be perfectly fine when used from the cli as esm is supported from node.js `12.22+`. some friction could potentially arise when used in code, but that can be mitigated by using dynamic imports in cjs if needed.

**Comment by kzc** [comment]
Even if rollup v3 moves to an all ESM toolchain for the CLI, rollup v2 should support both ESM and CJS during the transition period.  Although it's technically possible to mimic the semantics of `require` with dynamic `import()`, it's non-trivial. `require` module resolution has a lot of peculiar historical behaviors.

**Comment by dnalborczyk** [comment]
> Even if rollup v3 moves to an all ESM toolchain for the CLI, rollup v2 should support both ESM and CJS during the transition period. 

yes, I agree. that was just a thought I had in mind since it touched the `esm` topic.

**Comment by mreinstein** [comment]
@kzc  this is freakin awesome, thank you!! ❤️

**Comment by kzc** [comment]
Glad it's useful.  It simplified my workflow.

**Pull request merged**
